### ISSUE TITLE
'Alexa previous' acts as back button - it will not go to previously played video

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1002]
## Steps to reproduce
- Go to youtube, play a video, and autoplay to next video
- Say 'Alexa, previous'

### Expected behavior
- Fire TV goes back to previous video

### Actual behavior
- It acts as pressing back button, exits from playback

### Device information
- Fire TV Cube, 2.2

Logging this issue, in case the 'previous' command is meant to play previous video.  Please close if this is not the case.

**Comment by mcomella** [comment]
Actually, I no longer see this issue.

**Comment by npark-mozilla** [comment]
I can still see this on Fire TV cube.
- Open youtube video fullscreen
- say 'alexa next' to go to next video, repeat.
- say 'alexa previous'

Expected:
- go back one video
Actual:
- Exits to the video list

**Comment by kfontecilla** [comment]
As per @npark-mozilla - for this particular bug, it does not apply to 2.2 release, because it only happens in fire tv cube, which is outside the scope technically so, I've moved this bug back out to the backlog for triage.

**Comment by mcomella** [comment]
To summarize, I can reproduce this on:
- Cube

But I can't reproduce on:
- 4K
- Stick

**Comment by mcomella** [comment]
@kglazko (or someone else) Can you still reproduce? If not, please close!
