### ISSUE TITLE
Verify history is being cleared correctly

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1005]
I think we need to run clear on the WebView used by the app, not just the one in settings.

**Comment by psymoon** [comment]
So it looks like webView instance in BrowserFragment is null after the static cleanup methods get called from SettingsFragment. This suggests that we are clearing the history properly from the original implementation. Adding addition checks to make sure Browser webView instance calls cleanup() IFF not null. See https://github.com/mozilla-mobile/firefox-tv/pull/1016

**Comment by psymoon** [comment]
Looks to be working as intended with the current implementation

**Comment by Baron-Severin** [comment]
We've changed how we're handling WebView creation, so we need to reopen this issue.
