### ISSUE TITLE
Browser-session integration broke SessionLoadedIdlingResource 

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1010]
As mentioned in https://github.com/mozilla-mobile/firefox-tv/issues/998, this is also blocking the UI test development as the tests will not compile.  When this bug is fixed, ideally #998 should be resolved as well.

**Comment by liuche** [comment]
I'll take a look at this, if it's a small maybe I can fix this up really quickly and make sure the tests run again.

**Comment by mcomella** [comment]
Adding to v3.0 to make sure No-Jun gets his tests fixed soon. :)

Espresso, our test framework, has a concept of "idling resources": between each step of the test, the framework waits for all idling resources to be idle before moving to the next step. For example, an idling resource could be created around animations: we want all animations to finish before we execute the next test instruction (e.g. like asserting the view state for the new views after the animations complete).

We wrote an idling resource for our `Session` code. Recently, we replaced our `Session` implementation with the session implementation from Android Components and it wrote our idling resource. Your mission is to fix this idling resource.

To run UI tests, open them in the IDE (they're under `androidTest/`), right click on the class name and select "Run": you can select a device or emulator to run on. The tests using the idling resource are:
- IWebViewExecuteJavascriptTest
- ScreenshotTest

Make sure these both work!

Note: the tests may be broken in other ways (we don't build UI tests in CI so they break too easily: fix in #998).

**Comment by Baron-Severin** [comment]
Something high priority came up and I need to jump on to another project.  Sorry @psymoon

**Comment by pocmo** [comment]
Will have a look at this today.
