### ISSUE TITLE
SUMO article about MediaSession commands

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1023]
### Why/User Benefit/User Problem
We recently added voice commands for media control #930 , but we should get a SUMO article out about it.

### What / Requirements
What commands are supported

### Acceptance Criteria (how do I know when I’m done?)
SUMO page with supported voice commands.

**Comment by liuche** [comment]
@mcomella, can you list the media session commands that are supported? And then please assign/ping @jonisavage when they're listed here so she can add this to the Firefox TV SUMO page.

A user was asking on SUMO: https://support.mozilla.org/en-US/questions/1230308

**Comment by mcomella** [comment]
Our list of voice commands is here: https://github.com/mozilla-mobile/firefox-tv/wiki/Developer-guide-and-differences-from-Android#voice-commands

MediaSession is under one of the bullets and it links out to official amazon docs. Note that we only shipped MediaSession to 4K and Cube at present.

**Comment by liuche** [comment]
@mcomella: Seburo passed on a comment from a user who said that "next" doesn't work - is it only for Youtube? If there are caveats like site-specific functionality, we should include that in the wiki page.

**Comment by mcomella** [comment]
> is it only for Youtube?

It's only on sites that support MEDIA_NEXT/PREV keyboard events. I'll document.

But again, it only happens on certain devices and that have to have the latest version which was only released today.

**Comment by mcomella** [comment]
fwiw, I did make an internal-only build that only supported play/pause so it's possible they sideloaded their build too.

**Comment by SeburoSUMO** [comment]
SUMO document drafted, just waiting for initial approval before publishing to SUMO.

**Comment by SeburoSUMO** [comment]
Article published at https://support.mozilla.org/en-US/kb/using-voice-commands-firefox-amazon-fire-tv

**Comment by liuche** [comment]
Talked to Seburo briefly and had a few changes, but this can be closed now I think.
