### ISSUE TITLE
Improve Firefox for Fire TV for reading articles

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1034]
### Why/User Benefit/User Problem
Mobile websites are intended to be consumed in a portrait orientation; in landscape mode, you can't read articles well because there isn't a lot of vertical space.

The Fire TV acts like a mobile device in landscape due to the screen size and UA: this makes it not great for reading articles.

One example solution: we can add vertical [letterboxing](https://en.wikipedia.org/wiki/Letterboxing_%28filming%29) to simulate a portrait orientation. Since the screen is so large, this could be combined so we can display two websites side by side.

### What / Requirements
- Decide if we want to improve the article reading experience
- Come up with a solution
- Implement it

**Comment by mcomella** [comment]
@athomasmoz We haven't found this to be a known user problem: should we just close this issue? If so, feel free to do so.

**Comment by athomasmoz** [comment]
Yes, good call.
