### ISSUE TITLE
Clicking on Pocket videos does nothing

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1037]
## Steps to reproduce
- On home screen
- Select Pocket
- Select video

### Expected behavior
- Navigate to video

### Actual behavior
- Nothing happens

### Device information
- Master 2a20bb98f1a6e1f5eb0693e7828223a79162b8d0
- Device (Samsung 4k in SF office)
- Fire OS 6.2.5.3

**Comment by mcomella** [comment]
I think we've seen behavior like this if you do something like (I don't remember exact STR):
- Select pocket
- Press back
- Select pocket
- Select video

But it works correctly if you don't back out of it.

**Comment by Baron-Severin** [comment]
It looks like this was introduced in PR #982.

**Comment by Baron-Severin** [comment]
The bug described above where backing out of a Pocket video puts the app into a bad state seems to be an unrelated and preexisting bug (reproduced on 0fda8e23).  Opened #1042 to track it
