### ISSUE TITLE
Replace webview abstraction layer with browser-engine-system component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#1039]
In the next Android components sprints we should have implemented all the functionality to start replacing the webview abstraction layer with `browser-engine-system` (`WebView` implementation of `concept-engine`).

I'm currently experimenting with a partially migrated build to identify missing pieces in our engine implementation.

As part of this migration we should be able to use the `feature-session` component here to automatically update the state (`browser-session`) from the engine events. With that we no longer need the Proxy and Callback objects.

With that finished Firefox for Fire TV should be the first app that uses the core components (`browser-session` <-> `browser-engine-*`). This will hopefully be the foundation to componetize more functionality and pull in other components that build on top of this core.

**Comment by pocmo** [comment]
> I'm currently experimenting with a partially migrated build to identify missing pieces in our engine implementation.

For now I'll keep that assigned to me in order to continue this experiment. I filed this issue to track and document the work happening.

**Comment by mcomella** [comment]
@pocmo For v3.0, we want to replace AmazonWebView with the SystemWebView #379.
1) Does this patch take this into account?
2) Will this patch be ready for v3.0? fwiw, we have a lot of other changes in v3.0, which could already make things unstable so I wonder if we should wait for v3.1 (but that'd require us to do use the system WebView ourselves first).

**Comment by pocmo** [comment]
@mcomella 

> Does this patch take this into account?

Yes. The integration of `browser-engine-system` will effectively cause a switch to the system's WebView.

> Will this patch be ready for v3.0? fwiw, we have a lot of other changes in v3.0, which could already make things unstable so I wonder if we should wait for v3.1 (but that'd require us to do use the system WebView ourselves first).

What's the time frame for 3.0? According to the milestone it's September 19, 2018? This seems doable.

>  I wonder if we should wait for v3.1 (but that'd require us to do use the system WebView ourselves first).

I see issues with waiting. The WIP patch will rot and we will have to start the integration all over because too much has changed.

**Comment by mcomella** [comment]
> What's the time frame for 3.0? According to the milestone it's September
19, 2018? This seems doable.

Yeah, that's about right.

**Comment by pocmo** [comment]
@mcomella I opened PR #1044 to share the current state. We should be able to provide most of the mentioned missing functionality in 0.21 tomorrow (not everything has landed yet though!).

Based on that what's your assessment of the risk compared to doing it later? My gut feeling is to get this in earlier than later and have the ability to iterate with the whole team on it (including QA) and identify problems.

Like with `browser-toolbar` for app **X** we are again committed to work towards your deadline and push out early component releases if needed.

**Comment by pocmo** [comment]
Merged. Follow-up work will continue in #1063.
