### ISSUE TITLE
Bad state on back press after Pocket

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1042]
## Steps to reproduce
- Fresh start
- Click Pocket
- Click any video
- Click back

### Expected behavior
- Returns to home (should this return to the Pocket carousel?)
- Focuses search bar

### Actual behavior
- Returns to home
- No view takes focus
- Unable to interact with app

### Device information
- Device (Samsung 4k in SF office)
- Fire OS 6.2.5.3
- Commit: 0ab13632

**Comment by liuche** [comment]
Talked to @Baron-Severin about STR - I don't think "back" works from Youtube because of #173 but not sure if this is still reproducible.

**Comment by liuche** [comment]
We decided during sprint planning that:
a) the Focus-loss is the most critical part, but we're not sure if this is still repro-able - if this is repro-able then we MUST fix it
b) the Youtube back behavior is #773

**Comment by dnarcese** [comment]
Pressing back from a Pocket video goes to the YouTube homescreen. Pressing back from the Pocket feed goes to the overlay with the search bar focused. I haven't been able to repro the focus loss bug.

Is this issue only for the focus loss bug? Or do we want to change the behaviour so that clicking back from a Pocket video goes to the Pocket feed?

**Comment by Baron-Severin** [comment]
This bug was that specific steps could cause the user to end up on the home page, but unable to interact with any views.  I just checked and it's no longer reproducible so I'm closing it.  We may want to change some of the back behavior here, but that will need to be a new issue and will require input from @aminalhazwani.

**Comment by AaronMT** [comment]
When I back out from a Pocket video I get stuck in the YouTube home-screen without a way to return to the browser. We should fix that.

**Comment by dnarcese** [comment]
@AaronMT Issues #773 and #1542 will fix that.
