### ISSUE TITLE
Write regression test to cover Pocket video failure

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1045]
### Why/User Benefit/User Problem
Ideally https://github.com/mozilla-mobile/firefox-tv/issues/1037 would have included a regression test that would prevent this issue from slipping through in the future, but UI tests don't currently compile.  Once they have been fixed, a test covering this case should be written.

### What / Requirements
- UI smoke test that covers basic pocket usage
- Suggest using the [robot pattern](https://academy.realm.io/posts/kau-jake-wharton-testing-robots/) to make test maintenance simpler

### Acceptance Criteria (how do I know when I’m done?)
- Tests should cover https://github.com/mozilla-mobile/firefox-tv/issues/1037 and https://github.com/mozilla-mobile/firefox-tv/issues/1042 (the second will have to be @ignored until it is fixed)

**Comment by liuche** [comment]
For this specific case, when the WebView was recreated, we failed to set JavascriptEnabled correctly, so this test should cover that case.
