### ISSUE TITLE
Pocket onboarding has bitcoin reference: is that okay? :)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1059]
![device-2018-08-31-140050](https://user-images.githubusercontent.com/759372/44936978-f3c87600-ad2b-11e8-83c7-0c5b5600826c.png)

Currently, onboarding is hard-coded to a series of images that differs from what the first feed may show. These include a bitcoin video (see far right), which seems exclusionary to a wider, non-technical audience. Is that a concern/okay?

We could also:
- Use the real Pocket element with Pocket onboarding (but it will look bad on network errors and take more work to implement)
- Change the images
- Have a hard-coded set of defaults for the first run Pocket experience so that onboarding and the content will be the same

**Comment by bbinto** [comment]
Please @aminalhazwani, go ahead and provide another thumbnail

**Comment by liuche** [comment]
Next action item here: Pull from Pocket API and download thumbnails to give to Amin to choose from.

**Comment by liuche** [comment]
Duping to #1119
