### ISSUE TITLE
Need ADM credentials for Push service

### ISSUE THREAD

**Issue by jrconlin** [mozilla-mobile/firefox-tv#1065]
### Why/User Benefit/User Problem
We've recently added [ADM support to Autopush.](https://github.com/mozilla-services/autopush/pull/1290). In order that it can be tested in stage and prod, we need to make sure that our operations folks get valid `Client_ID` & `Client_Secret`s for each platform ([See notes here](https://autopush.readthedocs.io/en/latest/adm.html) on how to get these values)

### What / Requirements
Once push support has been enabled, please provide the proper values to Mozilla Ops. These can be integrated into the Autopush server by adding the appropriate configuration line to the `autopush_endpoint.ini` file or using the `ADM_CREDS` environment variable. 

### Acceptance Criteria (how do I know when I’m done?)
- [x] Credentials are transferred to ops (ping :oremj on Slack to arrange transfer; **talk to oremj before transferring: we may not want to send these unencrypted**)
- [x] Ping :jrconlin: is there a low effort (<2 hours?) way to verify the credentials are set up correctly?
  * If so, verify credentials are set up correctly

### Tasks
Follow instructions on Amazon dev portal: https://developer.amazon.com/docs/adm/obtain-credentials.html#getting-your-oauth-credentials-and-api-key
Context in:
https://bugzilla.mozilla.org/show_bug.cgi?id=1488838#c6

---

As if by magic, you'll get fun things like "Send to Device", Simplified Device Pairing, WebPush notifications, faster cert updates, and all sorts of fun* things. 

(*"fun" is a relative term and you may be required to supply your own party hat. Some terms and conditions may apply. Offer may not be available in Narnia, Shangrila or Brigadoon, but they all have horrible wifi anyway.)

**Comment by jrconlin** [comment]
Please also update https://bugzilla.mozilla.org/show_bug.cgi?id=1488838 once keys have been acquired and provided to Ops.

**Comment by liuche** [comment]
@jrconlin is this blocking you? I think we're adding this feature in the next release, but right now we're finishing up 3.0 for code freeze next week - okay to handle this in a later sprint when we need it? If you need some lead time, let us know and we can prioritize the fun* appropriately.

**Comment by jrconlin** [comment]
closing https://bugzilla.mozilla.org/show_bug.cgi?id=1488838 for now to clean up tasks for ops.

**Comment by davismtl** [comment]
Best success criteria ever written.

**Comment by dnarcese** [comment]
> Ping :jrconlin: is there a low effort (<2 hours?) way to verify the credentials are set up correctly?

:jrconlin said there is not a low-effort way to test the credentials.

I have sent credentials to :oremj and will close this issue when they have been added to Autopush.

**Comment by dnarcese** [comment]
This is completed now
