### ISSUE TITLE
Do we handle ACTION_VIEW / ACTION_SEND Intents?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#1077]
Follow-up from #1063.

I wasn't able to test SHARE or VIEW intents. I couldn't find an app that actually sends that intent to open a browser. Do we support that? Is this something that we supported before or was this just code that existed from Focus?

**Comment by liuche** [comment]
Yes, we do support VIEW and SEND, with some caveats, but we don't handle the overlay state correctly - if you open a url with VIEW or SEND but the overlay is open, it doesn't hide the overlay but the web content is showing correctly underneath

For VIEW:
`adb shell am start -a android.intent.action.VIEW http://www.mozilla.org -n org.mozilla.tv.firefox.debug`

For SEND (to search for cats):
`adb shell am start -a android.intent.action.SEND --es android.intent.extra.TEXT cats -n org.mozilla.tv.firefox.debug/org.mozilla.focus.MainActivity`

(with a little help from https://developer.android.com/studio/command-line/adb#IntentSpec )

And without specifying the package, we get a share popup:
![view](https://user-images.githubusercontent.com/1082253/45390556-8e4e7200-b5d4-11e8-8f61-b90ee21457bb.png)
