### ISSUE TITLE
URL next to loading indicator shows previous url, and then updates

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1081]
## Steps to reproduce
- From home
- Click on any tile

### Expected behavior
- Site loads
- Loading indicator appears in bottom left corner of screen
  - **URL shows to the right of loading indicator**

### Actual behavior
- Site loads
- Loading indicator appears
  - **The URL does not appear until the website has almost finished loading, or previous url if there is history**

### Device information

- Device (Samsung 4k in SF office)
- Fire OS 6.2.5.3
- Commit: e20111a7d0b64b57d4b6beccfa2709e15778d261

**Comment by bbinto** [comment]
@csadilek - could you please confirm if this related to the session race condition you've experienced?

**Comment by Baron-Severin** [comment]
Reproduced this on commit ec097ab058862129f0b5baa0294983ee32a67ab5, which was before we replaced the browser-engine-system.

**Comment by liuche** [comment]
This used to work in 975a09e - we should prioritize fixing this because it's causing other regressions.

**Comment by Baron-Severin** [comment]
Root cause is that `Session.url` is set by `SystemEngineView#onPageFinished`, which is called pretty late in the loading process.  I've opened an issue on A-C: https://github.com/mozilla-mobile/android-components/issues/825

**Comment by pocmo** [comment]
Is this fixed with 0.25.1?

**Comment by Baron-Severin** [comment]
@pocmo It is!  Thanks again.

Closed by https://github.com/mozilla-mobile/firefox-tv/pull/1201
