### ISSUE TITLE
Replace "firefox:home" search bar placeholder

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/firefox-tv#1086]
## Steps to reproduce

1. Launch Firefox for Fire TV

### Expected behavior

Placeholder is set to "Search with Google or enter address"

### Actual behavior

Placeholder is set to "firefox:home"

### Device information

* Fire TV device: AFTA
* Firefox version: e20111a

**Comment by AaronMT** [comment]
Also when you begin to type text in the address-bar, it appends it to this string instead of replacing it.
