### ISSUE TITLE
Firefox crashes when backgrounded by "Alexa, ..."

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1089]
Affects 2.2 (which is on the pendant/diamond and the cube)

STR:
1. Play video in Firefox
2. Say "Alexa, go home", which takes you to Fire TV homescreen
3. Open firefox

Expected:
On the same page, can resume video

Actual:
Firefox goes to Firefox homescreen (with pinned sites, etc)

* Also related: when a video is playing and the user opens the "heart" UI (long-press HOME button in Firefox) video will continue playing, but should stop.

Should prioritize fixing this on the pendant.

A more specific STR + video to come.

**Comment by liuche** [comment]
@haldeman99 to clarify.

**Comment by liuche** [comment]
The 2.2 versions on-device repro on both cube and pendant, doesn't happen on Stick.

However, building from master, I cannot repro on either device.
Cube: OS version of the device is Fire OS 6.2.2.3 (NS6223/1852)
1. Open Firefox, play YT video
2. Say "Alexa, go home", returns to Fire TV home screen
3. Click on Firefox app to open
4. Video is still there

Pendant OS version is Fire OS 6.2.5.3 (NS6253/1431)
1. Open Firefox, play YT video
2. Hold microphone button on remote, say "Go home", returns to Fire TV home screen
3. Click on Firefox app to open
4. Video is still there

Didn't test on Stick with master, I assume it works.

@Sdaswani can we send Amazon a LAT or something so they can test on their devices? I think this might just be fixed but I'd like them to verify it, in case the OS versions are different. Also, since we're close to finishing 3.0 anyway, if this is fixed we should just ship the fix with 3.0 rather than a dot-release.

**Comment by Sdaswani** [comment]
@liuche I think a LAT is a good idea - is master in a LAT-able state?

**Comment by liuche** [comment]
@Sdaswani kind of - the Fire TV Stick is crashing on start but we won't get a fix in till tomorrow. However, this STR can be tested without that because it doesn't affect stick. We could also cut a branch from 7742000

**Comment by Sdaswani** [comment]
I think waiting for a fix and then LATing master tomorrow is fine @liuche .

**Comment by haldeman99** [comment]
Is master 3.0, or 2.1?

**Comment by Sdaswani** [comment]
master is 3.0 @haldeman99

**Comment by haldeman99** [comment]
Great, if you invite me to the LAT, I can verify.

**Comment by liuche** [comment]
@Sdaswani to check with @haldeman99 when the Fire TV Stick will get an OS update that fully supports MediaSession.

**Comment by liuche** [comment]
I think this is blocked on #1108 landing, because it also affects restoring the browser fragment.

**Comment by Sdaswani** [comment]
@haldeman99 confirmed this is fixed! 😊
