### ISSUE TITLE
Redundant home tile image resources

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1092]
```sh
find . -name "*youtube*"
...
./app/src/main/res/drawable-xxxhdpi/tile_youtube.png
./app/src/main/assets/bundled/tile_youtube.png
```

**Comment by mcomella** [comment]
Impact:
- We're shipping a few extra kb of images
- If we ever change this code or the asset, we may use the wrong one and create a bug. Until then, it's not really a problem (beyond the image sizes)

**Comment by athomasmoz** [comment]
@mcomella is this still an issue after the recent homescreen updates?

**Comment by mcomella** [comment]
Yes but it's trivial to fix so I'll just do it.

**Comment by mcomella** [comment]
QA: we removed a redundant youtube asset. Make sure the bundled YouTube tile's icon remains the same. The only time the image is set is on start-up so I do not expect testing this to require any extra amount of "breaking" testing to be necessary.
