### ISSUE TITLE
Update Firefox logo

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1095]
The colour of the word 'Firefox' in the logo needs to be updated.

**Comment by aminalhazwani** [comment]
Thanks for opening the issue @dnarcese, here https://github.com/mozilla-mobile/firefox-tv/wiki/Design#assets you can find the exported assets 🙂 Let me know if the exported sizes reflect the resolution densities and if you prefer a different naming, thanks!
