### ISSUE TITLE
Navigation history not preserved

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1099]
Build: 6dc3e493daba124e58d8d4af397c3ba5cb9aa75c

Run in Android AVD (1080P) API 27

1. Visit http://example.com
2. Tap the menu button
3. Go to Settings, and return (hit back)
4. Visit http://mozilla.org
5. Tap the menu button

Expected to see the back button accessible. It is greyed out.

I should be able to return to example.com as my first visited URL

**Comment by AaronMT** [comment]
Reproducible on a Fire TV Cube device too

**Comment by liuche** [comment]
Looks like this is blocking #1083 which is in the 3.0 sprint.

**Comment by npark-mozilla** [comment]
Another STR:
go to google.com
go to imdb.com
go to youtube and open a video, play it
Open tiles page, press back button to traverse the history

Expected:
All sites should be shown
Actual:
google.com and imdb.com is not shown while pressing back button.  But when it reaches firefox:home, press forward, google.com and imdb.com will be shown.  This is on Basic TV Stick.

**Comment by AaronMT** [comment]
This should block 3.0
