### ISSUE TITLE
Unable to remove custom pinned tiles

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1100]
Build: 6dc3e493daba124e58d8d4af397c3ba5cb9aa75c

Run in Android AVD (1080P) API 27

1. Visit http://example.com
2. Tap the menu button
3. Tap Pin
4. Long tap on the example tile
5. Tap remove or tap the pin icon

Expected to see the new tile removed. Tapping remove does nothing.

**Comment by liuche** [comment]
@AaronMT is this reproducible on API 25? For reference, since the devices currently only support API 22 and 25, ideally we should mainly test on that.
