### ISSUE TITLE
Menu press on Pocket video feed should open overlay

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1109]
## Steps to reproduce
From clean start
- Open pinned site
- Click menu
- Open pocket
- Click menu

### Expected behavior
@aminalhazwani Should this go back to the main menu, or to the previously opened site?

### Actual behavior
Nothing happens

### Device information
Device: Fire Cube, smaller TV in office
Fire OS: 6.2.2.3
Commit: e0ae14e04f35f94a600385c8e34d5d62886d52c1

**Comment by aminalhazwani** [comment]
Menu button should always open the menu unless otherwise indicated. So in this case it can open the overlay menu with the Pocket tile focused.
