### ISSUE TITLE
Enable link to expose Pocket megatile error screen

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1111]
The screen added in #889 needs a simple UI test.

**Comment by dnarcese** [comment]
A link needs to be added to expose this screen so that it can be tested.
eg navigating to 'firefox:error:pocketConnection' will show the error screen

**Comment by npark-mozilla** [comment]
renaming the title, will create a separate bug for UI test

**Comment by AaronMT** [comment]
On master I attempted to go to _firefox:error:pocketconnection_ (according to  `${APP_URL_PREFIX}error:pocketconnection` but that yielded a WebView error. What's the link?
