### ISSUE TITLE
[a11y] No accessibility string for "help/more information" button on Pocket feed

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1125]
We definitely won't have time to localize this for 3.0, but we should get a string for this "help/info" button. @BrianNJones what do you think?

Right now, a11y just announces "Button".
Here's a screenshot of the button highlighted - VoiceView announces "Button".
![help](https://user-images.githubusercontent.com/1082253/45626453-e7644d00-ba8f-11e8-8706-f54de431d27d.png)

Clicking this button will re-show the onboarding screen that introduces the Pocket video feed feature.
![pocket-intro](https://user-images.githubusercontent.com/1082253/45626964-17602000-ba91-11e8-86d8-d76c1fcd4026.png)

See this comment for more context:
https://github.com/mozilla-mobile/firefox-tv/issues/828#issuecomment-382710975

**Comment by liuche** [comment]
In the meantime, @BrianNJones could we use the string "Recommended videos" or "Video recommendations by Pocket"? Neither really explains this "more info" button very well.

**Comment by liuche** [comment]
@eejay can you also let us know how important this is? The "?" button re-shows the onboarding UI that was already shown so the button isn't "critical" UI, but the lack of labeling is bad. Also, any thoughts on non-localized (for 3.0) or localized?

**Comment by bbinto** [comment]
I'd suggest to go with a) for first launch and follow-up with a bug fix soon after (3.1)

**Comment by BrianNJones** [comment]
@liuche @bbinto , is there a reason we can't use: 
The most interesting videos on the Web. Recommended by Pocket, now part of Mozilla.

**Comment by liuche** [comment]
@BrianNJones sorry for this being so out of the loop: the string for this is for the "help" button (which is the question mark), so the use case is:

(in accessibility mode)
1. Open Pocket Fragment
2. Move selection to "?" button

I would think having the "?" announce "The most interesting videos on the Web. Recommended by Pocket, now part of Mozilla." seems redundant. 
Maybe something like "More information about Pocket" or "Pocket help"?

**Comment by liuche** [comment]
@BrianNJones any thoughts on this?

**Comment by BrianNJones** [comment]
I'd vote for redundant here. It may be redundant, but it's contextual and probably helpful.

**Comment by BrianNJones** [comment]
> 
> 
> Okay, sounds good.
> 
> So just to confirm, @BrianNJones, the flow would be like this:
> 
>     1. move to "?" button on homescreen
>        Announces: "The most interesting videos on the Web. Recommended by Pocket, now part of Mozilla."
> 
>     2. Click "?", re-launches onboarding:
>        Announces: "Introducing Videos recommended by Pocket"
> 
>     3. Move down (announcing same thing as 1)
>        Announces: "The most interesting videos on the Web. Recommended by Pocket, now part of Mozilla."
> 
>     4. Move down:
>        Announces: "Okay, got it" "Button"

Yes, thank you, liuche!

**Comment by mcomella** [comment]
@BrianNJones While I think this is cleverly more efficient for screen reader users, from a developer's perspective I'm concerned about providing a different experience for certain users over others. For example, if the onboarding or help experience changes drastically (e.g. perhaps including new configuration options), we may forget to update this string to take into account those changes and screen reader users may not be able to take advantage of that experience. In the worst case, screen reader users can be missing out on new options, information, or onboarding. It goes back to the principle that the most inclusive experience for all users is generally the same.

What do you think? Do you think we should modify the string at all?

**Comment by mcomella** [comment]
@eeejay ^ Do you have any thoughts?

**Comment by eeejay** [comment]
So the issue is how to label the "?" button? I think it should give the same information a sighted user would have (ie. not much). So it should just be labelled something like "information", or "about pocket".

(putting the text content of the next screen as the label does not make things easier for the user.. they will still click on it, and it doesn't describe the button)

Is part of the issue here that we missed some string freeze and can't introduce new ones? I would say using an unlocalized one is better than nothing..

**Comment by BrianNJones** [comment]
My initial impulse was to prioritize context, but Eitan's "should have the
same information a sighted user would have (ie.  not much)" makes more
sense. (It's also the most accurate context, now that I think about it.)

Thanks!
Brian

**Comment by liuche** [comment]
Okay, sounds good - I'll wait to get more strings from @BrianNJones, and open another PR.

**Comment by BrianNJones** [comment]
"About Pocket"
