### ISSUE TITLE
Menu button unresponsive during loading

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1134]
## Steps to reproduce
From fresh install
- Select any tile
- Select the menu button

### Expected behavior
- Menu should open

### Actual behavior
- Menu does not open

### Additional information
- We handle key presses in `BrowserFragment#handleSpecialKeyEvent`
- Menu presses are only handled if the current URL is not our home screen
- As described in https://github.com/mozilla-mobile/firefox-tv/issues/1081, URL does not update until a website has almost finished loading
- Therefore, when the user has no session history, the menu button becomes unresponsive during loading

### Device information
Samsung
* Fire TV device: Stick
* Firefox version: 0165b0b94e9e98a6977262b9c074ec6e818b3cde

**Comment by liuche** [comment]
I'm also sometimes hitting a state where the arrow buttons don't work, and only the menu button works.

**Comment by Baron-Severin** [comment]
@liuche Opened https://github.com/mozilla-mobile/firefox-tv/issues/1142 for that arrow button bug.
