### ISSUE TITLE
Travis CI failure

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1138]
Currently Travis CI is failing, causing PR merge blocks

```Exception in thread "main" java.lang.RuntimeException: Gradle distribution '/home/travis/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1' does not contain any directories. Expected to find exactly 1 directory.```

**Comment by mcomella** [comment]
From [the raw log](https://api.travis-ci.org/v3/job/430119591/log.txt):
```
/home/travis/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4-all.zip: Permission denied
```

Looks like the CI system isn't letting us unzip, which would create the directory it's missing.

**Comment by mcomella** [comment]
Potentially workaround, chmod the file?

**Comment by mcomella** [comment]
I wonder if upgrading the gradle version or gradle plugin would also fix this issue.

**Comment by mcomella** [comment]
Worth noting focus doesn't have these issues. I also saw this in the android-components logs:
```
Downloading https://services.gradle.org/distributions/gradle-4.4-all.zip
...
Unzipping /home/travis/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4-all.zip to /home/travis/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1
Set executable permissions for: /home/travis/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4/bin/gradle
```

I don't see this in our logs.

**Comment by mcomella** [comment]
`--no-daemon` didn't fix anything either. My next steps would be comparing our:
- .travis.yml with components
- Our output logs with components
- Our travis configuration (through the website UI) with components

But I'm going to leave this to the TV team.

**Comment by mcomella** [comment]
Maybe our dependency versions too.

**Comment by psymoon** [comment]
Looks to be cache fetching timeout issue.

From Travis CI docs:

> Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source:

    Android SDKs
    Debian packages
    JDK packages
    Compiled binaries
    Docker images

Docker images are not cached, because we provision a brand new virtual machine for every build.

**Comment by psymoon** [comment]
Purging cache works
