### ISSUE TITLE
Send Sentry report for SSL errors

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1140]
The telemetry event `sslErrorEvent` exists but is not implemented.
To implement, SSL errors need to be handled separately. An [issue](https://github.com/mozilla-mobile/android-components/issues/804) was filed in android components to help make the implementation easier.

**Comment by liuche** [comment]
@bbinto is this something you care about? Please help prioritize.

**Comment by pocmo** [comment]
Afaik this was just inherited from Focus (where we wanted to see how a specific SSL error affected our users) and was never intended to be a probe we ship / care about in Firefox for Fire TV?

**Comment by bbinto** [comment]
I think we can take it out (for now), not worry about it now.
