### ISSUE TITLE
Enhance Turbo Mode onboarding screen

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/firefox-tv#1147]
### Why/User Benefit/User Problem

We introduce Turbo Mode on first app launch but we don't show how Turbo Mode looks in the app - aka rocket icon.

### What / Requirements

Add a rocket icon to the Turbo Mode onboarding. Potentially we could also add a section of the screen so that users see where they are going to find the Turbo Mode button.

**Comment by aminalhazwani** [comment]
@liuche I uploaded the two proposal with the web inspector, see "Turbo Mode Onboarding" here https://github.com/mozilla-mobile/firefox-tv/wiki/Design#mocks-with-a-web-interface

And in case we opt for option 2 I added the asset here https://github.com/mozilla-mobile/firefox-tv/wiki/Design#assets

Option B can be animated (we could create a video that we bundle with the app) or can also be a static image.

Both option A and B use the same buttons and typography as the Pocket onboarding, just posting this for reference:

<img width="792" alt="screen shot 2018-09-20 at 3 57 44 pm" src="https://user-images.githubusercontent.com/1721875/45823420-f811fe80-bced-11e8-9aeb-2c80afe69581.png">

I lean towards option B (with or without video) as it displays the product, the brand, the turbo mode button/icon and sets the right expectations. Option A is a bit too anonymous, we could add the Firefox brand there as well but it might still be detached to the product.

**Comment by Baron-Severin** [comment]
@BrianNJones We're updating this layout to match the following link.  It includes a large image over the top half of the screen, what should its content description (i.e., accessibility string) be?

https://firefoxux.github.io/people/aalhazwani/firefox-for-fire-tv/turbo-mode-onboarding/index.html#artboard1

**Comment by Baron-Severin** [comment]
> @Baron-Severin @aminalhazwani
> Turbo Mode helps you browse faster
> Turbo Mode automatically blocks ads and trackers. If a site doesn't act the way you expect, try turning it off.

@BrianNJones I don't understand, is this entire string the image's content description?  Do we need the line break?  I'm not sure how line breaks are handled by Talk Back.

**Comment by aminalhazwani** [comment]
@Baron-Severin this is how we could set the line break:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/1721875/46461492-13393f80-c7bf-11e8-8ce1-4e751ce3dd2c.png">

The distance between the text and the buttons remains unvaried.

**Comment by Baron-Severin** [comment]
FYI @BrianNJones @Sdaswani I'm blocked here until I hear back about the content description for that image.  Is there anyone else I need to be reaching out to?

**Comment by BrianNJones** [comment]
@Baron-Severin @Sdaswani , sorry thought we were clear w/Amin's feedback.

**Comment by Baron-Severin** [comment]
@BrianNJones To clarify, the text on the bottom half of the screen is fine.  We're completely clear there.  Users with Talk Back enabled (for example, users with poor / no vision) need to be read a description of the image on the top half of the screen when they click on it.  That description is what we're currently missing.  After that, we're good to go.
