### ISSUE TITLE
New screenshots for Amazon store

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1150]
Our app looks really different now, we should either make the banner match, or even make it look better. (top right corner)
![tv-firefox](https://user-images.githubusercontent.com/1082253/45765817-48c62080-bc36-11e8-9198-ecc45ea5c699.png)

@aminalhazwani thinks the Silk banner looks a lot better:
![tv-silk](https://user-images.githubusercontent.com/1082253/45765832-511e5b80-bc36-11e8-9602-2df99f59d66a.png)

**Comment by liuche** [comment]
@lwa-moz also, do you need other details for marketing from us? We can give you a changelog, but anything in addition?

**Comment by lwa-moz** [comment]
No additional details necessary, but if @aminalhazwani has a recommendation for the screenshot to use, I want to make sure he's happy!

**Comment by aminalhazwani** [comment]
Hello there, some of the aspects that we could consider for the next Amazon store banner are the following. If we want to display the product - aka Firefox:

- make the banner more bright and light full
- use a more modern scenery and TV
- keep a perpendicular perspective
- don't include TV remotes as the browser is controllable only via the Fire TV remote

If we want to display something more abstract:

- create something new or 
- reuse existing assets that we used for the promotion of Firefox in general. This could be photos, illustrations or more abstract drawings.

We should also consider that the asset will be used in two screen. This one:

![homescreen-1](https://user-images.githubusercontent.com/1721875/45819370-6ea9fe80-bce4-11e8-8926-025c7171c862.png)

And this one:

![homescreen-2](https://user-images.githubusercontent.com/1721875/45819374-72d61c00-bce4-11e8-87e2-315a0c283b93.png)

And then of course we also need to update the app screenshots 🙂 

![homescreen-3](https://user-images.githubusercontent.com/1721875/45819673-3d7dfe00-bce5-11e8-8d93-ce9516020578.png)
