### ISSUE TITLE
File serious Sentry issues from top 10-20 issues

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1152]
https://sentry.prod.mozaws.net/operations/firefox-tv/?query=release%3Aorg.mozilla.tv.firefox-2.1&sort=freq

- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/1159 Fatal exception on out of order Telemetry events

**Comment by athomasmoz** [comment]
@Sdaswani Can we close this? We are monitoring Sentry in our triage meetings
