### ISSUE TITLE
"OK, got it!" button is too short

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/firefox-tv#1154]
![pocket-onboarding_1537377917803](https://user-images.githubusercontent.com/3644868/45772219-5cc64e00-bc47-11e8-997c-883dcacf08a6.png)

Some locales have text overflowing the button (French), others text spanning two lines (Italian), German has both.

Side note: if possible, we should avoid transforming text to uppercase via system or CSS.

**Comment by aminalhazwani** [comment]
@liuche is it possible to make the button grow responsively based on the length of the content?

**Comment by liuche** [comment]
This should be fixed by #1148 - I think this button has a hard-coded size for some reason........
