### ISSUE TITLE
Holding menu button flashes between tiles view and webpage view

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1156]
## Steps to reproduce
- Open a webpage
- press and hold menu button
### Expected behavior
- go back to tile view, and stay there

### Actual behavior
- rapidly flashes between the tile view and web view

### Device information

* Fire TV device: Basic TV stick
* Firefox version: master branch

**Comment by aminalhazwani** [comment]
@liuche when VoiceView (https://www.amazon.com/gp/help/customer/display.html?nodeId=202105320) is enabled long press of MENU toggles Review mode on and off.

Is this something that could go in conflict if we let users open the Homescreen with a MENU long press? Also with VoiceView enabled I was able to reproduce the bug (with VoiceView you have to double press MENU to open the Homescreen).

Taking all of this into account what we could do is to display the Homescreen only on MENU single press. If users long press (and hold down) the MENU button nothing happens. What do you think @liuche?

**Comment by athomasmoz** [comment]
Not reproducible with new homescreen behaviour.
