### ISSUE TITLE
Dpad on youtube becomes unresponsive when menu button is held while loading the page

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1157]
## Steps to reproduce
- Open youtube from tile view
- While loading, hold the menu button, let it flash between tiles view and youtube page

### Expected behavior
- After YouTube is loaded, navigation can be done via dpad

### Actual behavior
- Cannot navigate within youtube, but on tiles view, dpad works fine
According to https://github.com/mozilla-mobile/firefox-tv/issues/1104, looks like this bug was fixed, but #1156 makes it possible to reproduce the bug again.

### Device information

* Fire TV device:  Basic TV stick
* Firefox version: master branch.

**Comment by liuche** [comment]
Okay, this looks like #1149 and there's a PR for that so I'm duping this there.
