### ISSUE TITLE
'Try again' button in error dialog is too bright

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#116]
Currently it's in Blue background and white text, which makes it very difficult to see in TV setting.

to reproduce:
type error:-1 in the URL bar.

**Comment by Sdaswani** [comment]
@lime124 @shorlander thoughts?

**Comment by npark-mozilla** [comment]
Rechecked the UI, now the color seems to be toned down, and the caption is legible.
