### ISSUE TITLE
Use Ember fonts

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/firefox-tv#1165]
### Why/User Benefit/User Problem

Matches OS system fonts as we also do on other platforms

### What / Requirements

Set text and type to Amazon Ember

### Acceptance Criteria (how do I know when I’m done?)

As above.

**Comment by dnarcese** [comment]
[Link to font assets](https://drive.google.com/drive/folders/1fqq2BHES5wT4dqiJ-TyOtFr8Kl8-0hNq)

**Comment by mcomella** [comment]
@dnarcese Are these just available through the system like they are on
Show?
https://searchfox.org/mozilla-mobile/rev/c906286050b69fb6b55fc4e69a99d8cb899d698a/firefox-echo-show/app/src/main/res/values/ember_fonts.xml

If not, to be explicit, are we allowed to commit the font assets or do they
need to be bundled at compile time?

**Comment by dnarcese** [comment]
@mcomella Looks like they are available through the system! In that case, we don't actually need the assets :)

**Comment by mcomella** [comment]
@dnarcese It'd be dope to share that ember_fonts.xml file in a-c
(follow-up?). :) @pocmo It feels like a new "Fire OS" (as opposed to
"Amazon products") module would be most appropriate here: what do you think?

**Comment by dnarcese** [comment]
> It'd be dope to share that ember_fonts.xml file in a-c (follow-up?). :) 

I filed #2056 to do this!

**Comment by pocmo** [comment]
> @pocmo It feels like a new "Fire OS" (as opposed to "Amazon products") module would be most appropriate here: what do you think?

Yes! When I started reading this from issue from the top I also thought about "something something Fire OS". :)
