### ISSUE TITLE
Add title to Homescreen sections

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/firefox-tv#1166]
### Why/User Benefit/User Problem

Enable users to identify what the section is about

### What / Requirements

Add a title above the Pocket megatile "Videos reccomended by Pocket" and above the pinned tiles grid "Pinned sites".

## Design

Source file is available on Google Drive `~/Firefox - Fire TV/Mocks/FFTV-master.sketch

**Comment by mcomella** [comment]
We've already started to do this.
