### ISSUE TITLE
Video does not fullscreen on bbc.com/ideas and m.youtube.com

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1172]
## Steps to reproduce
1. Navigate to bbc.com/ideas or m.youtube.com
2. Play a video
3. Fullscreen video

### Expected behavior
Video should fill the viewport.

### Actual behavior
Video is only in top left corner, but progress bar correctly fills to the screen width.
![device-2018-09-20-170405](https://user-images.githubusercontent.com/11432165/45847254-7378ad80-bcf8-11e8-8427-15fb3fe2c421.png)

### Device information
* Fire TV device: Pendant
* Firefox version: master [`d0422f5`](https://github.com/mozilla-mobile/firefox-tv/tree/d0422f5c7a70dbf1777b9a7e556b179d608ee4b6)

**Comment by liuche** [comment]
I updated fullscreen bug #938 to be more general and handle these other fullscreen problems too, so going to dupe the two.
