### ISSUE TITLE
Taskcluster release/LAT build broken: accept licenses

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1173]
We have a Taskcluster task to build an (unsigned) apk when we make a release (similar to Focus), which includes our Pocket and Sentry keys so they don't get forgotten by accident, but right now it's broken because we have to accept some new Android licenses.

Taskcluster task: https://tools.taskcluster.net/groups/YRTejeLaQSm-OvsGibCnCg
Commit: "Version bump to 2.2.0.2 for new LAT." c6d19ac875e106aede5073de8f4c4f11a5e3ddc9

```
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
    platforms;android-27 Android SDK Platform 27
 To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
 Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by liuche** [comment]
Hm, it looks like Focus has a different Docker file now - @pocmo is there a better way to update Docker images than building them locally? Otherwise, I'll see if I can just do this.

**Comment by pocmo** [comment]
No not really. We haven't automated building the Docker images. Something we could consider doing eventually.

In this case: Your docker image is using `sdkmanager`. You may be able to just run `yes | sdkmanager --licenses` at the beginning of your task. This should accept all new licenses. This may be a faster way to unblock you here.

Eventually you probably still want to update your Docker image to avoid the build process having to re-download the updated SDK for every build.

**Comment by liuche** [comment]
Updated the TC release docker image to match the ones for PRs, which fixes this issue, see green release build task:
https://tools.taskcluster.net/groups/Ofm4Ph1aSoS-i-1CsVWfuQ
