### ISSUE TITLE
Sleeping while watching videos

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#1175]
From a user support email:
"I just downloaded Firefox for FireTV and tried streaming some videos. I made the video fullscreen and and everything seemed fine until my Fire TV went to sleep. I did not have this problem with Silk browser, so I was wondering if there was was possible to be fixed.
Thanks"

**Comment by Sdaswani** [comment]
@liuche @Baron-Severin can you reproduce this? I thought we didn't do this especially given our long session times but maybe we always have. Can we fix?

**Comment by mcomella** [comment]
afaik, sleeping and not sleeping is handled by the WebView when it infers it's playing videos so I'm surprised this is happening: I wonder if it's a platform bug? I wonder if we can figure out which device they see these issues on.

**Comment by Sdaswani** [comment]
I did ask for the user's fire os and firefox version. I will also ask about their tv and fire device too.

**Comment by Sdaswani** [comment]
Fire OS version 5.2.6.6
Firefox Fire TV version 2.1
TV is Westinghouse 1080p
Device is Fire Stick Gen 2

**Comment by Baron-Severin** [comment]
I've reproduced with our office Stick on m.youtube.com, and I have a fix.  I have a question on the expected behavior though.  @athomasmoz do we want to prevent the browser from going to sleep:
-> when video is fullscreened?
-> when video is playing?
-> always?

**Comment by Baron-Severin** [comment]
FYI @athomasmoz @Sdaswani We're blocked here until we have an answer to the question about desired behavior in https://github.com/mozilla-mobile/firefox-tv/issues/1175#issuecomment-427528506

**Comment by Sdaswani** [comment]
My vote is only when the video is fullscreened, as there is intent that the user wants to keep the video playing (like I have the tv on in the background now).

**Comment by athomasmoz** [comment]
Agreed, we should do it when video is in fullscreen. That also matches the behaviour on other devices.
