### ISSUE TITLE
BrowserNavigationOverlay class is too long (detektCheck)

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1187]
Adding new lines of code to BrowserNavigationOverlay class fails deketCheck:
`LargeClass - 150/150 - [BrowserNavigationOverlay] at firefox-tv/app/src/main/java/org/mozilla/focus/browser/BrowserNavigationOverlay.kt:68:1`

@mcomella's quick suggested solution is to remove `BrowserNavigationOverlayScrollView` and `NavigationEvent`

**Comment by athomasmoz** [comment]
User Benefit - fixing this would make it easier to make changes to this class in the future.

**Comment by mcomella** [comment]
fwiw, it might be worth breaking out the home tiles as a new component which might mean we want to wait before changing this. Or maybe our changes would help break it out. :)

**Comment by Baron-Severin** [comment]
Without any good quick wins, satisfying this requirement really means refactoring `BrowserNavigationOverlay`.  How we do so is dependent upon an upcoming architecture meeting, where we will decide what approach we want to move towards.
