### ISSUE TITLE
Add PR template checklist with "Added tests" item

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1188]
See https://mail.google.com/mail/u/0/#search/review/QgrcJHrnvDFNJNCdmnWPDswbbZwpLHPtbPV for context.

**Comment by athomasmoz** [comment]
User benefit - Better code reviews, because it gives a partially automated checklist.

**Comment by mcomella** [comment]
Due to unauditable danger dependencies, moving to make a PR checklist template instead.

**Comment by athomasmoz** [comment]
Closing as duplicate of https://github.com/mozilla-mobile/firefox-tv/issues/1291
