### ISSUE TITLE
Send usage data doesn't visually take focus

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1189]
![send-usage-data](https://user-images.githubusercontent.com/13170306/46035663-6e30af80-c0b8-11e8-8f86-23b506848a15.gif)

## Steps to reproduce
- Open settings
- Move focus right once
- Move focus left once

### Expected behavior
- 'Send usage data' button should lose then gain focus

### Actual behavior
- 'Send usage data' does not visually gain focus

### Device information
* Fire TV device: Cube
* Firefox version: 5fe30dca9d7cb1d9fb777975de69d6deee845bd0

**Comment by mcomella** [comment]
iirc, VoiceView doesn't have a focused state but non-VoiceView does: I wonder if the boolean check got swapped. For historical context on why we do this, see the blame (or ask me to find it).

**Comment by mcomella** [comment]
Settings was moved to the homescreen.
