### ISSUE TITLE
Write regression test that covers clearing session data

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1192]
### Why/User Benefit/User Problem
This code works, but could easily regress.  If it does so, we need to catch it.

### What / Requirements
Write a regression test that ensures session history is cleared when the user clears data.  If/when we add session restoration logic, this test will fail and we can update how we clear data.

### Acceptance Criteria (how do I know when I’m done?)
Test should:
- Create session history (i.e., fake navigating to sites)
- Navigate to settings
- Clear data
- Test `MainActivity.session` to ensure that the data has been cleared

### Additional Information
This may have to be a UI test, as getting BrowserFragment under test using Robolectric has proven challenging.

**Comment by mcomella** [comment]
We discussed making this a UI test: we *really* want to make sure this is working and the UI control is part of that. To inspect cleared state, we can look at the UI and look at the files on disk if we're happy. There are concerns with how often UI tests run but they should run before release so we should be fine.
