### ISSUE TITLE
On error page, URL in menu, progress bar is replaced with data:...

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1193]
## Steps to reproduce
- Open browser
- Type "firefox:gnome" or other URL which will never resolve
- Click menu

### Expected behavior
URL is "firefox:gnome"

### Actual behavior
URL is `data:...`

![screenshot_1537908683](https://user-images.githubusercontent.com/759372/46042400-1e5ae400-c0ca-11e8-9cac-63bc20eb2db9.png)

This also affects the progress bar when changing sites:
![screenshot_1537908720](https://user-images.githubusercontent.com/759372/46042423-32064a80-c0ca-11e8-98cc-edb43c285204.png)

Can we write a regression test for this? Or file a follow-up to do so.

**Comment by mcomella** [comment]
We used to handle this behavior ourselves but now I think it's moved to components. I wonder if we can have them use the old behavior to fix this issue.

**Comment by mcomella** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/865 so we can override this specific `data:` URI. afaik, obfuscating all `data:` URIs could be a security risk: see my review.

**Comment by Sdaswani** [comment]
I have to say I don't think it's usual for folks to put in other schemes other than http: or https:, but maybe the progress bar case is more usual? @mcomella can you speak more about how often you see this defect surfacing?

**Comment by mcomella** [comment]
This occurs whenever a user navigates to a page which would cause an error,
e.g. no network connection, broken link, did not input url correctly.

**Comment by Sdaswani** [comment]
Ok happy to see A-C 25 fixes it.
