### ISSUE TITLE
java.net.URISyntaxException: Expected scheme-specific part at index

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1195]
## Steps to reproduce
- User types in invalid URL like "fgh:"

### Expected behavior
Error page loads.

### Actual behavior
Crash! Under some conditions: looks like we may need to a "security change".

This is a components issue: see https://github.com/mozilla-mobile/android-components/issues/863

### Device information

* Fire TV device: ?
* Firefox version: ?

**Comment by athomasmoz** [comment]
This issue will occur with any input that won’t be parsed as a search and is an invalid URI

**Comment by Sdaswani** [comment]
Looks like the new components build will address this.
