### ISSUE TITLE
Create component for home screen tiles

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1197]
### Why/User Benefit/User Problem
The homescreen code has the potential to be re-used including:
- HomeTileGridNavigation
- HomeTileScreenshotStore
- Bundled (and localized) tiles?

We can better decouple and test the code if we moved it out to a component. Users will benefit because we'll be able to more easily make changes in these features that affect all of our devices more quickly.

### What / Requirements
- Figure out which code to split it out
- Write it as a component iteratively (i.e. file more bugs to work on here)
- Re-integrate with code
- Figure out how we'll handle telemetry

**Comment by liuche** [comment]
One comment here: the TV preview mocks that Amin showed us at SF allhands moves away from a grid, and towards a "pocket-style swipe tiles". So we probably won't want to reuse *GridView anymore, and actually try to pull the Pocket feed out into a component. I thought I filed a bug about this, maybe @dnarcese would remember if there is one...?

**Comment by dnarcese** [comment]
There doesn't seem to be anything filed for that.

**Comment by mcomella** [comment]
> mocks that Amin showed us at SF allhands moves away from a grid, and towards a "pocket-style swipe tiles". So we probably won't want to reuse *GridView anymore, and actually try to pull the Pocket feed out into a component.

Good point. We can still pull out our model code (`HomeTileScreenshotStore` and friends) though.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
