### ISSUE TITLE
APP_URL_POCKET_ERROR is unused?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1198]
I only see us switching over it but not us defining it: https://github.com/mozilla-mobile/firefox-tv/search?q=APP_URL_POCKET_ERROR&unscoped_q=APP_URL_POCKET_ERROR

**Comment by dnarcese** [comment]
This URL was only added for testing purposes, so that there is an easier way to show the error screen.

**Comment by mcomella** [comment]
It looks like it gets used.
