### ISSUE TITLE
Show progress indicator for page loading on overlay

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1199]
### Why/User Benefit/User Problem
There is no feedback to the user when a page is loading (from navigating to a new url or refreshing) while on the overlay menu. This could be confusing, especially in the case of refreshing since the overlay doesn't hide automatically to show the webview progress indicator.

### What / Requirements
Ideas:
- Make the existing progress indicator also visible on the overlay
- Show some kind of progress indicator in the url bar of the overlay

### Acceptance Criteria (how do I know when I’m done?)
Visual progress is provided on the overlay screen when a page is being loaded or refreshed.

**Comment by athomasmoz** [comment]
@dnarcese is this still an issue? When I click refresh or go to a new URL, it takes me to the browsing screen, rather than staying on the overlay

**Comment by dnarcese** [comment]
@athomasmoz No, since we changed the behaviour this is not an issue anymore.
