### ISSUE TITLE
Focus lost from initial homescreen on menu button press

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1202]
## Steps to reproduce

1. Fresh install
2. On homescreen, press menu button twice
3. Press any dpad button

### Expected behavior
Focus should change depending on dpad button.

### Actual behavior
Nothing happens. Pressing menu button again brings back the focus to the homescreen.

### Device information

* Fire TV device: Pendant
* Firefox version: master [`e869530`](https://github.com/mozilla-mobile/firefox-tv/commit/e869530c2be44344627723c83defdf3af395a2be)

**Comment by mcomella** [comment]
I was able to reproduce this on v2.2 so probably not v3.0 worthy.

**Comment by mcomella** [comment]
My STR requires hitting the menu button twice.

When reproducing, dpad events don't go through `MainActivity.dispatchKeyEvent` anymore. Note that key events going into web content will go through this method though.

**Comment by mcomella** [comment]
I tried to see who handled the menu presses but it seems we're not handling it at the `onDispatchKeyEvent` level, unless we're mutating state. Here's the code I used:
```kotlin
        return listOf(Pair("media", { videoVoiceCommandMediaSession.dispatchKeyEvent(event) }),
                Pair("bf", { (maybeBrowserFragment?.dispatchKeyEvent(event) ?: false) }),
                Pair("super", { super.dispatchKeyEvent(event) })).any {
            val handled = it.second.invoke()
            if (handled) {
                Log.d("lol", "handled: ${it.first}")
            } else {
                Log.d("lol", "not handled: ${it.second}")
            }
            return handled
        }
```

`InlineAutocompleteEditText.onKeyPreIme` is also called, but it never returns true either.

Neither (nor `InlineAutocompleteEditText.onKey`) receives the subsequent key events until menu is hit again.

**Comment by mcomella** [comment]
I get the following outputs on each button press:
```
2018-09-26 17:32:55.844 3567-3842/? W/bt_btif: bta_hh_co_is_peer_amazon_remote: result = 1, vid = 0x1949, pid = 0x410
2018-09-26 17:32:55.844 3567-3842/? W/bt_btif: bta_hh_co_is_no_unsniff_amazon_remote: result = 1, vid = 0x1949, pid = 0x410
2018-09-26 17:32:55.847 3567-3842/? W/bt_btif: bta_hh_co_is_peer_amazon_remote: result = 1, vid = 0x1949, pid = 0x410
2018-09-26 17:32:55.847 3567-3842/? W/bt_btif: bta_hh_co_is_no_unsniff_amazon_remote: result = 1, vid = 0x1949, pid = 0x410
2018-09-26 17:32:55.847 3450-3100/? E/AmazonInputManagerService: Toggle bit button map has not been initialized!
```

This is the same output as #1110.

**Comment by athomasmoz** [comment]
@AaronMT do you mind testing this one out? Wondering if it's still an issue

**Comment by AaronMT** [comment]
On the home-screen pressing menu does nothing on my 4K. I can directionally input perfectly fine.

**Comment by dnarcese** [comment]
I just ran into this again. I can reproduce by clicking the menu button twice. It only works once from a fresh install, but it is continuously reproducible after every fresh install.

**Comment by mcomella** [comment]
I can no longer reproduce as of f85091396b3e4eefef129378e39d2cdf6ca78a0a (master after v3.7.1).
