### ISSUE TITLE
When removing a pinned tile for the current page, pin in navigation bar doesn't update immediately

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1210]
## Steps to reproduce
- Go to a website (apple.com)
- Open menu
- Pin site
- Scroll to apple in home tiles
- Long-press, remove

### Expected behavior
Pinned icon turns into unpinned

### Actual behavior
Icon remains pinned. The icon updates to unpinned if you move your focus up to the navigation bar at the top.

Here's an example where I unpinned IMDB but it still appears as pinned when I'm on the website:
![image](https://user-images.githubusercontent.com/759372/46115038-2f7b2200-c1aa-11e8-92b3-c9285ffa981f.png)

### Device information

* Fire TV device: 4k
* Firefox version: v3.0

**Comment by dnarcese** [comment]
Dupe #1249
