### ISSUE TITLE
Website not fit for display

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1217]
Running e869530 on a FireTV Cube in the office on a 1080p monitor.

Visit amazon.com, see picture

![image](https://user-images.githubusercontent.com/102331/46155388-2b501280-c245-11e8-840a-800bcf6febb9.jpeg)

I can't scroll to the left to reveal and access the menu bar e.g, on Amazon.

Silk doesn't have this issue.

**Comment by mcomella** [comment]
@AaronMT What does the Silk look like? I'm trying to reproduce and:
- I can reproduce on Firefox, though it's not as bad
- Silk has the same problem but displays the desktop site so it doesn't look as bad as Firefox

This looks like overscan to me, for which we have #1055 to handle. @AaronMT Would you agree? Do you think we should dupe?

**Comment by AaronMT** [comment]
Yeah it's #1055
