### ISSUE TITLE
Turning off Turbo mode in Onboarding doesn't toggle the overlay button

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1218]
## Steps to reproduce
From fresh install, on the Turbo mode onboarding screen, click 'Turn off'.

### Expected behavior
Turbo mode button in navbar is unselected.

### Actual behavior
Turbo mode button in navbar is still selected until you navigate to a different fragment (ie settings page or Pocket feed) and then re-open the overlay.

### Device information

* Fire TV device: Pendant
* Firefox version: master [`e869530`](https://github.com/mozilla-mobile/firefox-tv/commit/e869530c2be44344627723c83defdf3af395a2be)

**Comment by mcomella** [comment]
In #1210, we similar forget to update the nav state: I wonder if our invalidation got messed up in one place that syncs with this.

**Comment by AaronMT** [comment]
tracking 3.1?

**Comment by AaronMT** [comment]
Still reproducible on master (056c157218683ce4f03d1f53ababed4205bd643c)
