### ISSUE TITLE
[1364] #6/7: Implement Web configuration test

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1220]
*edit: this is probably more up-to-date and concise.*

Some of our web configurations are product requirements and they're easy to break. If possible, we should test this through the WebView so to ensure things are working if components change, or we add GeckoView. Things to test:
- User agent (ensure it doesn't contain device identifier)
- Video autoplay is enabled (necessary for YouTube experience)
- Downloads are disabled
- File access is disabled (note: `file:///android_asset/` is always accessible)
- https://github.com/mozilla-mobile/firefox-tv/issues/1220

---

*edit: Initial bug filing.*

### Why/User Benefit/User Problem
Amazon has asked us to do a few things:
- Set the user agent in a certain way
- Disable downloads
- iirc, Disable file access

Additionally, there are some important settings we don't want to regress:
- `mediaPlaybackRequiresUserGesture`

We should write tests to ensure these values never change (e.g. accidentally during components updates). We could consider doing an integration test that checks the webView settings directly or, preferably but for more effort, replicate the user use case in which these would fail. Integration tests might be good enough to catch most regressions but may not cover, e.g. settings getting changed when switching between sessions.

### What / Requirements
- Write tests or file follow-up issues to address these tests

**Comment by athomasmoz** [comment]
@mcomella Is this still relevant? If so, how would you prioritize it? These seem like areas that wouldn't be touched often

**Comment by mcomella** [comment]
> These seem like areas that wouldn't be touched often

True though it may be good to make defensive tests: a-c may change this code and break our product.

Then again, now that they have official APIs to set these values (and tests for them), they're less likely to break us than in the past so I'm fine closing this and adding regression tests when we find these features actually regress.
