### ISSUE TITLE
Back/forward navigation broken after fullscreen

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1224]
Split off from #938 (which contained two problems, one of which was fixed)

### Steps to reproduce
1. Go to m.youtube.com, load a video
2. Fullscreen the video
3. Open overlay and click on navigation button to go back

### Expected behavior
Youtube website opens

### Actual behavior
Black screen

### Additional Information
@pocmo noted in slack that A-C is unable to intercept back presses from the WebView, and thinks we will have to call exitFullscreen if one occurs while fullscreen is active.

**Comment by pocmo** [comment]
That's surprising and seems to be wrong. I'll open an issue on our side and then we can investigate.
