### ISSUE TITLE
Fix A-C 25 update style

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1225]
In the interest of time, https://github.com/mozilla-mobile/firefox-tv/pull/1201 was landed functional but incorrectly styled.  The PR should be brought up to our preferred style guidelines.

- Inner function `createErrorResponse` within `CustomContentRequestInterceptor#onErrorRequest` paramaters should be renamed.  `withUri` -> `errorResponseUri`, `withErrorCode` -> `errorResponseCode`

**Comment by athomasmoz** [comment]
No longer exists. A-C now handles it
