### ISSUE TITLE
Remove WebView from view hierarchy in `BrowserFragment.onDestroyView`

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1229]
iirc, we're not doing this right now and if we don't, in theory, the WebView will keep a reference to the previous Context/view hierarchy until it gets added again. This isn't a memory leak persay, but it's using more memory than it should.

CC @Baron-Severin

**Comment by Baron-Severin** [comment]
Good point.  We're already removing it from its parent, but we're doing so in `WebViewCache#getWebView`.  We can just move that code over to `WebViewCache#onDestroy`.

**Comment by mcomella** [comment]
@Baron-Severin This can be removed, right? I'm pretty sure components does this under the hood.

**Comment by Baron-Severin** [comment]
@mcomella I don't really have any context into that, you might want to check with someone from A-C.

**Comment by mcomella** [comment]
Components does this as of https://github.com/mozilla-mobile/android-components/commit/9bd4ad1c9192a17954e109b29b26cebc99325916
