### ISSUE TITLE
Firefox Stuck on Media Players

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1234]
## Steps to reproduce
1. Navigate to watch.cbc.ca (or hgtv.ca)
2. Choose a video to watch and click on it

### Expected behavior
You are taken to the page for that video and it automatically starts playing

### Actual behavior
On latest
* You are taken to the page for that video, and the player loads forever
* Clicking "back" on remote, nothing happens
* If you bring up overlay and click a pinned item or typing in a URL, you are taken back to the CBC video page with the loading spinner

On 2.2
* Firefox crashes

### Device information

* Fire TV device: Cube / Fire TV Stick basic
* Firefox version: see actual behaviour

**Comment by levisacal** [comment]
I was able to repro this on hollywoodreporter.com. Any video on the site loads forever and it eventually times out. Also the site is a top 10 pinned site when launching the browser

**Comment by mcomella** [comment]
We had previous issues with CBC video:
- https://github.com/mozilla-mobile/firefox-tv/issues/488
- https://github.com/mozilla-mobile/firefox-tv/issues/487

**Comment by athomasmoz** [comment]
@psymoon to investigate before next sprint planning

**Comment by psymoon** [comment]
This is most likely platform (webview) or a-c problem. It looks like the session "hangs" and any webview related operations are blocked while Fire-TV UI (overlay, etc) still works

**Comment by dnarcese** [comment]
This looks to be an Amazon WebView bug. Loading the videos on an empty WebView project produces the same behaviour, but it is not reproducible on emulators. @Sdaswani can you follow-up with Amazon?

**Comment by Sdaswani** [comment]
@dnarcese can you 1) link to the plain vanilla webview project here and 2) detail what device you [reproduced the issue](https://github.com/mozilla-mobile/firefox-tv/issues/1234#issuecomment-438831728) on?

**Comment by dnarcese** [comment]
1) plain webview project: https://github.com/mcomella/WebViewRaw
2) I reproduced on Fire TV 4k

**Comment by athomasmoz** [comment]
#1495 may also be the same issue. Should retest that one after fix for this goes in.

**Comment by jamiesonpepper** [comment]
Almost logged a net new bug, but eventually found this reference as I experienced the watch.cbc.ca issue. Is this assigned to someone for a fix or target release in the future or pending on an Amazon WebView fix for a FireOS update?

**Comment by athomasmoz** [comment]
Hi @jamiesonpepper thanks for confirming you experienced this issue as well. The problem is with playing content from JW Player v8 (tracked in #1577 ). You're correct, this is pending a change to Amazon Web View. Unfortunately, I don't have a target date for that, but I will keep this issue updated.

**Comment by athomasmoz** [comment]
Consolidating similar issues. Tracking under #1577
