### ISSUE TITLE
Investigation: Use Geckoview as Rendering Engine

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#1235]
### Why/User Benefit/User Problem
Users want a browser that does more than a plain vanilla 'Webview'.

### What / Requirements
FFTV should be running with Geckoview as it's rendering engine.

### Acceptance Criteria (how do I know when I’m done?)
FFTV is running reliably with Geckoview as it's rendering engine.

**Comment by Sdaswani** [comment]
From @st3fan : Make sure to loop in @pocmo to talk about whether migrating connect to use the engine component here makes sense. If connect is still based on the old focus code base, it may be more work to support GeckoView than to migrate to the engine components which support multiple engines out of the box.

Also @boek and @ekager can help out with this given their experience in Focus. Also sync with @mcomella .

**Comment by mcomella** [comment]
Fire TV is already using the engine component so I think getting it
integrated should just mostly work.

**Comment by pocmo** [comment]
That's interesting. :)

If you want to do what we do in our sample browser then you could introduce a separate build flavor and in that flavor instantiate `browser-engine-gecko(-beta/nightly)` instead of `browser-engine-system` and it should just work.

There will be edge cases where we use WebView features that have no or so far didn't need a GeckoView equivalent (e.g. changing the user agent). This is a list of things we'd need to come up with an add the missing APIs to GeckoView and the engine wrapper if required.

**Comment by Sdaswani** [comment]
> There will be edge cases where we use WebView features that have no or so far didn't need a GeckoView equivalent (e.g. changing the user agent). This is a list of things we'd need to come up with an add the missing APIs to GeckoView and the engine wrapper if required.

@pocmo what happens in these edge cases when there was no GV equivalent - does the call just no-op?

**Comment by pocmo** [comment]
> @pocmo what happens in these edge cases when there was no GV equivalent - does the call just no-op?

Yeah, for example here:

https://github.com/mozilla-mobile/android-components/blob/34600dfa35ecd8d471293b2711b1ef14edd2b802/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L161-L173

The exception is currently settings. If you explicitly flip engine settings that are not supported by the engine then we throw an `UnsupportedSettingException`.

**Comment by Sdaswani** [comment]
ok i think for what we want to do here - just get GV minimally working so we can smoke test - this should be just fine.
