### ISSUE TITLE
Some links from Settings->About page are not loaded

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1238]
## Steps to reproduce
1. Go to Settings -> About
2. Try to access the 3rd (licenses) and the 4th (GNU General Public License v3) link from the page

### Expected behavior
Links are loaded 

### Actual behavior
Links are not loaded

Also was unable to access the last link (here) from the page.

### Device information

* Fire TV device: Fire TV Stick Basic (1st Generation)
* Firefox version: 2.2.0.2

--

**Comment by levisacal** [comment]
The issue is on 2.2.0.2 Master version from 10/01/2018

**Comment by athomasmoz** [comment]
@aminalhazwani  what do you think about having links from the settings page open in the existing browser? This may avoid edge cases like this where certain links don't work.

**Comment by mcomella** [comment]
The only crash on v2.2.0.2 is #1241 (assuming this was built using the LAT): perhaps that's what was seen?

**Comment by aminalhazwani** [comment]
> @aminalhazwani what do you think about having links from the settings page open in the existing browser? This may avoid edge cases like this where certain links don't work.

@athomasmoz we do something similar on Connect. The only downside is that there isn't a quick way to go back to the settings once you get a license webpage.

**Comment by dnarcese** [comment]
Dupe #1731
