### ISSUE TITLE
Display Author on Pocket Videos

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1239]
### Why/User Benefit/User Problem

Right now, when you click into the recommendations, we display the _platform_ attribution (namely, YouTube) directly under the video tile. So even though we have a lineup of videos from, say, Bloomberg, Vox, National Geographic, PBS, HowStuffWorks, and TedEd, they all display as being from YouTube -- since that's simply where the vast majority of them are sourced. The videos I curate from BBC are the only ones that attribute to anything other than YouTube.

Is there any way to make the case that we should show attribution there to the creator of the video, rather than the platform? To credit Bloomberg or National Geographic for instance in the display?

### What / Requirements

* Show author when available

### Acceptance Criteria (how do I know when I’m done?)

* When available, the youtube author is displayed
* When not available, just youtube is displayed

### Notes from Pocket

The API change is live now: for YouTube videos the authors field is now populated with the YouTube channel. For example:
   ```"authors":{
      "96611324":{
         "author_id":"96611324",
         "name":"Collider Videos",
         "url":"http:\/\/www.youtube.com\/channel\/UCWvMmm_sSdgALpo1Ci4WvtQ"
      }
   }```

**Comment by dnarcese** [comment]
@kennylong According to the API docs, this `authors` field is now added to the public endpoint. Is this something we can also get added to the global recommendations endpoint?

**Comment by kennylong** [comment]
@dnarcese This would take a little more work than what we've done for YouTube videos, but it's something that we have flagged as an improvement to make to the API (and our underlying curation process).

**Comment by liuche** [comment]
@kennylong do you have an estimate on how long that would be? No rush, just to help us with planning.

**Comment by kennylong** [comment]
@liuche Probably not a particularly useful estimate, but I can say that it's definitely not happening in Q4 of this year. We plan to do some related work in Q1, so this _might_ happen then.

**Comment by kennylong** [comment]
@dnarcese Sounds like I totally misunderstood your question, and you're asking about the /v3/firefox/global-video-recs endpoint, not the /v3/firefox/global-recs endpoint.In that case, I believe this should be a quick update (sometime next week?).

**Comment by kennylong** [comment]
@dnarcese @liuche Sounds like I totally misunderstood your question, and you're asking about the /v3/firefox/global-video-recs endpoint, not the /v3/firefox/global-recs endpoint.

In that case, I believe this should be a quick update (sometime next week?). The person that woudl make this update is offline for the weekend but I will follow up with him on Monday.

Sorry for the confusion -- my estimate for the /v3/firefox/global-recs endpoint would be maybe Q1 ;)

**Comment by dnarcese** [comment]
@kennylong That was my miscommunication, sorry! This change is only needed for the /v3/firefox/global-video-recs endpoint- thanks for the estimate.

**Comment by kennylong** [comment]
@dnarcese You can now include `authors=1` in the request (when version >= 2) to get the video publisher (author) of each video in the response.

**Comment by dnarcese** [comment]
@kennylong Awesome, thank you!

**Comment by liuche** [comment]
Actually, I don't think this requires strings, because this is just replacing the "source" string with "author" and that doesn't have any label strings that need to be translated.

**Comment by dnarcese** [comment]
@aminalhazwani If there is more than one author, how should they be displayed? Would a comma-separated list make sense?

**Comment by aminalhazwani** [comment]
@dnarcese yes, comma-separated list makes sense! Eg `CNN, YOUTUBE`
