### ISSUE TITLE
Replace workaround for accessing default user agent with components

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1240]
We take the system's user agent string and mutate it to get our user agent. The new components API made it difficult to get the default user agent so we worked around it in #1204 – https://github.com/mozilla-mobile/firefox-tv/blob/043631c5b61e08b668d1cbe386331fbeef7aab7a/app/src/main/java/org/mozilla/focus/FocusApplication.kt#L25. We should replace this with the components solution shipping in 0.26: https://github.com/mozilla-mobile/android-components/issues/899

---

_edit:_ The a-c implementation is insufficient for our use case (keeping the GV UA the same as the WV UA): see https://github.com/mozilla-mobile/firefox-tv/issues/1240#issuecomment-498449963. As such, we should:
- [ ] Update the code comments to remove the TODO for this bug and explain why we're using the workaround we are instead of using the suggested a-c implementation (because we want GV to have the same user agent string)

**Comment by athomasmoz** [comment]
IMPACT

If we continue to use this method, we risk something breaking in the future.

**Comment by mcomella** [comment]
This got complicated: system and gecko variants return different default userAgentStrings so we have to pass the system string in from the Application anyway if we want to keep the user agent strings the same as they are now.

**Comment by mcomella** [comment]
> This got complicated: 

I elaborated in https://github.com/mozilla-mobile/android-components/pull/931#issuecomment-498449477. I think we should keep the workaround and update the comments: I'll update comment 0 with the action items. Note that we'll need to override the `SystemEngine.defaultUserAgent` to prevent a-c from calling into `WebSettings` and breaking `MainActivity`, however.

**Comment by mcomella** [comment]
This will be closed with the changes in
