### ISSUE TITLE
Test Top Sites from Browsers

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1242]
### Why/User Benefit/User Problem

As a user, I want my favourite sites to work on Firefox for Fire TV so that I can browse and watch content on my big screen TV

### What / Requirements

* Smoke test list of top sites
* For sites with videos available, test playing a video

### Acceptance Criteria (how do I know when I’m done?)

* We can either check off each of the top sites for US, UK, DE, CA, and JP as working on Firefox for Fire TV, or point to bugs that prevent them from working

**Comment by AaronMT** [comment]
[WIP](url
https://docs.google.com/spreadsheets/d/1IEsjJzYBcTAOgaMUpLIjYMOB8_vwARZIHbOd9tosLWs/edit?usp=sharing)

**Comment by npark-mozilla** [comment]
waiting for @rpappalax to merge data with that from connect.

**Comment by npark-mozilla** [comment]
Since the numbers are in above link, I think we can mark it closed?

**Comment by athomasmoz** [comment]
Yes, base don the doc it looks like everything has been tested and links to issues are included. @AaronMT can I close the issue?
