### ISSUE TITLE
Pressing Back from Pocket Video on YT Goes Back to Youtube

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#1258]
This was not filed by Amazon but I am wondering if there is an easy fix and if we can get it into 3.0 so we can keep Pocket content highlighted.

## Steps to reproduce
1. Click on a Pocket Video from YT
2. Play the Video
3. Press Back on the Remote

### Expected behavior
You are taken back to Pocket content

### Actual behavior
You are taken to Youtube home screen

### Device information

* Fire TV device: ?
* Firefox version: ?

**Comment by liuche** [comment]
This is already #773 and a large, so this won't be an easy quick fix. Remove RB label?

**Comment by Sdaswani** [comment]
dupe.
