### ISSUE TITLE
Netflix home page asks to "Rotate your phone to portrait to continue"

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1259]
## Steps to reproduce
1. Try to reach netflix.com

### Expected behavior
Page is loaded correctly

### Actual behavior
Site is asking to rotate your phone to portrait to continue. User cannot continue to the actual site.

### Device information

* Fire TV device:  Fire TV Stick Basic Edition
* Firefox version: 3.0

**Comment by mcomella** [comment]
This is a webcompat issue: it's a bad practice to force users into a
particular orientation because you don't really know about the
characteristics of their device (i.e. like a TV). Next steps:
- Verify it's actually a webcompat issue :)
- See if we can do anything
- Contact netflix to change

**Comment by cartertrout** [comment]
Netflix wants its users to stream through the Netflix native app rather than the browser (with the exception of desktop, where Netflix uses browsers because there is no native app model). 

When we engage Netflix, we should consider refraining from disclosing the device details (although that might not be possible) because Netflix will likely make a business decision to not invest in their website for these devices.

**Comment by mcomella** [comment]
Waiting on webcompat: https://github.com/webcompat/web-bugs/issues/19963

**Comment by levisacal** [comment]
This is a multi-part message in MIME format.
--------------3E79B05439A84DCF0AE295CE
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit


  

    
  
  
    Hello,
      
      
      
        I am out of office from October 22 to November 2. Back at work
        on November 5.
      
      
      For
        any urgent issues or any enquiry please contact Ioana Chiorean
        <ioana.chiorean@softvisioninc.eu>
        
      
      
        Thanks,
      Levente
      
    
    -- 
      
        
          
             Sacal Levente
              Junior QC
                Engineer, QA
            
          
          
               
            
          
          
            
              The content
                  of this communication is classified as Softvision
                  Confidential and Proprietary Information.
            
          
        
      
    
  


--------------3E79B05439A84DCF0AE295CE
Content-Type: image/png;
 name="oohedehlemoaljnp.png"
Content-Transfer-Encoding: base64
Content-ID: 
Content-Disposition: inline;
 filename="oohedehlemoaljnp.png"

iVBORw0KGgoAAAANSUhEUgAAAFcAAAAPCAYAAACRFVP2AAAACXBIWXMAAAsSAAALEgHS3X78
AAADjklEQVRYw+VYPY7aQBT+Fm0P3ZSQfqR1GSkFsyfAewLMCdZbpVynTLXsCWKfIN4TZOhS
gjR9oJwq5gSk+SZ6GhkMC0iR8iSEZM/Pe9/73jdvfLPb7XAtU9oMABQAEgBrAIV3dn2htS2A
nwA+e2dv3jEXAJbe2fxa8d9eEdgRgBrAHR+NAVgApdJmBwCnghLZmP5/fefcq1vvimunBLYi
iB8I9iXtE4CP+Eft9oprG/6XZOn6koufw/ozK+Zou9ntdlDaJNTGAMiSLCu9s01U7hmAnKzc
sNRr72wdaVoCoA9gBaDhmiWAuSjLBYM1SpuU6wLAPFrP0D9Qt+0+3aR/BYAhgG3Y1ztbdmmu
OCNSzg/xzb2zSzEuYRygzwZARky23C+/pTZaAvFGZ1IAL/w3YtEawIQLLPh4CmCqtHnyzs7P
SPRSgN5EEpLxXQCrVTeVNgWAZ/Goz3FjpU0igBzvOXyXBDXYUMQ3EwkaiDVKca6EPR+VNuse
He8DmHlnU+9s4Z1NANwLJgXHJwAqACPvrPHOGmrpCsALMwo+DyDkHJt7Z5d8F8ozrBFkIyRs
wmClfoMV0hxIUPB3JXT+lQwsOpJbCrY/iPlvoZpIxNgCWyvi8NdneaAZGZB31spSYBI2BKsR
49Yi+OJMmSpjzWbC+i3v2yyMGyhtUu/smkkdHUoK456EfYMkcX7KpPeJQev54p3NZJUDGPXo
8Ib0/620sUqbXGaJmw/3MUewLjkT3JoskGwNAW28s7ZjfiXK+bvSplHalNTsQxb8XkSECjaP
Dmlpr2EOsQnVN+wRmATAjM4l1NtflAIAGAktPGTNOcjSuToCNxXAd83PGMdKMHkK4IfS5hKX
heaUmHshKO9s6Z3NvLMDAA9k0LPSZsTMbEWgbWU15i0MF2AvAPSZ3GHEnoM3QsaRUC+fRCUU
R4A23qOroXrsKYH0lDZpXDayDRL9aQngTmlTtgBrj9TEGIykhX01ZQri5F919cnhtKespRxf
Ch1uDjB+Kcq5DngobQbiID+qeuJLxBzAUGmz4uS16CAWwoGcm04JSs2WJPSElUxKh204xypt
Gmp5HrH3sUXzum6EQ/7GSpt9FbHPMnY4d5SR+P3s1ItQjyL9KpjyjSVetZyOJrRiHPsoNs5O
2Dd0Hn0mqDnQNWyP1NuS7WMVvdoC+NL1gUacPZWonHDRuZeXkJNuaO/94tXRc/739gdJBclT
Fd1F2QAAAABJRU5ErkJggg==
--------------3E79B05439A84DCF0AE295CE--

**Comment by athomasmoz** [comment]
Closing as low-priority. As mentioned above, there is a Netflix app on the device that makes more sense for users
