### ISSUE TITLE
Improved Action Counts

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#1263]
This [action count tabl](https://sql.telemetry.mozilla.org/queries/49923#134223)e is not super helpful. Can we please have it changed per the following:

1) Break this all down by day or week.
2) More compact home tile click counts.
3) Is there really no other actions besides 'menu', 'pocket' and 'home_tile'?

I'm also fine just getting this in Amplitude instead.

cc @mmccorks and @athomasmoz

**Comment by mcomella** [comment]
Telemetry bugs need to be filed on BZ now: closing.

@athomasmoz If you want to use the action count table in telemetry, can you file a bug on BZ with the data team to filter out the startup time events (and any others that make the action count table useless)?
