### ISSUE TITLE
When adding a custom tile, previously added tiles are shown first

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1265]
Specific issue but noticed this just now on my Fire TV stick. When I removed tiles and then added new tiles, previously shown tiles are shown. Not sure if there's a caching issue here we can further investigate into clearing.

Also not sure if there's any other way to reproduce other than clearing all defaults first too.

See video, I added Google and saw my previously added Twitter tile flash first: 
![device-2018-10-09-121257](https://user-images.githubusercontent.com/102331/46683088-49126580-cbbd-11e8-8cb6-4f03ff89bcd9.gif)

**Comment by liuche** [comment]
Making this a P3 because not that many people use a lot of custom tiles (or remove all tiles). This could be a problem with RecyclerView (and also might happen if there are too many tiles).

**Comment by athomasmoz** [comment]
No longer applicable. You are taken back to the website right away when you pin a site
