### ISSUE TITLE
Cannot login to Pintereset with Google or Facebook

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1273]
## Steps to reproduce
1. Go to pinterest.com and try to log in using FB or Google

### Expected behavior
Successfully logged into Pintereset with FB or Google

### Actual behavior
Unable to log into Pinterest using FB or Google

### Device information

* Fire TV device: Fire TV with 4k and Alexa Voice Remote
* Firefox version: 3.0

**Comment by liuche** [comment]
Duping this to #1468.
