### ISSUE TITLE
Video playback shaky glitch on watchcartoononline.com

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1275]
## Steps to reproduce

1. Go to watchcartoononline.com
2. Watch any video (i.e. family guy)

### Expected behavior

Video plays without any issues

### Actual behavior

Video playback has a shaky glitch

### Device information

* Fire TV device: fire tv with 4k and Alexa Voice Remote
* Firefox version: 3.0

**Comment by levisacal** [comment]
Same issue reproducible on twitch.tv

**Comment by athomasmoz** [comment]
@levisacal can you share a video of what the glitch looks like?

**Comment by levisacal** [comment]
Hi @athomasmoz,

Wasn't able to reproduce anymore on the current production version neither on the above site or on twitch or vimeo.

But when entering full screen on watchcartoononline.com the screen did not show the video. I have logged in another issues for this  https://github.com/mozilla-mobile/firefox-tv/issues/1476

**Comment by athomasmoz** [comment]
Thank you! I'll close this issue and will triage the new one you've created
