### ISSUE TITLE
Blank page after trying to sign up with FB credentials on ebay.co.uk

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1277]
## Steps to reproduce

1. Try to sign up on ebay.co.uk with FB credentials

### Expected behavior

Signing up with FB credentials runs smoothly

### Actual behavior

Blank page after choosing to sign up with FB credentials

### Device information

* Fire TV device: fire tv with 4k and Alexa Voice Remote
* Firefox version: 3.0

**Comment by liuche** [comment]
Duping to #1468.
