### ISSUE TITLE
Create release build validation task (to prevent releasing the same version twice)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1280]
### Why/User Benefit/User Problem
Sometimes for pre-release versions, we mishandle the version numbers and release two builds with the same ID or forget a git tag. This is also a threat for release builds.

Not having a clear idea of which release is which can convolute our data (did this report come from 1.1 or the second 1.1?), making it harder to solve reproduce issues and solve problems for our users when that is dependent on version.

At compile-time, we should ensure:
- Bonus-ish: The user has no local changes
- The user's checked out git commit is tagged with the same version as the build name

And give users an escape hatch to build local builds without validation. Since git tags are unique, we can never release two of the same version number.

Part of this will be solved by https://github.com/mozilla-mobile/firefox-tv/issues/1173 which will create the builds on CI from a git tag, but without this fix, we may still forget to bump the version (unless we can get CI to do that for us and that's hard).

### What / Requirements
- Create gradle task to validate release builds
  - Does checkout out git commit's tag == buildName?
  - Bonus: Confirm no changes in working directory
- assembleRelease.dependsOn(validationTask)
- A way for users to disable this validation, e.g. `./gradlew assembleRelease -Pno-validation`

**Comment by mcomella** [comment]
@athomasmoz I did this in my free time (to learn how to manipulate our build system): should we include it in the sprint? I don't know that it's useful to track this since this time isn't guaranteed nor do I want to encourage other people to use their free time like this. :)

**Comment by athomasmoz** [comment]
Thanks @mcomella . I added it to the sprint just for organizational purposes. If you don't want to track the time you spent against it, let's just leave the estimate off. That way it won't impact our velocity
