### ISSUE TITLE
Test Plan: Mission Critical Flows

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1287]
### Why/User Benefit/User Problem

As a user, I want to ensure I can still do all my normal activities on Firefox for Fire TV after an update

### What / Requirements

* Determine what automated tests we want to write to cover our mission critical flows

### Acceptance Criteria (how do I know when I’m done?)

* There is a list of automated tests to implement for our critical flows

**Comment by liuche** [comment]
One caveat, for GeckoView, Espresso integration doesn't work yet so we need to see:
a) how much to invest in WebView testing
b) if there are other things that we need from GeckoView

**Comment by mcomella** [comment]
Alternatively, assuming GeckoView will get a 2-way JS API, we could write
our UI tests with JavaScript injection rather than espresso to change and
validate state.

**Comment by mcomella** [comment]
The test plan is complete and is documented in this email: https://groups.google.com/a/mozilla.com/forum/#!topic/firefox-tv/1Cw0_hrIYMo

**Comment by mcomella** [comment]
First next step available in #1327.
