### ISSUE TITLE
[META] Homescreen Overlay & Channels

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1304]
### Why/User Benefit/User Problem

Improve the user’s understanding of how to navigate the browser.

### What / Requirements

* Bring settings to the homepage to enable users to configure their browser
* Update home design to account for additional page content from pocket & settings
* Separate pinned tiles from nav bar & slide up to help users understand that it's an overlay

- [ ] parent of #1310 
- [ ] parent of #1071 
- [ ] parent of #1311 
- [ ] parent of #1167 
- [ ] parent of #689 
- [ ] parent of #1312 
- [ ] parent of #1313 
- [ ] parent of #1314 
- [ ] parent of #1315 
- [ ] parent of #1878

**Comment by athomasmoz** [comment]
Closing in favour of keeping individual tickets only

**Comment by mcomella** [comment]
@athomasmoz FYI: this is redundant to #1630 (our new homescreen channels meta): not sure how we want to organize these older bugs from Amin's designs.

**Comment by athomasmoz** [comment]
Thanks, closing in favour of #1630 with the updated design
