### ISSUE TITLE
Locale does not immediately update

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1305]
## Steps to reproduce
- Open Firefox
- Go to Fire TV Home
- Navigate to Settings
- Open preferences
- Open language
- Change language
- Re-open Firefox

### Expected behavior
- Language should reflect new choice

### Actual behavior
- Language stays on old choice
(Note: it does eventually change, but I have yet to work our STRs. @npark-mozilla do you think you guys could take a look?  It often takes a few minutes)

### Device information

* Fire TV device: 4k
* Firefox version: 49b0e3ada1c1501fe434c2e36129bf9b04ba1b03

**Comment by athomasmoz** [comment]
Closing as lower priority.
