### ISSUE TITLE
Follow-up: Use IconGenerator instead of untested PinnedTileScreenshotGenerator

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1340]
`../pinnedtile/PinnedTileScreenshotStore.kt` copies code (see #599) from `IconGenerator.kt` which contains tests - use `IconGenerator` and remove the untested methods from `PinnedTileScreenshotStore`.

Context/commit: https://github.com/mozilla-mobile/firefox-tv/commit/e2bf0aae25fd24a54f8e70c88c625081f7e48fbd

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
