### ISSUE TITLE
Add combineLatest function

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1352]
This allows us to combine multiple LiveData objects together in a fluent manner.

If more advanced versions of this are required, this should be replaced by importing RxJava.

**Comment by liuche** [comment]
@Baron-Severin are there more parts to this bug that still need to be done, before it's closed? Maybe you forgot the commit message hook :P

**Comment by Baron-Severin** [comment]
@liuche Whoops.  I hooked it into its own PR, instead of the issue.

**Comment by Baron-Severin** [comment]
@liuche whoops.
