### ISSUE TITLE
The Web Pages are refreshed every time when opening them again

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#1359]
## Steps to reproduce
1. Launch FF for fire TV and access YouTube(or any website)
2. Press the menu button in order to reach the FF for fire TV home screen
3. Open again YouTube(or any website)
### Expected behavior
The YouTube(or any website) is opened right from where it was left when navigated to FF home screen
### Actual behavior
The YouTube(or any website) is refreshing when accessing it again
### Device information

* Fire TV device: Fire TV with 4k and Alexa Voice Remote
* Firefox version: 3.0.1

### Notes
* Please note that this is more like and enhancement/question regarding this issue.
* Is it intended for web-pages to refresh every time when accessing them again?
* Note that eve if watching a YouTube video after multitasking to FF home screen and going back to
* YouTube, it will refresh and the YouTube screen is displayed instead of the video.
* Also, note that I tested this on a TV(with YouTube app installed on the TV, a Samsung 4k tv) and when returning from another app, the app wasn't refreshed and the video was still displayed.

![the web-pages are refreshed every time when opening them again](https://user-images.githubusercontent.com/42831109/47437484-5df01b00-d7b1-11e8-8976-39b116b013cc.gif)

**Comment by liuche** [comment]
I would say this is working as expected - the tiles are meant to be links, so it's as if you were loading a link, not "closing the overlay."

I think this is more about our homescreen being confusing - the intended way to "go back to youtube" is to click "back" or "menu" to close the overlay.

I'm going to close this based on my understanding of the STR and the video, but please reopen if it this isn't the case.
