### ISSUE TITLE
firefox:error:pocketconnection is only visible once

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1369]
Visit Firefox:error:pocketconnection, see try again, tap that and attempt to visit Firefox:error:pocketconnection again. Expected to see an error but get a white screen.

This is causing issues with testing.

**Comment by athomasmoz** [comment]
Note: This is used to create screenshots for error pages for pocket, so that we can test & send for localization

**Comment by liuche** [comment]
Hey @Delphine we are a little blocked on getting a screenshot for this particular error screen working for snapshots - however, this isn't a screen that we expect people to see, so we'll add this for 3.2, just giving you a heads up!

**Comment by Delphine** [comment]
I think that should be fine in that specific case :) thanks for the heads-up!
