### ISSUE TITLE
[1396] #5: Implement test for data upload enable toggle

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1370]
Users expect the data toggle to work so we respect user's choices. We want to ensure:
- The data upload toggle will switch on and off and the state will persist when you leave and return to settings (and may even the app); we may need to enable data upload in debug builds to fix this
- The data upload toggle's state matches the internal representation

**Comment by mcomella** [comment]
May need to fix #384 first.

**Comment by athomasmoz** [comment]
Not included: testing the functionality of the settings that are being toggled.

**Comment by mcomella** [comment]
For the internal representation, I was thinking we'd check the global flag "is data upload enabled" flag rather than validating we're not uploading: unit tests (presumably) will cover the latter.

**Comment by liuche** [comment]
Linking this to #1396 so we don't lose it.
