### ISSUE TITLE
Break out screenshot tests into individual files

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1377]
Refactors out TVScreenshots into individual files for each test

**Comment by liuche** [comment]
@AaronMT btw you can auto-close issues when PRs merge by having "Closes #issue-number" in a commit message.

Also, just a heads up that we'll be doing further work on the releases/v3.1 branch for the 3.1 release - it hasn't diverged much yet, but things like #202 Request Desktop Site and #1284 Casting YT will be landed on that branch while we do rearchitecting.
