### ISSUE TITLE
Scrolling through news story is difficult when there is share bar overlay

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#138]
![screen](https://user-images.githubusercontent.com/6930774/34062957-f1e44fe6-e1b4-11e7-9e07-2653bb0bb0cb.png)

Go to www.thestar.com, select a story, and scroll down using down on D-pad
When trying to scroll up, if the selection is on any one of the share icons of the top bar overlay, it won't scroll.  One has to go right/left to unselect the share icons in order to scroll back up again.

This seems to be a general issue with pages that are mean to be scrolled on a touchscreen. there are dom elements that are difficult to see whether they are selected when cycling through with the direction pad.

**Comment by bbinto** [comment]
Let's see if this will be fixed with 2.0

**Comment by liuche** [comment]
Also related to #420, which would fix this issue.

**Comment by athomasmoz** [comment]
Unable to reproduce on the star. Larger issue tracked in #278
