### ISSUE TITLE
[architecture] Toolbar into MVVM

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1392]
### Why/User Benefit/User Problem
This is a continuation of the architecture rewrite. Currently the toolbar is embedded in the overlay and the logic to update button state is not consolidated so it's not as testable, which makes regression testing more difficult, and makes changing the code more error-prone.

### What / Requirements
Make a Toolbar Repo, VM, and separate out WebView.

### Acceptance Criteria (how do I know when I’m done?)
Toolbar has a Repo and is broken into MVVM, with tests

**Comment by Baron-Severin** [comment]
@aminalhazwani I noticed some odd toolbar behavior, and I wanted to verify with you what we wanted before putting too much work into recreating it.

STR:
- Navigate to pinned tile (URL bar is updated)
- Open menu 
- Open URL bar keyboard 
- Delete a few characters 
- Close keyboard (URL bar text is unchanged)
- Unfocus URL bar

Expected:
???

Actual:
User text is replaced by current URL


So my question is, when should we update URL bar text?  I believe desktop behavior updates it on redirect, refresh, back, and forward.  Are we copying that behavior, or do we have other requirements?

**Comment by Baron-Severin** [comment]
Thanks for the clarification!  I'm changing the behavior to update the URL when the user interacts with something (clicking a tile, forward, back, refresh, etc), but otherwise to hold on to what they last typed.

@aminalhazwani on an unrelated question, I noticed that we don't currently close the overlay when the user refreshes.  That feels wrong, do you mind if I change that?

**Comment by aminalhazwani** [comment]
> @aminalhazwani on an unrelated question, I noticed that we don't currently close the overlay when the user refreshes. That feels wrong, do you mind if I change that?

@Baron-Severin yeah, I absolute agree. I think we have an issue for that, lemme find it. Here https://github.com/mozilla-mobile/firefox-tv/issues/1288 🙂
