### ISSUE TITLE
[architecture] Focus handling

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1395]
### Why/User Benefit/User Problem
Our view focus code is complicated and not very centralized, and right now it's very fragile. We want a way to handle focus changes, especially for switching between different screens (e.g. Settings icon on homescreen remains focused when returning from Settings)

### What / Requirements
Have a centralized way to handle focus changes, so we can ensure something is always focused, and focus is cached correctly.

### Acceptance Criteria (how do I know when I’m done?)
Plan for handling Focus changes, and implementing that.

**Comment by psymoon** [comment]
I think we should incrementally tackle this - maybe an initial patch for the foundation is required @devinreams @athomasmoz

**Comment by liuche** [comment]
Could have broken out these pieces:
* Android re-focusing on app return (instead of focusing parent layout)
* Focus direction based on app state/per view
* Screen transition: previous focus/default focus
