### ISSUE TITLE
On a fresh install, Pocket megatile is skipped when scrolling down

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1408]
## Steps to reproduce
Uninstall Firefox, this only happens on a fresh install
Install Firefox, and click through onboarding screens
Scroll down from nav bar

### Expected behavior
Pocket megatile gets highlighted

### Actual behavior
Nav highlight skips down to home tiles. Scrolling back up works again.

### Device information

* Fire TV device: Cube
* Firefox version: master 1213142

**Comment by liuche** [comment]
@Baron-Severin probably fallout from #1283 ?

**Comment by Baron-Severin** [comment]
@liuche sounds probable.

**Comment by Baron-Severin** [comment]
The Pocket refactor is going to affect the logic for this.  I have a fix on a PR into the refactor, @liuche could you take a look at it?

https://github.com/Baron-Severin/firefox-tv/pull/1
