### ISSUE TITLE
Record telemetry for which remote controls we receive key events for

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1409]
### Why/User Benefit/User Problem
Typically users will use the Amazon hardware remote to input actions. However, they may not always: it'd be good to know how often alternative control mechanisms are used so we know how well we need to support these devices. I believe touch events include a device identifier of some kind.

### What / Requirements
- ~~Figure out which device identifiers there are~~
- Add telemetry to mark if the remote is a fire tv remote or not
- Open a data science bug (see [comment](https://github.com/mozilla-mobile/firefox-tv/issues/1409#issuecomment-448776631)) to get menu button usage for users

**Comment by mcomella** [comment]
It looks like this is possible. Each `KeyEvent` has a `getDeviceId()` method that can be inserted into `InputDevice.getDevice(deviceId)` and returns the following data:
```
mControllerNumber = 0
mDescriptor = "b22c13fd894df46e595d7bb76ed2136d6293541a:19490407"
mGeneration = 14
mHasButtonUnderPad = false
mHasVibrator = false
mId = 5
mIdentifier = {InputDeviceIdentifier@6388} 
mIsExternal = true
mKeyCharacterMap = {KeyCharacterMap@6389} 
mKeyboardType = 1
mMotionRanges = {ArrayList@6390}  size = 0
mName = "Amazon Fire TV Remote"
mProductId = 1031
mSources = 769
mUniqueId = ""
mVendorId = 6473
mVibrator = null
```

In particular, mName, mVendorId, and mProductId seem like useful fields to potentially record.

We need to figure out the question we want to answer to determine how we should record the telemetry (e.g. we should probably only send one event for each controller used).

**Comment by mcomella** [comment]
For my Samsung smart TV remote that controls the Fire TV, I see:
```
mControllerNumber = 0
mDescriptor = "a718a782d34bc767f4689c232d64d527998ea7fd:00000000"
mGeneration = 2
mHasButtonUnderPad = false
mHasVibrator = false
mId = -1
mIdentifier = {InputDeviceIdentifier@6451} 
mIsExternal = false
mKeyCharacterMap = {KeyCharacterMap@6452} 
mKeyboardType = 2
mMotionRanges = {ArrayList@6453}  size = 0
mName = "Virtual"
mProductId = 0
mSources = 769
mUniqueId = ""
mVendorId = 0
mVibrator = null
```

Curiously, the device name is, "virtual": I guess the smart TV is controlling the fire TV through software.

Note also that the `deviceId` changes between devices even if it's the same remote (i.e. cube has 6 for fire TV remote but stick has 5 for fire TV remote).

**Comment by athomasmoz** [comment]
The question we want to answer is "what controls do users have available to them?" It doesn't look like that information is returned, but if we can map the mName, mVendorId, and mProductId back to a remote, that should do it! So I agree those fields make sense to track

**Comment by liuche** [comment]
I think this would be worth prioritizing for Q1, @athomasmoz!

Also, @mmccorks is there a way to see what percentage of our users have never used the menu button?

**Comment by mmccorks** [comment]
@liuche so long as there is an event sent when the menu button is used we could do that. Can you file a data science bug to pull that data?
