### ISSUE TITLE
When fullscreen video is enabled, cursor should disappear

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#141]
Not just youtube, but on any video site, once the fullscreen is activated the cursor should disappear until the screen is clicked again.  Cursor persists and distracts the view.
![screen](https://user-images.githubusercontent.com/6930774/34063435-b1c9ca96-e1b7-11e7-9d2d-4f66282154b7.png)

**Comment by mcomella** [comment]
We do this.
