### ISSUE TITLE
Take L10N screenshots

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1446]
All features with strings have landed, with the exception of #1286 Youtube Casting Hint (which is blocked) and #202 Request desktop site (which is toast-strings only - do we take screenshots for toasts?).

@AaronMT how long would screenshots take, and can you make sure that we are getting screenshots for the new "Turbo Mode onboarding" screen?

**Comment by AaronMT** [comment]
First run turbo mode on boarding: https://www.dropbox.com/sh/kzcf7d66sw0oke6/AAC3Z4Zjk1toFiVeTdT7ahUea?dl=0

**Comment by Delphine** [comment]
Thanks Aaron! very helpful :)

**Comment by liuche** [comment]
@Delphine are there more screenshots that you need? If not, I'll close this issue (since screenshots won't work for any of the other new features, and we're removing Youtube hint from this release).

**Comment by Delphine** [comment]
I think we are good to go then. thanks!
