### ISSUE TITLE
Upgrade to a-c 0.30 - Use a-c ic_device_desktop

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1452]
The previous desktop site icon was not the right size, so using our own version until a-c is upgraded.
(Didn't want to block merging https://github.com/mozilla-mobile/firefox-tv/pull/1411 on this)

Link to a-c issue: https://github.com/mozilla-mobile/android-components/issues/1256

**Comment by pocmo** [comment]
Removing a-c label: This was released with 0.30.0.
