### ISSUE TITLE
lateinit property not initialized before access in MainActivity

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1455]
First seen: 10/31/18
Approximate instances per day: 60

See https://sentry.prod.mozaws.net/operations/firefox-tv/issues/4898723/?query=is:unresolved

From the stack trace, it is not clear to me what property has not been properly initialized.  The fact that this is a Kotlin error leads me to believe that the problem is on our end, and with such a low error count seems likely to be caused by an infrequent lifecycle edge case.

**Comment by mcomella** [comment]
This hasn't been seen since 3.0.2.
