### ISSUE TITLE
CNET video fails to load

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1463]
- Visit http://cnet.com 
- Visit the videos section and click on any video

The controls are all greyed out and the video is black. I suspect on load it's hitting some compatibility error in web console.

This works in Silk.

Tested with c1fd2d0030a518be8b59eb5365aac9c103422642 (master) on a 4K Stick.

**Comment by dnarcese** [comment]
Looks like turbo mode is blocking the video. Turning it off allows the video to play.

**Comment by dnarcese** [comment]
This issue is being seen across all products that use tracking protection, so an update to the Disconnect lists is needed to stop blocking cnet videos. An issue has been filed with them [here](https://github.com/disconnectme/disconnect-tracking-protection/issues/61).

**Comment by dnarcese** [comment]
Closing as wontfix, see https://github.com/disconnectme/disconnect-tracking-protection/issues/61#issuecomment-458639408
