### ISSUE TITLE
Clean up LiveData tests

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1467]
Our first LiveData tests were written in a way that can be improved.  The following improvements should now be made:

- Move from Espresso to JVM.  Use `PreventLiveDataMainLooperCrashRule` rule to allow this
- Use `postValue` instead of wrapping tests in `ActivityTestRule#runOnUiThread`
- Replace awkward creation and replacement of observers with our new `LiveData#assertValues` extension function

**Comment by mcomella** [comment]
We're moving away from LiveData anyway: closing.
