### ISSUE TITLE
Release WebView reference in onLowMemory

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1469]
We have a fair number of out of memory exceptions, especially on the Stick, and they appear to be thrown primarily when the app is backgrounded.  With a recent change that allows `WebViewCache` to store significant state between `WebView` instances, it may make sense to release our `WebView` reference in low memory scenarios.

To do:
-  Clear `WebViewCache` in `onLowMemory`
- Verify that this does not cause harmful edge cases

**Comment by mcomella** [comment]
> they appear to be thrown primarily when the app is backgrounded.

@Baron-Severin How do we know this? Is this information in sentry?

**Comment by Baron-Severin** [comment]
@mcomella only anecdotal at this point, unfortunately.  I know I've seen OOM crashes while the app is backgrounded, particularly when other apps start videos.  I don't ever recall seeing one while actively using our app.  It would be good to log this condition to Sentry to verify.

**Comment by mcomella** [comment]
Android components would have to support this use case: closing. @Baron-Severin If you still feel this is important, please file in a-c.
