### ISSUE TITLE
Images missing in browser

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1477]
Build: 03605889383ed1d861e4326acef552824cc20d08

Lately I am seeing missing images on sites 

E.g, Reddit

![screen shot 2018-11-07 at 11 17 19 am](https://user-images.githubusercontent.com/102331/48144403-ceea0500-e27e-11e8-99ce-af21f67da307.png)

E.g, CNN

![screen shot 2018-11-07 at 11 19 13 am](https://user-images.githubusercontent.com/102331/48144496-08bb0b80-e27f-11e8-9b9f-781b33c2ba0f.png)

E.g TD Bank

![screen shot 2018-11-07 at 11 20 44 am](https://user-images.githubusercontent.com/102331/48144611-3607b980-e27f-11e8-88b8-e8805414343e.png)

**Comment by Baron-Severin** [comment]
This looks like https://github.com/mozilla-mobile/firefox-tv/issues/1264.  Turbo mode is blocking custom fonts, so we get these weird symbols instead.

**Comment by AaronMT** [comment]
Can confirm disabling turbo mode fixes this.

**Comment by mcomella** [comment]
I agree with Severin: dupe #1264.
