### ISSUE TITLE
Move transformation logic out of PocketVideoAdapter, into PocketViewModel

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1484]
Currently, if the Pocket API does not return an author, the pocket video adapter is transforming the author field into the platform of the video by formatting the url. This transformation should happen in the VM, but `FormattedDomain#format` needs reference to context, which the VM doesn't have.

Possible solution (from @Baron-Severin):
- change FormattedDomain from being a singleton into being a class that accepts context (or preferably application) through its constructor
- make all of the static methods instance methods, use the application context from the constructor
- add a formattedDomain field to the ServiceLocator
- pass formatted domain into the VM

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
