### ISSUE TITLE
Failed Pocket network requests do not print their exceptions

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1489]

**Comment by mcomella** [comment]
@Baron-Severin Have you verified what is in these exceptions? We generally avoid logging exceptions that may contain PII (like urls) or are from an external source (like this) so we don't leak private information. While other apps can't read the logs, users can share their logs to other parties which could contain this confidential information, not knowing about the confidential info.

We could also consider logging these exceptions only in debug builds (maybe this could be a feature of the android components log wrapper).

CC @liuche as reviewer

**Comment by Baron-Severin** [comment]
@mcomella  Opened https://github.com/mozilla-mobile/firefox-tv/issues/1537
