### ISSUE TITLE
Grey Screen on Resuming Firefox for Fire TV

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/firefox-tv#1492]
## Steps to reproduce
Open Firefox after allowing device to idle a while, and notice a grey screen pops up.
### Expected behavior
Webpage or start page should load normally.
### Actual behavior
You get a grey screen and nothing loads unless you press the home button. This includes URLs, refreshing the page, etc.
### Device information
Fire OS 6.2.3.2
* Fire TV device: Fire Stick 4k (2018)
* Firefox version: 2.1.2

**Comment by mcl21014** [comment]
Behavior seems occasional, not 100% sure on how it's triggered.

**Comment by safemanusa** [comment]
I get same thing. I press the return button on the remote and it returns back to the page you were on. Does not seem to go to a screen saver.

**Comment by mcomella** [comment]
@npark-mozilla Have you seen behavior like this on `v2.1.x`? If so, we should try to reproduce again on `v3.x`. Note that both reporters see this on the Fire Stick 4k.

**Comment by npark-mozilla** [comment]
I remember seeing grey screen a while ago, but haven't seen it recently. but @levisacal can take a look

**Comment by mcl21014** [comment]
Seems to only effect 2.x on the Fire Stick 4k as far as I can tell.

**Comment by levisacal** [comment]
Wasn't able to repro this on the current production version 3.0.2 with Fire Stick 4k and Fire OS 6.2.5.5.

Tried to repro by resuming Firefox after going idle or first resuming the device from screen saver and then resuming Firefox

**Comment by athomasmoz** [comment]
This should be fixed in #1501 . Closing
