### ISSUE TITLE
Crash on Sky Video

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#1495]
## Steps to reproduce
When I try to open the following https://video.sky.it/news/diretta on Fire TV and Fire Stick keep crashing.

### Expected behavior
No crashes

### Actual behavior
Crash

### Device information

* Fire TV device: TV Stick
* Firefox version: Production

**Comment by giofish** [comment]
Video showing crash:
https://youtu.be/J_vIOSXqlkc

**Comment by athomasmoz** [comment]
Retest after #1234

**Comment by giofish** [comment]
watch.cbc.ca (or hgtv.ca) not available outside canada. 
Tried hdtv.com videos not playing

**Comment by athomasmoz** [comment]
Thanks for adding details on the additional sites! We're tracking CBC & HGTV under https://github.com/mozilla-mobile/firefox-tv/issues/1234

**Comment by athomasmoz** [comment]
Consolidating similar issues. Tracking under #1577
