### ISSUE TITLE
Pocket links freeze browser in 3.0.2.1

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/firefox-tv#1498]
## Steps to reproduce
Open one of the suggested Pocket links on the main page of Firefox.
### Expected behavior
Pocket link loads up and an article or video or whatever is displayed.
### Actual behavior
The links have some sort of Mozilla text placeholder and a bunch of jargon as their text description. Upon selecting a dark grey screen appears and the throbber appears indefinitely, only way to stop the loop is to force stop Firefox.
### Device information

* Fire TV device: Fire Stick 4k
* Firefox version: 3.0.2.1 prerelease

**Comment by liuche** [comment]
That seems like we may have forgotten to include the Pocket key in this pre-release build - I'll close this, but we recently also fixed #1173 so hopefully this won't happen again on pre-release builds.

**Comment by mcl21014** [comment]
If they reappear, is there something that can be done? Like add the ability to hide the pocket feed on prerelease builds?

**Comment by liuche** [comment]
@mcl21014 if you see them again, please file a bug! That way we can fix it as soon as possible.

Are you still seeing this? If you are, please let me know - this could be something else if you see this again, and I'd appreciate hearing more details! (where you got the build from, when you installed it, etc)

**Comment by mcl21014** [comment]
Yes I'm still seeing it on the prerelease build. I downloaded the source for 3.0.2.1 and compiled it in Android Studio with some help. Installed it a few days back.
