### ISSUE TITLE
Update Firestick 4K to Firefox 3.x

### ISSUE THREAD

**Issue by safemanusa** [mozilla-mobile/firefox-tv#1501]
## Steps to reproduce
I cannot get FireFox 3.0 on my Firestick 4K. 

I tried to uninstall and re download but still get same version.

### Expected behavior
Update button

### Actual behavior
No vehicle to update

### Device information

* Fire TV device: Firestick 4K
* Firefox version: 2.1.2

**Comment by mcomella** [comment]
Thanks for reporting! Due to differences in the device's software I don't know that we've released to the Firestick 4K yet: https://github.com/mozilla-mobile/firefox-tv/blob/master/CHANGELOG.md#302---2018-10-30

@Sdaswani Can you confirm? What's our plan for releasing v3.* to the Firestick 4K?

**Comment by mcl21014** [comment]
I can get it on my Fire Stick 4k. But it's version 2.x, which is the production version.

**Comment by Sdaswani** [comment]
@Sdaswani funny you mention this - @haldeman99 and I just spoke and he said in his testing 3.0 worked well on this device, so if 3.1 is shipping after black friday, we can just do a version bump on the two APKs and add the 4k stick for 3.0.

@athomasmoz should we do this this week?

**Comment by safemanusa** [comment]
Thanks guys for updating so quickly! Is there any way to get the working version? Does 3.0/3.1 support tv.youtube.com? Is there anyway to get added to the developer version updates? Would love to do test beta versions.

**Comment by safemanusa** [comment]
According to the change log 3.0 was already released to Firestick 4K?

![image](https://user-images.githubusercontent.com/19233164/48371237-f2e38700-e680-11e8-9bfd-713ac1e89896.png)

**Comment by Sdaswani** [comment]
@safemanusa i can add you to the Live App Testing, please let me know your amazon devices email address. We support http://www.youtube.com/tv, but not tv.youtube.com AFAIK.

**Comment by safemanusa** [comment]
Oh thanks so much @Sdaswani. I sent my email address to your email address. I did open another issue related to tv.youtube.com. I am hoping that tv.youtube.com is something that can be made available soon! Many folks are looking for this availability!

**Comment by mcl21014** [comment]
Please add me as well to live testing @Sdaswani when you have a moment. I shot you an email a day or so ago. I'd be honored to help catch issues in the prerelease versions as I've already done. My credentials to login are different than my GitHub email, so please don't mistake the mail as spam.

**Comment by athomasmoz** [comment]
@Sdaswani Yes, ideally we get all devices onto the latest version. If the Stick 4k looks good with 3.x, let's go for it.

**Comment by mcl21014** [comment]
In my experience the startup grey screen issue is gone on 3.x on the Fire Stick 4k.

**Comment by Sdaswani** [comment]
@liuche will do this as part of the 3.1 submission.

**Comment by liuche** [comment]
Submitted 3.1 and included all Fire TV devices.

**Comment by Sdaswani** [comment]
i think we need to re-open this, right @liuche ?

**Comment by athomasmoz** [comment]
All devices now have the same code. It's listed under 2 version numbers which we will fix next release.
