### ISSUE TITLE
Users don't have/know about the Menu button

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1508]
We've seen a few users commenting on how they don't know how to open the overlay.

One possibility is that users are continuing to use their TV remote (like the Samsung Smart TV), which doesn't have a Menu button.

Some thoughts/options:
* Hint: We used to have a "hint" on the homescreen with the "menu" button as an icon. However, this wouldn't handle the case where people are not using the Fire TV remote.
* Remap: Not sure how difficult it would be to allow users to "remap" an existing button (like in video games). See #1308 for adding custom remote commands.
* Is there a "standard" multi-button combination that correlates to a "menu" press? Needs investigation.

**Comment by liuche** [comment]
Tagging @aminalhazwani, bc I'm filing this from discussion w/ @athomasmoz during triage.

**Comment by aminalhazwani** [comment]
For reference this is what Silk does on fresh install as soon as you visit your first website.

![silk](https://user-images.githubusercontent.com/1721875/48479222-fd2f8d80-e806-11e8-809f-fb7d28430ec1.png)

**Comment by aminalhazwani** [comment]
Also, other things to keep in mind, on fresh install we have the Turbo Mode onboarding, and right after the Pocket onboarding. One after the other.

**Comment by aminalhazwani** [comment]
And another thing that we might also consider the fact that the TV is accessible to the whole household.

**Comment by athomasmoz** [comment]
Closing off this issue. Research suggests users have the menu button, but aren't aware of what it does. We've starting breaking this out into solutions, the first is #1907
