### ISSUE TITLE
Update to a-c 0.31.0

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1520]
0.31.0 is needed to fix #1264

**Comment by pocmo** [comment]
I want to highlight an important change in 0.31.0 that will affect you, see changelog here:
https://mozilla-mobile.github.io/android-components/changelog/#0310

In that version we removed the workaround you requested about always playing protected content (DRM) in favor of a full-featured permission API. The changelog contains a snippet that shows how you can re-create this behavior with the new permission API. Let @csadilek or me know if you have any questions about that.
