### ISSUE TITLE
Enable QA to verify telemetry on endpoint

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1522]
### Why/User Benefit/User Problem
Right now the only way we know the telemetry is working is during the developer's initial testing. Since there's no recurring testing, the code could change and break telemetry: in general, we can only assume our telemetry is accurate so we may not be making accurate data-based decisions that affect our users.

### What / Requirements
The minimal effort implementation is to provide a mechanism for QA to do manual testing: they want to perform events locally and device and verify the server receives them. The way we agreed to do this (but could potentially be changed if you talk to Frank) is to send our telemetry events to a "qa" channel (currently, the channel is created based on our build types, either "debug" or "release"). A proposed way of changing this would be to create a flag in Intents sent to MainActivity that would enable the QA channel.

One potential problem is that the mobile metrics ping does not get sent until it batches enough events (500?) so we'll have to figure out a way to work around that.

fwiw, the data pipeline team is implementing a roughly real time implementation to display telemetry events that doesn't go through the full data pipeline: this should be good enough to start.

Steps:
- Ensure we're uploading telemetry in debug builds
- When the user desires so, upload pings to the "qa" channel (only for debug builds?)
- Figure out how to get the mobile metrics ping to send to the server (if applicable)
- Write tests to ensure this functionality works correctly and won't break

### Acceptance Criteria (how do I know when I’m done?)
- Automated tests say this is passing
- QA have confirmed they can use this feature to verify telemetry
  - Message them
  - Comment in this issue for the data pipeline side: https://bugzilla.mozilla.org/show_bug.cgi?id=1507921

**Comment by mcomella** [comment]
FYI @athomasmoz: this is a joint effort with other teams so we should do this sooner rather than later.

**Comment by Sdaswani** [comment]
@athomasmoz any idea when this will be prioritized in Q1?

**Comment by athomasmoz** [comment]
It's prioritized just under some P1 bugs, so it's a potential for next sprint or the one after.

**Comment by mcomella** [comment]
Glean gives this to us for free – closing in favor of glean support.
