### ISSUE TITLE
Make PocketEndpoint.GLOBAL_VIDEO_ENDPOINT null if key is invalid

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1527]
Currently, we check whether or not the Pocket key is valid before making our initial Pocket request.  However we make these requests from several other locations in the code as well (periodic background updates, user initiated retries from an error megatile).  This previously led to a bug where invalid requests were being made.

One more reliable way to fix this would be to null out the PocketEndpoint entirely when the Pocket key is not found.  This would change the endpoint to a nullable type, forcing all users to handle cases where the request could not be made.  This would make it impossible to make a Pocket request in cases where the key was not available.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
