### ISSUE TITLE
PocketOnboardTest is failing (Espresso)

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1528]
It looks like using rule `MainActivityTestRule` with argument `skipOnboarding = false` is not showing an onboarding screen.  

Removing the rule and replacing it with the former `new ActivityTestRule<MainActivity>(MainActivity.class, false, false);` does not solve the problem either.

### Device information

* Fire TV device: Cube
* Firefox version: af3ea79c44c930b353f45e527f15760d7c6c30cb

**Comment by AaronMT** [comment]
Saw this today on trying to run it. Regression from https://github.com/mozilla-mobile/firefox-tv/issues/1218 ?

**Comment by psymoon** [comment]
This is the result of temporary behaviour change from https://github.com/mozilla-mobile/firefox-tv/pull/1512 for 3.1 Turbo Mode fix. Once we get https://github.com/mozilla-mobile/firefox-tv/pull/1514, we can revisit my hotfix and use LiveData instead
