### ISSUE TITLE
Inconsistent author on pocket videos

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/firefox-tv#1530]
## Steps to reproduce

In the case of videos from YouTube channel "Seeker" the author is not always consistent. Sometimes is marked as "Seeker" and sometimes as "YouTube".

![pocket-seeker](https://user-images.githubusercontent.com/1721875/48710411-7ca6cd80-ec08-11e8-895e-94bede4e1c32.png)

![pocket-youtube](https://user-images.githubusercontent.com/1721875/48710426-892b2600-ec08-11e8-8e5b-07da4dc4408c.png)

### Device information

* Fire TV device: AFTA
* Firefox version: 3.1

**Comment by dnarcese** [comment]
In this case, it is showing YouTube because the pocket api returned an empty list for the `authors` field.

@kennylong should it be possible for there to be no author for a video? Are there certain cases where this happens?

**Comment by athomasmoz** [comment]
@dnarcese nice job building in a graceful fallback for this. Sounds like the issue here is on the pocket side. I suggest we close this issue once we get confirmation from their team to look into this.

**Comment by kennylong** [comment]
@dnarcese This looks like a rare corner case -- we have it captured but don't have an immediate fix. Given the graceful fallback handling, my understanding is that that's okay if it occasionally shows up like this, but let us know if you feel differently (and also if you see this issue come up more frequently).
