### ISSUE TITLE
Only print Pocket IO exceptions on debug builds

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1537]
### Why/User Benefit/User Problem
We are currently logging IOExceptions encountered when making Pocket related network requests in `PocketEndpoint#getGlobalVideoRecommendations`.

Users sometimes paste their logs online, potentially without realizing that personal information could be compromised.

### What / Requirements
We should only log these exceptions from debug builds.

**Comment by Baron-Severin** [comment]
Specifically, these are logged in `PocketEndpoint#getGlobalVideoRecommendations`.

**Comment by mcomella** [comment]
We're moving to the android-components implementation so this is no longer necessary.
