### ISSUE TITLE
Leaving loading video website to open pocket tile causes browser to not load any site

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1546]
## Steps to reproduce
- Go to 680news.com
- Click a video (latest video image) , wait until the page loads
- The page is loading for a while, doesn't look like it's completed, so click menu button to go to the main view
- Select one of the pocket tile to load
### Expected behavior
- Website loads

### Actual behavior
- Load freezes, the progressbar is frozen

IT looks like if I go to main menu while the page is loading and open another site, I can't load any more  websites

This is with both tracking protection on/off
### Device information

* Fire TV device: Cube
* Firefox version: 3.1 release

**Comment by npark-mozilla** [comment]
logcat shows repeat of the following:
```
11-21 19:01:00.870  3414  3463 I AUDIOALG: RefDlyEstimation: maxRxy 0.000000 maxPos 0
11-21 19:01:00.871  3414  3463 I AUDIOALG: asyncProcess : waiting...
11-21 19:01:02.912  3414  3463 I AUDIOALG: asyncProcess : process @@@
```

**Comment by npark-mozilla** [comment]
This may be a dupe of #977

**Comment by athomasmoz** [comment]
@npark-mozilla I just tried this on the release version. 680news.com latest video plays for me. I know you were seeing the issue on your cube though, do you mind retesting with the live version?

**Comment by npark-mozilla** [comment]
I just tested on live version, and I see the video playback fine, with no freeze on both cube and stick.  Only difference I notice is that the cookie warning popup shows up early when I go to 680news.com which I can dismiss, rather than the same time when I go to the video link.   Not sure what happened there though.  I suppose we can close this issue then?  (I see cnn website is loading fine now too)

**Comment by athomasmoz** [comment]
Phew! Thanks for checking that out. I don't think we need to log a bug for the cookie popup showing up early, unless we start to see any issues caused by that.
