### ISSUE TITLE
Peloton videos crash the browser

### ISSUE THREAD

**Issue by mconca** [mozilla-mobile/firefox-tv#1549]
Peloton just released a digital version of their product allowing subscribers to view any of their workout and training videos online. Trying to view these with Firefox for Fire TV seems to crash the browser, however.

STR:
1. Navigate to onepeloton.com
2. From the site's hamburger menu, select Sign In
3. Select Classes from the top nav bar
4. Pick any class
5. Press play

Result:
Screen goes blank for a few seconds, then the user is returned to the main Fire TV home screen.

Expected Result:
Video plays.

* Fire TV device: Fire TV (not the stick)
* Firefox version: 3.0

Note:  I am able to successfully play these videos in the Amazon Silk browser on same device.

**Comment by AaronMT** [comment]
Might need a minimal test-case if sign-in is required.

**Comment by liuche** [comment]
May be related to #1495, and we should see if this a WebView version problem.

**Comment by athomasmoz** [comment]
Consolidating similar issues. Tracking under #1577
