### ISSUE TITLE
Test Pocket backoff logic

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1554]
### Why/User Benefit/User Problem
When writing `PocketVideoRepo`, we were unable to test the most complex and error-prone part of the code (failed request backoff logic).  It currently regulates calls using coroutine delays, making testing difficult.  

There should be a way to handle time through an abstraction that allows us to test this code.  As this code is complex, this should be a high priority.

### What / Requirements
Test PocketVideoRepo backoff logic.

**Comment by psymoon** [comment]
It might be worth it to look into https://github.com/square/okhttp/wiki/Interceptors to possibly replace our manual retry logic

**Comment by Baron-Severin** [comment]
Note to QA on this one:  this changes a lot of logic around Pocket, but we want to verify that there are no functional changes.  It would be great to double check that:
1) If the project is built without a Pocket key, no network requests are made
2) Under normal circumstances, only a normal number of requests are made (that is, after a request succeeds it isn't followed by more requests)
3) A general smoke test of Pocket related features looks good

If you need any support from me to verify any of that, I'm happy to help!

**Comment by Baron-Severin** [comment]
> Note to QA on this one: this changes a lot of logic around Pocket, but we want to verify that there are no functional changes. It would be great to double check that:
> 
>     1. If the project is built without a Pocket key, no network requests are made
> 
>     2. Under normal circumstances, only a normal number of requests are made (that is, after a request succeeds it isn't followed by more requests)
> 
>     3. A general smoke test of Pocket related features looks good
> 
>     4. Non-EN locales still don't see Pocket, and don't make Pocket requests (note that it takes Fire TV a few minutes for locale changes to propagate out, and restarting our app for some of those changes to take effect)
> 
> 
> If you need any support from me to verify any of that, I'm happy to help!

@npark-mozilla given the problematic history of these Pocket files, I think it would be good to prioritize testing this fairly highly.  Do you know if anyone is available to take a look at it?

**Comment by npark-mozilla** [comment]
I think @levisacal should have bandwidth to test it, and create test cases in testrail.  @levisacal , if you have questions about getting a pocket key for local build, either let me or @Baron-Severin know.

**Comment by levisacal** [comment]
@Baron-Severin could you please advise how to test the network requests? Do you have any test cases in mind I could follow? Thanks

**Comment by Baron-Severin** [comment]
@levisacal if you're comfortable with it, using a packet sniffer like Wireshark or Charles to watch the actual requests in flight would be perfect.  If that's too much of a hassle, I can add logs into the code that makes the calls.  The former would be preferred because the latter would carry a small risk of error on my part.

I don't have any test cases, are there any in Test Rail?  If not, I can help create some.

**Comment by npark-mozilla** [comment]
If we're testing on device, it'd be more difficult to set up packet sniffer app for monitoring - If you can generate logs in the adb logcat, that would make testing much easier - and rule out other non-firefox tv android network requests that might be shown.  I don't think we have done this kind of testing before on mobile, would be a good idea to use this PR as an example for future.

**Comment by npark-mozilla** [comment]
Actually... since on the phone simulator, we can run firefox-tv pretty well (unlike tv-sim).  If so, then perhaps we can try the network profiler in Android Studio: https://developer.android.com/studio/profile/network-profiler .  @levisacal could you give a shot with firefox-tv running on a pixel 2 simulator?

**Comment by levisacal** [comment]
I started using the Android studio Network profiler with the actual Fire TV device to inspect the Pocket network request.

With a build without the Pocket key, there are no Pocket network requests. Looking into the other checks as well.
