### ISSUE TITLE
Remove Pocket code from WebRenderFragment#onUrlChanged

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1560]
### Why/User Benefit/User Problem
There is some outdated code in `WebRenderFragment#onUrlChanged` that should have been removed during the Pocket refactor.  As it was missed, we cannot be sure that it is not currently supporting important behavior.

### What / Requirements
- Remove Pocket related code from `WebRenderFragment#onUrlChanged`
- Verify that behavior is unchanged

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
