### ISSUE TITLE
ProgressView is visible after switching fragments

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1567]
## Steps to reproduce
From home screen
- Navigate to any site
- Open menu
- Open Pocket screen
- Back to main menu
- Close menu (i.e., return to browser)

### Expected behavior
- ProgressBar will be invisible

### Actual behavior
- ProgressBar is visible (but motionless)

### Device information

* Fire TV device: Pendant
* Firefox version: Release

**Comment by athomasmoz** [comment]
Closing as can't reproduce
