### ISSUE TITLE
JW Player Version 8 Crashes Fire TV

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1577]
## Steps to reproduce

1. Open Firefox
2. Open https://developer.jwplayer.com/tools/stream-tester/?playerversion=7
3. Open https://developer.jwplayer.com/tools/stream-tester/?playerversion=8

### Expected behavior

Both URLs should display the JW Player testing site, and the "TEST PLAYER" video should auto-play

### Actual behavior

Player version 7 works as expected
Player version 8 crashes Firefox. You are taken to Fire TV homescreen

### Device information

* Fire TV device: Firestick Basic Edition
* Firefox version: 3.1.2

### Notes

This is likely causing the following bugs:
#1234 
#1571  (haven't confirmed this is JW Player)
#1237 
#1815

**Comment by athomasmoz** [comment]
Note: this issue doesn't exist on Echo Show. Maybe we don't need to go all the way up to Chromium v70 for the fix? cc @liuche

**Comment by liuche** [comment]
Actually, I just tried this out on Fire TV with master (3.1.3) and I don't see a crash for 7 or 8.

The full-screen cuts off though:
![jw7](https://user-images.githubusercontent.com/1082253/50365754-d1e93e00-052a-11e9-9f8e-a351812d291d.png)

**Comment by athomasmoz** [comment]
Additional notes to help debug:
* This appears to crash on some devices, and endlessly load on others
* It happens with any JW Player video, a few sites you can try are 
- watch.cbc.ca (go to live video)
- hgtv.ca
- video.vice.com

**Comment by dnarcese** [comment]
The behaviour is different between debug and release builds. The player consistently crashes on release builds but on debug builds there is no crash but the webview breaks (current site is still responsive but unable to visit any other sites).

**Comment by dnarcese** [comment]
I've linked the crashes to this sentry report -> https://sentry.prod.mozaws.net/operations/firefox-tv/issues/4789503/
@athomasmoz It has affected 145k users. Let me know if there is other information you need!

**Comment by athomasmoz** [comment]
Consolidating a few bugs into this one. Before closing this, we should retest on sites:
* cbc.ca #1234
* hgtv.ca #1234
* imdb.com #1237
* timeout.com #1815
* skyvideo #1495 
* peloton.com #1549 
NOTE: I closed the original bugs for the above issues as duplicates. They should be re-opened if the issue still exists
NOTE: not all videos on these websites use JW Player. Should confirm the test is done on a video using that player

**Comment by athomasmoz** [comment]
No longer reproducible. However, uncovered a new issue tracked in #2170

**Comment by athomasmoz** [comment]
TODO: Confirm that the sites are no longer crashing.
cbc.ca #1234
hgtv.ca #1234
imdb.com #1237
timeout.com #1815
skyvideo #1495
peloton.com #1549

**Comment by athomasmoz** [comment]
Closing this ticket. Crash no longer occurs, but we are seeing videos cut off #2170
