### ISSUE TITLE
Can't go back out of YouTube from a Pocket video with remote back

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1584]
Similar to #1542, but specifically for the case where you got to YouTube from clicking a video in the Pocket feed.
## Steps to reproduce
1. Visit any site
2. Open overlay and click Pocket
3. Click video
4. Try to exit YouTube with remote back button
### Expected behavior
Ability to go to the previously visited site.
### Actual behavior
Stuck on YouTube side navigation bar.
### Device information

* Fire TV device: 4k
* Firefox version: 3.1.2

**Comment by dnarcese** [comment]
Visiting YouTube from Pocket acts differently than visiting from the home tile because it does not actually visit 'youtube.com/tv' or 'https://ftv.cdn.mozilla.net/ytht'. In the current implementation for exiting YouTube, we check for 'https://ftv.cdn.mozilla.net/ytht' in the backstack and then go back to the previous item. Since videos have different urls everytime, a different approach is needed.

Possible other approach:

- Check whether the active element has not changed between the last 2 back clicks. This means YouTube focus has settled on one item and that the next back click needs to go back in the backstack.

**Comment by dnarcese** [comment]
A possible approach to handle visiting YouTube from Pocket or from typing youtube.com/tv into url bar:

- Anytime YouTube is visited (coming from a website other than YouTube), add the index of that website in the backstack to a list. When remote back is clicked and the YouTube guidelist is focused, pop and visit the last index in the list. This will handle cases where YouTube is visited multiple times in a session. 
_Edge case_: If a user clicks toolbar back multiple times to back out of YouTube, the list will not get updated so next time they back out with the remote, they will be taken to an incorrect site. I'm not sure how often this would happen and if it is worth the time to handle?

@mcomella Does this seem like a valid approach?

@athomasmoz How important do you think handling the edge case is? The main issue of being able to back out of YouTube would be solved, but in the (probably rare*) case, the history could be out of order and cause confusion for the user. 
*Looking at telemetry, the remote back is being clicked significantly more than the toolbar back.

**Comment by athomasmoz** [comment]
Thanks for checking the telemetry, I'm not surprised remote back is used more. Do you mind detailing out the steps for the edge case? I'm having a hard time following it.

**Comment by dnarcese** [comment]
@athomasmoz yup! Hopefully this makes more sense:
1. visit google
2. visit youtube tile and watch video
4. visit imdb
5. visit youtube tile and watch another video
6. click toolbar back several times until back on imdb
7. click toolbar back again to get to first youtube video
8. click remote back several times to back out of youtube

Expected: Taken back to google
Actual: Taken back to imdb

**Comment by athomasmoz** [comment]
Do you get stuck in a loop then? So,

7. click remote back several times to back out of youtube (taken to imdb)
8. click remote back again (taken to youtube)
9. click remote back again (taken to imdb)?

**Comment by dnarcese** [comment]
@athomasmoz I don't think you would get stuck in a loop. The next time you exit YouTube with remote back, you would get back to Google. If you exit YouTube with toolbar back, it would still follow the backstack correctly and get you back to Google as well.

**Comment by athomasmoz** [comment]
Oh ok. I think that's a fair trade off. But we should keep a bug logged for that in the backlog

**Comment by mcomella** [comment]
> Anytime YouTube is visited (coming from a website other than YouTube), add the index of that website in the backstack to a list. When remote back is clicked and the YouTube guidelist is focused, pop and visit the last index in the list. This will handle cases where YouTube is visited multiple times in a session.

What's the difference between this solution and the current implementation? What information are we gaining? What are the trade-offs (pros, cons) between this solution and the current implementation?

> A possible approach to handle visiting YouTube from Pocket or from typing youtube.com/tv into url bar:

How does this solution address visiting YouTube from Pocket (i.e. going back in the fragment back stack)?

> @mcomella Does this seem like a valid approach?

You tell me! :) @dnarcese

**Comment by AaronMT** [comment]
Still reproducible on master (3020765b406db21367dd400696a7e2403063fba5) on my 4K

**Comment by athomasmoz** [comment]
@AaronMT Is this a dup of #773 ? I scheduled that into next sprint as a P1 thinking it was this issue. Agree it is important

**Comment by AaronMT** [comment]
Nearly the same 

#773 can't easily get back to the feed
#1584 can't get back to the browser

**Comment by athomasmoz** [comment]
Got it, thanks for the clarification. I'll update priorities and make sure this one #1584 is on the table for next sprint.
