### ISSUE TITLE
Firefox exits when back button is pressed on a webpage after the app is reopened

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1589]
## Steps to reproduce
- Enable turbo mode, open website by typing in the URL bar
- After the page is open, press back button to go back to main view
- Press back button again to exit
- Select the app to reopen
- Type the same URL (different URL should also work)
- Press back button

### Expected behavior
- Shows the tile view and remains there

### Actual behavior
- Shows the time view briefly, then exits the app

### Device information
* Fire TV device: Cube, Fire OS 6.2.5.8
* Firefox version: 3.2.1.3

**Comment by npark-mozilla** [comment]
Workaround:  use the menu to get back to the home-screen instead of the back-button

**Comment by dnarcese** [comment]
Seems to be that the second time the app is opened, `firefox:home` isn't properly being added to the history stack, so from the first website, the app thinks there is nothing to go back to, and therefore closes.

**Comment by npark-mozilla** [comment]
FYI, this does not repro on 2.1.2

**Comment by Baron-Severin** [comment]
I see this in the logs when this crashes.  Possibly related to a memory leak?

```
2018-12-19 10:50:38.503 10439-10439/org.mozilla.tv.firefox.debug E/StrictMode: class org.mozilla.tv.firefox.MainActivity; instances=2; limit=1
    android.os.StrictMode$InstanceCountViolation: class org.mozilla.tv.firefox.MainActivity; instances=2; limit=1
        at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
```

**Comment by npark-mozilla** [comment]
I can no longer repro this issue, closing it
