### ISSUE TITLE
Cannot back out of YT if the app is reopened

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1595]
## Steps to reproduce
- Open app, open YT by clicking the tile
- Click a couple of video links
- Press back button until tile view is shown
- Press back button to exit the app
- Reopen app
- open YT by clicking the tile
- Click back button to exit YT to tile view
### Expected behavior
- Shows tile view
### Actual behavior
- Stays in YT
Pressing menu to show tile view then clicking back only returns to YT
### Device information

* Fire TV device: Cube
* Firefox version: 3.1.3

**Comment by npark-mozilla** [comment]
Workaround: click menu button to go to tile view, clear history, then press back button

**Comment by AaronMT** [comment]
Reproducible on the 4K too, same build.

**Comment by npark-mozilla** [comment]
I cannot repro this on the latest LAT
