### ISSUE TITLE
Add on-screen button to overlay to exit Firefox

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1619]
### Why/User Benefit/User Problem
Users say it's difficult to exit the app, adding a button to the overlay will help users who can already access the menu overlay to exit the app

### What / Requirements
Design for button to exit the app, on the overlay (This is already part of the IA in https://github.com/mozilla-mobile/firefox-tv/issues/1071#issuecomment-437353066 , and there's a design, we just need the button asset - in the meantime we can use a placeholder icon)
Telemetry to see usage, and measure effectiveness

### Acceptance Criteria (how do I know when I’m done?)
* Button added to overlay that can exit app
* Telemetry probe added to track the number of times the exit button is used

### Design

* Here's the icon https://drive.google.com/open?id=1fGEOhh9Mzv8ABEa4JpqZrH5fHpmp0_Dc&authuser=tshakespeare@mozilla.com
* The icon should be placed to the left of the settings cog

![image](https://user-images.githubusercontent.com/43346208/51064204-5c194500-15b3-11e9-94a3-ea555b9f448b.png)

**Comment by lime124** [comment]
here is the icon: https://drive.google.com/open?id=1fGEOhh9Mzv8ABEa4JpqZrH5fHpmp0_Dc&authuser=tshakespeare@mozilla.com

The goal was to use the same icon as the remote to reinforce the idea of fire tv home. I got approval from Bryan Bell on the design.

**Comment by athomasmoz** [comment]
Thanks @lime124 ! Good idea with the icon design.

**Comment by athomasmoz** [comment]
@lime124 your design is based off the new collapsed toolbar, which is currently [blocked](https://github.com/mozilla-mobile/firefox-tv/issues/1315#issuecomment-453598061)

Do you think it would make sense to add this home/exit button to the existing toolbar?

**Comment by athomasmoz** [comment]
Confirmed design & updated original description in this ticket to reflect.

**Comment by dnarcese** [comment]
@athomasmoz What should the behaviour of the exit button be?
- similar to remote home button: after clicking button and re-opening app, you are returned to the same state
- similar to back button exit behaviour: re-opening starts from a clean state with no history

**Comment by athomasmoz** [comment]
@dnarcese thanks for checking, it should match the home button behaviour. The back button to exit behaviour is only different because it exits after you've gone back through the whole history stack.
