### ISSUE TITLE
Track Clicks on YouTube Tile

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1620]
### Why/User Benefit/User Problem

Determine how many people & sessions use Firefox for things outside YouTube

### What / Requirements

* YouTube Tile clicks are tracked

### Acceptance Criteria (how do I know when I’m done?)

* We can pull data to determine the count & percent of sessions that include non-YouTube tile clicks
* We can pull data to determine the count & percent of users that click non-YouTube tiles

### Anti-vision

* Aside from YouTube, we do not track which tiles are clicked on or which URLs they go to

**Comment by dnarcese** [comment]
@athomasmoz Should a YouTube tile click still count for a click on a `bundled` home tile? 
ie. in our Telemetry we have an entry for `bundled` `home_tile` clicks and there will be a new entry for `youtube` `home_tile` clicks. When a user clicks the YouTube tile, should the number for both entries increase, or just the youtube entry?

**Comment by athomasmoz** [comment]
Yes, I don't want to change the behaviour there. We should still have it count for a home tile click. 

I'm glad you called it out though, sounds like something that should be documented. Do we have documentation on the different events tracked?
