### ISSUE TITLE
Audit and clean up cases where there is no Session even though we expect one

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1631]
Follow-up from #1394: There are a couple of places where we "force create" a session because we expect one but one does not exist. These are suspicious and we should clean them up, or fix the problems that could lead to these (or comment them clearly).

When initializing WebRenderFragment from a session: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt#L102

When loading a url: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/webrender/WebRenderFragment.kt#L312

**Comment by liuche** [comment]
We could probably also optimize clearing data, which currently recreates the activity, but could just call `EngineSession.clearData` - unclear why we needed to recreate the activity now, but maybe there was a reason.

**Comment by liuche** [comment]
Here's a case where there are no sessions, and we're running into problems:
https://github.com/mozilla-mobile/firefox-tv/pull/1726/commits/10f59c7c16af6120d3c08257291fd63211a8d46e#diff-5bbca9b9bb8d3ee9beb6a9e08b9ebdd4R152

basically, after "Clear Data" we don't have any sessions AND we don't have a WebView to fetch from the layout.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
