### ISSUE TITLE
[#1394 Follow-up] Improve about:home handling w/ fewer special cases

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1638]
As part of #1394 we found that the about:home history item introduces a bug when loading VIEW intents (which we'll need in #1284). We should re-evaluate how we approach that, possibly:
* Removing `about:home` from the history stack entirely now that Overlay is just a Fragment
* Use `canGoBackTwice` to make sure we shouldn't be exiting the app

This also needs to handle the case of closing a Firefox instance that's been opened via an Intent (like a VIEW intent). Right now, this toggles the Navigation Overlay, because "back to exit" behavior checks for the app to be on about:home, which isn't the case when Firefox is opened from cold start via an intent.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
