### ISSUE TITLE
Backing during page load causes URL bar to switch between URLs

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1639]
### From home screen
- Open tile X
- Return to overlay
- (wait ~.5 seconds)
- Open tile Y
- Return to overlay
- (wait ~.5 seconds)
- Select back button

### Expected behavior

- URL bar should display URL A

### Actual behavior

- URL bar switches back and forth between URL A and URL B

### Device information

* Fire TV device: Cube
* Firefox version: 77b6ac3809067762674f0f9c65c368cac7c09b98

![back-during-load](https://user-images.githubusercontent.com/13170306/50716243-a475b780-1035-11e9-8d0a-8af3b49662d1.gif)

**Comment by athomasmoz** [comment]
Retest after #1646

**Comment by mcomella** [comment]
I can no longer reproduce. @Baron-Severin Can you still reproduce? If not, please close.
