### ISSUE TITLE
Track Overlay Architecture regressions in 3.1.3.* LAT

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1640]
Here's a bug to add any regressions that you find for our LAT branch https://github.com/mozilla-mobile/firefox-tv/tree/releases/v3.1.3.1

Some known issues:
- [x] Clicking "menu" on Pocket won't bring up Overlay
- [ ] Can't exit if open Firefox from cold start with a VIEW intent for a url
- [ ] Exiting app with "back" doesn't clear history (we should discuss whether this is intended behavior @athomasmoz)
- [ ] Pocket Youtube video focus problem
* Click a Pocket video
* dpad down to highlight "pause" button in player
* Open overlay and click a different Pocket video
* Try clicking dpad buttons or back button
- [x] Can't load Youtube after visiting Settings > About

If you find any other bugs (especially focus bugs, or bugs on Youtube), please aggregate them here!

**Comment by levisacal** [comment]
YouTube overlay is missing also with the following STR:
1. Start up Firefox with a clean profile (Clear all cookies and site data)
2. Open YouTube from the top 10 sites panel and remain on the Welcome! Sign in - it's free page
3. Open up a Pocket Video

YouTube overlay is missing.

The issues is not 100% reproducible

**Comment by dnarcese** [comment]
There is a focus regression related to switching fragments. The previous behaviour was that when you click the Pocket megatile and then return to overlay, the megatile would be focused, and the same for clicking Settings. This doesn't happen anymore - focus goes to the top element on the visible screen.

**Comment by mcomella** [comment]
This is an old release: I don't think we need this bug anymore.
