### ISSUE TITLE
BasicNavigationTest is broken on emulators

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1649]
This test verifies (among other things) that the URL bar is filled with the page title after opening a URL. 

On emulators, the URL bar shows various assets instead of page titles (#1444) whenever Turbo mode is enabled.

I attempted to turn off Turbo mode early in the test to mitigate this, which works in NetworkPageLoadTest, but here it led to strange process crashes.

**Comment by mcomella** [comment]
No-Jun also mentioned StrictMode violations: not sure if this is still
relevant.

**Comment by mcomella** [comment]
I can no longer reproduce this.
