### ISSUE TITLE
Crash the first time you open Firefox through YouTube.com app

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1655]
## Steps to reproduce

1. Search "youtube"
2. Download "YouTube.com" app
3. Open app, unselect checkbox and click "Firefox"

### Expected behavior

Youtube opens in Firefox

### Actual behavior

Looks like something tries to load, then you are taken to Fire TV homescreen. Note: this only happens the first time after installing the app

### Device information

* Fire TV device: Cube
* Firefox version: 3.1.3

**Comment by levisacal** [comment]
After Firefox is opened up, the remote directional pad does not re-focus any UI element on YouTube. The only way to perform interactions is to access the start page by using the menu button and to access any other link.

**Comment by psymoon** [comment]
WIP fix pr merged here - https://github.com/mozilla-mobile/firefox-tv/pull/1688. Next step is to reproduce and verify that it's fixed
