### ISSUE TITLE
After Clearing Data, the first attempt to exit app through "back button" doesn't work

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1657]
Build: 08758c21ef6cc8f820d9e4ea30520e358c3e6b64 (master)

 - Clear Private Data 
 - Hit Back (address-bar will be focused)
 - Hit Back again (address-bar is not focused) - (the app should close but doesn't?)

From then, hitting the remote directional pad does not re-focus any UI element. The only way to perform interactions is to close and reopen the browser.

**Comment by liuche** [comment]
@AaronMT I think this is fixed on the new master (now that we've merged the overlay changes in) - can you verify this?

**Comment by AaronMT** [comment]
The worst of it is fixed however on first `back` attempt when the address-bar is focused, it is ignored (thus if one is trying to back out of the application, they have to hit back twice).

**Comment by athomasmoz** [comment]
Can you confirm the new STR? Is this correct:

- Clear Private Data
- Hit Back (address-bar will be focused)
- Hit Back again

Expected behaviour: App closes
Actual behaviour: address-bar is not focused. Hitting back again will exit app

**Comment by athomasmoz** [comment]
Todo: determine if this is still an issue on the latest & whether or not it's a regression

**Comment by mcomella** [comment]
I can no longer reproduce this on master (with Settings now below the fold).
