### ISSUE TITLE
[#1394 Follow-up] Be explicit about startup flow

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1658]
We have several entry points into the app (Intents, restoring instances, onCreate) and #1394 simplified the flow through these steps, but it needs to address all these entry points (and make sure each entry point does any setup necessary, like creating sessions).

See for more context: https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245436918

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
