### ISSUE TITLE
[#1394 Follow-up] Use onSaveInstanceState for restoration

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1659]
In #1394, we removed usage of `onSaveInstanceState` to save state on app close, because it was breaking when using "Clear Data".
Some options to look at:
- Don't do activity recreate - since we're recreating the activity, the app goes through the `onSaveInstanceState` which is interacting badly with the fragment manager (and leaving the Settings Fragment in a limbo state, detached from the activity, but still in the forefront)
- Why is fragment manager not being destroyed properly (and leaving the old Settings Fragment around)? Figuring this out would allow us to still recreate activity

For more context: https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245187268

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.

We haven't noticed any problems so maybe this is working fine.
