### ISSUE TITLE
[#1394 Follow-up] Retain focus when going "back" from Pocket or Settings

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1660]
## Steps to reproduce
Highlight Pocket on Navigation Overlay
Open Pocket
Hit back

### Expected behavior
Pocket item is highlighted on Navigation Overlay, showing user the previous state

### Actual behavior
Default Navigation Overlay highlight behavior

**Comment by liuche** [comment]
We won't need this once we switch to channels #1630

**Comment by mcomella** [comment]
> We won't need this once we switch to channels #1630

We're committed to channels and we may forget to revisit: pre-emptively closing.
