### ISSUE TITLE
[#1394 Follow-up] Verify behavior

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1661]
- [ ] after ac37 lands, verify back/forward buttons toggle correctly on page navigation (and don't toggle indefinitely)
- [ ] Does switching from LinearLayout to FrameLayout w/ Fragment containers cause any perf regressions? https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245149464
- [ ] Verify telemetry is still working

**Comment by mcomella** [comment]
We haven't noticed any problems so I guess we've addressed all these.
