### ISSUE TITLE
[#1394 Follow-up] Add helper function to throw illegal states in a Sentry.capture(Throwable)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1662]
One thing we started doing in #1394 was sending Sentry reports when we assert states that we don't expect. This is currently very piecemeal, so we should make a helper function to do this.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
