### ISSUE TITLE
[#1394 Follow-up] Move Action.Show*Toast to consumable

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1663]
See context:
https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245857132

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
