### ISSUE TITLE
Refactor overlay into split

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1664]
Refactor overlay into split

    This will involve adjusting fragment transactions so that WebRenderFragment is visible

**Comment by mcomella** [comment]
I haven't made progress beyond the initial PR that landed: feel free to take this (but if it's untaken, I can tackle it again tomorrow).

**Comment by liuche** [comment]
I'm also sending @brampitoyo a build so I can get some feedback on various sizing of the toolbar, window space, etc, but since this is landing turned off I can file the polish in a later bug.
