### ISSUE TITLE
Consider adding TestRail test case for opening Firefox through youtube.com app

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1665]
We recently found a crash when opening Firefox through the youtube.com app: #1655. Currently, we have no automation to test this case (receiving links from external apps) so we should consider adding a TestRail test case for this.

I was thinking we test both opening Firefox for the first time and opening Firefox while it's already running. Steps:
- Install Firefox
- Clear data (through UI or `adb shell pm clear org.mozilla.tv.firefox` (or append `.debug`))
- Open youtube.com app (installed from Amazon store), selecting Firefox if not already preferenced

Expected: Youtube.com/tv opens

- Go to other page in Firefox (e.g. google video search tile)
- Close Firefox
- Open youtube.com app, selecting Firefox

Expected: Youtube.com/tv opens

@AaronMT What do you think? Alternatively, we can try to get automation to test this and maybe the dev fixing #1655 will do that.

Note: No-Jun requested I file a GitHub issues for this and assign Aaron so that's what I did. Let me know if that is incorrect in any way. :)

**Comment by npark-mozilla** [comment]
@levisacal , could you look into this? thanks!
