### ISSUE TITLE
PinnedTileTests is broken

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1668]
### The Problem
There are two known issues with this test.
- An off by one error.  We `assertPinnedTileExists` in position 11, however this should target the 11th tile (i.e., position 10)
- The 11th tile appears off screen, causing the Espresso assertion that it exists to fail

### Attempted Solutions
- Deleting several tiles (allowing room for the new one to be on screen), and then targetting the correct index *does cause this test to pass*, but the resulting code is confusing.
- Using `RecyclerViewActions.scrollToPosition` was unsuccessful.  The screen did not scroll as expected.  This may have been due to misuse of the API on our part

### Proposed solution
Ideally, we would be able to substitute in pinned tiles for tests.  This would let us include a smaller number, ensure that each pointed to a MockWebServer (rather than loading real data), and ensure that newly pinned tiles are shown on screen.

**Comment by AaronMT** [comment]
Akin to #1360 this should be prioritized the same as that.

**Comment by mcomella** [comment]
afaik, PinnedTileTests is no longer broken: it doesn't have an `@Ignore` so I assume it's running and passing.
