### ISSUE TITLE
Add Fretboard

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1676]
### Why/User Benefit/User Problem

As a PM, I want Fretboard set up on Firefox for Fire TV to run split testing, so that I can measure the impact of new features using A/B tests

### What / Requirements

* Fretboard is added to Firefox for Fire TV

### Acceptance Criteria (how do I know when I’m done?)

* Fretboard package has been added to FFTV
* Determine package structure

**Comment by psymoon** [comment]
Created a bug for Kinto backend: https://bugzilla.mozilla.org/show_bug.cgi?id=1521161
