### ISSUE TITLE
Firefox will not start after updating to Firefox TV v3.2.2

### ISSUE THREAD

**Issue by netz-filter** [mozilla-mobile/firefox-tv#1684]
After the update to Firefox TV v3.2.2 from the Amazon DE Appstore Firefox does not start anymore.

After uninstalling Firefox with a subsequent reinstallation, the Pocket message "Here come from Pocket recommended videos" with a query "OK, understood" Firefox crashes again.

If you try to open Firefox again, only a gray screen appears briefly and the app crashes again.

Amazon Fire TV Stick 4K
Fire OS 6.2.5.8 (1711686788)

**Comment by Hocer** [comment]
Exact same issue here.

Please fix ASAP!

**Comment by AaronMT** [comment]
Was unable to reproduce on my 4K (6.2.3.2) device (English). Clean installation of 3.2.2 and first-launch works for me.

I then upgraded my OS firmware to 6.2.5.8, swapped from English to German and reinstalled the application and can reproduce the crash.

`01-16 10:58:35.550  6710  6710 E AndroidRuntime: Process: org.mozilla.tv.firefox, PID: 6710
01-16 10:58:35.550  6710  6710 E AndroidRuntime: 	at org.mozilla.tv.firefox.pocket.PocketVideoFragment$onCreateView$1.onChanged(PocketVideoFragment.kt:61)
01-16 10:58:35.550  6710  6710 E AndroidRuntime: 	at org.mozilla.tv.firefox.pocket.PocketVideoFragment$onCreateView$1.onChanged(PocketVideoFragment.kt:38)
01-16 10:58:35.607   668   679 W ActivityManager:   Force finishing activity org.mozilla.tv.firefox/.onboarding.OnboardingActivity
01-16 10:58:35.614   668   679 W ActivityManager:   Force finishing activity org.mozilla.tv.firefox/.MainActivity
01-16 10:58:35.682   668   784 W InputDispatcher: channel 'fbf9aa6 org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-16 10:58:35.682   668   784 E InputDispatcher: channel 'fbf9aa6 org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-16 10:58:35.684   668  5048 I WindowManager: WIN DEATH: Window{fbf9aa6 u0 org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity}
`

**Comment by levisacal** [comment]
Reproduced on my 4k fire tv (6.2.5.8) as well with any other locale than EN.
