### ISSUE TITLE
Fix ToggleDataCollectionTest#WHEN_data_collection_button_is_toggled_THEN_button_state_persists_when_returning_to_settings

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1700]
I noticed that this is broken on master.  This needs to be fixed (or at the very least ignored) before we can get ui tests on CI.

**Comment by liuche** [comment]
I'll pick up this bug - I wonder if I broke this while resolving conflicts during the rebase.

**Comment by liuche** [comment]
No need to QA, this should just pass now in the UI tests.

**Comment by AaronMT** [comment]
Awesome, thanks!
