### ISSUE TITLE
Allow Proguard to keep all the necessary @JavascriptInterface classes/methods with WebView

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1705]
Generated in the default `proguard-rules.pro`. Uncomment https://github.com/mozilla-mobile/firefox-tv/blob/master/app/proguard-rules.pro#L23

**Comment by mcomella** [comment]
@psymoon Is this to remove unused `@javascriptInterface` or to prevent unused methods, e.g. like the ones in `@javascriptInterface` from being removed?

In any case, this seems fragile (need fully-qualified class names of classes with `@JavascriptInterface` so if it's working now without these lines of code, I'm hesitant to add them.

**Comment by psymoon** [comment]
@mcomella: I think proguard obfuscates android internal classes as well. We need to verify other `webview` operations that rely on internal JS work correctly in both release and debug builds.  We definitely don't want `public *;` though. Possibly related - https://github.com/mozilla-mobile/firefox-tv/issues/1758

**Comment by mcomella** [comment]
@psymoon Given @dnarcese confirmed that all of our `@JavascriptInterface` features are still working, I don't think we're seeing any negative effects from not doing this. Given the lack of negative effects and the fragility of implementing this (hard-coded qualified class names in a separate file), I was wondering if we should just close this issue and not implement the fix. What do you think?

CC @liuche

**Comment by mcomella** [comment]
@psymoon ping ^

**Comment by psymoon** [comment]
@mcomella yeah, we can close this for now but will keep this as a reference to https://github.com/mozilla-mobile/firefox-tv/issues/1705

**Comment by mcomella** [comment]
> @mcomella yeah, we can close this for now but will keep this as a reference to #1705

@psymoon Did you mean to link another issue? The issue you mention is this issue.

**Comment by psymoon** [comment]
> @psymoon Did you mean to link another issue? The issue you mention is this issue.

Oops, fixed 😅
