### ISSUE TITLE
Testing: Have UI Tests run daily

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1706]
We're currently working on adding automated tests into CI. Until then, we should run tests periodically and provide results.  As a temp measure, QA will run UI test suite locally until the automation is in place.  @levisacal , could you run the tests daily (when there is a commit to master) and generate issues for failures?  If you have issues running the test, we can help you.

**Comment by levisacal** [comment]
I have ran a test suite on 3.3.0-LAT1. The results can be found here. https://testrail.stage.mozaws.net/index.php?/runs/view/14956&group_by=cases:section_id&group_order=asc&group_id=24883

I have also logged in 3 new issues (#1732, #1731 , #1730 ) but I don't think that they are major issues.

Also left a comment on #1598 as the issues is still reproducible

**Comment by npark-mozilla** [comment]
Actually we want to automation suite to be run daily as a sanity check.  @AaronMT and I will send you instructions on how to execute the automation suite soon.  Leave us any comments if you run into issues.

**Comment by mcomella** [comment]
@npark-mozilla Can this be closed?

**Comment by AaronMT** [comment]
Yes. I'll open a bug for BitBar once the PR is tidied with review.
