### ISSUE TITLE
Youtube video plays in wrong aspect ratio after playing no-YT video fullscreen

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1719]
## Steps to reproduce
- Go to 680news.com, pick a video, play fullscreen
- Click menu button, go to youtube, play video

### Expected behavior
- YT video plays fullscreen

### Actual behavior
- YT video plays using only top half of the screen
![img_20190124_235536327](https://user-images.githubusercontent.com/6930774/51748856-b0c0c380-207b-11e9-9569-dee68827f24c.jpg)

Workaround: kill app, restart
### Device information

* Fire TV device: Fire TV Cube
* Firefox version: 3.3.0 LAT

**Comment by athomasmoz** [comment]
@npark-mozilla Reproducible on 3.2.5 with stick basic edition. Not marking as a release blocker, but marking as a P1 and adding to next sprint.

**Comment by mcomella** [comment]
I wonder if this is related to #1625, where fullscreen videos on cc.com get cut off.

**Comment by liuche** [comment]
We should try to reproduce on Silk, but this could also be something going wrong with our fullscreen code (which is now handled in AC).

**Comment by mcomella** [comment]
First next step: try to figure out whose fault it is (us, ac, webView?).

**Comment by levisacal** [comment]
Reproducible on 4k Fire Tv remote also.

**Comment by Baron-Severin** [comment]
I'm able to consistently reproduce this on v3.2.5, but only occasionally on master (57bf23f96cc4c9b6163096a039451ab0dd0d66e4).  There are a few differences that could account for this:
- master has a different A-C version
- I built master on debug, but tested the release version of v3.2.5

I'll update here as my investigation progresses.

**Comment by Baron-Severin** [comment]
It would be great to figure out what's actually happening here, but in the meantime I have confirmed that exiting fullscreen mode before loading YouTube does successfully fix the problem.

I'll keep trying to find a better solution, but I'm timeboxing it to the end of the day.
