### ISSUE TITLE
Website briefly flashes when going to About or Privacy Notice in Settings

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1722]
## Steps to reproduce
- Open a website
- Press menu to open overlay, go to Settings, and click 'About' or 'Privacy Notice'

### Expected behavior
- Corresponding page shows up 

### Actual behavior
- Before the corresponding pages show up, the previously opened website briefly flashes

### Device information

* Fire TV device: Fire TV Basic
* Firefox version: 3.3.0 LAT

**Comment by athomasmoz** [comment]
I'm going to close this as likely won't fix. I don't think it's a poor user experience, it just suggests that about & privacy notice are web pages. May be fixed in the future as we bring settings to home screen.
