### ISSUE TITLE
After visiting youtube initially, the back button is never greyed out

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1723]
## Steps to reproduce
- Open app, open youtube via tile. Open video
- Open menu overlay, visit a non-youtube app.
- Press back button on overlay until it is greyed out

### Expected behavior
- After reaching youtube, the back button on overlay should be greyed out

### Actual behavior
- Back button is never greyed out
### Device information

* Fire TV device: Fire TV Basic
* Firefox version: 3.3.0 LAT

**Comment by athomasmoz** [comment]
This is a regression. Marking as P1, but not release blocker.

**Comment by liuche** [comment]
Context: we used to copy the back/forward state, but now we just check for `canGoBackTwice`.

**Comment by Baron-Severin** [comment]
YouTube adds a lot of redirects to our back/forward history.  By repeatedly pressing back, I am eventually able to get the back button to grey out (this does take eight or so clicks).  This is pretty silly, but I'm not sure it's something we want to change.  As far as I can tell, we would need some special case for backing on YouTube, which 1) is a lot of work for minor web compat, and 2) opens us up to making potentially serious mistakes (e.g., disabling the back button when a user is on a video).  

I would be curious to know how the desktop team approaches this issue.  From personal experience as a user, I know it's not a solved problem.

FWIW, this doesn't appear to me to be a regression. It's possible that YouTube has changed something on their end, but I was able to reproduce this on c3ae6625 (Nov 30, 2018).  That commit enables the back button based on `Session#canGoBack`, which is tied directly to `WebView` state.

**Comment by Baron-Severin** [comment]
@npark-mozilla I can also reproduce this on youtube.com/tv on desktop FF and Chrome.  I think this is something that needs to be fixed on YouTube TV's end.
