### ISSUE TITLE
GPL and Licenses links from About section not working

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1731]
## Steps to reproduce

1. Go to About-> GNU General Public License
2. Try and access the link by pressing on GNU General Public License v3 as it seems that is a link.

### Expected behavior

GNU General Public License link is opened

### Actual behavior

Link is not working.

When trying to access the link again, the GNU General Public Licensev3 is only bolded.

### Device information

* Fire TV device: 4k with remote
* Firefox version: 3.3.0-LAT1

**Comment by liuche** [comment]
I took a quick look at this and in `LocalizedContent.kt` we need to specify the android assets uri locations for these local html files. One is the licenses.html and the other is the GPL.html, both of which are in app/src/main/assets/ but right now are just being referenced by their filename with no path.
