### ISSUE TITLE
Rename confusing "webview" to differentiate between EngineView and WebView

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1735]
As part of #1720 it's confusing that both EngineView and WebView use the variable `webView`
https://github.com/mozilla-mobile/firefox-tv/pull/1726/commits/10f59c7c16af6120d3c08257291fd63211a8d46e#r251492765

This should be very small to rename, with an improvement in clarity (because the Engine/Session/WebView architecture from AC is already fairly complex).

**Comment by mcomella** [comment]
@psymoon Should this be moved to the current sprint milestone?

**Comment by psymoon** [comment]
@mcomella Yes
