### ISSUE TITLE
Handle "Clear Data" more correctly

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1736]
## Steps to reproduce
We've encountered a lot of crashes related to Clear Data and the cleanup/recreating activity around that. For context, we're doing both a) handling Fragment management manually without calling lifecycle events through `onPause`, etc, b) only handling `MediaSession` cleanup in lifecycle events.

We need to clean this up. Some options:
* Call cleanup events outside of lifecycle
* Don't recreate activity anymore because AC37 should fix WebView memory leak that was related to us resorting to destroying the activity for cleanup
* Do we even need to destroy the WebView?
* Hook lifecycle events back into Fragment behavior (not sure if this would actually simplify the situation and doesn't enforce lifecycle management further down the line anyways)

### Expected behavior
* Not calling WebView methods when the WebView has been destroyed
* Possibly only relying on cleanup methods rather than destroying everything on data clear
* Clear states for Session/Engine/WebView lifecycles so we don't get these bugs anymore

### Actual behavior
Crashes related to this:
#1453 low-crash rate Kotlin NPE when cleaning up MediaSession
#1631 Session could be null, even though we don't expect it
#1611 SettingsFragment crash (though this is no longer 
#16 Clean up MediaPlayer resources

### Device information

* Fire TV device: any
* Firefox version: 3.2+, some bugs on release-only

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.

If there's a high enough crash, we can then address this.
