### ISSUE TITLE
Pocket feed continues to be shown after language change

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1737]
Tested with 3.3.0-LAT1 on a 4K.

Currently on locale change through the OS, the Pocket feed will continue to show.

* E.g, change from English to German system language

* Expected: Pocket feed hidden
* Actual: Pocket feed still visible

**Comment by AaronMT** [comment]
The reverse happens for German to English where the feed will remain hidden.

**Comment by AaronMT** [comment]
Work-around, device reboot

**Comment by liuche** [comment]
We've seen the Amazon device also do this (show dialogs/notifications in the wrong language) - since it's not a common use case (switching between languages) we didn't prioritize this in the initial implementation.

**Comment by athomasmoz** [comment]
Closing as won't fix. This is a common issue when switching languages and will update after a few mins.
