### ISSUE TITLE
#2 YouTube- When performing a voice search during playback and returning to the app, the video fast-forwards for a bit with no sound prior to resuming.

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#174]
Steps to Reproduce:

                1. Install and Launch the app.

                2. Select the YouTube Icon.

                3. Play any video.

                4. Initiate Voice Search.

                5. Click back on the remote to return to the video.

                6. Click Play to resume the video.

                7. Observe.

Actual Result: Video fast-forwards with no sound for a couple seconds prior to resuming.

Expected Result: Video should resume from where the user left off without any issues.

**Comment by athomasmoz** [comment]
Not reproducible
