### ISSUE TITLE
Add release history post v3.2.2 in CHANGELOG

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1749]
In our CHANGELOG, currently we have release history for v3.2.2 but nothing after that, even though I see v3.2.3, v3.2.4, and v3.2.5 in our local git tags: what are those releases? What shipped in them?

fwiw, as a developer unfamiliar with FFTV, I'm trying to use the CHANGELOG to identify where a regression started (#1748) and I'm unable to do so because it's missing information.

Can we use the github releases version history to recreate the history? https://github.com/mozilla-mobile/firefox-tv/releases

**Comment by dnarcese** [comment]
3.3 also needs to be added.

**Comment by mcomella** [comment]
Great – thanks for the explanations, Daniela!
