### ISSUE TITLE
desktopModeTest and  networkPageLoadTest fails: wait for SessionLoadedIdlingResources to become idle timed out 

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1755]
## Steps to reproduce
Levente was able to repro this test failures on device (4K pendant and basic tv stick)
This was not reproducible on cube, or canadian base tv stick.

[Test Results - All_Tests2.html.zip](https://github.com/mozilla-mobile/firefox-tv/files/2813570/Test.Results.-.All_Tests2.html.zip)

master branch, commit 57bf23f96cc4c9b6163096a039451ab0dd0d66e4
### Device information

* Fire TV device: 4K pendant, basic TV stick
* Firefox version: master

**Comment by mcomella** [comment]
See also #1748 which has a similar failure.

**Comment by mcomella** [comment]
I made a speculative fix in #1748: please check if this test is fixed after that change lands.

**Comment by levisacal** [comment]
@mcomella @npark-mozilla DesktopModeTest & NetworkPageLoadTest passed on 4k and Basic Stick device on the latest commit fed9081
