### ISSUE TITLE
WebView stops working with Don't Keep Activities enabled, caused by components WebView memory leak

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1761]
## Steps to reproduce
- Enable Don't Keep Activities
- Open app
- Open page from home tiles
- Return to home screen (leaving app open)
- Open app again
- Try to navigate to new page

### Expected behavior
WebView goes to new page

### Actual behavior
WebView does not respond to new events

### Device information

* Fire TV device: Android TV emulator API 26; have not tried on device
* Firefox version: master

Could be indicative of problems in our WebView state restoration code.

**Comment by liuche** [comment]
Anything where the webview stops is a problem, and this could indicate other problems that aren't common. Test the state restoration cases.

**Comment by mcomella** [comment]
QA: the fix for this issue 1) removes the sessions from the sessionManager when the activity is destroyed and 2) re-adds them when the activity is recreated to work-around a memory leak in components. This is pretty dangerous: we may end up losing the user's session unexpectedly. In addition to using the STR in this bug, it'd be good to verify browsing state - and the WebView - is restored as expected when the app is opened and closed with don't keep activities enabled.

**Comment by mcomella** [comment]
QA: this is getting backed out in #1782.
