### ISSUE TITLE
Verify all @JavascriptInterface-related features are working correctly

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1763]
In #1758, a theory is that the website works well in release but not debug because our javascript code via `@JavascriptInterface` is being proguarded out. In theory, that would prevent users from using some features. We should verify all the `@JavascriptInterface` features are working. If they're not, we should address #1705 and recognize that #1758 will likely start affecting release builds too, so we'll probably need to fix that ASAP.

**Comment by dnarcese** [comment]
I've verified that the following commands are working both in debug and release (v3.2.5) builds
- remote media buttons
- voice commands: play, pause, fast forward/rewind, next/previous
