### ISSUE TITLE
#5 Reddit- Unable to search.

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#177]
Steps to Reproduce:

                1. Install and Launch the app.

                2. In the search bar, type reddit.com.

                3. Scroll down past the pop up.

                4. In the top menu bar, select search magnifying glass.

                5. Type anything (i.e. Cats) and click submit.

                6. Observe.

Actual Result: Nothing happens, search results do not display.

Expected Result: User should be able to use the search feature to find content.

--
note: a workaround would be #202 to Add Desktop Site

**Comment by liuche** [comment]
Raised again by Amazon as part of our 1.1 release.

**Comment by athomasmoz** [comment]
Promoting to P2. Seems to be a trend across sites, since this happens with Google too #1962 

Maybe there's a way to address this for any site's search bar

**Comment by mcomella** [comment]
@athomasmoz fwiw, this would be much easier to fix with GV (in fact, it might _just work_ with GV) because it knows it knows about the input method and the responses it should return.

**Comment by mcomella** [comment]
Dupe #1962.
