### ISSUE TITLE
Move goBackBeforeYoutube() logic into EngineView.ext

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1773]
`goBackBeforeYoutube()` in WebRenderFragment utilizes `EngineView`'s associated `webview` instance. After a-c 0.37 merge, `(engineView as ViewGroup).getChildAt(0) as WebView` is not the correct way to acquire the `webview` as they are referenced in `Session`.

`EngineView.ext` already has centralized method of acquiring its associated `webview` instance. We should move all usages of `webview` there

**Comment by athomasmoz** [comment]
This could cause memory leaks
