### ISSUE TITLE
When UI tests are running on cloud, states are not being reset between tests

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1775]
## Steps to reproduce
When UI tests are run on Bitbar and Google Firebase, they reported identical set of failures which could not be reproduced locally.  After the investigation, the failures were reproducible locally when test orchestrator was disabled in Gradle.  It seems like those cloud servers do not run test orchestrator, even when it's enabled in Gradle.

* Fire TV device: All sims/devices
* Firefox version: ?

**Comment by npark-mozilla** [comment]
We need to fix this before we can run tests on CI.

**Comment by AaronMT** [comment]
Swapping to BitBar's Android Orchestrator framework seems to resolve this issue.

https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator
