### ISSUE TITLE
Display OS and browser engine version in About page

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/firefox-tv#1785]
### Why/User Benefit/User Problem

Users will need to know which OS and browser engine version they are testing when reporting bugs.

### What / Requirements

Show the OS and browser engine version.

### Acceptance Criteria (how do I know when I’m done?)

A user can tell which OS and browser engine version they are testing.

Depends on #1951

**Comment by cpeterso** [comment]
Listing the engine type and version on FFTV's About page would be convenient for testers, but they can also check a site like http://useragent.me/ to see which WebView or GeckoView version they have.

**Comment by cpeterso** [comment]
This issue will probably be fixed by #1919, so I will move this issue out of Sprint 6 into the backlog.

**Comment by psymoon** [comment]
@athomasmoz @cpeterso how important is showing OS & browser engine version in the about page to users (i.e. general population)? This is currently blocked by https://github.com/mozilla-mobile/firefox-tv/issues/1951

However, some partial work for https://github.com/mozilla-mobile/firefox-tv/issues/1919 is done where we are able to show the same information to debug variant audience (mostly internal?).

**Comment by athomasmoz** [comment]
@psymoon I would actually close this in favour of the ticket you're already working on #1919 . Showing the information beyond release version to end users is not needed and could be confusing. The goal is about showing the information to people working on the project so that they can ensure they're testing on the right version, and identify which version a bug is present on.

**Comment by cpeterso** [comment]
Is the debug mode described in #1919 available in LAT and production FFTV builds? I assume testers (Mozilla QA and LAT users) will test production builds and might need to know which GeckoView version they're testing.

**Comment by psymoon** [comment]
@cpeterso the changes that got merged today for #1919 would not be available in LAT and production builds - so we would still need About page exposure then

@athomasmoz I guess I didn't take LAT & production testing users into consideration; I will close this when About page changes make it into master
