### ISSUE TITLE
Use correct Taskcluster secrets dir

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1800]
We have been using the obsolete `project/firefox-tv/tokens` when we should be using `project/mobile/firefox-tv/tokens`.

This is blocking #1792, and in the bigger picture #615.

**Comment by liuche** [comment]
Going to pick this up now bc it's blocking QA.

**Comment by liuche** [comment]
Verified that the secrets are already in `projects/mobile/firefox-tv/secrets` and that there are no more references to `projects/firefox-tv` in the code base as part of this PR.

**Comment by liuche** [comment]
Not sure this needs QA beyond the PRs that you're testing with.

**Comment by AaronMT** [comment]
I think we're good here. We have the right credentials now.
