### ISSUE TITLE
Clean up our app dependencies in build.gradle with buildSrc/declarations

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1807]
Having a centralized place for versions & dependencies improve readability and integrations

Examples:
https://github.com/mozilla-mobile/reference-browser/blob/master/buildSrc/src/main/java/Config.kt
https://github.com/mozilla-mobile/reference-browser/blob/master/buildSrc/src/main/java/Dependencies.kt

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
