### ISSUE TITLE
Grey screen after Home button interruption from a non YT full screen video

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1814]
## Steps to reproduce

1. Watch a non YouTube video in full screen
2. Exit browser using the Home button
3. Return to browser

### Expected behavior

Video/content is displayed/loaded

### Actual behavior

Grey screen and no load after re-entering the browser

The About/Privacy Notice section are also greyed out when trying to access them.

Site content is loaded again after clearing cookies and site data

### Device information
* Fire TV device: Basic Fire TV stick - Fire OS 5.2.6.8
* Latest affected Firefox version: 3.4.1-LAT1

**Comment by AaronMT** [comment]
Reproducible with videos on the front-page on giantbomb.com

**Comment by liuche** [comment]
This looks similar to what we saw in #1758 - but now it's on other video websites and also release 😬

**Comment by liuche** [comment]
Did some investigation and it looks like our upgrade to AC-0.41 broke this - hunch right now is that in the memory leak cleanup, the webview is getting detached, but when resuming it's not getting reattached.

**Comment by liuche** [comment]
Made a quick fix for the release, which is just exiting fullscreen when the WebView is stopped.

However, the longer-term solution is either a) figuring out why the video content is not resumed to play in the fullscreen view, or b) switch to using the `FullscreenFeature` from AC and see if it's hooked into lifecycle methods

**Comment by levisacal** [comment]
Check the issue and couldn't repro it anymore.
