### ISSUE TITLE
Crash on timeout.com when trying to start video

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1815]
## Steps to reproduce

1. Select the Video search tile and search "London"
2. Select the second result (https://www.timeout.com/london/things-to-do/101-things-to-do-in-london)
3. Wait for website to load and hover over the video section to try and start the video

### Expected behavior

Site loads without any issues

### Actual behavior

Crash after hovering over the video before trying to start it 

### Device information
* Fire TV device: 4k pendant - Fire OS 6.2.5.8
* Latest affected Firefox version: 3.4.1-LAT1

[Crash Time Out Video Search.txt](https://github.com/mozilla-mobile/firefox-tv/files/2851926/Crash.Time.Out.Video.Search.txt)

**Comment by liuche** [comment]
This looks like a JWPlayer bug, which is a known issue that we are trying to fix with a WebView upgrade #1577

**Comment by athomasmoz** [comment]
Consolidating similar issues. Tracking under #1577
