### ISSUE TITLE
Update scrolling + navigation fix for Gecko builds

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1819]
Required: https://bugzilla.mozilla.org/show_bug.cgi?id=1508372

**Comment by cpeterso** [comment]
Randall says he will land the new GV API soon ([bug 1508372](https://bugzilla.mozilla.org/show_bug.cgi?id=1508372)). FFTV will need to use this new GV API.

**Comment by cpeterso** [comment]
After this bug is fixed, we should retest Twitch video bug https://bugzilla.mozilla.org/show_bug.cgi?id=1504886.

**Comment by cpeterso** [comment]
Removing "blocked" label because Randall landed the new `scrollTo` and `scrollBy` GV APIs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1508372#c7

**Comment by athomasmoz** [comment]
After investigation, Simon determined this is a larger amount of work. Plan is:
* Land hotfix to unblock testing
* Create stories to address larger issues & make this user-ready

**Comment by psymoon** [comment]
>     * Create stories to address larger issues & make this user-ready
https://github.com/mozilla-mobile/firefox-tv/issues/1912
