### ISSUE TITLE
geckodebug vs. INSTALL_FAILED_DEXOPT

### ISSUE THREAD

**Issue by bdekoz** [mozilla-mobile/firefox-tv#1821]
## Steps to reproduce

checkout repo, add as new project in android studio, make sure instant run is off in project settings. Select "geckoDebug" as a build variant, clean, make build. When that is done, take the generated apk file and install it on a fire tv device.

aka

adb install app-gecko-debug.app

### Expected behavior

Success

### Actual behavior

Failure INSTALL_FAILED_DEXOPT

make clean and rebuild fails to fix

Selecting the "systemDebug" instead of "geckoDebug" variant (and using that generated apk) works as expected

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

**Comment by psymoon** [comment]
@bdekoz Hm, I can't seem to reproduce this on my device. Is this off master branch? Can you provide Fire TV device and OS info?

**Comment by bdekoz** [comment]
Hey, I tried this again today off of master branch and got clean build installs of GeckoDebug and SystemDebug. S, I'm closing this. Sorry for the noise.
