### ISSUE TITLE
./gradlew assembleSystem fails because of release build failure

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1827]
## Steps to reproduce
run ./gradlew assembleSystem (Build variant name has changed since #1776)

### Expected behavior
all variants of System (webview) builds are completed

### Actual behavior
> Task :app:validateReleaseConfiguration FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateReleaseConfiguration'.
> Unable to build release builds with uncommitted change

Noticing this when running locally, and on a PR as well.  Feel free to close the issue (possibly with a workaround in our case where we're working on CI) if it's expected.

**Comment by AaronMT** [comment]
Currently blocks #1825

**Comment by psymoon** [comment]
Suspect - https://github.com/mozilla-mobile/firefox-tv/blob/master/buildSrc/src/main/java/org/mozilla/gradle/tasks/ValidateAndroidAppReleaseConfiguration.kt#L52

Interesting it's happening in TC though - looks like a git staging issue. Maybe we should purge the cache?

**Comment by npark-mozilla** [comment]
Seeing it in this PR run: https://github.com/mozilla-mobile/firefox-tv/pull/1825/files  maybe because none of the codes are modified? (and just the tc scripts?)

**Comment by liuche** [comment]
Summary: the secrets files need to be added to the .gitignore because they're being downloaded and considered "uncommitted changes". Yay our validation checks caught a bug!

**Comment by AaronMT** [comment]
Confirmed.
