### ISSUE TITLE
Refactor LegacyCursorViewModel to CursorViewModel

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1828]
Incremental refactor work for `CursorViewModel` as changes get made to the `LegacyCursorViewModel`.

https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/webrender/cursor/LegacyCursorViewModel.kt

https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/webrender/cursor/CursorViewModel.kt

**Comment by mcomella** [comment]
Dupe #1912.
