### ISSUE TITLE
In GV cursor and scroll are unresponsive

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1842]
## Steps to reproduce
Run GV build, go to website, move cursor

### Expected behavior
cursor/scroll moves

### Actual behavior
cursor /scroll unresponsive

This is reported before, filing issue to keep track

**Comment by psymoon** [comment]
Dupes from:
https://github.com/mozilla-mobile/firefox-tv/issues/1820
https://github.com/mozilla-mobile/firefox-tv/issues/1819

**Comment by mcl21014** [comment]
Also affects the settings menu after loading a URL.
