### ISSUE TITLE
Can't close Keyboard popup when pressing hardware back

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1844]
## Steps to reproduce
- Build geckoDebug variant
- Click Google Videos PinnedTile
- Click on Search bar
- Click hardware remote back

### Expected behavior
- Keyboard layout closes

### Actual behavior
- Nothing happens

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

**Comment by devinreams** [comment]
Needs investigation to decide if fixable on this side or to share with @cpeterso to look into more.

**Comment by liuche** [comment]
Someone needs to confirm if this is something that GV is doing (consuming the back, dpad?) bc this works with WV.

**Comment by cpeterso** [comment]
Since the keyboard closes as expected in FFTV+WV but not FFTV+GV, I filed a GV bug for a GV engineer to investigate:
https://bugzilla.mozilla.org/show_bug.cgi?id=1530486

**Comment by cpeterso** [comment]
I asked Makoto to look at this issue from the GV side (in GV [bug 1530486](https://bugzil.la/1530486)). If you think this is an issue in the FFTV code, please let me know.

**Comment by psymoon** [comment]
@cpeterso I think this is GV bug, there's nothing we do in our end for this

**Comment by cpeterso** [comment]
Makoto just landed a fix for the GV bug, so tomorrow's GV build should be fixed. This bug was related to GV's handling of the key codes generated by the remote.

https://bugzilla.mozilla.org/show_bug.cgi?id=1530486

**Comment by cpeterso** [comment]
@psymoon - Does the hardware back button work correctly for you now that GV bug 1530486 has been fixed?

**Comment by psymoon** [comment]
> @psymoon - Does the hardware back button work correctly for you now that GV [bug 1530486](https://bugzilla.mozilla.org/show_bug.cgi?id=1530486) has been fixed?

@cpeterso confirmed fixed with nigthly 68.0.20190414095735
