### ISSUE TITLE
[1783] Identify reasonable subset of Rx to use

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1848]
Rx has a notorious learning curve and part of that is the sheer number of operators and functions at the developer's disposal. This creates problems: with too much functionality to learn, nobody can be an expert at everything and code readability/maintainability suffers. Some C++ development teams solve this problem by defining an acceptable subset of the language to use: we should do the same for Rx. Over time, we may consider expanding this list but to start, we should keep it small.

**Comment by colintheshots** [comment]
This is a hard question. I feel like one has to interatively add more Rx as the team's understanding grows. Observable and Single seem obvious inclusions. Does one include Maybe, Flowable, and PublishSubjects?

Include:
Map, flatMap, filter, subscribeOn, observeOn, distinctUntilChanged, fromCallable, scan if doing MVI, debounce, first, last, skip, take, skipLast, takeLast, merge, retryWhen, serialize, timeout, subscribe, replay, refcount.

**Comment by sashei** [comment]
I don't have much to add to @colintheshots ' -- we found it easier to have a tiny `Optional` wrapper class than to use `Maybe` (replicated in whole below):

```kotlin
data class Optional<T>(val value: T?)
fun <T> T?.asOptional() = Optional(this)
```

`Subject`s or `Relay`s also came up as a need for us fairly quickly.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.

We're not running into many problems with Rx operator over-use so maybe this is unnecessary.
