### ISSUE TITLE
Can't navigate on Youtube after going home (repro-able)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1850]
This is very similar to #1808, but is a) a new regression from #1830 and b) 100% reproducible.
(We found #1830 while investigating #1808, but the fix for #1830 causes this bug. #1808 is still not highly reproducible and is now eclipsed by this issue)

## Steps to reproduce
Open Firefox from cold start
Open Youtube
Go to Amazon home
Re-open Firefox

### Expected behavior
Can navigate right/left on Youtube w/ dpad

### Actual behavior
Can't use dpad on Youtube. Can open overlay. Workaround: refresh.

### Additional context
This is a regression from #1830, where we move the WebView focus caching from webview.onFocusChanged to Overlay close - which also caches immediately on page load. This means that the FIRST time you open Youtube, we cache the focus as the `<body>` element, because the page hasn't finished loading. If you subsequently open the overlay, this caches correctly and you don't see the non-navigation behavior.

A few things to look at:
- When is a better time to cache?
- We tried caching when the page was loaded, but there were some weird seemingly unrelated problems (webview becaume extremely slow, grey screen on resume from Home)

### Device information
* Fire TV device: all
* Latest affected Firefox version: master db265a82151f03cf867d117567d556a821da2b23
* Earliest affected Firefox version: same, introduced in #1830

**Comment by levisacal** [comment]
Hi @Baron-Severin where can the issue be tested ? As there is a QA ready label on the issue but the latest LAT is still 3.4.1-LAT1. Thanks.

**Comment by Baron-Severin** [comment]
This should be closed by #1853; #1851 is just a mitigation.

**Comment by Baron-Severin** [comment]
Do you have policies for where you test from?  I'll be merging it into master as soon as TC finishes, you could either test from there or from the branch directly (https://github.com/mozilla-mobile/firefox-tv/pull/1853).

Should we be waiting until we've merged to add the `qa-ready` label?

**Comment by levisacal** [comment]
@Baron-Severin  not sure about the policies around the qa-ready label. Maybe @npark-mozilla can help us here.

**Comment by levisacal** [comment]
not reproducible anymore on 3.4.1-LAT2
