### ISSUE TITLE
Grey screen on YouTube resume under specific circumstances

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1858]
## Steps to reproduce
- Open YouTube (not reproducible on any other site)
- Press menu button to open overlay
- Press home button
- Reopen FFTV
- Press menu button to close overlay

### Expected behavior
- WebView is visible

### Actual behavior
- Grey screen is displayed (attached below)
- Hitting select or any D-pad direction fixes the problem

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 6df28612e213679775aed4529251e41fb3a24774
* Earliest affected Firefox version: ?

(screenshot of actual behavior)
![grey-screen](https://user-images.githubusercontent.com/13170306/53039826-e2d40400-3434-11e9-9ad1-45290273beae.png)

**Comment by dnarcese** [comment]
Maybe this fix will also fix #1559?

**Comment by Baron-Severin** [comment]
@dnarcese it looks like it's very likely the same bug.  I'll close this one and move the information here over to other bug.
