### ISSUE TITLE
Consider refactoring all EngineView.evalJS() calls to their respective API calls

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1859]
Example: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/system/java/org/mozilla/tv/firefox/ext/EngineView.kt#L66

`evalJS()` should eventually be private

This allows us to understand all use cases for JS injections (which we should eventually look to get rid of) as well as improve integrability once we refactor EngineViewExtension functions to a-c

**Comment by psymoon** [comment]
Related: https://github.com/mozilla-mobile/firefox-tv/issues/1248

**Comment by athomasmoz** [comment]
Injecting JS is risky. This would allow us to take that risk out of our code and leave it to a-c/gv
