### ISSUE TITLE
Check out leanback support APIs, see if there's anything useful in there for us

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#186]
All of these: https://developer.android.com/training/tv/start/layouts.html

**Comment by mcomella** [comment]
> Inheriting directly from LeanBack theme will cause crashes because we need to be inheriting from AppCompat also

Close if it's not possible (I'm not sure why we can't inherit with AppCompat?)

**Comment by mcomella** [comment]
Let's make this more generic. https://developer.android.com/reference/android/support/v17/leanback/package-summary.html Thanks Sebastian!

**Comment by athomasmoz** [comment]
@mcomella Is this still something you're interested in pursuing? Or should I close until we come across a reason to investigate?

**Comment by mcomella** [comment]
It'd be nice to do but we have an idea of the items that are in there so we might remember to check if we're implementing a component like this: I'm happy to close.
