### ISSUE TITLE
Remote UI test failures log misleading failure messages

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1861]
PRs are occasionally failing when TC appears to fail to download all necessary files for our remote UI testing.  @liuche and I have each seen this once today.  Restarting the PR was enough to get the build to pass.

Full TC logs at https://tools.taskcluster.net/groups/JGcX5ElRRw6WIG9Go2M5hA/tasks/JGcX5ElRRw6WIG9Go2M5hA/runs/0/logs/public%2Flogs%2Flive.log
Logs that look relevent included below
```
/ [0/6 files][    0.0 B/ 15.0 MiB]   0% Done                                    
CommandException: 
Downloading this composite object requires integrity checking with CRC32c,
but your crcmod installation isn't using the module's C extension, so the
hash computation will likely throttle download performance. For help
installing the extension, please see "gsutil help crcmod".
To download regardless of crcmod performance or to skip slow integrity
checks, see the "check_hashes" option in your boto config file.
NOTE: It is strongly recommended that you not disable integrity checks. Doing so
could allow data corruption to go undetected during uploading/downloading.
/ [1/6 files][ 30.0 KiB/ 15.0 MiB]   0% Done                                    
/ [2/6 files][ 37.5 KiB/ 15.0 MiB]   0% Done                                    
/ [3/6 files][  2.7 MiB/ 15.0 MiB]  18% Done                                    
/ [4/6 files][  5.3 MiB/ 15.0 MiB]  35% Done                                    
-
- [5/6 files][ 13.3 MiB/ 15.0 MiB]  89% Done                                    
CommandException: 1 file/object could not be transferred.
+ exit 10
[taskcluster 2019-02-19 23:32:00.143Z] === Task Finished ===
[taskcluster 2019-02-19 23:33:21.929Z] Unsuccessful task run with exit code: 10 completed in 1361.287 seconds

```

**Comment by npark-mozilla** [comment]
I will look at this, but the failure to copy over files actually do not affect the pass/fail status of the the PR run, because the shell script exitcode is collected before the file transfer - https://github.com/mozilla-mobile/firefox-tv/blob/c69fcba8d1166bbb3e6c754913c216e99696c3ba/tools/taskcluster/execute-firebase-test.sh#L53

In above case, the PR failed because of the sessionLoadedIdlingResource timeout, as can be seen in: https://console.firebase.google.com/u/0/project/moz-firefox-tv/testlab/histories/bh.3c34c7cf235a156d/matrices/7203398314144975389/executions/bs.28c661910f400b0e

**Comment by Baron-Severin** [comment]
@npark-mozilla would it be possible to adjust the output to link to the failure?

**Comment by npark-mozilla** [comment]
there’s no direct link given to the failure, but the artifacts folder contains something like `public/test-artifacts/2019-02-19_23:26:35.668437_dxTC/taimen-26-en-landscape/test_result_1.xml` where you can readily see the stacktrace of failures

**Comment by Baron-Severin** [comment]
It's a problem if TC failures don't print out the reason they failed.  Right now they're failing tests, but maybe next time they might not be be.  It's pretty important that we find some way of including that in the logs.

**Comment by npark-mozilla** [comment]
After talking to severin, in order to close this bug, we should have the error msg saying that there was a UI test failure at the end of the log.
