### ISSUE TITLE
IllegalStateException: File name too long when compiling unit tests

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1868]
## Steps to reproduce
- `./gradlew assemblesystemdebugunittest`

### Expected behavior
Successful compile

### Actual behavior
Failed compile:
```
e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: /home/mcomella/dev/moz/firefox-tv/app/build/tmp/kotlin-classes/systemDebugUnitTest/org/mozilla/tv/firefox/ext/LiveDataPostIfNewTest$GIVEN old value was posted AND a different value was posted WHEN the original value is posted again THEN three total values should have been emitted$1.class (File name too long)
File being compiled at position: file:///home/mcomella/dev/moz/firefox-tv/app/src/test/java/org/mozilla/tv/firefox/ext/LiveDataPostIfNewTest.kt
The root cause was thrown at: FileOutputStream.java:-2
```

It looks like we're unable to save the class file because the name of the generated class (from the lambda?) is too long.

### Device information
* Fire TV device: N/A
* Latest affected Firefox version: up/master
* Earliest affected Firefox version: ?

I'm running ubuntu 18.04 on ext4: I'm guessing APFS (or whatever) on macOS has a longer file name limit (ext4 seems to be 255 bytes; APFS is 255 UTF-8 characters).

See also https://github.com/mozilla-mobile/firefox-echo-show/issues/247

**Comment by psymoon** [comment]
Wonder if this would be relevant once we successfully replace LiveData with RxJava

**Comment by mcomella** [comment]
Even after fixing the test name, I receive an error for another test:
```
Cause: /home/mcomella/dev/moz/firefox-tv/app/build/tmp/kotlin-classes/systemDebugUnitTest/org/mozilla/tv/firefox/pocket/PocketVideoFetchSchedulerTest$GIVEN Pocket is enabled by locale THEN WorkManager will enqueue a request using the keep existing work policy$1.class (File name too long)
```

It sounds like this bug ruins our entire test naming strategy.

---

However, after a quick google, it appears this is a limitation of my particular configuration: the max file name limit is 143 bytes when using ecryptfs (no longer recommended by ubuntu) but 255 when using ext4 directly. Since this configuration is not recommended, I'm going to close this as WONTFIX.
