### ISSUE TITLE
Investigate a new staged rollout strategy (Fretboard + Crash ping?)

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1870]
With Fretboard integration, we can incrementally define release buckets for staged rollouts

Pains:
- Inability to do a staged rollout through appstore
- Complex versioning results in overhead when triaging

Gains:
- Independent dashboard & queries 
- Encourages well architectured (and refactored) feature implementation
- Would theoretically work with crash ping integration (https://github.com/mozilla-mobile/firefox-tv/issues/1379)

Potential Cons: 
- Inability to do staged rollouts on specific devices
- Inability to differentiate crash rates on each rollout buckets (can we use crash ping?)
- Need workarounds for staged rollouts for buckets > 2

**Comment by mcomella** [comment]
This is no longer necessary: Amazon has staged rollouts built in.
