### ISSUE TITLE
Allow `system` and `gecko` configurations to co-exist on device

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/firefox-tv#1880]
### Why/User Benefit/User Problem

When automating comparisons of the system WebView-based and the GeckoView-based versions, sharing an application ID is frustrating.

### What / Requirements

More `applicationIdSuffix`.

### Acceptance Criteria (how do I know when I’m done?)

When you can install them both to the device and  have them co-exist.

**Comment by devinreams** [comment]
Closed at #1883
