### ISSUE TITLE
Follow-up: Add animation for split overlay - "push toolbar"

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1884]
In #1664 we split the overlay (and then switched back to the previous layout), but the animation doesn't work on the tv (but does work with a touchscreen).

The problem is that scrolling on the TV uses [`arrowScroll`](http://androidxref.com/8.0.0_r4/xref/frameworks/support/core-ui/java/android/support/v4/widget/NestedScrollView.java#1225), which doesn't trigger [scroll callbacks](http://androidxref.com/7.1.2_r36/xref/frameworks/support/design/src/android/support/design/widget/CoordinatorLayout.java#2176) that the `CoordinatorLayout` listens for.

A fix for this would be to trigger a scroll event when scrolling with the arrow keys/dpad, maybe through calling the [onScrollChanged](http://androidxref.com/8.0.0_r4/xref/frameworks/base/core/java/android/view/View.java#13426) method of the View.

**Comment by devinreams** [comment]
Is this UX debt a priority if we aim to change the design? Need a decision from product/UX.

**Comment by mcomella** [comment]
@liuche Are we still implementing the split overlay? If not, please close.

**Comment by mcomella** [comment]
afaik, we're not still implementing the split overlay.
