### ISSUE TITLE
About screen takes a long time to open

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1887]
## Steps to reproduce
- Go to a page (e.g. vimeo.com)
- Open overlay, settings, About

### Expected behavior
About opens quickly

### Actual behavior
There is a quick transition to black, a long pause (2-3 seconds?), and a slow fade to About.

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 3.4-A (which is 3.2.5 which is months old...)
* Earliest affected Firefox version: ?

**Comment by devinreams** [comment]
Let's re-test this against the latest...

**Comment by liuche** [comment]
Tested this on master yesterday and I didn't see this so closing it.
