### ISSUE TITLE
YouTube does not autoplay with GeckoView

### ISSUE THREAD

**Issue by vickychin** [mozilla-mobile/firefox-tv#1901]
If a user selects a youtube video to play, Firefox+GV should just play the video and not require the user to press play again once the video buffers.

## Steps to reproduce
1. Go to www.youtube.com/tv
2. Select a video to play

### Expected behavior
After selecting the video to play I'd expect the video to just play

### Actual behavior
The video buffers and then the user has to press play again for the video to start playing

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: Master Branch + GV debug build
* Earliest affected Firefox version: ?

**Comment by cpeterso** [comment]
This bug might be related to block autoplay not being disabled correctly in GV: #2040.

**Comment by dnarcese** [comment]
Closed in [`1c49d4b`](https://github.com/mozilla-mobile/firefox-tv/commit/1c49d4b1b9dde70ec378d5e0c0e0e435772435ce)
