### ISSUE TITLE
Helper Text for Nav Bar Controls

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1908]
### Why/User Benefit/User Problem

As a user, I'm not sure what the icons in the navigation bar mean

### What / Requirements

Add helper text when an icon in the navigation bar is focused

### Acceptance Criteria (how do I know when I’m done?)

* Helper text is added for the navigation bar icons:
  * "Back"
  * "Forward"
  * "Refresh Page"
  * "Search or enter address"
  * "Turbo Mode ON" / "Turbo Mode OFF"
  * "Request Desktop Site ON" / "Request Desktop Site OFF"
  * "Settings"
  * "Quit Firefox"
* Text is localized
* Transitions...

**Comment by brampitoyo** [comment]
I will tackle this issue next week. Stay tuned.

**Comment by liuche** [comment]
@brampitoyo since these already have strings for accessibility, can those just be reused?
Like this: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/res/values/strings.xml#L54
(and others)

**Comment by brampitoyo** [comment]
@liuche:
> since these already have strings for accessibility, can those just be reused?

Yes, please. Let’s reuse all the strings and then see how they look in the product. My concern is string length, but as long as we don’t encounter any screen-breaking issue, we should be ok.

@dnarcese you can inspect the helper text mockup here:
https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i03/#artboard1

Just one important thing to note: the side padding value is incorrect. It should be 8px, not 8.5px.

And with that, we’re ready to implement.
