### ISSUE TITLE
GV build does not scroll page content at all via remote (uncertain of other input methods)

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/firefox-tv#1909]
## Steps to reproduce
Open a web page where the user has to scroll. Such as some of the pages pinned to the Firefox start page.
### Expected behavior
You can scroll down the page while using the remote
### Actual behavior
The page does not vertically nor horizontally scroll.
### Device information
* Fire TV device: Fire Stick 4k.
* Latest affected Firefox version: Firefox 3.4-GV (with GV 67)
* Earliest affected Firefox version: Firefox 3.4-GV (with GV 67)

**Comment by mcl21014** [comment]
Oops filed a duplicate. Well, at least this still gives some insight.

**Comment by psymoon** [comment]
Dupes from https://github.com/mozilla-mobile/firefox-tv/issues/1819
