### ISSUE TITLE
Minimizing app during loading of youtube video causes playback to fail

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#191]
- Go to youtube app, select a video that takes a while to load (i.e. Live video)
- While the video is loading, press home button to exit
- Enter Focus again, and play any video

Video won't play, showing constant loading icon.  This happens to any video, so the app has to be killed and restarted again

**Comment by athomasmoz** [comment]
Closing ticket. Video appears to continue loading video I was originally trying to load and plays okay. So seems no longer reproducible
