### ISSUE TITLE
Clean up non-critical AndroidX related warnings

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1911]
- [ ] Syncing causes the following warning to be shown. This setting was already active before the AndroidX update.  My current guess is that it was not yet marked as experimental in our old Gradle version, and bumping Gradle caused the warning to be shown.
<img width="811" alt="screen shot 2019-03-06 at 10 26 33 am" src="https://user-images.githubusercontent.com/13170306/53904224-688dad00-3ffa-11e9-9a61-7cc544adf0e3.png">

- [ ] Syncing will sometimes (no solid STR yet) show a series of red warnings under the 'build' tab in AS.  They mention something about string interpolated project fields (e.g., `"${project.identifier}"`).  (I'll add more detail here when I'm able to reproduce again)

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.

If we decide these are actually problematic to the app, we can reopen.
