### ISSUE TITLE
Refactor Cursor to improve maintainability; fix dropped frames

### ISSUE THREAD

**Issue by devinreams** [mozilla-mobile/firefox-tv#1912]
Related to https://github.com/mozilla-mobile/firefox-tv/issues/1890

### ACCEPTANCE CRITERIA

* Perceived performance of cursor on GV+FFTV is equal or better than FFTV+AWV
* Perceived performance of cursor is equal or better than what's live today

---

_edit: We have observed the cursor has three problems:_
- The code is hard to maintain
- The cursor jitters when scrolling the page on GeckoView builds
- Every 1/8 of the screen length or so, the cursor drops a frame while moving

We will address the 1st and 3rd; bug #2102 is filed for the 2nd item.

**Comment by mcomella** [comment]
See #472 for implemented performance improvements and #685 for follow-up thoughts. Feel free to pick my brain for ideas!

**Comment by athomasmoz** [comment]
Blocks #1819

**Comment by athomasmoz** [comment]
@psymoon A few questions
* What about the scrolling is blocking #1819 ?
* Do the recent cursor changes from #1907 resolve this?

**Comment by psymoon** [comment]
@athomasmoz 
>     * What about the scrolling is blocking #1819 ?
Depends on the target audience. If end-user, yes this is required. If internal, merging https://github.com/mozilla-mobile/firefox-tv/pull/1971 would suffice IMO
>     * Do the recent cursor changes from #1907 resolve this?
No

**Comment by athomasmoz** [comment]
So is this story just a general suggestion to improve how smooth the cursor is? And if so, how does that relate to GV and #1819 ?

**Comment by mcomella** [comment]
> _edit: We have observed the cursor has three problems:_
> 
>     * The code is hard to maintain
> 
>     * The cursor jitters when scrolling the page on GeckoView builds
> 
>     * Every 1/8 of the screen length or so, the cursor drops a frame while moving

We're looking into all three of these (and timeboxing the refactor).

**Comment by mcomella** [comment]
QA: we almost entirely rewrote the cursor code. Please ensure:
- It's working properly on each web page
- It correctly enables itself and doesn't steal key events when transitioning between screens (e.g. opening and closing the overlay, going to YouTube TV which doesn't support cursor, etc.)
- The cursor still feels good to use, is very functional
- The cursor has minimum dropped frames

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/firefox-tv/issues/2130 to restore the tests that were deleted during this refactor.

**Comment by mcomella** [comment]
I also filed some known issues:
- #2131
- #2132
