### ISSUE TITLE
Show build variant when in debug mode

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1919]
### Why/User Benefit/User Problem

As a Mozilla team member running tests, I'd like an easy way to see which build variant I'm currently on, so that I don't run my testing against the wrong variant

### What / Requirements

* Display build variant when in debug mode
* Display engine type (GV or WV) and version

### Acceptance Criteria (how do I know when I’m done?)

* Technical & non-technical mozillians can see which build they are running when in debug mode
* Technical & non-technical mozillians can see whether they're using GV version or WV version when in debug mode
* There are no end user facing changes
* There are 2 related issues. They should be closed off or reprioritized once this work is completed #824 #1785 

- [x] debug overlay for developers
- [ ] about page for QA, LAT and end users (#1785 )

**Comment by mcomella** [comment]
I think production Focus builds provide the GeckoView build number. We should:
- Do at least what they do
- Share their code (can this be a component?)

**Comment by mcomella** [comment]
See also adding commit to builds – #824 – and I notice that Fenix provides a, "Built on Aug 4th @ 2am" too.

**Comment by psymoon** [comment]
Related: https://github.com/mozilla-mobile/firefox-tv/issues/1785
