### ISSUE TITLE
Back/forward buttons in overlay do not work on YouTube TV

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1927]
## Steps to reproduce
- Open app
- Click Youtube tile
- open video
- open overlay
- hit back

### Expected behavior
Youtube goes back to homepage

### Actual behavior
Youtube stays on the current video

### Device information
* Fire TV device: Stick gen 2
* Latest affected Firefox version: latest, v3.4.1-lat1?
* Earliest affected Firefox version: ?

I cannot reproduce this issue when using the hardware back button.

**Comment by devinreams** [comment]
@Baron-Severin will immediately check this against 3.5 LAT 1 (was working before)

**Comment by Baron-Severin** [comment]
@devinreams issue is reproducible on 3.5-LAT1.  Also reproducible on 3.0 (from early October).  Not sure when this was introduced, but it was a while ago.

**Comment by devinreams** [comment]
Thanks @Baron-Severin 

>Not sure when this was introduced, but it was a while ago.

@athomasmoz given that, I don't know if we should consider this a "release blocker" and prevent us from finishing what we have in progress (but still keep it prioritized as you see fit). Do you agree?

**Comment by Baron-Severin** [comment]
If it impacts the decision making process, I might be able to get a fix by EoD.

**Comment by athomasmoz** [comment]
@Baron-Severin Thanks for checking that. Agreed, we can downgrade from a release blocker to a P1. So let's keep it in the sprint, but not block the release on it. 

cc @devinreams

**Comment by Baron-Severin** [comment]
There's some confusing code here that I'm going to straighten out.  Shouldn't take more than a day or two, and the end result should be a lot nicer.

#### Problems
- Hardware back buttons trigger two kinds of events in `MainActivity`, one through `onBackPressed` and one through `dispatchKeyEvent`
- Both of these paths route through `ScreenController` and `WebRenderFragment`, but through different methods
- The path going through `dispatchKeyEvent` explicitly handles back presses in a few places
- Toolbar back button presses take a third, entirely separate code path
  - This path doesn't hit the `YouTubeBackHandler`, which causes the bug

#### TODO
- If, in `MainActivity#dispatchKeyEvent` the key is `back`, short out
  - Handle hardware back logic exclusively through the `onBackPressed` route.
- Update the toolbar back route to go through the `YouTubeBackHandler`
  - Share as much of these code paths as possible

#### Questions / Risk Analysis
- Where should this logic live?
  - `SessionRepo` shouldn't be emitting more events than necessary, and "Emit ESC press" would have to be an event
- The current code path is convoluted
  - Triple check the order of all calls being made, make sure changing this doesn't cause any side effects to change

**Comment by Baron-Severin** [comment]
Blocked on https://github.com/mozilla-mobile/firefox-tv/issues/1939
