### ISSUE TITLE
Error: "Browser encountered unknown protocol"

### ISSUE THREAD

**Issue by devinreams** [mozilla-mobile/firefox-tv#1933]
https://docs.google.com/document/d/1nl-ORadIzadrl3ATL9UEa2FwFB4sw1hPKkHoXi3b4jA/edit?usp=sharing

**Comment by liuche** [comment]
* Verify with current master build on both Cube and Stick

**Comment by liuche** [comment]
Summary: error handling is getting called before we can intercept the load.

**Comment by devinreams** [comment]
Closing for now. Thanks @liuche @psymoon.

**Comment by devinreams** [comment]
Re-opening with more detail added in original doc.
