### ISSUE TITLE
Don't do stuff in `FirefoxApplication` in Gecko processes

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/firefox-tv#1935]
Right now, `FirefoxApplication` runs code in every process in the app. Unfortunately, this includes processes that are private to Gecko, and can result in some very difficult to debug problems. Apps should not run any of their own code in processes owned by Gecko at all. It seems like we may need some help from a-c to make this easier on apps.

**Comment by snorp** [comment]
Maybe @pocmo has some ideas for a-c?

**Comment by pocmo** [comment]
I filed this:
https://github.com/mozilla-mobile/android-components/issues/2312

Related:
https://github.com/mozilla-mobile/android-components/issues/2207

How we avoid this in Fenix:
https://github.com/mozilla-mobile/fenix/blob/49142349b8843e6f452867bc983b994c7d941b12/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L41-L47
