### ISSUE TITLE
Investigate root cause of webview grey screen on app re-open

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1940]
## Steps to reproduce
Open Firefox, load Youtube
Click home button on remote to return to Amazon home
Reopen Firefox

### Expected behavior
Youtube page shows

### Actual behavior
Grey screen

### Device information
* Fire TV device: all
* Latest affected Firefox version: master ac9c612b5e4c44af98a25d6906f962668b0f9e6c
* Earliest affected Firefox version: #1559 or more reliably with 3.2.2 w/ AC 37

Some bisection work and attempted workarounds in #1865 - landed a hacky fix in #1865 to get this out on release, so that will need to be backed out in order to investigate this.

### Bisection + workarounds
For AC32-36.1, grey screen is not a problem. The upgrade **to 37** shows the grey screen, and this is where AC switches from using the the webview from the layout to the EngineView.

Some workarounds tried:
- (didn't work) Tried calling `engineView.resume` to trigger the webview to "load" from grey screen
- (didn't work) Tried scrolling the webview in WebRenderFragment resume with `engineView.scrollByClamped` which scrolls the webview
- (works, but scrolls) Sending a dpad-right event when the fragment resumes if it's on the Youtube site

I also tried bisecting across the individual AC commits, but for one of the commits there were a lot of significant changes that I didn't pursue and did the hacky workaround.

**Comment by psymoon** [comment]
**UPDATE:**
<img width="1424" alt="Screen Shot 2019-04-11 at 5 12 31 PM" src="https://user-images.githubusercontent.com/3597594/55993767-e722dd80-5c7d-11e9-8fe9-e36c7c015bc1.png">
<img width="1435" alt="Screen Shot 2019-04-11 at 5 13 00 PM" src="https://user-images.githubusercontent.com/3597594/55993769-ebe79180-5c7d-11e9-8812-3acb69e76004.png">

Comparing the two cases when the `WebRenderFragment` is _active_ (_i.e. show()_). UIAutomatorViewer shows nothing under `container_web_render` when the "Grey Screen" issue is present

**Comment by athomasmoz** [comment]
There are 2 grey screens

1. Consistent issue #2058 that we will put into 3.7 release.
2. Intermittent issue - there's a band aid fix that we'll aim to get in 3.7. Longer term fix is #1395

**Comment by psymoon** [comment]
**Note to QA**: this story now reflects _**2** separate grey screen issues_:

1. "intermittent grey screen" aka lost EngineView focus 
> **STR:**
> - Open app and load any website (i.e. Youtube TV tile)
> - Allow the device to go to sleep or screen saver (**adb shell settings put system screen_off_timeout 5000** => set device to go to screen saver after 5 seconds)
> - Wake up the device

2. "100% grey screen issue" aka WebRenderFragment fail to render
> **STR:**
> - Open app & load youtube tile
> - Press home
> - Open app from "Your apps & Games" tiles (NOT from recent) - which evidently recreates MainActivity

https://github.com/mozilla-mobile/firefox-tv/pull/2058 addresses & fixes both issues above.

@npark-mozilla @athomasmoz @devinreams

**Comment by npark-mozilla** [comment]
Note to @abodea : so once #2058 is merged, we should test above two STRs, #1989, and #1559
