### ISSUE TITLE
Refactor debug/release specific code

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1953]
We have a few places where we do debug specific operations in our codebase. Ideally we don't want to ship release products with unused/unnecessary code. Refactor them to their respective variants

**Comment by mcomella** [comment]
@psymoon Can you provide specific examples of this code? The only one I see is SWIPE_TO_REFRESH in Features but it seems reasonable to branch on build type because, presumably, this will soon be branching by Fretboard instead.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
