### ISSUE TITLE
App Freezes when attempting to install new APK (have not reproduced)

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1956]
Initial report: https://app.appbot.co/apps/1658893-firefox-for-fire-tv/reviews/1088698641?utm_campaign=slack-review-header&utm_medium=slack&utm_source=slack

Automated translation:
```
English Translation
it does not work
Wanted to download an app, now nothing works under Firefox. Neither back nor menu button work.
```

### Steps to reproduce
(unknown)

### Expected behavior
- Should not be able to download/install a new APK
- Browser should continue to function as normal

### Actual behavior
- Browser froze
- Menu and back buttons became unresponsive

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

### Additional information
I attempted to reproduce on a Cube.  Tried installing from Play store and apkpure.com.  I was unable to download any APKs (this is expected), but could not reproduce any bad behavior.  @athomasmoz even though I couldn't reproduce, this sounds like really bad behavior.  Is there any way we could reach out to this user to learn more about what they were doing?

EDIT: note that the original report was in German, so we may need translation support when reaching out.

**Comment by liuche** [comment]
I wonder if locale has anything to do with this? e.g. if we try this with the German locale.

**Comment by athomasmoz** [comment]
TODO: Request more information from user to see if we can reproduce because the resulting behaviour makes the app unusable. However, this is something outside our code use cases.
