### ISSUE TITLE
Submit button on keyboard doesn't submit your search on Google

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1962]
## Steps to reproduce

1. Open Firefox
2. Go to google.com
3. Type in a search term and hit play on the remote (or the submit button on screen keyboard)

### Expected behavior

Search is performed with the term you submitted

### Actual behavior

Search term is displayed in the search bar. You must mouse over to hit magnifying glass to submit the search

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 3.4-A
* Earliest affected Firefox version: ?

### QA Notes
The scope of this fix expanded substantially.  The behavior described above is true on many different websites (YT, Amazon, & Reddit were all tested).  This is a bad enough experience that we decided to try enabling the fix on _all_ input elements that raise soft keyboards with 'submit' buttons.  Quick testing looks promising, but if you can find anything where this breaks user expectations, regardless of the website, please bring it up.

It's worth noting that this won't fix behavior everywhere.  As long as it fixes Google search and doesn't break any important flows, that's fine.

**Comment by liuche** [comment]
On the emulator using the cmd+backspace (or another key that triggers a "back") will work - is that something that could help?

**Comment by athomasmoz** [comment]
Additional details
* Does this work on Silk? No
* Does desktop mode resolve this? No

**Comment by athomasmoz** [comment]
Bumping this up in priority after learning that searching on google is a common use case

**Comment by athomasmoz** [comment]
Check if this is something in our control. Timebox ~3hrs

**Comment by athomasmoz** [comment]
Try injecting into the page to fix this. Although it's hacky, we suspect that if it breaks, it will just fall back to the functionality we have today. Timebox 3 hours

**Comment by mcomella** [comment]
We've done previous research on something similar – https://github.com/mozilla-mobile/firefox-tv/issues/177 – that might have info about fixing this the "correct way".

**Comment by Baron-Severin** [comment]
Investigation note: I don't know if we'll be able to handle this by injecting hacks.  Google Search is pretty thoroughly minified (and minified properties are exceptionally volatile).  The only attributes I can see that we might be able to latch on to are either 1) locale specific (e.g., content description), or 2) layout specific (e.g., "click the icon furthest to the right").  1 isn't a viable option for us, and 2 could lead to bad behavior if the structure of the page ever changed.

I guess we'll have to do it the correct way.  😢

**Comment by mcomella** [comment]
On Tue, Nov 19, 2019 at 11:20 AM Severin Rudie <notifications@github.com>
wrote:

> 1) locale specific (e.g., content description), or 2) layout specific
> (e.g., "click the icon furthest to the right"). 1 isn't a viable option for
> us, and 2 could lead to bad behavior if the structure of the page ever
> changed.
>

 @Baron-Severin could we apply the transformation to all <input> on Google
search pages? I don't think it'd be too destructive.

**Comment by Baron-Severin** [comment]
@mcomella seems like a good suggestion.  I'll give it a shot, thanks.

**Comment by Baron-Severin** [comment]
Looks like we might need to make some changes to this.  Moving it back into 'in progress'.

**Comment by abodea** [comment]
Verified as fixed on **`v4.6-LAT1`** using Fire TV Stick 4k.
## For more details please check the following: 

| Site  | Navigated to the results after pressing on Submit? |Comments?|
|-------------| :-------------: |:-------------:|
| **Google** | Yes ✔️ using both keyboard and remote button | Works on Desktop mode too  | 
| **Amazon**  | Yes ✔️ using both keyboard and remote button   | Works on Desktop mode too    | 
| **Reddit**  | Yes ✔️ using both keyboard and remote button   | Works on Desktop mode too    | 
| **Bing** | Yes ✔️ using both keyboard and remote button    | Works on Desktop mode too    | 
| **IMDB** | ❌ Keyboard and remote buttons didn't perform the search | N/A    | 
| **Rotten Tomatoes** | ❌ Keyboard and remote buttons didn't perform the search  | N/A    | 
| **Flickr** | ❌ Keyboard and remote buttons didn't perform the search  | N/A    | 

**As mentioned in the description**
> No other sites have been affected by this change

**I tried on other websites, see the table above, but the change didn't affect other sites.**

>No user flows that you notice have been broken

**I couldn't identify any user flow to be broken.**
