### ISSUE TITLE
Unpinned icon only half-filled on TV Stick

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1963]
## Steps to reproduce
Open Firefox, go to unpinned site
Open overlay

### Expected behavior
Pin icon is unfilled

### Actual behavior
Pin icon is half-filled

### Device information
* Fire TV device: Stick, not present on 4K
* Latest affected Firefox version: master a0e4502 
* Earliest affected Firefox version: ?

**Comment by dnarcese** [comment]
Dupe of #1303.

**Comment by liuche** [comment]
lol I guess I must really hate this half-filled pin since I keep filing bugs on it
