### ISSUE TITLE
Some fields in about:config do not persist when toggled

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1980]
## Steps to reproduce
- build gecko variant
- go to about:config
- set `media.media-capabilities.enabled` to false
- restart app

### Expected behavior
- `media.media-capabilities.enabled` is still set to false

### Actual behavior
- `media.media-capabilities.enabled` is back to true (default value for 67)

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

**Comment by cpeterso** [comment]
I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1536872

**Comment by cpeterso** [comment]
@psymoon, is this about:config bug still reproducible with a recent snapshot of GV 68? cpearce says that he regularly changes pref values in about:config in FFTV+GV and the new values are correctly saved across sessions.

**Comment by psymoon** [comment]
@cpeterso it's no longer reproducible now
