### ISSUE TITLE
Add GV nightly and beta

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1981]
IMPACT: Get new versions of GV earlier so that we can catch bugs / get fixes earlier. 

Effective starting a-c version 0.48+

GV nightly is now 68
GV 67 is in beta

Related to https://github.com/mozilla-mobile/firefox-tv/issues/1924

**Comment by psymoon** [comment]
This depends on how we decide to do staged rollout. Should we decide to sync release channels with Gecko, we would need to set it up accordingly

**Comment by athomasmoz** [comment]
Closing as covered under #1924
