### ISSUE TITLE
Grey screen on resuming back to imdb.com after sleep time out 

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1989]
## Steps to reproduce

Open imdb.com

Let the device sleep

Wake up the device

Open FF (should open imdb.com)

### Expected behavior

Imdb site should show

### Actual behavior

Grey screen after opening up FF after sleep time out.

After scrolling down a bit, the site re-appears

Could not reproduce on 2nd generation Fire TV stick

### Device information
* Fire TV device: 4k pendant, FireOS 6.2.6.0
* Latest affected Firefox version: 3.6
* Earliest affected Firefox version: 3.6

**Comment by liuche** [comment]
Thank you! This looks like the Grey Screen bug of the past because we just put in a workaround in #1814 😞 

Linking this to #1940 because it seems like it's still a problem, but on other sites.

**Comment by athomasmoz** [comment]
Confirm #1940 fixes this issue.

**Comment by psymoon** [comment]
@abodea confirmed this is no longer reproducible
