### ISSUE TITLE
Deprecate EngineViewCache

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1998]
We no longer need it after the refactor (also we can use `SessionStorage` for persistence). We have a strange set of dependencies and complexity around it outside its purpose - so simply getting rid of it may be risky. Spend some time to investigate and successfully deprecate `EngineViewCache`.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
