### ISSUE TITLE
Centralize `Session.Observer` operations (i.e. refactor to SessionRepo)

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2002]
We have `SessionRepo` for this reason; however, there are still a few other places where we are still explicitly using `Session.Observer`. This is bad for two reasons:
- Inconsistency in app states
- Duplicate efforts

See `WebRenderFragment` and `FirefoxProgressBar` for examples

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
