### ISSUE TITLE
Add Request Desktop Site

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#202]
_Added by @bbinto_

**Why/User Benefit**
- Some websites don't work well for users because the mobile website is being loaded
- Avoid/remove web compat issues

**What**
- Include option to switch to Desktop site
- For responsive websites, nothing might change for the user
- Behaviour:

    Requesting desktop will change for the current site while you're on that site
    If you browse to another site, it will have desktop off
    If you visit the site in the future, it will have desktop off

**Acceptance Criteria (how do I know when I’m done?)**
- Option to switch to desktop website and back to mobile (if needed)
- Feedback is given once the switch was made
- Probe how often users switch between desktop and mobile

**KPI&Data**
- Can we figure out if/how users switch the toggle on site A vs. site B
- Can we tell if users prefer desktop vs. mobile (or vice versa)
- Total number of times people are using the feature
- The number of unique users who are using the feature
- The percentage of our total active users who are using the feature
- The average number of times per day users are using the feature

---
There are some mobile sites that just don't work very well because sites expect a mobile keyboard, so we need to offer some way for users to switch to a more cursor-friendly site, e.g. request desktop site.

We'll need to have a spec for how the state of "desktop site" changes as users navigate between pages.
* What situation causes "request desktop site" to revert to the default? (going to a different subdomain?)
* Do we remember the desktop site state when returning to pages?

Once we have a spec eng can investigate the implementation and maybe propose changes if we want to keep this feature small.

BREAKDOWN:
- [ ] Implement back end logic of requesting a desktop site
- [ ] Add in UI components for requesting desktop site

**Comment by liuche** [comment]
@bkmunar we went over this in Backlog grooming, did you have any updates on this, or a branch we can reference?

**Comment by athomasmoz** [comment]
Behaviour:
* Requesting desktop will change for the current site while you're on that site
* If you browse to another site, it will have desktop off
* If you visit the site in the future, it will have desktop off

**Comment by liuche** [comment]
We should match the same overlay behavior (whether to close) based on what Turbo Mode does. (So for now, don't close.)

Based on this, we'll need some toast strings to make sure people know what is happening.
* Accessibility strings for the button (checked/unchecked) [for reference, the Pin button is "Pin to homescreen".
* Toast for turning on/off requsting desktop site - since there isn't really an "opposite" action to "request" we were thinking something like "Request non-desktop site" because we don't necessarily want to emphasize that we're using "Mobile" sites for the TV (if this is confusing to users).

We don't do anything different when switching back to mobile site once leaving a domain.

Telemetry: for pinning, we should also add an extra about whether the site is pinned in Desktop mode (because pin will not "save" desktop mode).

**Comment by athomasmoz** [comment]
Approach: We will create a local component for this one, not an android components one. We may consider moving it over in the future

**Comment by liuche** [comment]
Strings-needed, but eng isn't blocked on getting those - we can easily swap strings in once we have them.

**Comment by aminalhazwani** [comment]
Hello, here a summary of the experience (depending on #1288):

On launch we display a new button for "Request desktop website", next to "Turbo mode". The icon should be already available in the android components repo (https://github.com/mozilla-mobile/android-components/blob/master/components/ui/icons/src/main/res/drawable/mozac_ic_device_desktop.xml). As for the back/forward, reload, and pin the icon is disabled as no website is open behind the homescreen.

![homescreen at launch](https://user-images.githubusercontent.com/1721875/47145835-004c6200-d2cb-11e8-80c6-958561ad1cd3.jpg)

Opening a website will open the default version of said website.

![open google com](https://user-images.githubusercontent.com/1721875/47145908-2c67e300-d2cb-11e8-91a2-1adea45665fc.jpg)

When opening the homescreen (with the menu button on the remote) the "Request desktop website" will be now enable and ready to be used.

![open menu request desktop website](https://user-images.githubusercontent.com/1721875/47146043-82d52180-d2cb-11e8-963c-9f51a12e1720.jpg)

Selecting the "Request desktop website", will close the menu, load the desktop version of the website and display a toast notifying the user that the desktop website has been requested.

![close menu load desktop website display toast](https://user-images.githubusercontent.com/1721875/47146169-ccbe0780-d2cb-11e8-9fc3-59d8fd9eb963.jpg)

When reopening the homescreen the "Request desktop website" is now active (like the "Turbo mode" button).

![open menu request desktop active](https://user-images.githubusercontent.com/1721875/47146722-f0358200-d2cc-11e8-871a-4dd2e02e5d9a.jpg)

If selected will request the default website.

![close menu load default website](https://user-images.githubusercontent.com/1721875/47146633-c54b2e00-d2cc-11e8-92cb-24e78d758b8b.jpg)

**Comment by AaronMT** [comment]
Will refresh fetch the current URL with the current UA depending on the mode selected?

**Comment by liuche** [comment]
@AaronMT here's the comment above detailing the behavior: https://github.com/mozilla-mobile/firefox-tv/issues/202#issuecomment-428702249

I'll add it to the top-level comment.

**Comment by liuche** [comment]
@BrianNJones I realize that we still need to export these strings for localization, even if we aren't going to be using them immediately. Let me know if you need any more clarification on the strings! Would end of this week, or beginning of next week (oct 29) be enough time for you?

**Comment by BrianNJones** [comment]
@liuche @aminalhazwani , if I'm thinking about this correctly, we should be able to use the same strings for both accessibility and the toast:
- Request desktop version of this site
- Return to non-desktop version

(I'm thinking "return" since a site will always open as mobile. And, Amin, I def agree about "non-desktop." There's not a perfect word for, but using "mobile" is unnecessarily confusing.)
