### ISSUE TITLE
Incorporate GV Builds into Weekly BETAs

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2020]
### Why/User Benefit/User Problem

As an FFTV team member, I want to keep in sync with GV's latest builds, so that I can catch bugs & get access to fixes early.

### Acceptance Criteria (how do I know when I’m done?)

* A weekly BETA build includes a GV variant
* There is a plan in place for incorporating GV into weekly BETAs
  * Plan includes the schedule for incorporating new GV builds
  * Plan includes how we make sure the schedule is followed
  * Plan is documented on wiki https://github.com/mozilla-mobile/firefox-tv/wiki/Releng-Checklist
  * Team is committed to following plan

### Related ideas/tickets to consider

* #1799 
* #1924

**Comment by athomasmoz** [comment]
Incorporating into #2018

**Comment by liuche** [comment]
One thing I realized - we can update GV in #2018 as well but the LAT we send out would probably be WebView (not GeckoView, and we don't have a way to switch between the two), and therefore GV wouldn't be tested by QA as part of the LAT.
