### ISSUE TITLE
Combine WebRenderComponents and ServiceLocator

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2022]
Both serve the same purpose, combine them

### Impact

Less code to maintain. Confusing for developers that WebRenderComponents is separate, because everything else is centralized to ServiceLocator

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
