### ISSUE TITLE
Youtube TV stuck at loading screen

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2031]
## Steps to reproduce
- open FFTV
- go to Youtube TV tile
- close the app by going home
- reopen the app
- go to Youtube TV tile again

### Expected behavior
- Youtube TV loads correctly

### Actual behavior
- Youtube TV stuck at loading screen (happens intermittently)

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

**Comment by Baron-Severin** [comment]
Looks like this is reproducible on emulator as well.

FFTV version: f48803168d87fa91115e946b925bc27d512af883
Emulator: Android TV, API 25

**Comment by cpearce** [comment]
Is this when using GeckoView, or with the SystemView? If GeckoView, this could be issue #2040. You could verify that by pressing a button on the remote once YouTube has started loading, and then you should see playback start.

**Comment by psymoon** [comment]
@cpearce this is for SystemWebView

**Comment by Baron-Severin** [comment]
Some additional notes.

100% reproducible STR
- Using emulator
- Turn on "don't keep activities"
- Open FF
- Open YouTube Tile (will load)
- Press the home button (FF will be killed in background)
- Reopen FF
- Load YouTube (will be stuck on loading screen)

Notes:
- If you force kill the app when YouTube is failing to load, on the next launch YT will load as expected
- Refreshing YT does not fix the problem
- Navigating to a new site and then returning to YT does not fix the problem
- I haven't yet noticed anything weird in the WV debugger during YT loads, but I'm still investigating

**Comment by Baron-Severin** [comment]
- Removing the WebViewCache doesn't fix this bug

**Comment by Baron-Severin** [comment]
- When following the above STR, most websites load as expected
  - Some sites never finish loading (progress bar remains active)
  - Such sites include www.google.com, www.mail.google.com, dive.google.com, www.flickr.com

**Comment by Baron-Severin** [comment]
I'm logging page ready status on this branch here.  Build and connect with Chrome remote device inspector to view logs.  https://github.com/mozilla-mobile/firefox-tv/pull/2043

When the app is working normally, pages go through ready state: interactive, ready state: complete, then emit an onLoad event.  When following the above STR, pages stick on ready state: interactive.  This happens on every website I've tested.

We get our loading state from A-C, presumably they fire the completion event based on some heuristic to avoid the problem where some pages stick at 99% loaded for an excessive length of time.  That would explain why we notice the bug on some pages but not others (none actually finish, but some satisfy that heuristic).

**Comment by Baron-Severin** [comment]
Note that when "don't keep activities" is active and we background the app, our `Application` class is not destroyed (and therefore `onCreate` is not called when the app is started again).  This is the scenario in which pages refuse to load.

When the app is manually killed, the `Application` DOES go through `onCreate`, and the bug is not reproduced.  This may be important.

**Comment by liuche** [comment]
@Baron-Severin so if this is an acceptable workaround is that something that we'd want to land and put into a new LAT? @athomasmoz was hoping to get this fix in, though @npark-mozilla does that mean the QA test will need to extend for one more day, with a new build?

**Comment by npark-mozilla** [comment]
@liuche sure, one more day would be sufficient, with the emphasis around this fix and a quick sanity check

**Comment by Baron-Severin** [comment]
@liuche @npark-mozilla the fix @psymoon suggested works, and seems perfectly fine to me, but neither of us knows _why_ it works.  We were hoping to try and figure that out, but timebox it to the end of the day.  So if I can't work out the root cause, we'll just merge this in the morning.

Is that alright?

**Comment by liuche** [comment]
That seems fine - only concern is that @abodea is in a split timezone from us, so @npark-mozilla up to you if you want to delay testing by a day, or just add on one day at the end to test this fix + sanity check.

**Comment by Baron-Severin** [comment]
If it's problematic, we can merge now.  I honestly doubt I'll manage to figure this out by EoD.

**Comment by psymoon** [comment]
@liuche @Baron-Severin what about merging the fix and make a follow-up story?
