### ISSUE TITLE
Identify process improvements to improve collaboration between FFES/FFTV

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2039]
Upon re-review of my code sharing proposal #1992:

> There actually isn’t a significant amount of shareable code between FFTV and FFES so I no longer think just sharing this code will drive significant improvements to collaboration between the products.

> Given the limited technical overlap (i.e. amount of code to share), process improvements (which?) will be more effective in improving collaboration

We should set aside time to think through process improvements that could allow for better collaboration. I think Devin and I have both been thinking about this on the side. Already, the team has:
- Merged sprint planning & backlog for both products

I'm not sure how actionable this issue is but it could be worthwhile to take an hour just to think through that. **This would be a good thinking process to timebox.**

---

Some additional ideas we could implement:
- Remind each other during stand up to move code to components if it can be shared
- Move developers back-and-forth between products (how? e.g. developer rotation)
- Enforce that any broad changes that can be done on both products (e.g. SDK 28 upgrade, androidx migration) should be done by the same person
  - Enforce that any shared code moved into components should be reintegrated into both products by the same person

**Comment by liuche** [comment]
@devinreams do you have something else that's tracking this? Also discussed keeping this open to keep track of comments or discussion. However, if you have some other place to track this we could close it.

**Comment by mcomella** [comment]
I'm going to say this bug isn't useful: closing.
