### ISSUE TITLE
Block autoplay is unintentionally enabled in GeckoView

### ISSUE THREAD

**Issue by cpearce** [mozilla-mobile/firefox-tv#2040]
If you look here:
https://github.com/mozilla-mobile/firefox-tv/blob/93fdb5d7220c70a7e19d70228370923869a698fe/app/src/gecko/java/org/mozilla/tv/firefox/webrender/WebRenderComponents.kt#L72

You see GeckoView is being initialized with ` mediaPlaybackRequiresUserGesture = false`, but that has no effect in GeckoView; that's a WebView setting.

It seems block autoplay is intended to be disabled in GeckoView, but isn't.

If you want to disable block autoplay in GeckoView, you need to be turning off block autoplay by calling `runtimeSettingsBuilder.autoplayDefault(GeckoRuntimeSettings.AUTOPLAY_DEFAULT_ALLOWED)` before the call to [runtimeSettingsBuilder.build()](https://github.com/mozilla-mobile/firefox-tv/blob/93fdb5d7220c70a7e19d70228370923869a698fe/app/src/gecko/java/org/mozilla/tv/firefox/webrender/WebRenderComponents.kt#L55).

**Comment by dnarcese** [comment]
Closed in [`1c49d4b`](https://github.com/mozilla-mobile/firefox-tv/commit/1c49d4b1b9dde70ec378d5e0c0e0e435772435ce)
