### ISSUE TITLE
Tooltiptest.kt fails on slower devices

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2042]
## Steps to reproduce
On bitbar, it's shown that tooltipTest() fails on slower devices (non-4K).  The log indicates that the script does not wait enough for:
- the button to become active
- the popup text to show up

It might be a good idea to use Uiautomator syntax to wait for the visual elements to be displayed for this test.

### Device information
* Fire TV device: Cube, Gen 2 Stick

**Comment by npark-mozilla** [comment]
For some reason, on Gen 2 device, it seems that it requires a different decorview matcher for the popup, as I see consistent error msg that says: 

`<failure>androidx.test.espresso.NoMatchingRootException: Matcher 'with decor view of type PopupWindow$PopupViewContainer' did not match any of the following roots: [Root{application-window-token=android.view.ViewRootImpl$W@3697164b, window-token=android.view.ViewRootImpl$W@10218828, has-window-focus=false, layout-params-type=1000, layout-params-string=WM.LayoutParams{(647,160)(wrapxwrap) gr=#10000033 sim=#1 ty=1000 fl=#41800208 fmt=-3 wanim=0x10302de surfaceInsets=Rect(0, 0 - 0, 0)}, decor-view-string=AppCompatTextView{id=2131296673, res-name=tooltip, visibility=VISIBLE, width=182, height=46, has-focus=false, has-focusable=false, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(647,160)(wrapxwrap) gr=#10000033 sim=#1 ty=1000 fl=#41800208 fmt=-3 wanim=0x10302de surfaceInsets=Rect(0, 0 - 0, 0)}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Turbo Mode, input-type=0, ime-target=false, has-links=false}}, Root{application-window-token=android.view.ViewRootImpl$W@3697164b, window-token=android.view.ViewRootImpl$W@3697164b, has-window-focus=true, layout-params-type=1, layout-params-string=WM.LayoutParams{(0,0)(fillxfill) sim=#13 ty=1 fl=#81810100 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1920, height=1080, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) sim=#13 ty=1 fl=#81810100 surfaceInsets=Rect(0, 0 - 0, 0) needsMenuKey=2}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}}] at`

**Comment by AaronMT** [comment]
@npark-mozilla I see a failure on the 4K. 

https://mozilla.testdroid.com/#testing/device-session/296208/432147/6662612

Is this issue summary correct?

**Comment by npark-mozilla** [comment]
@AaronMT ah, that was the custom upload I made with changes, I was using the default project to test out.

**Comment by npark-mozilla** [comment]
so the problem is that for API 22, the popup text was not the `PlatformPopup` type. Workaround woudl be to detect the Android API, and use appropriate matcher.
