### ISSUE TITLE
Release 3.7-A to full audience

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2052]
### Vision statement / What / Requirements

Release 3.7-A to all devices. Currently just on 4k stick

### Impact

All users will get the features & improvements in 3.7-A

### Acceptance criteria

* We are confident from the 3.7-RO release on 4k stick that the release is stable and can be promoted to all devices
* 3.7-A is released to all devices.

**Comment by liuche** [comment]
We'll try this out with 3.7.1!

**Comment by liuche** [comment]
Bumped this to 5% because it's the weekend, but will continue to bump this early next week to 10% and then 50%.

**Comment by liuche** [comment]
Bumped to 50%

**Comment by liuche** [comment]
I haven't seen any new issues, and the rest of the issues are low ( https://sentry.prod.mozaws.net/operations/firefox-tv/issues/5432517/ ) or fixed by #2095, so I released this! Closing this bug out now.
