### ISSUE TITLE
YouTube video flashes for 1-2 seconds when opening Firefox About

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2057]
## Steps to reproduce
1. Launch Firefox.
2. Access any YouTube video.
3. Tap on the menu button.
4. Navigate to settings.
5. Select `About` button and open it.

### Expected behavior
Firefox About is displayed correctly and no visual issues are present.
### Actual behavior
When opening Firefox About YouTube video flashes and then the Firefox About is displayed.

### Device information
* Fire TV device: Fire TV Stick 2nd Gen
* Latest affected Firefox version:  **`Firefox for Fire TV 3.7-LAT2(Build #59.0.3071.125)`**
* Earliest affected Firefox version: **`Firefox for Fire TV 3.6-RO(Build #59.0.3071.125)`**
### Notes
For more details please see the following attachments: [video](https://drive.google.com/file/d/1khGZlYdaQ5WQS9eDJaQWIzigJ6UbTurV/view?usp=sharing) and [logcat](https://drive.google.com/file/d/1_xEZsbmhTpa6EDZtSlSO6PzCkVAB5PWA/view?usp=sharing)

**Comment by athomasmoz** [comment]
Closing this issue as lower priority. Behaviour is somewhat expected, since it's loading a new web page.
