### ISSUE TITLE
Investigate alternative solutions for Fragment show/hide

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2065]
### Vision statement / What / Requirements
- We are moving further away from android lifecycle
- Other dependencies (specifically a-c) has lifecycle assumptions in their implementations
- Investigate other ways to implement our ScreenController

### Impact
- Some future features are limited with the current implementation (we are always assuming one instance of WebRenderFragment)
- More prone to issues/regressions due to assumptions made by dependencies

### Acceptance criteria
- ADR and follow-up stories for incremental work

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
