### ISSUE TITLE
Youtube TV back key doesn't work

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2070]
## Steps to reproduce
- Open FFTV (with gecko variant)
- Go to Youtube.com/TV
- Click on any video
- Press back on hardware button

### Expected behavior
- back works as expected (YT TV navigation)

### Actual behavior
- back doesn't work

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

**Comment by athomasmoz** [comment]
This is a workaround. The larger issue is #1837
