### ISSUE TITLE
Youtube loses control after menu bar

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2072]
## Steps to reproduce
- Open youtube, play video
- Play with controls, make it visible
- Press menu to go to overlay
- Press menu again to return to video
- Access youtube video control, or exit the video

### Expected behavior
- Control is visible, and video can be stopped with back button

### Actual behavior
- App does not respond to inputs, other than menu overlay

### Device information
* Fire TV device: Gen 2 stick

**Comment by dnarcese** [comment]
Similar to #1830? @npark-mozilla does reloading the page fix it?

**Comment by npark-mozilla** [comment]
@dnarcese yes actually, it seems like it's the same bug as #1830.  (Tested on latest LAT)

**Comment by liuche** [comment]
Was trying to compare with other versions to figure out what was going wrong, and I came across this in other places.

Repros:
* 4K-70* 3.7-RO from store shows this
* Stick 3.7-RO debug
* Stick 3.7-RO release

Does not repro:
* Stick-70* 3.5-B
* Cube-70* 3.5-B

So this seems like a regression from 3.7-RO.

**Comment by liuche** [comment]
Will keep investigating this tomorrow, but if someone else has time to look it in the AM feel free to pick it up!

**Comment by liuche** [comment]
Derp, that was easy to find - we're letting engineView request focus as part of the Youtube loading bugfix in #2031 and that's throwing off what focus gets cached when the overlay closes.

**Comment by liuche** [comment]
When this PR merges it'll be QA-ready, and I will cherry-pick it to the 3.7.1-RO and make an apk, and then submit it.
