### ISSUE TITLE
From youtube page, can't go to Forward page

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2075]
## Steps to reproduce
- Open youtube page, wait until it completes
- Go to overlay, go to cnn.com
- After page is loaded, press back button to go back to YT page, and Forward button is activated
- Press Forward

### Expected behavior
- Goes to cnn.com

### Actual behavior
- Frozen youtube screen is shown, probably the same reason as #2072 and #1830 

### Device information
* Fire TV device: Gen 2

**Comment by athomasmoz** [comment]
@npark-mozilla do you mind retesting this one now that #2072 and #1830 are fixed?

**Comment by npark-mozilla** [comment]
Actually, now this might be available to general devices, let's see whether @kglazko can see this on her device.  Could you check whether you have the update for your Fire TV, and whether this is reproducible?

**Comment by npark-mozilla** [comment]
Seems like it's not available to all devices, I'll check it tomorrow.

**Comment by npark-mozilla** [comment]
This behavior is gone, but a related bug was found: https://github.com/mozilla-mobile/firefox-tv/issues/2115
