### ISSUE TITLE
Update Screenshot UI Tests

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2087]
### Vision statement / What / Requirements
Current Screenshot UI Tests were written a while ago, and it needs to be kept up to date to run.

### Impact
L10N people will have screenshots

### Acceptance criteria
It shows all strings that user normally come across

**Comment by npark-mozilla** [comment]
Turns out I need to accommodate tooltips feature as well, might take a bit.

**Comment by athomasmoz** [comment]
@npark-mozilla is this complete?

**Comment by mcomella** [comment]
Merged PR is https://github.com/mozilla-mobile/firefox-tv/pull/2105

**Comment by npark-mozilla** [comment]
@athomasmoz yes it is.
