### ISSUE TITLE
We stopped collecting telemetry for back, forward, refresh

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2103]
### Vision statement / What / Requirements
It looks like in the toolbar refactor, telemetry events were dropped for back, forward, and refresh buttons. Only pin, turbo, desktop mode, and exit clicks send a telemetry event ([see this method](https://github.com/mozilla-mobile/firefox-tv/blob/6414fec25d71a56ebfd20a59a3ec18b63e48d189/app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/ToolbarViewModel.kt#L144)).
### Impact
We have missing data for back, forward, and refresh button clicks.
### Acceptance criteria
Add back the telemetry events for all toolbar button clicks.

**Comment by athomasmoz** [comment]
Thanks for catching and adding this!

**Comment by mcomella** [comment]
It'd be cool if this could be caught by a test next time: @dnarcese, do you think it's possible to write tests for these? Maybe use Mockito to verify the expected `TelemetryWrapper` methods are being called.
