### ISSUE TITLE
[1630] Implement pinned piles as first generic channel

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2110]
### Why/User Benefit/User Problem

As a user, I want the tiles on the homescreen to be organized using both up/down arrows and side-to-side so that I can reach my desired tile faster given my FireTV remote. And to match the interaction I'm used to on other Fire TV apps

In future, this will also allow further categorization of home screen tiles

### Acceptance Criteria (how do I know when I’m done?)

* Pinned tiles is a channel on the home screen
  * It includes a localized name
  * Tiles are organized horizontally
* Implementation can be re-used for future channels of links
  * Check if settings code is reusable
  * Consider how multiple rows of these should be organized (e.g. all in a RecyclerView? Consider if we ever want to reorder, add/remove, etc. but maybe keep it simple :))
* All other design features are differed to separate stories

### Considerations

* Should the current ordering be maintained? Or should it be YT, Google, custom, then remaining bundle tiles?

## Things to follow up on
Follow up issue opened at https://github.com/mozilla-mobile/firefox-tv/issues/2159

**Comment by liuche** [comment]
We don't have this string yet, so we'll need to get this strings created/approved and then localized.
