### ISSUE TITLE
[1630] Make Pocket a Channel - land after freeze

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2111]
### Why/User Benefit/User Problem

As a user, I want the tiles on the homescreen to be organized using both up/down arrows and side-to-side so that I can reach my desired tile faster given my FireTV remote. And to match the interaction I'm used to on other Fire TV apps

In future, this will also allow further categorization of home screen tiles

### Acceptance Criteria (how do I know when I’m done?)

* [x] Pocket is a channel on the home screen
  * [X] It includes a localized name - only shown on EN locale
  * [x] Tiles are organized horizontally
* [x] Pocket cannot be removed from pinned
* [x] Shares code where possible from pinned tiles channel in #2110 
* [x] Pocket fragment is removed
* [x] Pocket telemetry is working as it did previously
  * We should ping Pocket when this drops, as it will likely have a large impact on their impression rates

---

liuche suggested we should not file follow-ups and should keep this open. As such, after PR #2178, we have some follow-up items:
- Long-click to remove bugs
  - [x] Long-clicking on Pocket crashes the app
  - [x] Long-clicking on pinned tiles displays a dialog but selecting remove does not remove the tile
- Focus bugs
  - [x] Pressing right when reaching the end of the Pocket channel selects the pinned tiles
  - [x] Press left when reaching the end of the Pinned tiles selects the Pocket channel
- [x] Use updated string for Pocket channel title (blocked on results from athomasmoz below)
- [ ] Pocket styling matches mocks #2280

**Comment by liuche** [comment]
We'll need to get a section string for this: we have the following strings Pocket, Recommended videos by Pocket, Recommended Videos - but we could come up with a totally new string too.

**Comment by Baron-Severin** [comment]
FYI, this is a draft PR showing how to create a new channel.
https://github.com/Baron-Severin/firefox-tv/pull/5/files

**Comment by devinreams** [comment]
@Baron-Severin please break into a separate style issue for those changes

**Comment by Baron-Severin** [comment]
> We'll need to get a section string for this: we have the following strings Pocket, Recommended videos by Pocket, Recommended Videos - but we could come up with a totally new string too.

The mocks show `Pocket Editor's Choice`, which seems good to me.  We only show Pocket to EN-US users, so localization isn't a blocker.

> @Baron-Severin please break into a separate style issue for those changes

Will do.  I'll edit this to link when it's up.

**Comment by athomasmoz** [comment]
Hey @Baron-Severin , I'm organizing the remaining Pocket tickets. To confirm, the remaining work for this one is:
* Prevent users from removing pocket tiles
* Ensure Pocket telemetry is working as before
* Remove the Pocket megatile

**Comment by Baron-Severin** [comment]
@athomasmoz Pocket megatile is already removed, and I just finished preventing users from removing Pocket tiles.  Remaining should just be:
- Ensure telemetry is working as before

**Comment by liuche** [comment]
For the strings-needed label, I filed [this Trello card](https://trello.com/c/rJ3aD5N3/101-fftv-pocket-category-name) for the Content Team. 
If we don't need this localized, we should put this title in a non-localized string, because otherwise, all our changes to this string will get localized anyway.

**Comment by athomasmoz** [comment]
Bug found: Title should be "Recommended by Pocket". @mcomella suggested he could add this change into his PR.

**Comment by mcomella** [comment]
@athomasmoz What's the updated string for the title of the Pocket channel?

**Comment by athomasmoz** [comment]
> @athomasmoz What's the updated string for the title of the Pocket channel?

@mcomella it's "Recommended by Pocket" thanks!

**Comment by mcomella** [comment]
We landed the initial implementation but still need to land the follow-ups.

We didn't update the commit titles (which auto-closed this issue) to avoid having to run CI again. x_x

**Comment by mcomella** [comment]
The remaining Pocket channel work is being tracked in #2280.
