### ISSUE TITLE
[1630] All channels have proper focus behavior

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2112]
### Why/User Benefit/User Problem

As a user, I want the tiles on the homescreen to be organized using both up/down arrows and side-to-side so that I can reach my desired tile faster given my FireTV remote. And to match the interaction I'm used to on other Fire TV apps

In future, this will also allow further categorization of home screen tiles

### Acceptance Criteria (how do I know when I’m done?)

* Channel behaviour matches designs described in #1630 
* ~Channel title format~ moved to at #2189
* ~Arrows for scrolling channels~ removed due to decision by UX
* [x] Focus behaviour
* ~Confirm spacing~ moved to #2189
* [ ] SUMO articles referencing homescreen & settings are updated

**Comment by Baron-Severin** [comment]
Engineering note on the scrolling behavior (focused view stays on the left side of the screen): reading through documentation, it _looks_ to me like this should be achievable using some combination of `BaseGridView#windowAlignment`, `#windowAlignmentOffset` and `windowAlignmentOffsetPercent`, but I haven't yet managed to get it to work.

**Comment by devinreams** [comment]
UX stuff moved into #2189
