### ISSUE TITLE
List of New Homescreen Tiles & Categories EN-US

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2113]
### Why/User Benefit/User Problem

As a user, I want to see tiles on the homescreen that suggest where I can find content on the web, and let me get there in a few clicks, rather than typing out a search/url

### Acceptance Criteria

- [x] A list of categories for home screen tiles (EN_US)
- [x] A list of tiles for each category (EN-US)
- [x] Tiles are safe for families
- [x] Determine if any extra info is needed to help users understand why each tile was chosen

**Comment by mcomella** [comment]
@athomasmoz Content suggestion: I've heard archive.org (the internet archive) has a lot of interesting public domain content including video. For example, here's their videos filtered on "feature films" – https://archive.org/details/feature_films – and searching for Charlie Chaplin in those films: https://archive.org/details/moviesandfilms?and[]=chaplin&sin=&and[]=collection%3A%22feature_films%22

**Comment by mcomella** [comment]
^ It could be a good opportunity to show people content that isn't available anywhere else and that is in a different style than they might think to search for.

**2nd content suggestion**: there are probably some video services for phone/tablet on Google Play that don't have Fire OS apps: maybe we can identify which those are and link to their websites. For example, I assume there's a History Channel Google Play app but do they have a History Channel Fire OS app? 🤷‍♀️

**Comment by brampitoyo** [comment]
@athomasmoz I’ve finished curating categories and channels against Alexa US top sites list. We have 150+ sites across 11 categories – I hope it’s enough to get started.

@mcomella wrote:
> Content suggestion: I've heard archive.org (the internet archive) has a lot of interesting public domain content including video […]

This is a great idea. Through the channel approach, we have a chance to showcase niche, long tail and non-mainstream (but still popular!) sites.

I’ve added that specific section of archive.org into our channel listing.

@mcomella wrote:
> 2nd content suggestion: there are probably some video services for phone/tablet on Google Play that don't have Fire OS apps: maybe we can identify which those are and link to their websites […]

@athomasmoz had given TV channels (all of which are popular) its own place on the listing – and this includes sites like the History Channel, Discovery Channel, etc.

Unfortunately, all of these pay TV sites require you to sign in before you watch anything on demand. Signing in is not bad, but if we optimise for “finding something to watch quickly”, signing in is a barrier.

I’ve added the History Channel under the “TV” category, but also believe that we should prioritise listing sites that contain videos you can watch freely and instantly.

**Comment by mcomella** [comment]
> Unfortunately, all of these pay TV sites require you to sign in before
you watch anything on demand.

Probably not a P1 but: for users who already pay for these services but
there is no existing Fire OS app for them, it could be helpful to users if
we surfaced them in some way: a "paid subscriptions" channel for content
users might be paying for but didn't know they can get on their TV. If
there's no other way for users to access their content, it sounds like we
could be solving a significant problem for them.

**Comment by mcomella** [comment]
@brampitoyo A few more content suggestions:
- arte.tv ([from Wiki: ](https://en.wikipedia.org/wiki/Arte)ARTE is a Franco-German free-to-air television network that promotes cultural programming; it's French and German with english subtitles; content is free)
- ^ This seems partially funded by the EU. I heard their are other TV providers in other countries that feature free content (e.g. BBC, but also maybe scandanavian providers)

Also, in the MVP, categories that I enjoy but are missing is "History" and "Culture" (to be fair, the latter which can fit into many other categories, like food).

**Comment by devinreams** [comment]
This was completed in Sprint 3, closing. 🚀
