### ISSUE TITLE
Hollywood Reporter site shows "Secure connection failed" followed by whitescreen upon retry or blocks user from navigating to any other site

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2122]
## Steps to reproduce
Click Hollywood Reporter tile

### Expected behavior
Site opens

### Actual behavior
During the site is being loaded, it shows "Secure connection failed" dialog, and clicking 'Try again' shows white screen 

### Device information
* Fire TV device: Gen 2 (whitelisted)

**Comment by liuche** [comment]
This only happens on Hollywood Reporter. It looks like hollywoodreporter.com is trying to load a script, which is redirecting to launch.newsinc.com/js/embed.js and that's causing a security exception.

Trying this on Desktop Firefox, I get this warning:
```
Loading failed for the <script> with source “https://launch.newsinc.com/js/embed.js”. www.hollywoodreporter.com:1:1
Request to access cookie or storage on “https://launch.newsinc.com/js/embed.js” was blocked because it came from a tracker and content blocking is enabled. www.hollywoodreporter.com
```

Turning tracking protection off doesn't fix this problem, but probably Firefox Desktop just fails more gracefully. I also see this on all devices.

I don't see this on Silk, but Silk is on Chromium 73.

**Comment by liuche** [comment]
Filed this wecompat bug: https://webcompat.com/issues/30065

**Comment by kglazko** [comment]
I would think that regardless of webcompat, we should be able to handle these kinds of failures gracefully. Not being to navigate away from a site/use the URL bar/use basic navigation is a pretty difficult user experience.

**Comment by liuche** [comment]
Hm, that's a good point @kglazko - how often does this infinite loading loop happen? I wasn't able to repro that part at all, and was able to load other pages.
Can users click on a tile to leave the infinite loop? We know most people click tiles rather than entering text into the urlbar too.

**Comment by liuche** [comment]
Can we add a way to kill a misbehaving script, the way desktop browsers do?

**Comment by Baron-Severin** [comment]
I found an SO link that describes some attempted workarounds for the same problem.  Looks bleak.

https://stackoverflow.com/questions/20681876/android-webview-enters-unrecoverable-state-if-executed-javascript-enters-infinit

**Comment by athomasmoz** [comment]
Rolled into #2343 to track there.
