### ISSUE TITLE
[1630] Update Pocket onboarding screenshot for Pocket as a channel

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2124]
### What / Requirements
- Get screenshot of new onboarding experience from UX
- Replace existing onboarding screenshot with new screenshot

Note: we're trying to do the minimal implementation here and may follow-up with improvements

**Comment by brampitoyo** [comment]
### Current
![Current@2x](https://user-images.githubusercontent.com/51007/56872068-2a9c8a80-6a79-11e9-9a68-80533cc02469.png)

### Proposed
![Proposed@2x](https://user-images.githubusercontent.com/51007/56872051-e14c3b00-6a78-11e9-84a5-b400819e567c.png)

@mcomella What do you think?

**Comment by mcomella** [comment]
@brampitoyo The aesthetic is good. A few thoughts:
- "Recommended by Pocket" – do we want to indicate that these are curated by editors (as per user research)? I see "Pocket Editor's Choice" at the top but that might go unnoticed
- VR has a niche, gamer/tech-centric audience: for the initial item, do we want to pick an item that has a broader audience?
- Our focused item highlights don't look like that yet (with the double blue rim): that's #837. If it's not too difficult, we should try to use the current design

A crazy thought: with channels, do we even need this screen anymore? What if we pulled the onboarding text directly into the channel so it looked like this:

```
## Pocket Editor's Choice
_The most interesting videos on the web. Recommended by Pocket, now part of Mozilla._
----  ----  ----
|  |  |  |  |  |
----  ----  ----

**Comment by athomasmoz** [comment]
Oh I like that idea. Even crazier, what if the title was something like "you may be interested in.." and the description mentions Pocket? Maybe we can do a quick comparison of wording to see what resonates best, given the feedback that people thought it was sponsored content. And, of course, make sure Pocket is still happy with it.

**Comment by brampitoyo** [comment]
@mcomella wrote:
> A crazy thought: with channels, do we even need this screen anymore? What if we pulled the onboarding text directly into the channel…

@athomasmoz wrote:
> […] what if the title was something like "you may be interested in.." and the description mentions Pocket?

Great idea! Why have an interruptive tutorial modal if just-in-time explanation can work?

![Phase 3@2x](https://user-images.githubusercontent.com/51007/57003944-805e6780-6c1e-11e9-847e-8700f41a4d57.png)

Let’s say we show this description when the homescreen shows up for 5 sessions worth (1 session = FFTV is opened and closed). This means that YouTube viewers who never uses the homescreen will still have this description show up.

When we’re reasonably sure that the user has understood what it’s about, we can hide the description to save some space for other sections.

I’d be happy to discuss titling and naming with the Pocket team! They should also know that we want to list their videos directly on the homescreen, with no page inbetween.

**Comment by mcomella** [comment]
@brampitoyo @athomasmoz To be explicit, are we moving forward with this design or do we want to discuss with Pocket first?

**Comment by brampitoyo** [comment]
@mcomella @athomasmoz I think that this design will be fairly easy to approve (in a sense that we’re moving elements around without changing the way it works or the way it’s ordered), but we should still meet with Pocket to double-check.

**Comment by liuche** [comment]
Added strings-needed label bc we might want to update the "Pocket stories" explanation string.

**Comment by liuche** [comment]
We'll just update the screenshot with Pocket channels.

**Comment by mcomella** [comment]
> We'll just update the screenshot with Pocket channels.

To elaborate, we want to get this in the sprint if possible and we're falling behind so the more involved changes got cut. I filed https://github.com/mozilla-mobile/firefox-tv/issues/2179 to potentially implement them as described in https://github.com/mozilla-mobile/firefox-tv/issues/2124#issuecomment-488182954

@brampitoyo Can you supply us with a new image for the Pocket onboarding like https://github.com/mozilla-mobile/firefox-tv/issues/2124#issuecomment-487427803 ? We currently take [a mock of the pocket mega tile](https://searchfox.org/mozilla-mobile/source/firefox-tv/app/src/main/res/drawable-xhdpi/pocket_mega_tile.png) and [insert it into a layout](https://searchfox.org/mozilla-mobile/source/firefox-tv/app/src/main/res/layout/pocket_onboarding.xml). Ideally, we could just swap in the image.

**Comment by mcomella** [comment]
@brampitoyo For time's sake, it may or may not be worth taking into my earlier feedback in going with the simple change: https://github.com/mozilla-mobile/firefox-tv/issues/2124#issuecomment-487768506

**Comment by brampitoyo** [comment]
@mcomella wrote:
> Can you supply us with a new image for the Pocket onboarding […] Ideally, we could just swap in the image.

The image is attached below. Does it look ok for our purpose?

![pocket-editors-choice@2x](https://user-images.githubusercontent.com/51007/57274056-02063780-70ee-11e9-9701-ae8fd3d301e5.png)

**Comment by mcomella** [comment]
> The image is attached below. Does it look ok for our purpose?

Daniela opened a PR so it seems that way!
