### ISSUE TITLE
[1630] Users can only remove pinned tiles

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2125]
### Why/User Benefit/User Problem

As a user, I want to remove a pinned tile that I no longer use, so that I don't need to scroll past it when looking for other pinned items

### What / Requirements

- [ ] Pinned tile removal works now; make sure it still works after channel redesign
- [ ] Long press does not show option to delete tile on Pocket & Settings
- "do not allow Pocket to be removed" happening at #2111

**Comment by devinreams** [comment]
Now happening at #2111
