### ISSUE TITLE
Track Distractions (Q2SP3)

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2126]
This is to track work/bugs that are not planned for in the sprint. If it's not tracked in the "In Progress" section it should be added as a comment here. If we add a bug after the fact, also comment it below.

### Impact
This will help us keep track of how much additional work comes up that's unplanned, so we can plan better in the future and take that into account.

### Acceptance criteria
Comments below

**Comment by dnarcese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [d](https://trello.com/c/Yj2vGHGE/2-d)

**Comment by mcomella** [comment]
I spent some time (unsuccessfully) today trying to identify big picture problems our team is having (to create and align my Q2 OKRs).

**Comment by mcomella** [comment]
We added #2133 to this sprint.

**Comment by liuche** [comment]
Added #2152 to the sprint, because it was part of the Retro action items.

**Comment by mcomella** [comment]
I've spent at least half a day, if not more, identifying the UX requirements with Bram on #2123 (and other issues): I think we should break #2123 into a separate implementation issue once the requirements are identified because there is a lot of UX discussion in that bug.

**Comment by psymoon** [comment]
Added https://github.com/mozilla-mobile/firefox-tv/issues/2156 to this sprint

**Comment by mcomella** [comment]
I spent maybe 45min - 1 hour today typing up product ideas and a fix for the typing problem.

**Comment by mcomella** [comment]
@Baron-Severin Can you document which issues you added to this sprint?

**Comment by Baron-Severin** [comment]
Added: https://github.com/mozilla-mobile/firefox-tv/issues/2162, https://github.com/mozilla-mobile/firefox-tv/issues/2163, and https://github.com/mozilla-mobile/firefox-tv/issues/2166
These are high priority issues related to the new channel implementation, and are tracked in the meta bug https://github.com/mozilla-mobile/firefox-tv/issues/2159

**Comment by mcomella** [comment]
Severin and I did a pair programming retro for ~30min and I spent another ~15min addressing action items.

**Comment by mcomella** [comment]
(maybe gratuitous) I spent about 30min talking to liuche about Q3 and to other teams about working together across teams.

**Comment by Baron-Severin** [comment]
Spent ~2.5 hours reading articles and research on pair programming + taking notes.

**Comment by mcomella** [comment]
I split out #2170 & #2171 into separate bugs (for better tracking; they're blocked on WebView) from #2076 and repurposed #2076 to a smaller scope (though I'm still investigating).

**Comment by mcomella** [comment]
Bug #2123 (Pocket UX reqs) was originally written as a, "Get UX & implement" bug and was unsized. I morphed it to, "Get UX" (it took maybe a day or two to work out the details for me) and broke it up further:
- #2154
- #2186
- #2187
- #2188

Which I added to the board.

---

I spent 30min reading Phoenix Project yesterday (and I intend to do the same today, provided there's time).

**Comment by mcomella** [comment]
I spent 30min cross-team mentoring.

**Comment by mcomella** [comment]
I spent maybe 15 min filing Fenix bugs.

**Comment by mcomella** [comment]
I spent 15+ min following up on athomasmoz's PRD presentation.

**Comment by mcomella** [comment]
We discovered an unforeseen issue with the Pinned tiles channel and added it to the sprint as a release blocker #2202.

**Comment by mcomella** [comment]
https://github.com/mozilla-mobile/firefox-tv/issues/2189 was repurposed to just address release blockers. https://github.com/mozilla-mobile/firefox-tv/issues/2208 is for final styling but is blocked on additional UX requirement gathering in https://github.com/mozilla-mobile/firefox-tv/issues/2209: these are not added to the roadmap.
