### ISSUE TITLE
Unnecessary grey space at top of screen when scrolling overlay down

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2139]
## Steps to reproduce
- Open overlay
- Scroll down so that page content scrolls

### Expected behavior
Content touches top of screen

### Actual behavior
There is a grey space about 1/3 the height of a home tile between the content and the top of the screen: the content is cut off.

![image](https://user-images.githubusercontent.com/759372/56934825-98a97780-6aa2-11e9-8f14-dd38d662cd83.png)

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 3.8
* Earliest affected Firefox version: ?

---

Usually this problem is caused because the scrollView has a margin or padding, rather than having the top-most content have padding (or there being a spacer View at the top of the content inside the ScrollView).

**Comment by liuche** [comment]
Closed by #2280
