### ISSUE TITLE
[1630] Source default Pocket content

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/firefox-tv#2154]
@mcomella wrote in https://github.com/mozilla-mobile/firefox-tv/issues/2123#issuecomment-488513914:

> As for the default Pocket video recommendations we ship with the application (that all users will see on first run and ~45 minutes thereafter), how do we want to source those?

Let discuss that content here.

If there’s a URL where we can have a look at all Pocket videos recommended up to this point, I’d be happy to pick a few. I’d also be happy to have the Pocket team curate an initial list.

CC @athomasmoz

**Comment by mcomella** [comment]
Ashley mentioned Pocket should have this content by the end of the week.

**Comment by athomasmoz** [comment]
Confirmed. And adding content is tracked under #2223 . Closing this issue
