### ISSUE TITLE
[2159] Clean up BundledTile Picasso implementation

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2164]
### Vision statement / What / Requirements
`BundledPinnedTile#toChannelTile` sets an image by calling `.load("file:///android_asset/bundled/$imagePath")`.

### Impact
This hardcoded path would be easy to accidentally change.  Additionally, I'm not certain that it will work as expected on all devices.

### Acceptance criteria
- A cleaner solution to this problem has been discovered and implemented

**Comment by mcomella** [comment]
I think prefixing the path with `android_asset` is what we're supposed to do: https://github.com/square/picasso/issues/332#issuecomment-30635004

Maybe we should wrap it in an extension function (or similar) so it's easier to discover and use.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
