### ISSUE TITLE
[2159] Develop strategy for FocusRepo to handle channels

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2165]
### Vision statement / What / Requirements
`FocusRepo` needs to know what the next highest, active, focusable view is after the navigation bar (among others).  This is how `NavigationBar#nextFocusDownId` is set.  Currently, this is set to:
1) Pocket Megatile, if available
2) Pocket try again button, if available
3) Pinned tiles, if not empty
4) Settings

If we add additional channels above and below pinned tiles, we will need some good way to let the FocusRepo know what is available to be focused.

### Impact
- If we don't do this, it could slow down adding new channels (or add regressions, if not noticed during dev)

### Acceptance criteria
- A good strategy for determining focus for views around channels has been determined
- This strategy is implemented for appropriate views
  - Navigation bar
  - Settings
(note that Pocket Megatile doesn't need this treatment, as it is being rewritten into a channel)

**Comment by athomasmoz** [comment]
@Baron-Severin is this needed for the channels work? Or is it a proposed improvement for the future?

@mcomella wasn't sure of the implications of this ticket.

**Comment by Baron-Severin** [comment]
> @Baron-Severin is this needed for the channels work? Or is it a proposed improvement for the future?

@athomasmoz nope, we're currently handling this manually, but it works.  Until we work out a clean way to handle it, adding additional channels will incur some tech debt.  I don't think this should be prioritized yet (taking on debt seems like a good decision atm), but it's worth keeping in mind.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
