### ISSUE TITLE
[2159] Unify ChannelTile IDs

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2167]
### Vision statement / What / Requirements
`BundledPinnedTile.id` is typed to String, while `CustomPinnedTile.id` is typed to UUID.  This presents challenges for the unified type, `ChannelTile`

### Impact
- Complicates transformations from `PinnedTile -> ChannelTile`
- Blocks removal of `BundledPinnedTile` and `CustomPinnedTile`

### Acceptance criteria
- `ChannelTile` has an ID field, which maps cleanly from `BundledPinnedTile` and `CustomPinnedTile`

### Note
- Depending on the implementation, this may need to happen as part of #2162

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
