### ISSUE TITLE
[2159] Expand ChannelTile, delete PinnedTile

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2168]
### Vision statement / What / Requirements
`CustomPinnedTile` and `BundledPinnedTile` serve very similar purposes, and should be able to be modeled as one type.  If possible, we should merge these into `ChannelTile`

### Impact
- This will simplify our code base

### Acceptance criteria
- `CustomPinnedTile` and `BundledPinnedTile` have been deleted
- All previous references to them are changed to `ChannelTile`
- Existing persisted tiles are still available as `ChannelTile`s (i.e., double check that our migration strategy works)
- Telemetry is unaffected

**Comment by athomasmoz** [comment]
NOTE: discuss in retro how to handle chores like this.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
