### ISSUE TITLE
[2159] Wrap channels in a RecyclerView

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2169]
### Vision statement / What / Requirements
Channels are currently added to a simple `LinearLayout`.  They should instead live in a vertical `RecyclerView`

### Impact
- If we ever need complex removal / movement animations, using a `RecyclerView` will make this much simpler
- If we have more channels than we can fit on screen, this will improve performance by recycling offscreen views

### Acceptance criteria
- Channels are added to a `RecyclerView`, instead of a `LinearLayout`

**Comment by mcomella** [comment]
P1: this will make it easier to add/remove new channel categories

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.

For example, this should be in this sprint, but it's not. We can figure this out when we're adding channels.
