### ISSUE TITLE
jwplayer test site fullscreen video content is offset, shows black bar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2170]
Break-out from #2076: this firefox-tv issue is also reproducible in a standalone WebView app so we think these are bugs in the WebView implementation.

See also #2171 for another jwplayer test site fullscreen bug.

## Steps to reproduce
- Create a standalone WebView app that supports fullscreen (or [use mine](https://github.com/mcomella/WebViewRaw/tree/2076-issue))
- Visit jwplayer 8 test site: https://developer.jwplayer.com/tools/stream-tester/?playerversion=8 (my app does automatically)
- Attach a remote debugger with Chrome dev tools
- Click down and right on dpad on until video starts playing
- Click down and right on dpad until video is focused
- Click select button to display the video player controls (e.g. by pausing)
- Before the video player controls disappear, execute the following JS to focus the fullscreen button: `document.querySelector('.jw-icon-fullscreen').focus()`
- Click select to enter fullscreen

### Expected behavior
Video content fills the screen

### Actual behavior
Video content is squashed to top 3/8 or 1/2 of screen

![image](https://user-images.githubusercontent.com/759372/57168704-c438a480-6db7-11e9-80a7-e1a1f818724e.png)

### Device information
* Fire TV device: Stick gen 2
* Latest affected Firefox version: v3.8+
* Earliest affected Firefox version: ?

**Comment by mcomella** [comment]
In Firefox for Fire TV, **I can also reproduce this on jwplayer 7** by double tapping the video to fullscreen. However, in a standalone app, I'm unable to fullscreen because I can't focus the right element to double-click and I can't focus the fullscreen button

**Comment by mcomella** [comment]
@athomasmoz Can you raise this with Amazon? This firefox-tv issue is also reproducible in a standalone WebView app so I think this is a bug in the WebView implementation. Note: this comment is similar to #2171 but both issues need to be raised with Amazon.

**Comment by liuche** [comment]
@devinreams can you bump this? It's happening in the standalone WebView app too, so this seems like an AmazonWebView problem. (Is linking to this bug enough, and then someone can investigate?)

**Comment by devinreams** [comment]
JWPlayer bugs had been reported with references to these exact issues and details and will share when hear back.

**Comment by liuche** [comment]
Action Items:
* Is there a workaround?
    * Is GeckoView is an option?
    * Worth more thorough investigation
    * Detect JWPlayer and do some JS magic to actually make video container fullscreen?
* Pull together more data to compile a detailed report for @devinreams @athomasmoz 

Puts TV Guide Channels at risk.

**Comment by liuche** [comment]
Timebox to 1 day.

**Comment by liuche** [comment]
Quick summary from Media Frontend meeting (the team mainly works on video decoding):
• What is the *resolution* the video player thinks it's at? (e.g. GeckoView told HD vs 4K, do we need some other kind of whitelist?)
• Desktop vs Mobile User Agent, maybe expecting taps vs clicks? (Try *Desktop Mode*?)
• Noteworthy that a lot of these are *fullscreen* issues - are we handling fullscreen incorrectly?
• Consider trying out *responsive design mode* (In desktop Firefox, type cmd+opt+m) - can edit User Agent, resolution (is it a website problem?)


And some less promising leads/thoughts:
• Autoplay? (Chrome gives video autoplay control) - does Chromium have this?
• JS API for putting things into fullscreen
• Maybe too much JS is running, causing performance problems
• Even if Chromium version is delayed (70 vs 73) older Android devices are probably on old WebView versions too. Would be surprised if Chromium 70 is the problem (Nils)
• Other suggestions: group by problem e.g. fullscreen, tap/clicks; which video players show which symptoms

**Comment by athomasmoz** [comment]
FYI - I noticed a lot of other sites using HTML5 players (JW player just one of them) are experiencing issues with playback too.

**Comment by psymoon** [comment]
Update:
- There is no API call to set fullscreen for both Flash & HTML5 `jwplayer` (API doc says due to phishing-related security restrictions)
- Verified not reproducible in gecko build
- Verified not reproducible in older builds
- Tried Resizing using `var x = $(window).innerWidth();
var y = $(window).innerHeight();
jwplayer().resize(x,y);`, didn't work in fullscreen mode.
- Request desktop-mode breaks fullscreen mode completely.

**Comment by athomasmoz** [comment]
Another site to test any fixes on: deadspin.com/video

**Comment by mcomella** [comment]
A review suggests this may have only started happening in v3.10: https://appbot.co/apps/1658893-firefox-for-fire-tv/reviews/1216464174?utm_campaign=slack-review-header&utm_medium=slack&utm_source=slack

**Comment by mcomella** [comment]
I can no longer reproduce this on first playback, probably due to our video offset fixes. However, **replaying the video will cause the video to be offset**. I'm going to close this and add it to our meta tracking bug https://github.com/mozilla-mobile/firefox-tv/issues/2851.
