### ISSUE TITLE
Simplify onboarding: move Pocket onboarding directly into channel

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2179]
### Why/User Benefit/User Problem

As a user, I want to know what the Pocket channel is when I see it on the homescreen

### Acceptance Criteria (how do I know when I’m done?)

* Pocket onboarding step is removed
* One-liner added to the Pocket channel
  * Pocket team to provide string
  * String does not need to be localized because it's EN locales only

**Comment by brampitoyo** [comment]
@mcomella I’ve updated the mockup with Pocket section description. You should be able to inspect the font colour, size, dimension, etc. there.

The link is the same, as always:
https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/#artboard2

I’ve also updated the image up above on https://github.com/mozilla-mobile/firefox-tv/issues/2179#issue-440974305 to reflect the mockup.

**Comment by liuche** [comment]
Is there a new string for this copy, promoting Pocket? Just want to check to make sure if it's something that should be changed.

**Comment by athomasmoz** [comment]
Yes, we should work with the Pocket team on the correct copy.

**Comment by brampitoyo** [comment]
@athomasmoz Let’s send them an email about this. Just to note that the copy has not changed at all.

What we’re proposing are:

* Move the description copy “The most interesting videos…” from an interruptive separate screen, to below the channel title
* Change the channel title from “Pocket” → “Pocket Editor’s Choice”. It was inspired by @mheubusch’s suggestions to clarify the fact that Pocket tiles aren’t paid placement

**Comment by Baron-Severin** [comment]
@athomasmoz @brampitoyo Is the copy in the mock final?

`Pocket editor’s choice`
`The most interesting videos on the web. Curated by Pocket, now part of Mozilla.`

**Comment by athomasmoz** [comment]
Hmm I was supposed to get it on Friday. Let me send a reminder, thanks for calling it out

**Comment by athomasmoz** [comment]
@Baron-Severin Here's the confirmed string "Fascinating videos to fuel your mind, curated from around the web." and the title can remain as "Recommended by Pocket"
