### ISSUE TITLE
Test New Homescreen Sites: News & Politics

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2180]
### Why/User Benefit/User Problem

When I click on a link from the Firefox homescreen, I expect to be able to browse & play videos/music on it.

### Acceptance Criteria (how do I know when I’m done?)

* All [MVP websites](https://docs.google.com/spreadsheets/d/1uuYQzG5RZKeB1UIdVXiPIacumJb3NN_YA_plKLF0nBA/edit#gid=1339469566) have been tested to ensure
  * A user can reach videos on the website
  * A user can play videos on the website
  * The website passes our [cleansing criteria](https://docs.google.com/spreadsheets/d/1uuYQzG5RZKeB1UIdVXiPIacumJb3NN_YA_plKLF0nBA/edit#gid=100135680)
  * A user is not required to log in to access content
* Sites with a poor experience have been flagged for 2nd opinion
* Bugs logged
* All above details have been filled out in the [spreadsheet](https://docs.google.com/spreadsheets/d/1uuYQzG5RZKeB1UIdVXiPIacumJb3NN_YA_plKLF0nBA/edit#gid=1339469566)
* MVP sites for the category has been confirmed (reach out to Ashley for help)

**Comment by Baron-Severin** [comment]
It seems that these are all being done concurrently by multiple people, so I'm dropping my assignment.
