### ISSUE TITLE
[1630] Reduce Pocket foreground fetch interval to conserve resources

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2187]
Break-out from #2123. This issue is a nice to have with Pocket channels.

### Why/User Benefit/User Problem
The Pocket server updates content every 6 hours with one video (i.e. 4 a day) but we update every 45 minutes while the app is foregrounded, which is wasteful for our user's bandwidth and our server bandwidth.

### What / Requirements
- [ ] Change update interval to a reasonable value
  - A little more than 6 hours? That's mostly optimal from a resource perspective.
  - Every 4 hours? That way a user doesn't have to wait as long to get content (but 6 hours is already so long - is waiting 4 hours in the background really different from waiting 6?)
- [ ] Specify update interval as a constant so it's easy to change

### Acceptance Criteria (how do I know when I’m done?)

**Comment by dnarcese** [comment]
We removed foreground fetch.
