### ISSUE TITLE
Address release blocker styling on channels

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2189]
_edit: we were unable to finish all the work here so we repurposed this to only address the release blocker issues. We moved the remaining work into a separate bug: #2208_

Channel styling needs to be updated.

- [x] Spacing between tiles, Pocket, toolbar
- [x] Font styling
- [x] Tile sizes
- [x] Double-check start/end margins of tiles, pocket, etc.

**Comment by Baron-Severin** [comment]
Mock: https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/

**Comment by mcomella** [comment]
Closed with merge of #2207.
