### ISSUE TITLE
DIFF_CALLBACK is unexpectedly public

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2190]
### Vision statement / What / Requirements
https://github.com/mozilla-mobile/firefox-tv/blob/5d4e8c635f104f064493887669a48a83b1a76f58/app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/channels/DefaultChannelAdapter.kt#L19-L23

### Impact
Annoying but not a huge blocker. Trivial to fix.

**Comment by athomasmoz** [comment]
Closing as lower priority. May fix in future if in the area.
