### ISSUE TITLE
Add News Sites to Homescreen

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2196]
### Why/User Benefit/User Problem

As a Firefox for Fire TV user, I want more media sites on the home screen, so I know where to find content & can easily navigate to it

### Acceptance Criteria (how do I know when I’m done?)

* News channel added to home screen for EN-US that includes:
  * Title: "News & Politics" (confirmed with content team)
  * [List of MVP sites](https://docs.google.com/spreadsheets/d/1uuYQzG5RZKeB1UIdVXiPIacumJb3NN_YA_plKLF0nBA/edit#gid=1339469566)
  * Each site has a tile image (logos provided here: https://github.com/mozilla-mobile/firefox-tv/issues/2209#issuecomment-492082424 )
  * Implement telemetry according to spec: #2262 
* Channel matches the design of pinned sites
* Sites within the category can be removed (channel will be removed if all tiles removed)
* Telemetry added for each tile
* Category is hidden behind experiment #2320

**Comment by liuche** [comment]
Same as #2195, these probably don't need to be localized but we can do so anyway. 

We'll be getting these finalized strings on Wednesday, from the Content team.

**Comment by athomasmoz** [comment]
Rolled into #2195
