### ISSUE TITLE
Pinned tile channel should order YT, Google, Custom tiles, Remaining bundled tiles

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2202]
### Vision statement / What / Requirements
In the new single row pinned tile channel, newly added tiles will be added to the end of the list. However, since there are more bundled tiles than there are spaces, these will be added off-screen. There are two issues:
- Users can't find their custom pinned tiles
- It takes many clicks to access pinned tiles

Requirements:
- [ ] Reorder pinned tiles channel to YT, Google search, Custom, Remaining bundled
- [ ] Verify adding tiles adds to the custom section
- [ ] Verify removing a tile of each category works correctly
  - [ ] Verify removing all tiles works correctly

**Comment by mcomella** [comment]
Makes sense to me.

> Idea: should the tiles be ordered by most recently visited?

Interesting idea: maybe we should create a follow-up issue to discuss this? I don't think we should address it now :)
