### ISSUE TITLE
[1630] Style channels to mocks

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2208]
Follow-up to #2189, where we implemented the bare minimum styling to ship the home tiles. This bug is to do the rest. This issue is blocked on gathering UX requirements #2209.

### Why/User Benefit/User Problem
If the homescreen is not delightful and usable, users won't like it. To solve these problems, we should style the homescreen to match the mocks: https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/

### What / Requirements
- [ ] Move channel title text to sit beneath the card
  - [ ] Verify settings title text styling matches the DefaultChannel styling
  - Blocked on mocks
- [ ] Update channel tiles image sizing (e.g. does bundled fill the card? What do screenshots do?)
  - Blocked on mocks
- [ ] Style pocket description text according to [the mock](https://user-images.githubusercontent.com/51007/57002885-b697e900-6c16-11e9-9b59-6aa6c8f4670c.png)
  - Note: this is if Pocket has landed. **We should decide which bug will address this before working on this bug**

**Comment by brampitoyo** [comment]
@mcomella @liuche 

> Move channel title text to sit beneath the card

We want title title text to sit beneath the card, only on these channels:

1. Pocket editor’s choice
2. Pinned tiles
3. Settings

On other channels (News & politics, Sports & health, etc.), the SVG logo is enough to spell out the name of each tile.

-----

> Update channel tiles image sizing (e.g. does bundled fill the card? What do screenshots do?)

@mcomella and I talked about this last week, but we haven’t set a guidelines for how to properly centre SVG logos inside a tile. I’m going to do this below.

There are two parts to image sizing in channel tiles:

1. Fitting the logo
2. Tile background colour

### Fitting the logo

**Mockup: https://codepen.io/brampitoyo/pen/MdvVed**

To fit the logo inside each tile, I’ve considered a couple of formulas and decided on a simple approach:

1. Set a separate `width: 84%` and `height: 62%` value for the logo, in proportion to tile size
2. Use `object-fit: contain`

This ensures that our tiles can accommodate long and narrow logos (e.g. The New York Times, The Wall Street Journal, etc.), square-ish logos (e.g. NFL, NHL, CNN, Pinterest), and every size inbetween.

The only tile size we use today is the second row from the top: 193.5×108px. However, the mockup also shows you how how the logo inside still fits well no matter how large the tile is (maybe it looks too large on `xlarge` size?). It also shows you how different tiles are designed to align vertically with each other.

### Tile background colour

When you go inside the `Site Logos` asset folder, you’ll see that each SVG file is named and has a hex colour value.

<img width="284" alt="Screen Shot 2019-05-20 at 2 04 52 PM" src="https://user-images.githubusercontent.com/51007/57992452-5eaf1c80-7b08-11e9-921e-7a521e91b5c9.png">

This is the colour value we should use for the background of each tile.

-----

> Style pocket description text according to the mock

The mock that we should follow is:
https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/#artboard1

**Comment by athomasmoz** [comment]
This ticket was finished by #2280
