### ISSUE TITLE
"Pinned Tiles" heading and "Clear Now" button is localized on DE and Zh-CN only

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2219]
## Steps to reproduce
Run Firefox-TV on a locales such as ES, FR, IT, JP

### Expected behavior
All texts are localized

### Actual behavior
The "Pinned Tiles" heading on the main view and "Clear Now" button under "Clear All Cookies" menu is still in English

### Device information
* Fire TV device: 4K Stick
* Latest affected Firefox version: 3.9 LAT 
* Earliest affected Firefox version: 3.9 LAT
![home-screen_1557379925370](https://user-images.githubusercontent.com/6930774/57460737-b1085780-7243-11e9-93f4-6437c36732b0.png)
![clear-all-data_1557379980786](https://user-images.githubusercontent.com/6930774/57460787-c8474500-7243-11e9-9d79-a5b2ec1aba8d.png)

**Comment by dnarcese** [comment]
These translations should be included in #2216. I'll make sure to add that PR to the release!

**Comment by athomasmoz** [comment]
Thanks @dnarcese , marking as release blocker and adding to sprint

**Comment by npark-mozilla** [comment]
With the today's latest import, other locales seem to show correctly, but JP still shows English for both the heading and button.

**Comment by liuche** [comment]
Looks like we're still waiting on JA to be fully translated: https://pontoon.mozilla.org/ja/firefox-for-fire-tv/

**Comment by dnarcese** [comment]
JA got translated in #2304
