### ISSUE TITLE
[1630] Update Sumo articles related to Pocket and homescreen

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2222]
Sumo articles related to Pocket and homescreen should be updated to reflect the changes in #1630

**Comment by mcomella** [comment]
I don't see any changes that need to be made though Pocket/homescreen functionality is limited to this line: "Easily discover and watch videos from YouTube, Pocket (now part of Mozilla) and other popular sites from the home screen.". There are no screenshots so there are no screenshots to update. Closing.
