### ISSUE TITLE
Only Mobile version of YouTube can be accessed after deleting all the Tiles

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2225]
## Steps to reproduce
1. Launch Firefox.
2. Access the Tile section.
3. Select and delete every single Tile.
4. Select the URL bar and access YouTube.
### Expected behavior
YouTube is opened correctly and not with the mobile interface.
### Actual behavior
YouTube is opened with the mobile interface if there are no Tiles available.
### Device information
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`Firefox TV v3.9 LAT2`**
* Earliest affected Firefox version: **`Firefox TV v3.8`**
### Notes
For more details please see the attachments: 
[logcat2.txt](https://github.com/mozilla-mobile/firefox-tv/files/3165359/logcat2.txt) and [video](https://drive.google.com/file/d/1vOkJpMWgZRRAZ1P2mvLYBgLqpj0zA4tB/view?usp=sharing)

**Comment by npark-mozilla** [comment]
@abodea Are you accessing YouTube's TV url?  (e.g. www.youtube.com/tv)  The std URL will take you to the regular YT page

**Comment by abodea** [comment]
On the URL bar, I typed: **`www.youtube.com`** because this was from autocomplete.
Maybe a user will not stay to type all the URL(www.youtube.com/tv) and just access the link without /tv that is recommended.
I can confirm that If I type **`www.youtube.com/tv`** it takes me to the regular YT page but without is only mobile YT.

**Comment by npark-mozilla** [comment]
Thanks, yes that is by design, and YT tile exists for that reason. In any case where #2224 happens, the user would run into this issue. and as @abodea suggests, it might be a good idea to add `/tv` as autocomplete youtube url, it might be a good feature.'
