### ISSUE TITLE
Add way to display a channel for only a specific locale

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2233]
### Why/User Benefit/User Problem

As an FFTV developer, I want a simple way to configure channels to be shown for only specific locales, since some channels of items may only be relevant to certain locales

### Acceptance Criteria (how do I know when I’m done?)

* For each channel, the developer can decide whether it will displayed to all locales, or only specific ones
* Add tests to make sure this won't break if shown/not shown

### Notes

Note: when we remove bundled tiles, we have to consider that non-en-US locales will not have access to the new channels.

I wonder if we should have a config file (DSL?) or something... 

Most importantly, keep it simple. :)

**Comment by liuche** [comment]
This somewhat depends on having another channel built (such as #2196) but what applies to Pocket stories (which is also en-US only) can also be generalized here to be used on any channels.

At some point, we may want to be able to support different locales (e.g. Set X of channels is en-US while Set Y is es-ES) but that's not necessary in this bug.

**Comment by liuche** [comment]
Right now, we are starting with en-US, but the next time we start picking sites, we'll need to handle different channels/sites later.

**Comment by mcomella** [comment]
@liuche I say we close this: if it's important to fix later (e.g. when adding a new supported locale), we'll identify this requirement then and open a new, more relevant issue.

**Comment by liuche** [comment]
Okay - closing a bug is fine, we can always reopen it.
