### ISSUE TITLE
Q2 Sprint 4: UX mocks centralization

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2238]
All the mocks for this sprint should be placed in this bug: this is to solve the problem for developers where the mocks to address a specific bit of engineering work are difficult to find. See https://github.com/mozilla-mobile/firefox-tv/issues/759#issue-311393555 for some prior art.

## Mocks

* https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/
* https://codepen.io/brampitoyo/pen/MdvVed

## Logo assets

* SVG: https://drive.google.com/drive/folders/12112POKFlky5JW9TIPejFr9EpMg5JepQ?usp=sharing
* PNG: https://drive.google.com/drive/folders/16f4ieORIlkYyApAnb9-1d8ev2yyQ15kT?usp=sharing

## Onboarding

![Homescreen - onboarding@2x](https://user-images.githubusercontent.com/51007/58397467-3ba2e080-80a5-11e9-875c-b1245108a250.png)

The copy for this screen, and the final image for when it’s completed, can be seen on #2318.

## URL and toolbar

![Homescreen - focus URL bar@2x](https://user-images.githubusercontent.com/51007/58397369-c3d4b600-80a4-11e9-8208-fc297f3729ba.png)

## Pocket editor’s choice

<img width="330" src="https://user-images.githubusercontent.com/51007/58397376-c8996a00-80a4-11e9-9231-bb470c6293c2.png"> <img width="330" src="https://user-images.githubusercontent.com/51007/58397377-c9ca9700-80a4-11e9-8c31-f11aa400923c.png">

The copy below the Pocket channel title can be seen on #2179.

Each Pocket video contains:

* A small title that describes where the video comes from
* A video description

The behaviour when focusing on the last (rightmost) item is consistent between Pocket, Pinned sites, and all other channels.

## Pinned sites

![Homescreen - focus Pinned tile 1@2x](https://user-images.githubusercontent.com/51007/57743144-0e0a7e80-7718-11e9-9369-5d4deefdc7b6.png)

Each pinned site has:

* A title
* Either an SVG logo, or a placeholder letter

Pinned site needs to be vertically positioned at the centre of the screen. **Whenever any channel needs to be vertically centred, it will have a 116dp padding to the top of the screen**.

## Other channels

Sites belonging to other channels have an SVG logo, but no title.

![Homescreen - focus News   politics tile 1@2x](https://user-images.githubusercontent.com/51007/57743418-1911de80-7719-11e9-9ed5-5ecaa55f8367.png)

Other channels are vertically centred.

### Positioning of 2nd-to-last and last channels

3rd-to-last channel is still vertically centred.

![Homescreen - focus Sports   health tile 1@2x](https://user-images.githubusercontent.com/51007/57744190-4f049200-771c-11e9-8eca-7b99d2602391.png)

2rd-to-last and last channels aren’t vertically centred. They are pinned to the bottom of the screen.

<img width="330" src="https://user-images.githubusercontent.com/51007/57744215-6fcce780-771c-11e9-8680-2186b3e5ca0e.png"> <img width="330" src="https://user-images.githubusercontent.com/51007/57744216-722f4180-771c-11e9-9d15-9bad9ed07c90.png">

**Comment by brampitoyo** [comment]
Added Codepen mockup. See https://github.com/mozilla-mobile/firefox-tv/issues/2208#issuecomment-493816614 for explanation of logo fitting and channel background colour.

**Comment by brampitoyo** [comment]
* Added an onboarding screen for the new homescreen
* Updated Pocket editor’s choice with new inline channel description

The link to the mockup stays the same.

**Comment by mcomella** [comment]
@athomasmoz Should we close this? Does the information in this bug need to be moved to a different place?
