### ISSUE TITLE
Pocket, channels, onboarding: add tests to ensure layout is correct in en-US and non-en-US locales

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2239]
### Vision statement / What / Requirements
In en-US, we have Pocket and the new channels. In non-en-US, we have neither of those. We should make sure these other locales appear as expected through testing.

### Impact
We can feel certain that our homescreen looks and acts correctly in each locale.

### Acceptance criteria
- We have a test in place each sprint (manual via TestRail, automated UI test, or otherwise) to ensure the homescreen is configured as expected (see requirements above)
- We have a test in place to ensure the homescreen looks correct (e.g. padding between channels is correct)
- We have a test in place to ensure the homescreen functions correctly (especially focus changes)

---

@npark-mozilla Is there already a TestRail test for testing on different locales? Are testers aware how each locale should look or do we have to respec the requirements? I think that'd be the lightest weight option here.

**Comment by npark-mozilla** [comment]
@mcomella We currently don't have test cases that require the tester to switch to a different locale.  Partly it is taken care of by the l10n screenshots.  @abodea we should add test cases where it is non EN-US locale, then both Pocket and the (future) category pinned tile should not be visible, and I think that would be sufficient?

**Comment by athomasmoz** [comment]
@npark-mozilla or @abodea we have a few items that are locale-specific now. Can you help us to add in testRail cases for these? Specifically,
- Pocket should be EN only
- TV Guide should be EN-US only

**Comment by abodea** [comment]
Hi @athomasmoz I have created the test cases 1-2 months ago, you can find them [here](https://testrail.stage.mozaws.net/index.php?/suites/view/2564&group_by=cases:section_id&group_order=asc) under the **`Pocket EN locale only`** section.

### Also, I did a testing once with all the locales available here are the results: 
- **English(US) --> Espanol(Mexico) - pocket disappeared** ✔️
- **Espanol(Mexico) --> English(US) - pcoket appeared** ✔️
- **English(US) --> Espanol(Espana) - pocket disappeared** ✔️
- **Espanol(Espana) --> English(US) - pcoket appeared** ✔️
- **English(US) --> Francais(Canada)- pocket disappeared** ✔️
- **Francais(Canada)--> English(US)- pcoket appeared** ✔️
- **English(US) --> Francais(France)- pcoket disappeared** ✔️
- **Francais(France)--> English(US) - pcoket appeared** ✔️
- **English(US) --> Deutsch(Deutschland) - pocket disappeared** ✔️
- **Deutsch(Deutschland) --> English(US) - pcoket appeared** ✔️
- **English(US) --> Deutsch(Osterreich) - pocket disappeared** ✔️
- **Deutsch(Osterreich) --> English(US) - pocket appeared** ✔️
- **English(US) --> Italiano(Italia) - pocket disappeared** ✔️
- **Italiano(Italia) - English(US)   - pocket appeared** ✔️
- **English(US) --> 日本人(JP) - pocket disappeared** ✔️
- **日本人(JP) - English(US)   - pocket appeared** ✔️
 
Also, I have created 2 new test cases for the **`TV Guide EN-US only`** that can be found [here](https://testrail.stage.mozaws.net/index.php?/suites/view/2564&group_by=cases:section_id&group_order=asc&group_id=50045).
Both sections are added in a Folder called `Locales Testing` containing specifically the **`Pocket`** and **`TV Guide channels`** test cases.
For **`Basic Functional Tests`** and **`FFTV Lite`** test suites.

**Comment by athomasmoz** [comment]
Sounds perfect, thank you! I'll close this for now, but hopefully it's something we can automate in the future to avoid the extra manual testing effort
