### ISSUE TITLE
Menu open/closed telemetry is not collected anymore

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2240]
## Steps to reproduce
Felix is looking at our telemetry and noticed that we are not collecting menu clicks anymore. This is problematic bc we need this telemetry for #2011 .

### Expected behavior
Collect telemetry when users click menu button

### Actual behavior
Telemetry method for menu click is unused

### Device information
* Fire TV device: all
* Latest affected Firefox version: 3.8
* Earliest affected Firefox version: 3.6

**Comment by mcomella** [comment]
To be explicit, we want to collect:
1. Menu is opened by menu key
1. Menu is closed without taking explicit action (e.g. no tile clicked, back not pressed, etc.)

To do this, from [our telemetry docs](https://github.com/mozilla-mobile/firefox-tv/blob/a1b01e8ab654dad831bb9f0c4c61403ea9ee971a/docs/telemetry.md), we wanted to:
- Fix "Menu shown by user" to represent 1.
- Fix "No menu action taken" to represent 2
  - This is currently broken on master: it gets called every time the WebView is focused and SELECT is pressed
- Remove "Menu hidden by user", which is redundant to the "No menu action taken" action

**We should also document this situation in our telemetry docs.**

**Comment by mcomella** [comment]
I landed the initial work to uplift in https://github.com/mozilla-mobile/firefox-tv/pull/2250. As per the comment in the PR, I plan to land another PR, that will not be uplifted, to add additional tests and clean-up.

**Comment by mcomella** [comment]
We merged to master and uplifted to release: leaving this open to add additional tests.

**Comment by liuche** [comment]
@mcomella is this still size S including tests?

**Comment by mcomella** [comment]
> @mcomella is this still size S including tests?

Yes, I intend to timebox it as such.

**Comment by mcomella** [comment]
The release blocking and urgent parts of this issue have been landed.
