### ISSUE TITLE
Consider adding regression tests for our telemetry events

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2253]
### Vision statement / What / Requirements
The accuracy of our telemetry data is vitally important because we rely on it to make product decisions. However, they are fairly easy to break these probes:
- There is no visual impact to the user so it's easy to forget to test when making changes
- It's time consuming to test: to understand the requirements & constraints of each probe in theory, to figure out how to test it in practice, and then to actually do it
- Adding new UI functionality may break probes (e.g. if there's an "overlay closed" event and we add the Pocket megatile, it may get sent for opening the megatile, even if that's not in the spirit of the probe)
- We have no testing beyond manual dev testing at the time of implementation, and if a dev thinks to test it later

These probes are important so we should consider adding regular testing of our telemetry probes, at least the ones that are most important to us for a given release.

### Impact
Without tests, our probes may break and we may not notice. This could result in:
- Inability to make decisions (when probe data is unexpectedly missing)
- Inaccuracy of decisions (when probe data is incorrect)

### Acceptance criteria
- [ ] Identified plan for testing telemetry events
  - [ ] Collaborated with QA to come up with ideal plan
  - [ ] Communicated plan to team & team agrees
- [ ] Implement plan

---

We previously discussed ways to test telemetry probes in #625 and determined we'd just write unit tests for them. However, writing these tests are hard so we haven't really been doing it.

Some possible solutions (consider combining them):
- Expose telemetry to QA (e.g. #1522, or log statements?) and add to TestRail
- Add unit tests: given telemetry occurs from UI events and it's hard to test UI this way, these are hard to write to guarantee even mostly-correctness. However, writing these tests will catch at least some errors and will help us write better designed telemetry code
- Add UI tests: these most closely test the user flows but take a long time to write and are hard to maintain
- Move telemetry probe recording into our architecture: this will decouple our probes from the framework, making it easier to identify their correctness in code and making it easier to test. The code to transfer the UI events into our app will likely remain untested, however (it's really hard to test this).

My initial intuition (i.e. should be thought through more) says we should:
- use TestRail to check our most important probes per sprint (to cover UI)
- See how hard it is to move telemetry probe recording into our architecture (move one probe to find out?). If it's easy, make it the best practice for new probes. If it's hard, forget it
- Ensure there are unit tests for our most important probes per sprint (to build up coverage of telemetry probes)
- Heavily encourage unit tests for all new telemetry probes (to build up coverage of telemetry probes; encourage better design of telemetry probes so they're less likely to break; encourage devs to think through all existing UI flows to verify probe correctness)

**Comment by athomasmoz** [comment]
Once we switch to Glean, we can manually test the events we care about.

**Comment by mcomella** [comment]
> Once we switch to Glean, we can manually test the events we care about.

^ It sounds like we don't need a long-standing bug for this.
