### ISSUE TITLE
Stop updating Pocket in the background if users are inactive

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2261]
Follow-up to #2223.

### Why/User Benefit/User Problem
In #2223, we plan to update Pocket nightly for all installed users. However, this is wasteful for users, and our servers, if they're inactive. We should conditionally update for users in the background based on whether they're inactive or not.

This is split from #2223 to simplify the engineering requirements of #2223.

### Acceptance Criteria (how do I know when I’m done?)
- [ ] Talk with UX to define inactive (app has not been foreground in one month? Two weeks?)
- [ ] Users who are inactive do not receive background Pocket updates
- [ ] Users who are active receive background Pocket updates

**Comment by dnarcese** [comment]
Solved in #2305. Pocket content gets updated nightly if the user opens the app. So inactive users will not receive an update until they use the app again.
