### ISSUE TITLE
[1630] Implement telemetry requirements for new homescreen tiles

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2262]
### Vision statement / What / Requirements
We're implementing new homescreen tiles this sprint but we never specified what the telemetry should look like: this bug is to define it, and implement it in the channels.

### Impact
Without defining telemetry, we:
- May receive no telemetry on the new channels
- May receive telemetry on the new channels that is not helpful
- May receive telemetry that skews existing channels

@Baron-Severin Do you know how the current implementation will send telemetry for newly added default channels?

### Acceptance criteria
- [ ] Same telemetry for new tiles as the Pinned tiles (tile name + number of clicks, we don't have custom tiles to worry about here)
- [ ] Verify pinned tile telemetry is working as described ^
- [x] We decided not to add new telemetry (like channel item focus/impressions vs just clicks)
- [ ] ~~If 2, product has defined telemetry requirements for new homescreen channels~~
- [ ] ~~If 2, engineering has implemented, or verified, behavior of new homescreen channels telemetry~~

**Comment by athomasmoz** [comment]
This blocks our stories to add the new tiles.

**Comment by liuche** [comment]
@athomasmoz I updated the Acceptance Criteria here, and I made a note of "what we are not doing in this bug" - @mcomella had suggested some alternative focus/impression criteria, but we won't add that if we want to keep the telemetry the same (for simplicity).

**Comment by liuche** [comment]
Updated this bug title to be "Implement/Verify telemetry requirements for new channels". However, since we don't have a channel yet, I think this is blocked, but I will reference it in the News and Sports issues.

**Comment by athomasmoz** [comment]
@liuche I'm a bit confused by this one. I thought this was blocking the stories to add new channels?

**Comment by liuche** [comment]
@athomasmoz I talked to @mcomella to clear this up - the requirement of this bug was simply "Define the requirements for Channel Telemetry" and now that we have that in the "Acceptance Criteria" and I've linked it to all the bugs, this bug should be done! So closing.
