### ISSUE TITLE
Track Distractions (Q2SP4)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2263]
### Vision statement / What / Requirements
See #2126 for example.

**Comment by mcomella** [comment]
I spent ~45min writing up, thinking through, and discussing [an SVG perf test ticket](https://github.com/mozilla-mobile/firefox-tv/issues/2260) that could have blocked work this sprint but we decided to not worry about.

**Comment by mcomella** [comment]
I moved https://github.com/mozilla-mobile/firefox-tv/issues/2209 (gather UX requirements) into the sprint because it wasn't in the sprint for some reason but it's blocking and I'm working on it.

**Comment by mcomella** [comment]
I spent ~45min thinking through alternative approaches to our Pocket update strategy (which could replace the strategy in #2223, which is in the sprint) but these were unused. I documented them https://github.com/mozilla-mobile/firefox-tv/issues/2255#issuecomment-492418494 but that issue is not in the current sprint.

**Comment by Baron-Severin** [comment]
I spent ~1 hour on Friday helping to fix a Fenix bug.

**Comment by mcomella** [comment]
I spent ~15min removing some no longer necessary code, `forceExhaustive`: https://github.com/mozilla-mobile/firefox-tv/pull/2303 I would normally have done this as part of another PR but those PRs were getting too large to do comfortably.
