### ISSUE TITLE
Nytimes settings menu cannot be scrolled and cannot access all the sections

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2268]
## Steps to reproduce
1. Launch Firefox.
2. Access **`www.Nytimes.com`**.
3. On the left top corner tap on the `hamburger` menu.
4. Wait until the options are displayed.
### Expected behavior
All the options are displayed with extra categories and the section is scrollable. 
### Actual behavior
Only 50% of the sections are displayed and the scroll is not working when reaching the bottom of the page.
### Device information
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`Firefox TV v3.9 LAT2`**
* Earliest affected Firefox version:  **`Firefox TV v3.8`**
### Notes
For more details please see the attachments: [video](https://drive.google.com/file/d/152UxzemHL9fwaJOxH2FW_QtR9NFvl9TC/view?usp=sharing) and [Logcat.txt](https://github.com/mozilla-mobile/firefox-tv/files/3182143/Logcat.txt)

**Comment by athomasmoz** [comment]
What's the landing page we want to link to? I see in the spreadsheet it says https://www.nytimes.com/video , but I get a secure connection failed error when I go directly to that. I'm wondering if users need this menu to get to the video section

**Comment by abodea** [comment]
Hello @athomasmoz yes I used `www.nytimes.com` as for the `www.nytimes.com/videos` i received the error you mentioned, I also updated this bug #2269 as we can used it a general one for the errors.
Note that the options I got on normal www.nytimes.com are working but there are a lot of them missing.

**Comment by mcomella** [comment]
I wonder if this is because we can't scroll within iframes: #278.
