### ISSUE TITLE
The CNN.com cannot be accessed as the "Secure connection Failed" error is returned

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2269]
## Steps to reproduce
1. Launch Firefox.
2. Select and access the URL bar.
3. Type any of **`www.cnn.com, https://us.cnn.com/videos`**.
4. Access the urls mentioned in step 3.
### Expected behavior
CNN website is loaded and no issues are displayed.
### Actual behavior
The `Secure Connection Failed` is returned when trying to access CNN. Video eventually plays, then runs into issues about 1 min in.
### Device information
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`Firefox TV v3.9 LAT2`**
* Earliest affected Firefox version:  **`Firefox TV v3.8`**
### Notes
Sometimes when clicking on the `Try Again` button from the returned error a white screen will be displayed and the browser will be stuck in that screen.
For more information please check the attachments: 
[logcat.txt](https://github.com/mozilla-mobile/firefox-tv/files/3182514/logcat.txt) and [video](https://drive.google.com/file/d/1nmKHCcufp9wFOgjRKRXiLzRqXxwrIPUG/view?usp=sharing)

**Comment by abodea** [comment]
Hello note that I was able to reproduce this issue with the **`www.nytimes/videos`** too, the site almost loaded but in the very end I received the **`secure connection failed`** error.

**Comment by athomasmoz** [comment]
Rolled into #2343
