### ISSUE TITLE
FFTV crashes when trying to play any video from "https://archive.org/" on a specific device

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2271]
## Steps to reproduce
1. Launch Firefox.
2. Access https://archive.org/ website.
3. Select and play any video from archive.org.

### Expected behavior
The video start playing and no issues are displayed.
### Actual behavior
FFTV crashes when trying to play a video.
### Device information
* Fire TV device: **`Fire Stick 2nd gen - Fire OS 6.2.5.8(NS6258/1607) // Fire TV Home version 6.1.3.0-267`**
* Latest affected Firefox version: **`Firefox TV v3.9 LAT2`**
* Earliest affected Firefox version:  **`Firefox TV v3.8`**

### Note
I think this issue is a related to a specific device as I was able to reproduce it only on this **`Fire Stick 2nd gen - Fire OS 6.2.5.8(NS6258/1607) // Fire TV Home version 6.1.3.0-267`** device but I wasn't able to reproduce it on this device **`Fire OS 5.2.6.9(632552020) - Fire TV Home Version 6.1.5.1-002`**
For more details please see the attachments below: 
[Archive .org.txt](https://github.com/mozilla-mobile/firefox-tv/files/3182661/Archive.org.txt) and [video](https://drive.google.com/file/d/1XgH0Uv6orZvOa3qX_YfulZFfxiui5DOm/view?usp=sharing)

**Comment by liuche** [comment]
Duping this to #2287
