### ISSUE TITLE
Consolidate doc files into wiki

### ISSUE THREAD

**Issue by devinreams** [mozilla-mobile/firefox-tv#2273]
Since the majority of our docs are in the Wiki, and its more accessible for more people to create/update, I propose:

- [x] moving our `/docs` material into the Wiki (for consolidation), and
- [x] updating the `/docs` to have a README.md pointing to the Wiki (for discoverability)
- [ ] search for links to the existing docs and update them

**Comment by devinreams** [comment]
After thinking about it more, I think the only thing that may be worth moving is the Telemetry doc and keep the ADRs where they are (close to the code for architecture decisions/code context).

But I also see the Telemetry doc was intentionally moved into the code. I wonder if @mcomella can provide [more context as to why](https://github.com/mozilla-mobile/firefox-tv/wiki/Telemetry/_history) and which location makes most sense (I still think Wiki given how we're using it now).

Quick PR started here at least to have a pointer for newcomers expecting more docs in the docs directory: 2275

**Comment by liuche** [comment]
Telemetry doc in the code is helpful so that a PR adding/changing a telemetry probe is required to also include the documentation changes.

**Comment by mcomella** [comment]
> Telemetry doc in the code is helpful so that a PR adding/changing a telemetry probe is required to also include the documentation changes.

Right – thanks for checking the history, btw. Here's [my original mailing list proposal to move it](https://groups.google.com/a/mozilla.com/d/msg/firefox-tv/etuG0-m5zCk/fai78nq_AQAJ). Basically, it says:
- Telemetry doc updates need to be reviewed so there are no mistakes
- (haven't done this in practice) Telemetry docs are versioned so, if we wanted to see what probes exist in the v3.8 release, we could check out that revision and open the telemetry doc file
- Contributors & non-team employees can edit docs/ in-tree by opening a PR but can't write to the wiki which requires GH write access (which allows writing to the source tree so we don't want to give access willy nilly)

It's worth noting that this won't matter with glean, which will generate docs for us.
