### ISSUE TITLE
UX: Receiving a Tab

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2277]
### Why/User Benefit/User Problem

I've found a video on my phone and want to play it through my TV, so that I can see it on the big screen while I continue browsing on my phone

### Acceptance Criteria

* User can send a tab to their TV
* User can go back & forward through their history stack after sending a tab, and that tab will be included
  * Should we show a hint to let users know this?

### Output

* Documented user flow for sending & receiving a tab
* Mocks for each step in the flow ready for engineering to start implementation on
* Finalized ~~localized~~ strings

### Not Included

* Log in (covered in #2279 
* Sending multiple tabs (consideration for future, but not part of this ticket)

**Comment by liuche** [comment]
Mocks have been created.
