### ISSUE TITLE
UX: Promoting Send Tab

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2278]
### Why/User Benefit/User Problem

As a Firefox for Fire TV user, I want to be notified about the ability to send a tab to my TV, so that I can start doing discovery on my phone and just watching the end content on my TV

### Acceptance Criteria (how do I know when I’m done?)

* New & existing users are informed about the ability to send a tab
* New & existing users can find information about how to send a tab
* Users warned before logging in that send tab only works from desktop, iOS, Fenix (so Fennec users don't log in and then can't use it)
- [ ] get copy + update copy/icon once Fenix ships
* Notification does not interrupt user when viewing content - this will be UI not a notification

### User Requirements

* Design in place to make users aware of send tab feature
* Finalized ~~localized~~ strings in place

**Comment by liuche** [comment]
Entry points:
* Sign in
* maybe a Pinned Tile with "get tab from phone/laptop"/"Send tab from another device"

**Comment by liuche** [comment]
Mocks have been created.
