### ISSUE TITLE
UX: Account Log in

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2279]
### Vision

As an FFTV user, I want to log in to my Firefox account so that I can send a tab to my TV from another device

### Acceptance Criteria

* User can trigger log in flow
* User can enter username and password
* Mistakes/incorrect username/password can be resolved (FxA web flow would handle this, but if we need more improvements we need to ask for them from the FxA team to optimize the web flow for TV).
* User can log out

### Output 

* Documented user flow for logging in
* Mocks for each step in the log in flow ready for engineers to start implementation against
* Finalized localized strings

### Not included

* Sign up for account
* Forgot username/password step. Although maybe we want to hint that this should be done through phone or laptop?

**Comment by athomasmoz** [comment]
@brampitoyo heads up, I just filled out all the details for this ticket. Let me know if you want to review on Tuesday

**Comment by liuche** [comment]
@brampitoyo will take the FxA pairing web flow and make some mockups for ways to "optimize for TV" (e.g. using dpad).

**Comment by liuche** [comment]
Mocks have been created.
