### ISSUE TITLE
Update Channel design to Match Mocks

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2281]
### Vision statement / What / Requirements

The current implementation doesn't match the mocks, which were created to provide the best experience for users and match the overall channels design. This ticket is to update our channels (pinned tiles and site categories) to match those [mocks](https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/#artboard1)

### Impact

* Improved User Experience
* Consistency between channels

### Acceptance criteria

* The following updates have been made to the Pinned tiles & site category channels to match the mocks:

**Comment by brampitoyo** [comment]
While we will update the design of most existing Pinned Tiles to a ‘cinematic’ style…

<img width="194" src="https://lh5.googleusercontent.com/j8QhBs1TKypmk8EosUyZSGoTTQfryQ8Mm6Onw50lMfe7kk7a8ZsNRi5RmkImbnomI_K9a0w50ZY2ezEgMynS=w3360-h1862"> <img width="194" src="https://lh3.googleusercontent.com/MLn_WXsloDzOBkaAewKLmdwTUe1xJHQJHpAFDmv2tO9HcO0cmeXLT-MkPM1amN01xUrTHUsvmCJyBRuy87Yu2WcbGUkE9doSwU10zO0HOpdGa_7JqDLEBZC0m1Am-93wLY44s-4QvEgPaYMM873fl0WJ-JlPOOXHU1rEubRcBN8yD-W6aul8PrSav1X0mAZIAuX6nN2WAPFyHad0-8OPP7TkMnFOJqqHNZ6zo-WnXXqsJdX8tgrWtjVMFQLQfIg-0aZp-C7MbDAHNDNCW50saz1mLZ_hhHfkF9lIPVbndKg1LBiO7LWm1rAQr-w1LKSU-x4HdJePYZBdrAp2Ayupd3VSe4F3ipxgPd4uBAMj-ydKDTAgqps5gs2Hb6ywR-4DIdF7UctJ--1zR61E34DosvdQGvZ5hlD6jjljRRNicsmrG5FwGkujp_h1yruya3u_lpXe2SuRCBtIYWpTzzS9MFc8MHCJdOznjIUKx73h7zxhBJDWmVKojaNzNiL8sNavpNGxTOkfYQSa_4t3Bn6GU7cUelz7X7FKYpTpx1TjK1aUl-xqkmMdZPLEfHHcHwWInDEoMR3KYi41cEX6hkyLfQIZ-4KnjAbDNX0FQUE=w3360-h1862"> <img width="194" src="https://lh3.googleusercontent.com/jjZrQDrwbQ7DrQ4kEebYLpOfnerAXy6miLhi0TBrsBu2dN3IEHfCXFSL6t_4OEgmAYKYDpMqU9roW8QVFyZxrX2jzYLNSsYoD32pwdc7n1bt3l_4M85lfrgl94yP8bc138oaa3xuGyZVrrMh1_OavCe1ffOabd9S8VjZdHoAN1-QgBNZPUbwyRy7Ac6Vr7knAIS1WwiHtXm4rHhwoLuZXIrjlab9KJWMYYpTDpPduqW7hOwkloyu2xR46yFJgcnWjtNrvUKU0sdsU77kQNJpkJ2Y-6vu4VtUmNmy0uZBOmC6DB_ckqggdodMKB-lim-3uZ9Yg9qX3KnJA4Ce7G4TDYlPlirp8YcDKfp310LWv0nOGJ_dYmpEnx0s2qSgeOKV-NSuiBCBuRze3q_AS3aUtneU4jnzv-MGY14_zeH01acz4BkzUJSiBYduL1GUiIGy3cKeTs1akVEIH6yJj1SdL_eLP72fqtpnPaP-IxqKUwroPDWDZnon_BCBpz0X7TMNjiptyyAYH9KbbVxMA9g4p6qabdYp3VU0WqLKqoVlXBxpbtRjRrHNrVIISW-H9gNdvp2u839fzwU-F82dyhLtxWxnyxc625gwdRaVXwc=w3360-h1222"> <img width="194" src="https://lh3.googleusercontent.com/Ufz0iPSYFpyXxR88hGZLHaBO2GdtXzj-PdEW5QdN9q4acVjO-5aD_FjkMftC97AhHgZfw6F5IyGW7cSXAOBEolu1xTsGqMKckEPy7c5fO9HEnTutxRtkKWVidDC7CJNxEtVJF6Ttm551h1WnuwdtsYsERPSCFAWQl-C3Do1SauCA5s2oFvH79cP9yg2ZvELR3YosceJ6eyeeeVCb01fYeABTzAm_5clDee8_MmeXYgSQIJOjOeglbkep6vGNDeTB6WE9sus6pnpymxfZAdXDJCga_ASJUe9APo3Y18fybeEqPXSn74W_Ax4sjym9U4yu4p_bGMg5tdpPQxnGrJhwsUPD1o5gUlOSu9tFOHDDbUGSyUdnE4mQU6hELo70n6M_rV-SWUIEKCl_DGzHIF-jGIhFDLbA3G3DcPrMw6_nyBo8ArvCRI0LGORU2zXMj6OaEREHOVI-0fel29U70Ae16QlaAanrNCjLhxmyzC8-Rk2epVc-wTUQ-pr-rQdc8DBs7ztmUOPA35_J2bvHBmqVisdSQexm8MpHnFOVXgY1bjj1eUPSedx8a7fMJG9ioLs3lzang815HqZ1DZAvFssVQNO7NcpNCtvCvQFTbeI=w3360-h1222"> <img width="194" src="https://lh3.googleusercontent.com/XE3zR2fSCIuKLTVVK8S3imCwU6EPGaU2cHkSQnHXJNBwXURJXcW9UmNEEXeZOHjPFukKiLqfKZToT04sSNRbRkKz6--n_PLb6AwISQZD0GUxPVd_c5ek5sVs-uOwDRdxfTkE0x1UeKfYAXkdWbid3xA0-_lAVuJSE9HOvsAPeg-OrNXRAbU1S-8ubwzk-P1-YAIhSUUfxYAPVDuXNz4tfVJpq5yysfjLRyRqPiEASpNxfOyaie7flt7R2PnPwG_8gNOamdRiU6e6bAjYGAjnOIm1CSKnJVkHqw7Ia6VS3A371_0LtREMpkmaN-pOk7uquDgjkKQ877yQ61oONLFOc9dM6HHjQgp0pwGtRJEsPcovdyhrSbIhUesEYTkWvrxu12-qgKT0_UHLNaWVj_JtxvXONGfZUegLJAfKjMElLzTVggV_1JLDhWW4y60z10Qz4wOYlCsaEO_3dEApXPrbEKJhS0cOTyg5gD3cMNC0ZZ98IvmSIdtQRRiKAZaElXap213ZWnzGOnhkaOQG6nch5JpeLx2sXhjB_NM-qtv8EVhGNU5u_1c92zkfeBXNzyg2N9abPCZ37sRXeKx8XHUXA5SRM9sv6FC7CBN5PlA=w3360-h1222">

We will not update the design of the YouTube and Google Video Search tile. We will simply position the existing square logo in the middle of a white tile:

<img width="194" src="https://lh3.googleusercontent.com/1Faw0lpmaJ6BwlUJM8Z10am3UkuckyD_xCaroo7cwk1JSD3iCSh5jeZ3ujJW8Eq8Ejnq3C9GuWR58KNA4RXm=w3360-h1862"> <img width="194" src="https://lh6.googleusercontent.com/5kP7CM5jdzzOk_Y27S7DkUzLQRyM9X6ZAl1Xp-ddmKKpHEmBuiueP43GHIn-gSj4elS_05HUAvgAHSBvA9vu=w3360-h1862">

We will update the tile designs after approval from Google – but chances are, we won’t need to alter them.
