### ISSUE TITLE
Firefox crashes when trying to play videos on certain devices

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2287]
## Steps to reproduce
1. Launch Firefox.
2. Access https://mashable.com/videos/ (or archive.org)
3. Select and play any video from mashable.com/videos.

### Expected behavior
The video start playing and no issues are displayed.
### Actual behavior
FFTV crashes when trying to play a video.
### Device information 
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`Firefox TV v3.10 LAT1`**
* Earliest affected Firefox version: **`Firefox TV v3.9`**
### Notes
For more details please see the attachments: [Logcat_Mashable.txt](https://github.com/mozilla-mobile/firefox-tv/files/3187624/Logcat_Mashable.txt) and [video](https://drive.google.com/file/d/1OLMmfS_nC8x0Ss8YvF7Iyq8vln-tTfKk/view?usp=sharing)

**Comment by mcomella** [comment]
I can no longer reproduce: this was probably fixed with the upgrade to Chromium 70. Though video playback performance is now poor: we can address that elsewhere (probably in some meta).
