### ISSUE TITLE
Pocket onboarding unexpectedly shown in non en-US locales

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2293]
## Steps to reproduce
- In Android emulator, Settings -> Languages -> change language (I used Korean)
- Clear app data (which should force stop): adb shell pm clear org.mozilla.tv.firefox.debug
- Open application
- Click through turbo mode onboarding

### Expected behavior
Pocket onboarding not shown

### Actual behavior
Pocket onboarding shown.

Note: the Pocket channel hides as expected.

### Device information
* Fire TV device: emulator
* Latest affected Firefox version: master 05e595355d26dc4047ec9a9dc614075dfcd6dfe2
* Earliest affected Firefox version: ?

Please add a regression test: we don't test this code path often and we need to know it's working (if automated tests are hard, perhaps we should add this case to TestRail?).

**Comment by abodea** [comment]
Verified as fixed in the latest Fire TV build `3.10-LAT4)`.
