### ISSUE TITLE
Video shows as black screen while sound plays when fullscreen at time.com/videos

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/firefox-tv#2296]
## Steps to reproduce
1. Go to time.com/videos
2. Select a video to play
3. Click icon to make it full screen
### Expected behavior
Video should play fullscreen
### Actual behavior
Screen shows as black and only video sound plays until minimized
### Device information
* Fire TV device: 4K stick
* Latest affected Firefox version: 3.9

* Earliest affected Firefox version: ?

**Comment by athomasmoz** [comment]
Does this only occur on Time? Could this be #2170

**Comment by athomasmoz** [comment]
Look into this as part of #2386

**Comment by athomasmoz** [comment]
Closing in favour of tracking in #2386
