### ISSUE TITLE
Pocket videos may unexpectedly update while the user is looking at them

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2297]
## Steps to reproduce
As a user, I'm using the app for a while and I open the overlay, scrolling through the Pocket videos for the one I want to watch. However, the videos suddenly update and the users loses their spot in the list.

To reproduce in a test environment:
- Open the overlay
- Open the Pocket megatile
- Wait at most around six hours (for server to update with new Pocket videos)

### Expected behavior
Pocket videos remain the same

### Actual behavior
Pocket videos are updated

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

In practice, this isn't that likely to affect users:
- A Pocket video is added every 6 hours so the content the users are looking at is likely to only shift one over rather than replace all the videos
- The chances that a user looking through the overlay intersects with the Pocket video update event is unlikely
  - In the new implementation with best-effort nightly background updates, this is even less likely to happen

**I recommend P3.** If Pocket videos get updated more frequently, we should revisit.

This is a **regression** from December: https://github.com/mozilla-mobile/firefox-tv/commit/0faf9d739562de6d9c941d8194be8396d2f1a5dd#diff-46bc4e394f804c8278ec11302e5199c5R348

When fixing this, **add a unit test for the integration** (as opposed to cache itself): this code path is rarely tested by hand so we need to know if it will break.

**Comment by athomasmoz** [comment]
@mcomella I noticed this mentioned the pocket megatile. Does this issue go away with our new Pocket approach on the homescreen?

**Comment by mcomella** [comment]
@athomasmoz Daniela and I came up with a solution in #2223 that fixes this; I'll close this when we lock in the solution by closing that bug. I added this task to the follow-up list of that issue.
