### ISSUE TITLE
Browser slows down device to become unusuable

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#230]
I've only seen this start on Youtube and I recently reproduced it while testing a patch that refreshes youtube a lot (during video playback) – maybe that could create a consistent STR?

The behavior persists inside native app UI (e.g. drawer), on the device homescreen (outside of the app), and even in `adb shell`. Nothing noticeable shows up in `top` for CPU or memory usage, nor in logcat dumps (Firefox CPU usage is ~2% at the time).

I wonder if it's related to us not releasing MediaPlayer as per the AmazonWebView docs #16.

**Comment by liuche** [comment]
Haven't been able to reproduce this, keeping the reference to #268
