### ISSUE TITLE
Turn on Hint Bar A/B Test

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2314]
### Vision statement / What / Requirements

As an FFTV team member, I want to A/B test the hint bar addition, so that I can determine if it helps raise awareness of the app navigation & features

### Impact

Test our success criteria for the hint bar - increase users that see the home page.

### Acceptance criteria

* A/B test has been started where:
  * 5.5% see the hint bar
  * 5.5% control group (no hint bar)

**Comment by liuche** [comment]
Updated this in the Kinto backend:
A: 0-5 (on)
B: 6-10 (control/off)

Assigning to @Baron-Severin to approve on the backend

**Comment by Baron-Severin** [comment]
> Updated this in the Kinto backend:
> A: 0-5 (on)
> B: 5-10 (control/off)
> 
> Assigning to @Baron-Severin to approve on the backend
> 
> Docs here: https://github.com/mozilla-mobile/android-components/blob/master/components/service/fretboard/README.md
> 
> `Filters` is the appropriate section.

Approved on the backend.
