### ISSUE TITLE
Ad-blocker popup prevents site access (popsugar.com)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2316]
## Steps to reproduce
1. Launch Firefox.
2. Access  **`https://www.popsugar.com/latest/Video`**.

### Expected behavior
A button for skipping the pop-up interstitial should be displayed in order to access the site.
### Actual behavior
Only the pop-up is displayed and site cannot be reached as the user is stuck in that screen.
### Device information 
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`Firefox TV v3.10 LAT1`**
* Earliest affected Firefox version: **`Firefox TV v3.9`**
### Notes
For more details please see the attachments: 
### This is from Firefox desktop
![download (5)](https://user-images.githubusercontent.com/42831109/58254527-a1286180-7d73-11e9-98c5-85cf7d9fd9c3.png)
### This is from Firefox for Fire TV
![IMG_20190523_085930](https://user-images.githubusercontent.com/42831109/58254786-2dd31f80-7d74-11e9-9b3d-c03e504b318e.jpg)

**Comment by athomasmoz** [comment]
@abodea Does this happen if turbo mode is off?

**Comment by abodea** [comment]
@athomasmoz I tried to reproduce it with turbo mode off and everything worked well, I was able to get past the ad-blocker popup.

**Comment by athomasmoz** [comment]
That's great! I'm going to close the issue since the website doesn't offer a way to view it with Turbo mode on.
