### ISSUE TITLE
The URL bar should be accessible when typing anything or for auto complete

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2317]
### Why/User Benefit/User Problem
As a Firefox for Fire TV user, I want to be able to select any text I typed on the URL bar in case I entered a wrong URL and the mistake is in the middle, to be able to modify it and not rewrite everything or delete until that point. 
Also, this will help with the auto complete, if I want to access **`www.vimeo.com/watch`**, right now in Fire TV the only auto complete is **`www.vimeo.com`** so I have to type all the URL, with this feature I will be able to autocomplete and still type after that.
### What / Requirements
Add the functionality to select the URL bar for a better experience. 
### Acceptance Criteria (how do I know when I’m done?)
The URL bar can be selected even when auto completing a website where we want to add /videos or any other text in the URL.

**Comment by abodea** [comment]
@athomasmoz @npark-mozilla for example the only and the fastest way to access **`www.vimeo.com/watch`** while the only option for auto complete vimeo is **`www.vimeo.com`** is to access vimeo.com and then tap on the menu button and add the /watch. This will save time and maybe if we will have more options for autocomplete this will help.

**Comment by athomasmoz** [comment]
This is an issue on the keyboard itself, not our implementation. Closing as won't fix

**Comment by liuche** [comment]
@abodea when I'm testing, sometimes I also just use a search to enter most of the words in the url, and then usually the site is one of the top search results.

**Comment by abodea** [comment]
@liuche yes but there are some cases for example `www.popsugar.com` when I enter the URL the only thing for autocomplete I have is `www.popsugar.com` but as it was mentioned we want the part of the website with videos, in this case `https://www.popsugar.com/latest/Video` so in order to get /latest/videos, I have to type it manually(all the url), users will always use what is in auto-complete.
And the only workaround for this and the fastest way to enter `https://www.popsugar.com/latest/Video` is to type `www.popsugar.com` - auto-complete - tap on menu button - tap on url bar - the `www.popsugar.com` is there and I only need to add `/latest/video`.

Thanks,
Andrei
