### ISSUE TITLE
Onboarding Step for New Homescreen

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2318]
### Why/User Benefit/User Problem

Promote our new home screen to users, so they know it exists and can browse through the sites. This is especially important since most categories will be below the fold.

### Acceptance Criteria (how do I know when I’m done?)

* Onboarding screen displayed the first time a user in EN_US opens Firefox from a fresh install, after Turbo mode
* Onboarding screen displayed once for users in EN_US on the new version
* Pocket onboarding is removed
* Changes are hidden behind experiment #2320 

![Homescreen - onboarding@2x](https://user-images.githubusercontent.com/51007/58389778-62e7b680-8081-11e9-94a3-5cd57c907022.png)

#### Copy from Gretchen (Content Strategy)

[Title] Now playing: the internet

[Body] Watch videos from the most popular sites: news, sports, music, and more. Scroll down. Select. Watch.

[Button] Ok, got it

#### Non-blocking requirements from @brampitoyo (UX):
- [x] Link to the Sketch plugin export for this screen w/ dp, fonts, etc: https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/ – same link as always
- [ ] Final image that includes the tiles we'll be shipping (this depends on finalized sites)

### Not Included

* Home screen does not need to be localized

**Comment by brampitoyo** [comment]
@athomasmoz 

* Added copy from Gretchen (Content Strategy)
* Added link to Sketch plugin export – it’s the same link as the one I’ve been using for this homescreen

**Comment by athomasmoz** [comment]
@brampitoyo now that we have a finalized list of sites, can you update the screenshot for this one?

**Comment by brampitoyo** [comment]
Here’s the asset for our onboarding banner, with updated list of sites (@2x resolution):

![new-homescreen-onboarding@2x](https://user-images.githubusercontent.com/51007/59172002-dcab9400-8b99-11e9-93f4-7f3842791adb.png)
