### ISSUE TITLE
In some news site, playing embedded video crashes the app

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#232]
STR:
go to 680news.com
Open one of the stories with video clips i.e. "Raptor’s Kyle Lowry surprises students with holiday shopping spree"
Click the play button in video pane

The app crashes.

Logcat attached, i think the relevant area is:
D/MtkOmxCore(  170): Mtk_OMX_FreeHandle
D/MtkOmxVdec(  170): [0xb83743a0] MtkOmxVdecDecodeThread terminated pVdec=0xB83743A0
D/MtkOmxVdec(  170): [0xb83743a0] MtkOmxVdecThread terminated
D/MtkOmxCore(  170): ## MtkOmxCoreCpuControlThread terminated
D/MtkOmxCore(  170): free_inst_handle dlclose(0x0xb52a8bd4), free(0x0xb83743a4)
W/System.err(12686): 	at org.chromium.components.external_video_surface.ExternalVideoSurfaceContainer.onFrameInfoUpdatedWMPI(ExternalVideoSurfaceContainer.java:358)
W/System.err(12686): 	at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
W/System.err(12686): 	at org.chromium.android_webview.AwContents.access$4800(AwContents.java:100)
W/System.err(12686): 	at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:3024)
W/System.err(12686): 	at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:46359)
W/System.err(12686): 	at com.android.webview.chromium.WebViewExtAmazon.onDraw(WebViewExtAmazon.java:31)
W/System.err(12686): 	at android.webkit.WebView.onDraw(WebView.java:2402)
W/System.err(12686): 	at android.view.View.draw(View.java:15623)
W/System.err(12686): 	at android.view.View.updateDisplayListIfDirty(View.java:14554)
W/System.err(12686): 	at android.view.View.getDisplayList(View.java:14576)
W/System.err(12686): 	at android.view.View.draw(View.java:15346)
W/System.err(12686): 	at android.view.ViewGroup.drawChild(ViewGroup.java:341
[crash.log](https://github.com/mozilla-mobile/focus-video/files/1572523/crash.log)

**Comment by mcomella** [comment]
First step: can we still repro?

**Comment by npark-mozilla** [comment]
This does not happen anymore, embedded videos play normally.
