### ISSUE TITLE
Add TV Guide channels to Fretboard Experiment

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2321]
### Why/User Benefit/User Problem

As a Product Manager, I want an A/B test set up for the TV Guide feature, so that I can measure whether it's providing value to users

### Acceptance Criteria (how do I know when I’m done?)
- [ ] Come up with a plan with QA to test "channels on" and communicate it over email - Timebox this to max 1 day
- [ ] **On June 3**: add channels to experiment #2320 (we want the categories to be visible for testing our release build before users see it so we can find regressions.) and pref to 0% for release builds

* Group A will show:
  * Each of the 5 new categories
  * Onboarding screen
* Group B is the control (do not show new Channels or Channels onboarding)
* ~~TV Guide experiment is set to X% (TBD from @athomasmoz) - Fretboard bug is #2320~~

**Comment by devinreams** [comment]
Closing to combine into #2320 since its all server side
