### ISSUE TITLE
Driver for: Testing list of sites, aiming to reach finalized list of sites

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2322]
### Vision

List of sites is finalized, so that we can start adding them to the home page

The owner of this bug doesn't need to do ALL the testing themselves, but should delegate and also remind the team to keep testing sites.

### Acceptance Criteria

* Goal: We have a final list of categories & sites that will be added to the home screen
  * Minimum of 4 categories
  * Minimum of 5 sites within each category
  * Order of categories & sites within them included
* If a category has been added that wasn't in the original MVP, content team has confirmed what Title should be used

### Approach

* Daily ping in FFTV channel (or email) about what categories still need to be worked on (so there is visibility and a reminder to the team to keep testing)
* Try to use the initial MVP categories & sites
* If a category needs a few more sites beyond what's marked MVP to fill it out, pull from the Post-MVP sites in the spreadsheet in order
* If it looks like we won't be able to get enough sites in a category, choose a new one in the order of tabs listed
* Make sure the sites in the list fit our [formula](https://docs.google.com/spreadsheets/d/1uuYQzG5RZKeB1UIdVXiPIacumJb3NN_YA_plKLF0nBA/edit#gid=100135680)

### Current State

* News & Politics - Done
* Sports - Need more sites. Test Post-MVP
* Music - Need more sites. Test Post-MVP
* Featured Video - Remove. Not enough sites
* Culture - Remove. Not enough sites
* Food - Test Post-MVP sites to see if we can add

**Comment by npark-mozilla** [comment]
Update: Food category does not have enough sites. Suffers from common issue of fullscreen video shift

**Comment by npark-mozilla** [comment]
Post-MVP Test of Sports is done, (Music does not have post-mvp list) still not enough sites to list.

**Comment by npark-mozilla** [comment]
While testing, most of the site failures can be attributed to following issues:
- Device crash (the device reboots while loading video)
- Fullscreen mode showing black area and video is shifted  (Probaby #2170 and/or #2172)

I can continue on testing sites listed in remaining categories, but it appears that this may be caused an OS issue that needs to be resolved.

**Comment by athomasmoz** [comment]
Thanks @npark-mozilla ! Do you have any more details on the crash that could help with investigation?

**Comment by npark-mozilla** [comment]
@athomasmoz the crash of the app itself was seen on Gen 2 device before master-o, and I believe it is related to https://github.com/mozilla-mobile/firefox-tv/issues/1795 . (Also see #2271 and #2287) But with master-o, the whole device reboots, which makes me think it is an OS issue.

**Comment by npark-mozilla** [comment]
Looking at the logcat, it seems that the Gen 2 device goes into a state of thermal throttling (with master-o) while rendering large videos as well, which would explain the slow performance.
