### ISSUE TITLE
Scrolling doesn't update padding of the items

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2324]
## Steps to reproduce
- Open fire-tv
- Navigate to Pocket channel
- Scroll all the way to the right (by holding)
- Scroll all the way to the left (by holding)

### Expected behavior
- first and last element have the correct padding

### Actual behavior
- first and last element do not have the correct padding

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

**Comment by liuche** [comment]
@Baron-Severin is this a dupe of a previous bug that you fixed?
If not, we should get a screenshot so we can see how bad this looks.

**Comment by psymoon** [comment]
I believe this is fixed via https://github.com/mozilla-mobile/firefox-tv/pull/2323/commits/d7daecfc15d229845c154a05290e60718129be13, please reopen if still reproducible
