### ISSUE TITLE
Add ability to remove tiles from new categories

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2326]
### Why/User Benefit/User Problem

As a user, I want to remove a tile from the home screen of Firefox, so that content isn't promoted to myself and my family that I don't want us to see

### Acceptance Criteria (how do I know when I’m done?)

* Users can remove tiles/sites from a category
* If all tiles in a category are removed, the category disappears
* Design & user flow for above points matches pinned tiles
* Focus is not impacted

### Not included

* This does not include a way to restore the tiles or categories

**Comment by psymoon** [comment]
@athomasmoz Do we have a list of categories for MVP?

**Comment by athomasmoz** [comment]
List is being finalized in https://github.com/mozilla-mobile/firefox-tv/issues/2322

**Comment by liuche** [comment]
> Do we want telemetry for removing Channel home tiles?
This should match our Pinned Tiles events
