### ISSUE TITLE
Focus handling for turbo mode button

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2332]
## Steps to reproduce
- open fftv
- navigate to turbo button
- press left on DPAD

### Expected behavior
- nothing

### Actual behavior
- pocket or pinned_tile gain focus

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

**Comment by athomasmoz** [comment]
Can you recover from this or are you stuck?
