### ISSUE TITLE
Track Distractions (Q2SP5)

### ISSUE THREAD

**Issue by devinreams** [mozilla-mobile/firefox-tv#2336]
Leave a comment with other untracked work you may have done.

**Comment by mcomella** [comment]
On Friday (i.e. technically before the sprint), I spent 30min changing the a-c Pocket APIs https://github.com/mozilla-mobile/android-components/issues/3115 to unblock https://github.com/mozilla-mobile/firefox-tv/issues/1976 (replace our code with a-c code), which was related to the work in https://github.com/mozilla-mobile/firefox-tv/issues/2325 but definitely not necessary.

**Comment by Baron-Severin** [comment]
Intern prework (spread out over the last week)
- 1 hour planning meeting with Sawyer
- ~1 hour writing "what will you be doing here?" documentation
- Unknown time reading emails and discussing

I will also be spending some time looking for good first issues for her to take on.

**Comment by mcomella** [comment]
I spent ~25 minutes filing Fenix bugs.

**Comment by mcomella** [comment]
I spent ~30 minutes following up with data science on https://github.com/mozilla-mobile/firefox-tv/issues/2091. This was prioritized in a previous sprint and is currently in Blocked but technically didn't prioritize it for this sprint.

**Comment by mcomella** [comment]
I sent ~2 hours fixing `Robolectric.buildActivity`: https://github.com/mozilla-mobile/firefox-tv/issues/2367 I added it to the sprint. I got involved in this because I thought it would be a quick fix. We should also consider how much time it will take to review and address review comments.

**Comment by mcomella** [comment]
And I spent another ~30min cleaning up the loose ends from the bug I mentioned above (communicating with the team, filing a now unblocked bug to make testing easier, etc.): https://github.com/mozilla-mobile/firefox-tv/issues/2369

**Comment by mcomella** [comment]
I spent ~1hr improving the security of our gradle dependencies in https://github.com/mozilla-mobile/firefox-tv/issues/2373; my investigation on "how long would this take" turned into "it's simple" and, of course, taking longer than expected.

**Comment by mcomella** [comment]
I spent 30min suggesting that new hires increase their heap size on AS, updating our onboarding docs to include it, and emailing tech leads to add those things to their own team's onboarding docs.

**Comment by mcomella** [comment]
I've put off my handling my email this sprint so I spent ~1hr managing it today and still have more to go.

**Comment by mcomella** [comment]
I spent 5min adding a missed release to the changelog: https://github.com/mozilla-mobile/firefox-tv/issues/2259

**Comment by mcomella** [comment]
fwiw, releng has been taking non-trivial amounts of time. Between shepherding the release blocker yesterday (most of the day) and today, trying to build the release build (with intermittent TC failures #2378), and updating the relman docs (to be fair, this should be less time intensive the more we clean up the docs) took most of the day.

**Comment by mcomella** [comment]
https://github.com/mozilla-mobile/firefox-tv/issues/2378 wasted a lot of my time during releng so I spent ~20min making and analyzing a PR that would give us more debug info: https://github.com/mozilla-mobile/firefox-tv/pull/2415

**Comment by mcomella** [comment]
I spent an hour closing out my workday goals. I spent another hour thinking about career progression.

**Comment by mcomella** [comment]
I was concerned there might be a bug in our home tile click logic so I investigated for 30min: I could not find a bug. This is related to https://github.com/mozilla-mobile/firefox-tv/issues/2091 which was deprioritized this sprint.
