### ISSUE TITLE
Fix Travis CI, or remove it by moving codecov to TC

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2337]
### Vision statement / What / Requirements
Travis is failing currently. We should either
1) Fix it
2) Get rid of Travis by moving codecov to Taskcluster
- codecov is currently running on travis and android-components managed to move codecov to TC: mozilla-mobile/android-components#1259 (comment)

We should do the task that requires the least work. If they are roughly the same, prefer consolidation to TC.
### Impact
No codecov reports on PRs until this is fixed.
### Acceptance criteria
Either
- Travis running and passing again on PRs

or
- Travis is removed
- Codecov is run on TC

**Comment by mcomella** [comment]
An additional problem: codecov is no longer tracking our historical coverage, e.g. last report is from 5/21: https://codecov.io/gh/mozilla-mobile/firefox-tv
