### ISSUE TITLE
Allow users to turn on Tracking Protection

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#234]
This is useful for sites with a lot of trackers, e.g. news websites like nytimes.

How can we do this with the least amount of new UI?

**Comment by liuche** [comment]
Things to consider:
* How do users know tracking protection is on?
* How to turn off tracking protection
* Explanation (first run? #289)

**Comment by bbinto** [comment]
For simplicity
- turn on by default
- user turns off TP, it stays off until they turn it on again manually
- no setting toggle

For future more smartness, after 1.1.
example
cnn.com - turned on
nytimes.com - manually turn it off
cbc.ca - it automatically turns back on

**Comment by liuche** [comment]
@bbinto @Sdaswani you mentioned pausing this and that it might not ship with 1.1, can you document some details here, or give a timeline for when we'll hear about this?

**Comment by bbinto** [comment]
Not at this moment, for now - please go ahead and don't worry about it.

Full speed for 1.1!

**Comment by Sdaswani** [comment]
@liuche sorry if we said pausing - the feature will go into the product no later than 2.0, and until we hear differently, it's going in 1.1.

**Comment by lime124** [comment]
<img width="527" alt="screen shot 2018-01-17 at 3 57 28 pm" src="https://user-images.githubusercontent.com/287322/35073737-3965c030-fb9f-11e7-8e6c-5fd6038319d7.png">

@liuche

**Comment by jonisavage** [comment]
SUMO article: https://support.mozilla.org/en-US/kb/turbo-mode-tracking-protection-firefox-fire-tv

We've also linked it under new features in the meta article: https://support.mozilla.org/en-US/kb/firefox-fire-tv

**Comment by liuche** [comment]
Here's what the final state of the enabled/disabled state looks like, but we can fix it later if necessary:

![switch-on](https://user-images.githubusercontent.com/1082253/35180207-267a08d8-fd60-11e7-854b-46cb3fc05d2e.png)
![switch-off](https://user-images.githubusercontent.com/1082253/35180209-289a8264-fd60-11e7-847c-a06afc04ef19.png)

**Comment by Sdaswani** [comment]
That looks better!
