### ISSUE TITLE
Improve Fire TV parental controls on app level

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#235]
_Added by @bbinto_

**Why/User Benefit**
- Protect kids from accessing the FFTV app

**What**
In Settings, Have a Parental Controls Icon that has the following instruction: "You can pin protect launches of Firefox for Fire TV by navigating to Settings -> Preferences and then toggling on Parental Controls. Set a pin and be sure 'Pin Protect App Launches' is turned On." 
- We can link to this page for more info: https://www.amazon.com/gp/help/customer/display.html?nodeId=202104970

**Acceptance Criteria (how do I know when I’m done?)**
- Security review performed, approval
- Probe when this setting is performed/set

**Comment by bbinto** [comment]
App-based PIN/protection does not come out of the box, we could figure out how to lock only Firefox.

**Comment by liuche** [comment]
@Sdaswani to start the conversation with Security about what PIN protection might entail, security review.

**Comment by bbinto** [comment]
@lime124 will provide high level sketches to run by security team for review

**Comment by liuche** [comment]
@aminalhazwani provided some IA sketches [here](https://www.lucidchart.com/documents/edit/80a8b024-99c7-4b02-bd7b-0ac3f685a185/0?shared=true&) - there's an MVP, as well as subsequent work and customization (for past 3.0).

**Comment by liuche** [comment]
Waiting on security feedback, point is @Sdaswani  and @aminalhazwani

**Comment by bbinto** [comment]
- As a parent, I want to watch adult content without my kids knowing about it
- As a parent, I don't want my kid to visit an adult content website

**Comment by Sdaswani** [comment]
@bbinto @lime124 @aminalhazwani I think we should just do this for 3.0:
"In Settings, Have a Parental Controls Icon that has the following schpeal: "You can pin protect launches of Firefox for Fire TV by navigating to Settings -> Preferences and then toggling on Parental Controls. Set a pin and be sure 'Pin Protect App Launches' is turned On."" We can link to this page for more info: https://www.amazon.com/gp/help/customer/display.html?nodeId=202104970

Of course I defer to @lime124 and @aminalhazwani but unless Amazon asks us for extra controls, I think relying on the built in parental controls is the 80% win.

I wonder if @liuche or @mcomella know if there is a way to deep link to the settings page so it can be easily accessed from our settings entry.

**Comment by lime124** [comment]
+1 to @Sdaswani. 

I think this is going to be the simplest and most straight-forward solution for people trying to set up parental controls. Then in a future release we can iterate more on some of the proposals  and ideas Amin has shared around white/black lists and a kids only view.

So ideally we would just need copy from Brian and an icon for settings. We can use what the About page looks like until we are able to clean up the Settings UI. It for sure won't be pretty 😬 

But let's for wait for confirmation from Amazon that they aren't wanting something else.

**Comment by Sdaswani** [comment]
@bbinto thoughts on a two step approach? If so we can probably get a prototype of the simple solution pretty soon, and then can mutable requirements and iterate to a final UX.

**Comment by bbinto** [comment]
@Sdaswani and @lime124, 100% agreed.

**Comment by Sdaswani** [comment]
"Here is the Android API for setting the permissions: https://developer.android.com/reference/android/content/RestrictionsManager.html#requestPermission(java.lang.String,%20java.lang.String,%20android.os.PersistableBundle)" More to come....

**Comment by athomasmoz** [comment]
Closing ticket for now. Will continue tracking market problem & create ticket when we have a solution planned
