### ISSUE TITLE
Replace deprecated `SearchEngineManager.load()` with `loadAsync()`.

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/firefox-tv#2352]
`SearchEngineManager.load()` is [deprecated now](https://github.com/mozilla-mobile/android-components/blob/77d384c/components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngineManager.kt#L58). `SearchEngineManager.loadAsync()` should be used instead.

Occurrences:
  - [SearchEngineManagerFactory](https://github.com/mozilla-mobile/firefox-tv/blob/b94a1f23a746a80765d17e33f07078eb7a0fd274/app/src/main/java/org/mozilla/tv/firefox/search/SearchEngineManagerFactory.kt#L26).

**Comment by mcomella** [comment]
@pocmo @dector When does a-c plan to remove this? We'd like to now when we should schedule this by.

**Comment by pocmo** [comment]
There's no timeline yet. We actually haven't really defined/documented how we want to deal with deprecated code. So far we have relied on [searchfox](https://searchfox.org/mozilla-mobile/source) to determine if specific code is used by some of our own apps.

Maybe this could be a "good first issue" for now?

**Comment by mcomella** [comment]
> Maybe this could be a "good first issue" for now?

Replacing a blocking call with an async equivalent can be non-trivial so I'll set this as `help wanted` instead.

**Comment by dector** [comment]
> Replacing a blocking call with an async equivalent can be non-trivial so I'll set this as `help wanted` instead.

Oh, it's just about renaming. :)
