### ISSUE TITLE
FF for fire tv crashes when trying to delete the last tile

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2354]
## Steps to reproduce
1. Launch FF for fire tv.
2. Select Pinned Tiles section.
3. Delete all the Pinned Tiles.
### Expected behavior
All the pinned tiles can be deleted from FF for fire tv.
### Actual behavior
When trying to delete the last tile, FF for fire tv crashes.
### Device information
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`v3.10-LAT3`**
* Earliest affected Firefox version: **`v3.10-LAT3`**
### Notes
This issue is reproducible all the time. The screen remains frozen for like ~15 second and the crashes.
For more details please see the attachments: [logcat.txt](https://github.com/mozilla-mobile/firefox-tv/files/3237423/logcat.txt) and [video](https://drive.google.com/file/d/1kDKQJ7SnDOFvnP5sMITeB_jEGysisVyW/view?usp=sharing).
Note that I tried on the latest release v3.9 to delete all the tiles for 5 times and FF didn't crashed.

**Comment by abodea** [comment]
Please note that this issue also occurs on the **`Fire TV Cube 4k.`**

**Comment by Baron-Severin** [comment]
Looks like this is caused by an infinite loop of focus updates.  This can be shown by adding a log in a `doOnNext` on `NavigationOverlayViewModel#focusUpdate`.  These updates are blocking the main thread and causing an ANR.

**Comment by Baron-Severin** [comment]
Focus is bouncing endlessly between the Pocket channel and one of the Pocket tiles.

**Comment by Baron-Severin** [comment]
Comment in `FocusRepo#updateFocusStateIfNew`: `// If pinnedTiles is empty and current focus is on home_tile, we need to restore lost focus (this happens when you remove all tiles in the overlay)`.  With the channel update, all channel tiles have an ID of home_tile, which is causing this infinite loop.

**Comment by abodea** [comment]
Verified as fixed in the latest Fire TV build `3.10-LAT4)`.
