### ISSUE TITLE
The language is changed only after restarting FF 1-2 times

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2355]
## Steps to reproduce
1. Launch FF for fire tv.
2. Tap on the Home button and go to settings.
3. Select any other language(example Espanol).
4. Enter FF for fire tv or restart it once.
### Expected behavior
The language is changed after restarting FF for fire tv once.
### Actual behavior
The language is not changed only after restarting FF for fire tv for like 1-2 times.
### Device information
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`v3.10-LAT3`**
* Earliest affected Firefox version: **`v3.9`**

**Comment by athomasmoz** [comment]
Closing as dup of #1305 .
