### ISSUE TITLE
Channel tile images

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2357]
A few tiles that are to be shipped with our TV guide layout don't currently have images.  They are:
- CBS News
- Huffington Post
- Vice
- Formula 1

Currently those tiles are using a placeholder image.
![tile-no-pngs](https://user-images.githubusercontent.com/13170306/58655660-6f614e80-82cf-11e9-8e67-238f0749f033.png)

**Comment by brampitoyo** [comment]
@Baron-Severin These assets are coming tomorrow. Thanks!

I also had a chance to test the APK you’ve provided on my Fire TV Stick. It looks great.

**Comment by brampitoyo** [comment]
@Baron-Severin You can find these PNG logos under the “News & Politics” and “Sports & Fitness” folders.

https://drive.google.com/drive/folders/16f4ieORIlkYyApAnb9-1d8ev2yyQ15kT?usp=sharing
