### ISSUE TITLE
Unify Pinned tile / TV guide tile creation

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2366]
### Vision statement / What / Requirements
Pinned tiles currently go through a confusing code path that varies based on their type (bundled or custom).  These should be made to be as consistent as possible.

Newer TV guide tiles are stored as data objects rather than JSON.  Bundled pinned tiles should take this approach as well.

### Impact
- Fixing these will make future changes to channels easier to write
- This should allow us to delete a fair amount of code that is currently duplicated

### Acceptance criteria
- Bundled and custom pinned tile inflation code paths are as similar as is possible
- Bundled tiles are stored as data objects similar to `ChannelContent.kt`

**Comment by mcomella** [comment]
[triage] I followed up with Severin via email about what we should do with this bug that we think is an aspirational refactor.

**Comment by athomasmoz** [comment]
Thanks for following up. Closing this issue, and can be re-opened if it becomes more important in future
