### ISSUE TITLE
Move event pings from focus-event to mobile-event

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#237]
- [x] Update the telemetry-android library (v1.2.0)
- [x] Upload the new version to bintray
- [x] Update the Firefox TV project to use 1.2.0, add code to use new ping builder type

**Comment by mcomella** [comment]
FYI: PR is open against telemetry-android: https://github.com/mozilla-mobile/telemetry-android/pull/65

Once that completes, we'll have to upload the new version, pull it down here, and use the new ping type.

**Comment by mcomella** [comment]
The PR landed: I added a checklist to the first comment for next steps.

**Comment by bbinto** [comment]
So all queries grabbing stuff from Athena> telemetry.telemetry_focus_event_parquet should be now called telemetry.telemetry_mobile_event_parquet?

**Comment by mcomella** [comment]
For Firefox TV, yes, I think so.

**Comment by Sdaswani** [comment]
@bbinto maybe add this to your dashboards to make sure we start seeing a trickle of events?
