### ISSUE TITLE
Background pocket video fetch happens in non-EN locale

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2370]
## Steps to reproduce
- Install Firefox TV, verify the stand initial list of pocket video tiles
- Change to Spanish
- Reopen Firefox TV, verify the pocket tiles are gone
- Leave the device powered and connected between 1-6 AM
- Wake up device, change back to English
- Open Firefox TV

### Expected behavior
- Pocket content is same as yesterday, because it was in Spanish locale during the update timeframe

### Actual behavior
- Pocket content is updated

If it's because it's scheduled already when the app was in EN-US initially, and executed the update in the background after locale change, and that's per design, we can close this bug.

### Device information
* Fire TV device: 4K stick
* Latest affected Firefox version: master branch
* Earliest affected Firefox version: -

**Comment by npark-mozilla** [comment]
Will retest tonight by changing the locale first then install the app

**Comment by dnarcese** [comment]
Verified - this is not a bug.
