### ISSUE TITLE
Turn on Hint Bar for All Users

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2385]
### Vision statement

As a user, I want to know what actions are available to me within the app, so that I can easily navigate to new pages and find new features

### Impact

A/B experiment proved that adding a hint bar brought more users reached the homescreen, and improved usage of features on the homescreen including URL bar and non-YouTube pinned tiles

### Acceptance criteria

* Hint bar feature is turned on for all users not in the experiment (the remaining 90%)

**Comment by liuche** [comment]
@athomasmoz is there a date you'd like this to be rolled out on? Our 4.0 release should be early next week, but Hint Bar can be turned on at any time. Is there any timing we should pay attention to (e.g. before 4.0 rollout, before TV Guide Channels turned on, etc)?

**Comment by athomasmoz** [comment]
Yes, before the TV Guide Channels experiment would be great, since it appears to be helping users discover the homescreen.

**Comment by liuche** [comment]
@mcomella please close this bug when you've reviewed the new branch on Kinto.

**Comment by g0hww** [comment]
Is there a way to disable the hint bar? I have seen it once, I don't need to see it ever again.

**Comment by mcomella** [comment]
> @mcomella please close this bug when you've reviewed the new branch on Kinto.

Completed yesterday around 2pm.

> Is there a way to disable the hint bar? I have seen it once, I don't need to see it ever again.

Thanks for letting us know! I filed https://github.com/mozilla-mobile/firefox-tv/issues/2466 to track the discussion/investigation/implementation.

**Comment by ciolt** [comment]
This hint bar is EXTREMELY annoying.

Nobody asked for this feature! Nobody wants it

**Comment by liuche** [comment]
Due to feedback, we'll be turning the hint bar off for the C group of users.

**Comment by liuche** [comment]
@mcomella will review this.

**Comment by liuche** [comment]
Turned off C experiment.
