### ISSUE TITLE
Investigation: Video Player Issues

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2386]
### Why/User Benefit/User Problem

As a user, I can't play videos on the any of the sports sites from Alexa's top sites

### Acceptance Criteria (how do I know when I’m done?)

* We have identified causes for the video playback not working on sport sites

### Output

* A list of probable causes for the issues we see with video playback in the sports section. Each cause includes
  * Which sites are affected
  * What's the next action to take for this (logging a bug (Amazon, site compat), doing a workaround or bug fix)
* Verify this is Chromium 70

### Not included

* Implementing workarounds is not included

### Timebox

4 days

**Comment by devinreams** [comment]
Additional details provided on one specific issue related to handling of certificates (private/confidential): 

https://docs.google.com/document/d/1esS8L4UuXgxwlEkjeMDGZjch7YMIAhAjT_vCE3qeST0/edit?usp=sharing

**Comment by liuche** [comment]
Note to self: also investigate whether mimicking Silk's User Agent would fix any of these?

**Comment by kglazko** [comment]
STR
Compare video playback quality of properly formatted site: https://kglazko.github.io/testsite/clean.html
and improperly formatted site: https://kglazko.github.io/testsite/

Expected:
Video on improperly formatted site plays normally in fullscreen mode like on Silk. 
* The page is locked and doesn't allow side-to-side scrolling. 
* The video plays correctly and is not cut off minimized
* The video expands to fill the screen when fullscreen and is not cut off

Actual:
* Video on improperly formatted site isn't locked and allows side-to-side scrolling
* Video will often be cut off or not centered when going into full screen with large areas of black showing similar to the affected disapproved sites.

Notes:
On clean version, this doesn't happen. Need to investigate why Silk "locks" the improperly formatted page and doesn't allow side-to-side scrolling and why we don't do that. It is possible that formatting of the page somehow affects the rendering of the fullscreen video.

**Comment by mcomella** [comment]
To follow up on Kate's research, maybe we can use `WebSettings.setLoadWithOverviewMode` or `WebSettings.getUseWideViewPort` to fix this issue. Perhaps there are other relevant methods in `WebView`, `WebSettings`, `WebChromeClient`, or `WebViewClient` too.

**Comment by dnarcese** [comment]
Things I investigated:
- use Silk's user agent `Mozilla/5.0 (Linux; Android 7.1.2; AFTMM)  AppleWebKit/537.36 (KHTML, like Gecko) Silk/75.2.22 like  Chrome/75.0.3770.101 Safari/537.36` ❌
- `loadWithOverviewMode = true` was already set and didn't change anything ❌
- `horizontalScrollBarEnabled = false` ❌
- `useWideViewPort = true` fixes videos that are off screen (like https://kglazko.github.io/testsite/) ✅
  - Filed to expose in a-c https://github.com/mozilla-mobile/android-components/issues/3666
- Silk uses a different media player, NuPlayer, but we use ExoPlayer for the same video
  - tested video.cntraveler.com on FF Fire tablet (chromium 59): it uses NuPlayer and plays fine
  - same video on FFTV (chromium 59) uses ExoPlayer and is improperly formatted

**This may be a video player issue**
 - next step: investigate how to change the media player and test if it fixes anything

**Comment by psymoon** [comment]
> STR
> Compare video playback quality of properly formatted site: https://kglazko.github.io/testsite/clean.html
> and improperly formatted site: https://kglazko.github.io/testsite/
> 
> Expected:
> Video on improperly formatted site plays normally in fullscreen mode like on Silk.
> 
>     * The page is locked and doesn't allow side-to-side scrolling.
> 
>     * The video plays correctly and is not cut off minimized
> 
>     * The video expands to fill the screen when fullscreen and is not cut off
> 
> 
> Actual:
> 
>     * Video on improperly formatted site isn't locked and allows side-to-side scrolling
> 
>     * Video will often be cut off or not centered when going into full screen with large areas of black showing similar to the affected disapproved sites.
> 
> 
> Notes:
> On clean version, this doesn't happen. Need to investigate why Silk "locks" the improperly formatted page and doesn't allow side-to-side scrolling and why we don't do that. It is possible that formatting of the page somehow affects the rendering of the fullscreen video.

@kglazko Visiting the improperly formatted site: https://kglazko.github.io/testsite/ on desktop or mobile browser doesn't appear to lock the screen either (have to scroll to the right to view the video). Will locking the video cause other site compatibility complications? 🤔

**Comment by dnarcese** [comment]
Findings around fullscreen:
- if you scroll the video offscreen the fullscreen, the fullscreen is cropped to where it was scrolled
- https://www.sbnation.com/videos the video is in a popup and you scroll the webpage behind it the fullscreen video position changes
- https://www.travelandleisure.com/video clicking fullscreen focuses a dom element on the page and scroll to it, causing fullscreen to be cropped (related issue #1212)

**Comment by dnarcese** [comment]
Same video problems occur on [raw webview app](https://github.com/mcomella/WebViewRaw)

**Comment by dnarcese** [comment]
Investigating the css for video player on https://video.golfdigest.com/watch/golf-digest-stephen-curry:
<img width="209" alt="image-20190710173213342" src="https://user-images.githubusercontent.com/11432165/61006971-ae0c0f00-a339-11e9-95da-0fd7d6e78c98.png">

It seems that the `transform` property is not being respected because checking and unchecking that value does not change anything. But changing the `left` value moves the video. 
Unchecking both the `transform` and `left` properties puts the video in the correct place.

Next steps: investigate other videos to see if they have this same style issue, then find a workaround.

**Comment by athomasmoz** [comment]
Remaining: File follow-up bugs & specific investigation ideas

**Comment by dnarcese** [comment]
Filed #2526, #2540, #2541, #2542 as follow-ups

**Comment by athomasmoz** [comment]
Thanks @dnarcese , how would you prioritize between them? #2542 sounds promising

**Comment by dnarcese** [comment]
@athomasmoz #2526, #2542, #2540, #2541
