### ISSUE TITLE
Warning for malicious sites, i.e. Safe Browsing

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#239]

**Comment by mcomella** [comment]
Some notes from our discussion:
- We don't use safe browsing in focus for privacy concerns
- Functionality is built into Android WebView (but Amazon?): https://developer.android.com/reference/android/webkit/WebView.html#startSafeBrowsing(android.content.Context,%20android.webkit.ValueCallback%3Cjava.lang.Boolean%3E) & a manifest tag
- SUMO article on desktop impl: https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work
- Desktop Firefox impl uses a blocklist they download every 30 days and sends limited metadata to safe browsing servers as a backup check
- Further discussion in https://developers.google.com/safe-browsing/v4/

**Comment by mcomella** [comment]
Dupe #1184.
