### ISSUE TITLE
The "Recommended" button lose the focus after a home button interrupt

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2390]
## Steps to reproduce
1. Install Firefox for Fire TV.
2. Access YouTube.
3. Tap on the up button in order to select `Recommended` button.
4. Tap on the remote home button.
4. Return to Firefox for fire TV.
### Expected behavior
When returning to Firefox the `Recommended` button should be selected
### Actual behavior
When returning to Firefox the `Latest` button is selected for ~1-3 seconds and then the focus jumps to `Recommended`.
### Device information
* Fire TV device: **Fire Stick 2nd Gen**
* Latest affected Firefox version: **Firefox TV v3.10-LAT4**
* Earliest affected Firefox version: **Firefox v3.9**
* Turbo Mode: With both **On and Off**
### Notes
* [video](https://drive.google.com/file/d/13UsvJo52w0gOqdl7KKXMyelFXvjGUcUj/view?usp=sharing)

**Comment by athomasmoz** [comment]
Thanks for logging. Since this is a low impact to the user, and it's just a quick flash of latest as the focus, I'm closing as low priority.
