### ISSUE TITLE
Websites from TV Guide Channels cannot be deleted

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2392]
## Steps to reproduce
1. Install Firefox for Fire TV.
2. Add the TV Guide Channels using the **`adb shell am start -n org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa activeExperiments TvGuideChannels-2195:B`** command
3. Launch FF for fire TV.
4. Select any website from `News & Politics, Sports, Music` tap and hold.
### Expected behavior
A menu should be displayed like in the `Tiles` section to remove the website you don't want
### Actual behavior
Nothing happens, eventually the website is opened after a long tap.
### Device information
* Fire TV device: **Fire Stick 2nd Gen**
* Latest affected Firefox version: **Firefox TV v3.10-LAT4**
* Earliest affected Firefox version: **Firefox TV v3.10-LAT4**
* Turbo Mode: With both **On and Off**

**Comment by athomasmoz** [comment]
This feature was not added yet. it's in progress #2326
