### ISSUE TITLE
YouTube "Exit prompt" is not displayed when trying to exit YouTube

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2394]
## Steps to reproduce
1. Install Firefox for Fire TV.
2. Select and enter YouTube.
3. Play any video.
4. Tap on the back button in order to close YouTube.
### Expected behavior
Right before exiting YouTube, a prompt should be displayed asking `Are you sure you want to exit YouTube?`
### Actual behavior
No prompt is displayed and YouTube is closed without a warning.
### Device information
* Fire TV device: **Fire Stick 2nd Gen**
* Latest affected Firefox version: **Firefox TV v3.10-LAT4**
* Earliest affected Firefox version: **Firefox TV v3.9**
* Turbo Mode: With both **On and Off**
### Notes
Here is a picture with my tv from home regarding this prompt:
![62375972_323747165224166_448406014610374656_n](https://user-images.githubusercontent.com/42831109/59107850-3023a500-8942-11e9-812b-a6a2e1046f53.jpg)
Also, please note that this issue also occurs on the Silk Browser.

**Comment by athomasmoz** [comment]
Closing as expected behaviour.
