### ISSUE TITLE
Upgrade A-C

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2396]
### Vision statement / What / Requirements

Upgrade a-c- to get the latest changes & improvements

### Impact

Improvements from technical side and potential bug fixes

### Acceptance criteria

* a-c build is upgraded to version ___

**Comment by mcomella** [comment]
@athomasmoz This happens regularly as part of the release management tickets, e.g. #2248 – is there a reason to have a separate ticket for this?

**Comment by athomasmoz** [comment]
I was actually creating this as a placeholder for next sprint, so we could fill in the a-c number. If it's covered in the checklist ticket, then I can close this. Should we be estimating the releng tickets each sprint?

**Comment by mcomella** [comment]
> Should we be estimating the releng tickets each sprint?

I think that'd be appropriate: it does take up a non-trivial amount of time. :( I think it's especially bad how much time is spent waiting around for builds to finish, breaking up big blocks of coding time, but I'm taking notes on how we can address that.

**Comment by mcomella** [comment]
Closing as part of the checklist.
