### ISSUE TITLE
Channel tiles repeat 5 times

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2406]
## Steps to reproduce
Enable Channels with fretboard setting

### Expected behavior
Channel tiles should not release

### Actual behavior
Tiles are repeated 5 times
![screen](https://user-images.githubusercontent.com/6930774/59165769-0956a180-8aef-11e9-9a7a-65759edc6ab2.png)

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 3.10 release branch
* Earliest affected Firefox version: 3.10 release branch
* Turbo Mode: Yes

**Comment by npark-mozilla** [comment]
Realized this is a known behavior since the tile feature is still in progress. Closing.

**Comment by npark-mozilla** [comment]
Actually, keeping it open in case we pref the feature on this week.

**Comment by mcomella** [comment]
Talked to Ashley: expected behavior is that we show the raw data instead of duplicating the tiles.
