### ISSUE TITLE
Allow setting locale for Firefox without needing to make code changes, device locale

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2418]
### Vision statement / What / Requirements
As part of #2320 we added a commandline way for QA to turn on specific Fretboard experiments, so we could deterministically choose an experiment branch. However, some experiments have locale restrictions (such as en-US only) and it's annoying that devs and QA have to change code in order to show certain features.

This would be a follow-up to #2320 to add a way to control the locale (similar to Fretboard experiments).

### Impact
Devs and QA who are not in the US will be able to control what locale their app is in, to test/build on top of features that are en-US only.

### Acceptance criteria
- Documentation of how to set locale (see https://github.com/mozilla-mobile/firefox-tv/wiki/QA )
- QA/Devs can set what locale Firefox launches in (without needing to change code)

**Comment by Baron-Severin** [comment]
- This should function similarly to how we can start the app from the command line while passing flags that enable/disable certain experiments.  Logic that handles that can be found in `IntentValidator#validate` and related code.

- Locales are mainly handled through `LocaleManager`.  This is extremely old code, and for the most part we all try to avoid touching it.  I have been told that it handles a number of locale edge cases that were encountered in Fennec, but it's not clear 1) whether or not those edge cases still exist in newer versions of Android, 2) what they were, or 3) whether FFTV (which only fully supports a few languages) would even run into them.  Cleaning up `LocaleManager` is on the todo list, but it's pretty far down.

- Not all code will handle locale checks in the same way.  For example, newer views will use the `KillSwitchLayout` to disable their visibility if the wrong locale is set, but older code may not follow this pattern.  Check that all cases are handled by this new option.

**Comment by wmichelle024** [comment]
- Update documentation to mention running the edited command for debug builds:
`adb shell am start -n org.mozilla.tv.firefox.debug/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa activeExperiments TvGuideChannels-2195:A,HintBar-2011:B`
