### ISSUE TITLE
Turn on TV Guide Experiment

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2424]
### Vision statement / What / Requirements

As a Product Manager, I want to run an A/B test on the new TV Guide feature, so that I can measure the impact and determine next steps

### Impact

Enable Product Manager to make decision on next steps for the homescreen & improving usage outside of YouTube

### Acceptance criteria

* A/B test is live where
  * A is control
  * B contains the TV Guide onboarding screen and new categories (news, sports, music) with their respective sites
  * A is set to 5% of audience
  * B is set to 5% of audience

### Prerequisites

* We should not start the experiment until 3.11 is rolled out to 100% of audience
* We should not start the experiment until hint bar is turned on for all users #2385

**Comment by athomasmoz** [comment]
Link to Felix's analysis to determine the 5% https://metrics.mozilla.com/protected/flawrence/firetv_guide_power_analysis.html

**Comment by liuche** [comment]
I've set these buckets to be:
A (control): [90, 95)
B (experiment): [95, 100)

where the lower number bucket is inclusive, and the higher is exclusive, according to the AC Fretboard docs: https://github.com/mozilla-mobile/android-components/blob/master/components/service/fretboard/README.md#experiments-format-for-kinto

This means it won't overlap with the HintBar [0,10) experiment, while also allowing us to turn on the experiment for the remaining 90% at some point using a single additional experiment (which only allows min, max).

**Comment by liuche** [comment]
Landed the new C branch, and the Kinto changes have been pushed.
