### ISSUE TITLE
Turbo Mode Onboarding screen is out of date

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2426]
When you launch the app for the first time, the Turbo Mode onboarding shows some of our old UI (specifically Toolbar buttons and Pocket channel).

![device-2019-06-12-121638](https://user-images.githubusercontent.com/1082253/59368312-d11fb080-8cf2-11e9-8f85-e521935f6833.png)

### Device information
* Fire TV device: all
* Latest affected Firefox version: 3.10 with new Pocket channel (but also earlier because of differences in the toolbar buttons)
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by brampitoyo** [comment]
Find the updated Turbo Mode onboarding banner here:
https://drive.google.com/file/d/1L3XCXUEgnbdx7J8CrKHqjjlngo__qJuF/view?usp=sharing

Alternatively:
![turbo_mode_onboarding](https://user-images.githubusercontent.com/51007/59405543-e550d400-8dfe-11e9-9793-bbeaee927254.png)

**Comment by liuche** [comment]
@brampitoyo thanks for the updated background! A few things that I noticed (and I'll attach a screenshot of our most recent build):
- We moved settings to a channel so we don't need the icon
- New Desktop Mode icon
- Is Vaccines a good title to show? It's a controversial topic, could we check with @lwa-moz 😅 

Otherwise looks good!

![Screenshot_1560437005](https://user-images.githubusercontent.com/1082253/59442395-fffb5c80-8dae-11e9-9fdc-fcbce9ef86e1.png)

**Comment by lwa-moz** [comment]
@liuche makes a good point that @brampitoyo is probably blissfully unaware of; but I'm not overly concerned. If we can cut the vaccines screenshot that'd be great, but there's always going to be a few users accusing Pocket of propagandizing.

**Comment by brampitoyo** [comment]
@liuche @lwa-moz I wasn’t aware of how big of a deal vaccines is. Sorry about that – and about the overdue reply!

Updated asset:
https://drive.google.com/file/d/1L3XCXUEgnbdx7J8CrKHqjjlngo__qJuF/view?usp=sharing

![turbo_mode_onboarding](https://user-images.githubusercontent.com/51007/60239348-747ee100-9901-11e9-806f-05281cac4642.png)
