### ISSUE TITLE
All the Tiles section is restored when adding to pin a deleted website

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2435]
## Steps to reproduce
1. Launch FF for Fire TV.
2. Select the `Pinned Tiles`.
3. Select the last tile(or any tile).
4. Delete them until `YouTube` tile remains.
5. Open `YouTube` tile.
6. Tap on the menu button(the FF menu overview is displayed).
7. Select the last tile `YouTube` and delete it.
8. Tap on the menu button(YouTube home screen is displayed).
9. Tap menu button again and pin the YouTube URL.

### Expected behavior
The YouTube new pin will be displayed in the tiles section.
### Actual behavior
All the previous deleted tiles are restored and the new tile added as pin is displayed too.
### Device information
* Fire TV device: **`Fire Stick 2nd Gen.`**
* Latest affected Firefox version: **`FF for Fire TV 3.1.1-LAT1`**
* Earliest affected Firefox version: **`FF for Fire TV 3.1.1-LAT1`**
* Turbo Mode: **`On and Off`**
### Notes
For more details please see the [video](https://drive.google.com/file/d/1kEpgtluc_dvfcX5gmaE1A3Emq7AFl5Rz/view?usp=sharing) [log-tile.txt](https://github.com/mozilla-mobile/firefox-tv/files/3289813/log-tile.txt)

**Comment by devinreams** [comment]
Could not reproduce in 3.10 so does appear new/regression to 3.11.

I deleted all tiles including the YouTube, re-pinned YouTube, and its the only tile there.
