### ISSUE TITLE
Account Sign-in Page

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2441]
### Why/User Benefit/User Problem

As an FFTV user, I want to log in to my Firefox account so that I can send a tab to my TV from another device once implemented

### Acceptance Criteria (how do I know when I’m done?)

* If user goes to log in page on FFTV,
  * They can dpad navigate to the input fields
  * Input fields will pop up keyboard

### Tasks

* Enable dpad navigation to the input fields
* Verify keyboard pop ups for input fields, placeholder matches hint on input
* Verify clicking next from email address will automatically advance to password field. If not, log a ticket in FxA Github (Shane Tomlinson)
* Determine if there's additional work needed to sign in (comment or log bugs)
* Determine if there's additional work needed to handle errors (comment or log bugs)
* Determine if there's additional work needed to persist sign-in across app restarts (comment or log bugs)

### Not included

* Entry point for sign in from home screen
* Sign in errors should already be implemented in the webview, so should not require additional implementation from our team

**Comment by liuche** [comment]
If we need any changes to the FxA signin flow (like auto-advance of input fields), we should ping A-S team (Shane Tomlinson).

**Comment by Baron-Severin** [comment]
* ~Enable dpad navigation to the input fields~
Done.  I'll push the PR up shortly
* ~Verify keyboard pop ups for input fields, placeholder matches hint on input~
Keyboard opens, placeholders match
* ~Verify clicking next from email address will automatically advance to password field. If not, log a ticket in FxA Github (Shane Tomlinson)~
Opened https://github.com/mozilla/fxa/issues/1735
* ~Determine if there's additional work needed to sign in (comment or log bugs)~
Login seems to work as expected
* ~Determine if there's additional work needed to handle errors (comment or log bugs)~
Opened https://github.com/mozilla/fxa/issues/1737
* ~Determine if there's additional work needed to persist sign-in across app restarts (comment or log bugs)~
Seems to work out of the box (after stopping and restarting, hitting the CC button calls onAuthenticated and onProfileUpdated)

Also opened https://github.com/mozilla/fxa/issues/1734 as a meta bug

**Comment by Baron-Severin** [comment]
@athomasmoz I think we should probably block on https://github.com/mozilla/fxa/issues/1736, probably not the other two.  There are videos and descriptions in the issues so you can see for yourself, they're all linked in [the meta bug](https://github.com/mozilla/fxa/issues/1734).

**Comment by athomasmoz** [comment]
Thanks. To clarify, this issue is now blocked on https://github.com/mozilla/fxa/issues/1736 , assigned to FxA
2 other issues were found, also assigned to FxA, that are non-blocking:
- https://github.com/mozilla/fxa/issues/1735
- https://github.com/mozilla/fxa/issues/1737

**Comment by athomasmoz** [comment]
I see the tickets on FxA board are now closed. Has this ticket been resolved?

**Comment by Baron-Severin** [comment]
> I see the tickets on FxA board are now closed. Has this ticket been resolved?

@athomasmoz sounds like it to me.  I'd like this to be QA'd though, so I'm going to close it and move into `ready-for-qa`.  Feel free to move it around if that's not where you would like it.

**Comment by athomasmoz** [comment]
Perfect, thanks. I'm going to remove the size label so it doesn't mix up our sprint capacity counting (since we didn't do engineering on it this sprint)
