### ISSUE TITLE
Integrate FxA Accounts Component

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2445]
### Why/User Benefit/User Problem

As an FFTV eng, I want to re-use the A-C component for accounts, so that I don't need to recreate & maintain a separate version for FFTV

### Acceptance Criteria (how do I know when I’m done?)
* FxA accounts component integrated into FFTV codebase
* Can load sign-in page

### Not included

* UI for signing in doesn't need to be polished #2441 

---

TODO:
- [x] Get credentials to allow sign in, as per https://github.com/mozilla-mobile/android-components/tree/master/components/service/firefox-accounts
- [x] Figure out which sign in API to use:
  - `feature-accounts` (seems to require multi tab so maybe not)
  - `FxaAccountManager` (seems right)
  - `FirefoxAccount`
- [x] Integrate component
- [ ] ? Improve documentation on how to integrate FxA

**Comment by liuche** [comment]
Have never seen this component before, will look at Fenix codebase.

**Comment by mcomella** [comment]
Status update: I've got an account logged in end-to-end with hacky code. Before we can merge, I should clean it up (into our architecture). Then we can parallelize:
- Fixing the sign in experience (bug is filed)
- Correctly updating the state as part of our architecture

**Comment by mcomella** [comment]
Status update: open PR. We'll need to rebase on breaking changes in the next a-c release, I'd like to write tests, and I should help improve the docs though.

**Comment by mcomella** [comment]
Closed in https://github.com/mozilla-mobile/firefox-tv/pull/2513; follow-ups in #2538.

**Comment by mcomella** [comment]
qa-ready: the feature can be enabled with the `SendTab-2511:B` [flag](https://github.com/mozilla-mobile/firefox-tv/wiki/QA#fretboard-experiments). The implemented experience is defined in the acceptance criteria.

Limitations: 
- Sign in button uses placeholder icon in nav overlay. Currently, it's "CC" next to the "Exit Firefox" button
- After signing in, the behavior after clicking "Sign in" again is undefined.
- After signing in, the only artifact that indicates that the user is signed is the "Sign in success" status page. 
- Content is loaded into the tab the user is using to browse content. The sign in page acts like any other page the user loaded. This is not necessarily intended to be the final experience (e.g. we may clear those items from the history stack in the future and return the user to the site they last browsed to)

**Comment by abodea** [comment]
Verified as fixed in the latest LAT 4.1-LAT2, I was able to activate the feature and I added bugs accordingly.
