### ISSUE TITLE
The settings elements/bar is moving when scrolling even if it fits the screen

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2449]
## Steps to reproduce
1. Launch FF for Fire TV.
2. Reach the bottom of menu overview.
3. Select `Send usage data` and scroll to the right.
### Expected behavior
The elements are selected one by one and the `Settings bar` is not moving.
### Actual behavior
The `Settings bar` is moving while scrolling
### Device information
* Fire TV device: **`Fire Stick 2nd Gen.`**
* Latest affected Firefox version: **`FF for Fire TV 3.1.1-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 3.1.1-LAT2`**
* Turbo Mode: **`On and Off`**
### Notes
* [Video](https://drive.google.com/file/d/15AKtMmoCRlZgBZlxPwuydvODx7m9wqSC/view?usp=sharing)

**Comment by liuche** [comment]
We haven't ported the Settings to match the tiles, so I'll dupe this to #2290
