### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2454]
### Why/User Benefit/User Problem
Users are confused that the overlay is an overlay over the web content. Adding animations may help make this more clear.
Adding other animations around the app may also improve overall user experience.
### Acceptance Criteria (how do I know when I’m done?)
Animation added to make it clear the overlay is an overlay.

**Comment by dnarcese** [comment]
wip: https://github.com/dnarcese/firefox-tv/commits/2454-animations

**Comment by dnarcese** [comment]
@brampitoyo Here are some screencaptures of the animations I implemented. Do you think these could land as-is or are there any changes you see are needed?

- Focused tile animation:
![tilefocus](https://user-images.githubusercontent.com/11432165/62235836-c51fa900-b39b-11e9-926c-c4bc8776643d.gif)

- Overlay fade and transparency change:
![overlayfade](https://user-images.githubusercontent.com/11432165/62235511-27c47500-b39b-11e9-80d3-5c2dd9ab263e.gif)

**Comment by brampitoyo** [comment]
@dnarcese This all looks good. Let’s ship it!

Just to double check: does the tile logo looks ok when zoomed in?

**Comment by dnarcese** [comment]
@brampitoyo Yes, the logo still looks ok when zoomed in.

**Comment by AndiAJ** [comment]
Hi, I've tested the above mentioned change on **Firefox TV v4.2 LAT2** using a **Fire TV Stick 2nd Gen** and these are my findings:

1. Focused tile animations ✅
Working and looking good, while navigating as well as when deleting a title.

2. Overlay fade and transparency change ❌
The **fading animation works**, on the other hand **the overlay doesn't show any signs of transparency**.

**Comment by dnarcese** [comment]
@AndiAJ Only the animations were merged - the transparency change was taken out for this release.
