### ISSUE TITLE
Handle AC breaking changes to searchDefault field in search JSON

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2462]
## Steps to reproduce
FFTV is no longer overriding search codes with FFTV-specific ones, which were added in #1876
See dropoff: https://sql.telemetry.mozilla.org/queries/63329#162207

### Expected behavior
FFTV should override the search codes from AC in [SearchEngineManagerFactory](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/search/SearchEngineManagerFactory.kt#L13), so that FFTV will use custom search codes rather than the defaults.

### Actual behavior
Replacement codes are not showing up, and from talking to AC this is likely due to AC changes to the search JSON list: https://github.com/mozilla-mobile/android-components/issues/2371

### Acceptance criteria
* Search codes can be overridden again (and the FFTV codes are sent, rather than the defaults)
* Regression tests for search code overrides. May need to ask AC if there aren't clear errors being thrown when overriding fails. To be explicit, the test should fail if upstream a-c changes break the search code overrides and the wrong search codes are used.

### Device information
* Fire TV device: all
* Latest affected Firefox version: master eef55eb 
* Earliest affected Firefox version: Apr 8, 2019
* Turbo Mode: N/A

**Comment by liuche** [comment]
P1 because this affects our use of search codes.

**Comment by liuche** [comment]
https://sql.telemetry.mozilla.org/queries/63329#162207 for changes in search code numbers

**Comment by Baron-Severin** [comment]
It looks like we need a change to A-C in order to fix this.  I've opened https://github.com/mozilla-mobile/android-components/issues/3711.

In the meantime, I'm writing an integration/regression test to cover this case.
