### ISSUE TITLE
Investigate: Why is there a Fretboard server spike at 8am UTC (midnight PT) daily

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2469]
### Vision statement / What / Requirements
Adrian :autrilla on the Services team says there's a daily 8am UTC spike within a 5-min period in FFTV Fretboard traffic, since June 17.

![image](https://user-images.githubusercontent.com/1082253/60613840-8ee11080-9d80-11e9-9ea8-f5e8c96eb585.png)
timezone UTC (spike at 8am UTC, so 4am UTC, 1am PST)

### Impact
Having servers handle this many requests is expensive, and ideally it would be staggered, or ping at some random time.

### Acceptance criteria

* Determine if there's anything we're doing within our code base that could cause the spike
* If so, a ticket has been created to address

### Timebox

* 2 hours

### Potential tasks
- When did the Pocket background ping ship? When did it see major adoption? Could it be related?
- Are there any other scheduled background tasks?
- Does Fretboard get triggered for anything other than app/process start?
- Anything else?

liuche will follow-up to see if there are automated tests that could trigger this. If that's (or what is investigated in this bug) is not the case then further investigation will be needed.

**Comment by mcomella** [comment]
Things to investigate:
- When did the Pocket background ping ship? When did it see major adoption? Could it be related?
- Are there any other scheduled background tasks?
- Does Fretboard get triggered for anything other than app/process start?

**Comment by liuche** [comment]
@oremj could you let me know who the right person to talk about this Fretboard ops work would be? I'm interested to see if a user agent is sent with the Fretboard request, or if there's any additional information about this spike.

**Comment by oremj** [comment]
What's the URL for that service?

**Comment by autrilla** [comment]
@oremj this is for Remote Settings

**Comment by liuche** [comment]
@oremj quick ping, is this still happening at the 1am PST fretboard ping?

**Comment by bqbn** [comment]
This issue was caused by https://github.com/mozilla-mobile/firefox-tv/issues/2651 and can be closed now.

**Comment by liuche** [comment]
I'm still confused by why all the devices are hitting that server all at the same time - once we decrease the load on this, can we see if this is still happening?
