### ISSUE TITLE
UX mocks consolidation: FxA sign in

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2474]
### Vision statement / What / Requirements

All the mocks for FxA sign in are in a single place, so our team can easily find them

**Comment by brampitoyo** [comment]
Just like my previous designs, all mocks for Receive Tabs and FxA Sign In may be viewed (and will henceforth be updated) at:

https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/
