### ISSUE TITLE
Receive Tab Button on Toolbar

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2489]
### Why/User Benefit/User Problem

As a FFTV user, I want an receive tab button on the toolbar, so I can easily sign in to my account and send tabs

### Acceptance Criteria (how do I know when I’m done?)

* There is a receive tab button in the toolbar for users who are not logged in
  * Button matches design
  * Clicking on the button takes users to the sign in page
* Telemetry event is tracked for clicking the receive tab button

### Design
https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/

![image](https://user-images.githubusercontent.com/43346208/60735801-810ac700-9f09-11e9-9fda-78b68d21d553.png)

### Not included

* Building out the pre-boarding screen #2495 
* Signed in state of the button
* Localization - this will come later

**Comment by athomasmoz** [comment]
@brampitoyo can you add the icon for this one?

**Comment by liuche** [comment]
@brampitoyo could you give us the resource icon?

**Comment by brampitoyo** [comment]
@athomasmoz @liuche I’ve just returned from PTO. Sorry for the overdue asset!

[SVG](https://cl.ly/3d37276e560a/receive-tabs.svg)

PNG: ![receive-tabs](https://user-images.githubusercontent.com/51007/61604768-ffe85980-ac96-11e9-80aa-f10393f48ff6.png)

PNG@2x: <img width="24" src="https://user-images.githubusercontent.com/51007/61604773-024ab380-ac97-11e9-9bb2-5b86753eb7c8.png">

**Comment by Baron-Severin** [comment]
> @athomasmoz @liuche I’ve just returned from PTO. Sorry for the overdue asset!
> 
> [SVG](https://cl.ly/3d37276e560a/receive-tabs.svg)
> 
> PNG: ![receive-tabs](https://user-images.githubusercontent.com/51007/61604768-ffe85980-ac96-11e9-80aa-f10393f48ff6.png)
> 
> PNG@2x: <img alt="" width="24" src="https://user-images.githubusercontent.com/51007/61604773-024ab380-ac97-11e9-9bb2-5b86753eb7c8.png">

@brampitoyo that SVG link isn't working for me, would you mind uploading it again?
