### ISSUE TITLE
IWebView is sometimes disabled/null during `loading` callback

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#249]
For #245 we add a bandaid for when the webview is null, but it's not clear why this is happening.

For context from that bug, the NPE is happening after the `loading` state has changed, which is hooked into the webview's `onPageStarted` and `onPageFinished` callbacks (in `SessionCallbackProxy`).

Are we destroying the webview after that callback, thus setting `isWebViewAvailable` to false and returning null? Or has the webview been set to null somehow?

**Comment by mcomella** [comment]
I can't reproduce on the emulator with the latest code (adding log statements).

With Kotlin, we have null in the type system so this is unlikely to be a problem. I designed WebFragment so WebView will have a value when BrowserFragment is around but it will return null when BrowserFragment's view is removed from the hierarchy.

I'll leave this open so I can test on device.

**Comment by mcomella** [comment]
I can't reproduce on device and I think we should be better protected now with Kotlin: closing.
