### ISSUE TITLE
Accounts Button on Toolbar

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2490]
### Why/User Benefit/User Problem

As a FFTV user, I want an account button on the toolbar, so I can easily find my account details and sign out

### Acceptance Criteria (how do I know when I’m done?)
#2529 must be done first because it exposes sign in state to the UI.

* There is an account button in the toolbar for users who are logged in
  * Button matches design
  * Icon description is "sent tab settings"
  * Clicking on the button does nothing until accounts page is ready
* Event is tracked for account button clicks

### Design

Text: "Sent tab settings"
https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/#artboard10
<img width="960" alt="image" src="https://user-images.githubusercontent.com/43346208/61807572-a7c46b00-adee-11e9-8e9a-1580b4ff17db.png">

### Not included

* Building out the accounts page
* Localization, which will be done once strings are finalized

**Comment by athomasmoz** [comment]
@brampitoyo can you add a link to the default asset (if user doesn't have a profile picture)

**Comment by brampitoyo** [comment]
Icon assets for default profile:

[SVG](https://cl.ly/54b5aaf4a4b2/avatar-authenticated-no-picture.svg)

PNG: ![avatar-authenticated-no-picture](https://user-images.githubusercontent.com/51007/61846732-5e624180-aefc-11e9-9836-a31eb7539c6e.png)

PNG@2x: <img width="24" src="https://user-images.githubusercontent.com/51007/61846735-61f5c880-aefc-11e9-825f-bcdca93eed35.png">

**Comment by mcomella** [comment]
@brampitoyo One mild concern I have with the current design is that users may feel uncomfortable seeing their profile photo, especially if it's their face, on the homescreen. Do you have any thoughts? I'm less concerned about this than I was on desktop – it's smaller and isn't around _all_ the time – so if you're fine, I'm fine. :)

**Comment by mcomella** [comment]
I noticed there are issues when using custom FxA avatars:
- They are not round like the mocks
- There is no selected state when they are highlighted

See the screenshot for more:
![image](https://user-images.githubusercontent.com/759372/63900216-b89b6a00-c9b4-11e9-80f4-0fe0c372319d.png)

@psymoon Can you address these remaining issues in this bug?

**Comment by mcomella** [comment]
Note: there's a startup crash when signed into FxA that will make this hard to work on: https://github.com/mozilla-mobile/firefox-tv/issues/2759
