### ISSUE TITLE
Receive Tabs with Firefox in the foreground

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2491]
### Why/User Benefit/User Problem

As an FFTV users, I want to receive a tab from Firefox on another device, so that I can watch/listen to content on my TV without having to navigate to the same page on my TV that I already have open on my other device

### Acceptance Criteria (how do I know when I’m done?)

BLOCK TICKET ON PUSH #2528 IF POLLING DOESN'T AUTOMATICALLY WORK
(This should work, and I think backgrounding then foregrounding the app should trigger a poll, but please verify)

* User can receive a tab on their TV from Fenix, iOS, or Desktop Firefox
* Tab will overtake current content
* A toast is displayed to the user to indicate what's happened
* User can go back & forward through their history stack after sending a tab, and that tab will be included
* A receive tab count is tracked, so that we can determine usage of the feature
  * Event does not include details on what the tab is
  * Can we track type of device? ie. desktop / android / iOS
  * After speaking with Ashley, we want to record when a tab is received and visible to the user. If a push is invalid (e.g. no `entries`), we can report those errors to Sentry. If there are many of those, we can investigate and adjust
* If a tab is sent when Firefox is not open, nothing happens

### Design

Finalized string: "Tab sent from [device name]"
[Mock](https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/#artboard8)

### Not included

* Queuing tab#2654 tab will overtake the currently displayed page
* Receiving tabs in the background: #2654

**Comment by liuche** [comment]
Until Push is working, the app can be backgrounded and resumed to trigger a fetch (rather than waiting for the 15 min polling).

**Comment by mcomella** [comment]
I learned automatic a-c polling is going to be removed soon. However, you can trigger it manually:

> so, for now just call accountManager.authenticatedAccount()?.deviceConstellation()?.refreshDeviceStateAsync() when you want to check for new tabs (e.g. in onResume)

**Comment by mcomella** [comment]
I have a WIP that receives tabs end-to-end. I need to clean up the code and address the other acceptance criteria.

**Comment by mcomella** [comment]
@brampitoyo If we receive multiple tabs to open, what should we do? Options:
- Pick one of the tabs to open. Note: tabs aren't guaranteed to be received in order so we can't say, "Open the last one", but I think we can make a best effort
- Open the tabs quickly in succession so they're all part of the back stack. I have a small concern that the devices are too slow for this (e.g. that they'll get stuck loading each intermediate page before switching) and that it'd be hard to implement, but I can try it out and see
- Let the user choose? This increases the scope

Picking one is the simplest implementation

**Comment by jonichan** [comment]
@athomasmoz I've drafted a couple of SUMO articles for this feature for your review/comments:

- [https://docs.google.com/document/d/1aRYCGZXuEE3mWLAE914qXDyOyWOAbRA0MJCXkU_aGQ4/edit?usp=sharing Receive tabs on Firefox for Fire TV]
-[https://docs.google.com/document/d/1NDBlhzmE03XwZZaxeo4TIy40juPO-b6UlyryNL5nWog/edit?usp=sharing Disconnect your Firefox Account from Fire TV]
- [https://docs.google.com/document/d/1J_Cvx9wjcPYD2BRo_TDUMhrRED2g7kE0hlpiblo6dXk/edit#heading=h.j00ebqy52cpi Sign in to Firefox Accounts on your Fire TV]

**Comment by mcomella** [comment]
QA: you have to add an ADM API key in order to test locally but we're still working out how to do that so please test on the next LAT or wait for the updates on the API key.

This PR enables end-to-end receive tab. Please verify that, when you send a tab to FFTV _when it is foregrounded_, the device will receive the tab within a few seconds (it uses push); we have not defined the behavior when the app is backgrounded (#2654).

**Comment by mcomella** [comment]
PR in #2775 completes the full acceptance criteria: closing.

**Comment by mcomella** [comment]
There's still a small amount of work – outside the acceptance criteria – to make sure all devs have the API keys to test push support. I'm continuing to work on that.

**Comment by abodea** [comment]
Verified as fixed on v4.5-LAT3 the tabs are received correctly.
I sent a tab while being in each section of the FFTV(Send usage data, Clear all cookies, About, Privacy) and even whit a page opened.
The tab sent from desktop was always received/loaded instantly.
