### ISSUE TITLE
Re-Authentication Flow - Toolbar

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2493]
### Why/User Benefit/User Problem

As a signed in FFTV user, I want to be warned if I have been logged out, so that I can re-authenticate and receive tabs again

### Acceptance Criteria (how do I know when I’m done?)

- [x] If a user is logged out of their account unexpectedly, the toolbar displays that they're logged out
- [x] If a user is logged out of their account unexpectedly, they have a simple way to log back in
  - To test, I think you can sign into accounts.firefox.com and revoke access from the Fire TV device

- [x] Re-authenticate clicks are tracked to help us determine how common this is happening to our users
- [x] The number of users in this state is tracked (I think we can use [the Preferences system](https://searchfox.org/mozilla-mobile/rev/8c8b0dac29761cab203489aec508f6bdfd3a1009/firefox-tv/app/src/main/java/org/mozilla/tv/firefox/telemetry/TelemetryFactory.kt#37) in telemetry)
- [ ] Request dashboard for the above metrics

### Design

* Toolbar account button will show warning tag & icon description if a user is unexpectedly logged out
  * String: "Sent tabs – sign in again"
  * [Mock](https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/#artboard13)
* Clicking the toolbar button when unexpectedly logged out will take users to the webview log in page

### Not included

* Localization

**Comment by athomasmoz** [comment]
@brampitoyo can you add the icon for this one?

**Comment by brampitoyo** [comment]
Icon assets for re-authentication/error:

[SVG](https://cl.ly/5a47479e8dcf/avatar-warn.svg)

PNG: ![avatar-warn](https://user-images.githubusercontent.com/51007/61846607-d7ad6480-aefb-11e9-87be-87b7ae9a9b99.png)

PNG@2x: <img width="24" src="https://user-images.githubusercontent.com/51007/61846614-dbd98200-aefb-11e9-80f3-21629d5e0e95.png">

**Comment by athomasmoz** [comment]
NOTE: partially done with #2494 , all that's remaining is changing the icon

**Comment by abodea** [comment]
@Baron-Severin can you help me turn this on?
I tried this **`adb shell am start -n org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments TurboModeRebrand-2689:B`** but I couldn't activate the experiment.

**Comment by abodea** [comment]
@athomasmoz for this 
`If a user is logged out of their account unexpectedly, they have a simple way to log back in`
`To test, I think you can sign into accounts.firefox.com and revoke access from the Fire TV device`

I revoked the access for Fire TV device but I didn't got logged out.(is this intended?)
Everything worked as expected but I was still logged in. After a login I was able to see the device again on the account and I could sent tabs again.

**Comment by athomasmoz** [comment]
> Everything worked as expected but I was still logged in
Was the broken account icon shown? And when you clicked it, did it take you to the sign in flow?

**Comment by abodea** [comment]
No, I was still logged in, my avatar was displayed. I wasn't logged out. Only when I logged out manually the broken account icon was displayed.

**Comment by athomasmoz** [comment]
Ok thanks. I'll check in with the accounts team on expected behaviour, but I don't think we'd need to block release on any changes here.

**Comment by dnarcese** [comment]
Adding a push event when access is revoked is tracked in FxA here https://github.com/mozilla/application-services/issues/1418
