### ISSUE TITLE
Account Page & Signout

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2494]
### Why/User Benefit/User Problem

As an FFTV user, I want to see who's logged into FFTV and log out of my account when I'm not using it, so that others in my family can log in to send tabs

### Acceptance Criteria (how do I know when I’m done?)

* Account page showing username & profile image
* Account page is shown when user is logged in and clicks on the toolbar icon
* Option to see send tab tutorial (links to nothing for now, since we don't have that screen yet)
* User is logged out when they click on the disconnect/logout button
* Clicks on each button on page is tracked (~~back~~, disconnect, receive tab tutorial)
* Initially focused icon should be "Receive Tabs" button

### Design

* Strings should match what's already in the app:
  * Title: "Sent tabs"
  * User image: "Signed in as <line break>[username@email.com]"
  * Tabs button: "Firefox tabs"
  * Sign out button: "Sign out "
* [Mock](https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/#artboard12)

### Not included

* Localization. This will come later

**Comment by Baron-Severin** [comment]
@brampitoyo do we have a default image that we can use if the user doesn't have an avatar, or while their image is loading?

**Comment by athomasmoz** [comment]
@Baron-Severin there's a default image for accounts in the toolbar story https://github.com/mozilla-mobile/firefox-tv/issues/2490#issuecomment-514894712 does that work?

**Comment by Baron-Severin** [comment]
> @Baron-Severin there's a default image for accounts in the toolbar story [#2490 (comment)](https://github.com/mozilla-mobile/firefox-tv/issues/2490#issuecomment-514894712) does that work?

@athomasmoz that's perfect, thank you!

**Comment by Baron-Severin** [comment]
>     * Clicks on each button on page is tracked (back, disconnect, receive tab tutorial)

@athomasmoz do we need telemetry for remote back clicks as well, or only clicks on the back button?

**Comment by athomasmoz** [comment]
Hi @Baron-Severin thanks for checking. Let's take both out to align with only collecting what we need. The goal of tracking that was to flag is users are going into their account and not finding what they need, which I think we can estimate in other ways. Glad you brought it up

**Comment by mcomella** [comment]
Like https://github.com/mozilla-mobile/firefox-tv/issues/2490#issuecomment-525966957, the custom FxA should be round, not square.

![image](https://user-images.githubusercontent.com/759372/63900700-3ad85e00-c9b6-11e9-8c88-cc76ab09fd6a.png)

I think this one is less important than the homepage because there are no other round, small icons to compare it against – maybe we should follow-up with Bram/Ashley about whether or not this is a high priority.

@Baron-Severin Can you take a look?

**Comment by mcomella** [comment]
wrt ^, I reopened this original issue because I believe this falls under the original acceptance criteria that this should match the mock.

**Comment by Baron-Severin** [comment]
@mcomella thanks, I'll fix this tomorrow morning.

**Comment by abodea** [comment]
Verified as fixed in v4.5-LAT3.
