### ISSUE TITLE
Pre-Boarding Receive Tab

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2495]
### Why/User Benefit/User Problem

As an FFTV users, I want to be informed about the ability to receive tabs on my TV, so that I can sign in and begin using the feature

### Acceptance Criteria (how do I know when I’m done?)

* Pre-boarding screen displayed to users when they open the app if they haven't seen it before (like turbo mode). It should be displayed last of all onboarding screens (make it clear in the code that no other screens should be added after this one, since it takes you to sign in)
* ~Pre-boarding screen displayed when users click the "receive tabs" toolbar button~ [This button will display the onboarding screen, which will be added by a later story](https://github.com/mozilla-mobile/firefox-tv/issues/2495#issuecomment-525086256)
* Pre-boarding screen can be dismissed
* Pre-boarding screen links to sign in flow

### Design

Strings: https://docs.google.com/spreadsheets/d/1z852T9AKhFpQFq8JcX633-zsC81vxAkKYKyilwdistU/edit#gid=0

Mock: https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/#artboard3

Asset: https://drive.google.com/file/d/1Jy2y23mlhoKUU_Q1G-PhkVMVF98gp_m9

### Not included

* Localization

**Comment by Baron-Severin** [comment]
@brampitoyo I don't see an image asset linked, is it already in the project?

**Comment by brampitoyo** [comment]
@Baron-Severin I thought I had posted the asset somewhere along with the onboarding asset, but maybe had forgotten.

I’ve posted the asset on the first comment above, and the link is:
https://drive.google.com/file/d/1Jy2y23mlhoKUU_Q1G-PhkVMVF98gp_m9

**Comment by brampitoyo** [comment]
@Baron-Severin 

> …we need a content description for the image

How does this alt text sound?

Illustration of tabs sent from phone and tablet to Fire TV


> I can't seem to select the title text in your spec, so I'm having trouble working out the text styling.

I’ve resolved the problem with the file, and the newly exported version should have properly inspectable title!


> …we're supposed to open this onboarding screen when a user clicks "Firefox tabs" from the FxA profile screen…

As per our discussion, we’re supposed to open the onboarding screen (#2496) when the user clicks on “Firefox tabs”, and not this pre-boarding screen. Sorry for the nomenclature confusion!

**Comment by athomasmoz** [comment]
Hey @Baron-Severin , is this hidden behind the same feature flag as our other tickets? Just want to double check we aren't showing anything until receive tab works

**Comment by Baron-Severin** [comment]
> Hey @Baron-Severin , is this hidden behind the same feature flag as our other tickets? Just want to double check we aren't showing anything until receive tab works

Yep, it's behind the same flag.  This would be a good thing to have QA verify, though.
