### ISSUE TITLE
Onboarding Receive Tab

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2496]
### Why/User Benefit/User Problem

As a user, I want an onboarding screen after I log in to my account, so that I know how to send a tab to my TV

### Acceptance Criteria (how do I know when I’m done?)

* Onboarding screen displayed to users after successful sign in
* Onboarding screen linked to from the accounts page via "Firefox tabs" button
* Onboarding screen can be dismissed
* Dismissing onboarding screen will take user to the homescreen
* We are tracking how many users see this screen

### Design

Strings: https://docs.google.com/spreadsheets/d/1z852T9AKhFpQFq8JcX633-zsC81vxAkKYKyilwdistU/edit#gid=0

Mock: https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/receive-tabs/i03/#artboard7

Asset: https://drive.google.com/file/d/1K1T4xMVAzEcwJz8eK9YwiZI1H8Hi5h93

### Not included

* Localization

**Comment by athomasmoz** [comment]
Issues to retest after this feature implemented:
* #2605 
* #2604
* #2603
* #2602

**Comment by brampitoyo** [comment]
I’ve added the onboarding asset up in the first comment.

The link to that banner is: https://drive.google.com/file/d/1K1T4xMVAzEcwJz8eK9YwiZI1H8Hi5h93/view?usp=sharing

**Comment by athomasmoz** [comment]
Hey @psymoon thanks for picking this up. Just wanted to call out that for the first item in acceptance criteria

> Onboarding screen displayed to users after successful sign in

Majority of the time, users will have to confirm login by email on another device. So successful login may not happen right after submitting password. You can test this by logging in with an account created >7 days ago

**Comment by dnarcese** [comment]
Should the onboarding screen be shown every time on successful login? After a bit of testing, I only saw it show up once.

**Comment by brampitoyo** [comment]
@dnarcese Yes, we should show the onboarding screen after each successful login.

I posted a more detailed response on https://github.com/mozilla-mobile/firefox-tv/issues/2861#issue-494907277
