### ISSUE TITLE
Bitbar UI test fails with channels experiment enabled

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2503]
See
https://mozilla.testdroid.com/#testing/device-session/296208/758804/15814976

This still happens after the Amazon OS update screen is cleared. (Although now the error happens on different scripts)

### Device information
* Fire TV device: 4K stick / Gen 2 Stick
* Latest affected Firefox version: 3.11
* Earliest affected Firefox version: 3.11
* Turbo Mode: True

**Comment by npark-mozilla** [comment]
Turns out, the new welcome screen for channels was not handled in the UI test, and the device in Bitbar was participating in the fretboard experiement.  In our UI test, this dialog should be handled during the first launch, along with the 'Enable Turbo' dialog as well.

**Comment by npark-mozilla** [comment]
Above was taken care of with the `TV_ONBOARDING_SHOWN_PREF` to true, but another test fails while accessing settings, and it's because we hardcoded the number of keypresses to get to the settings in https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/androidTest/java/org/mozilla/tv/firefox/ui/robots/NavigationOverlayRobot.kt#L173.  When channels experiement is enabled, this would definitely fail to access the setting.

**Comment by mcomella** [comment]
I believe all our UI tests are fixed now.
