### ISSUE TITLE
Turn on TV Guide for All Users

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2510]
This should be done on July 15, 2019 to time with 4.0 release

### Vision statement / What / Requirements

TV Guide is turned on for 100% of users.

### Impact

More users can take advantage of the additional linked sites & categories. ~~At the same time, we can continue our A/B test to measure the impact of this new feature~~

### Acceptance criteria

* TV guide (onboarding + new channels/sites) is turned on for all EN_US users

**Comment by liuche** [comment]
@athomasmoz what percentage should this be turned on for? Did we decide 100%, and turning off the experiment for the 10% of users?

**Comment by athomasmoz** [comment]
Yes, putting this to 100% and turning off the experiment is fine.

**Comment by liuche** [comment]
Still waiting on the final translated descriptions on the release, but we should get them soon, and then can push this to 1% and then turn this on for everyone.

**Comment by dnarcese** [comment]
It has been turned on now. I created #2558 to remove the experiment from code in about a month.
