### ISSUE TITLE
YouTube Originals(Premium) is still available if adding to pin a video from the Originals section(after the account with Premium was deleted)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2523]
## Steps to reproduce
1. Launch FF for Fire TV.
2. Access YouTube.
3. Watch any YouTube video from **`Originals`.**
4. Tap on the menu overview button and add it to pin.
5. Access YouTube and delete the account that contains YouTube premium(including Originals).
6. Tap on the menu overview and launch YouTube from the recent created pin.
### Expected behavior
The YouTube home should be displayed, without access to YouTube Originals if there is no account with premium membership active.
### Actual behavior
The YouTube Originals section/channel can still be accessed even after removing the premium account.
### Device information
* Fire TV device: **`Fire Stick 2nd Gen.`**
* Latest affected Firefox version: **`FF for Fire TV 4.0-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 3.11`**
* Turbo Mode: **`On and Off`**.
### Notes
[Video](https://drive.google.com/file/d/1dYXSNCMVnVpovHKtP75oXUYgCEedTEjv/view?usp=sharing)

**Comment by athomasmoz** [comment]
Closing as won't fix. We don't control the access to the content, just the links that folks are taken to, so this is something on the YouTube side. From our side, there's no explicit log out in the app, and we're taking the user to the URL they pinned.
