### ISSUE TITLE
FFTV Support for ADM

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2528]
### Why/User Benefit/User Problem

As an Amazon device user, I want to see tabs sent from my other devices on my TV right away, without having to ask for them on my TV

### Acceptance Criteria (how do I know when I’m done?)

* ADM is supported in FFTV
* [Graceful degradation](https://developer.amazon.com/docs/adm/integrate-your-app.html#gracefully-degrade-if-adm-is-unavailable) is supported in FFTV

### Not included

* FFTV support, which is covered in separate ticket

**Comment by dnarcese** [comment]
Followups:
- #2712 
- #2713
