### ISSUE TITLE
Expose Firefox Account signed in state in architecture

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2529]
### Why/User Benefit/User Problem

As an FFTV user, I want FFTV to hold my logged in state, so that I can receive tabs from other devices I'm logged in to

### Acceptance Criteria (how do I know when I’m done?)

* FxA library Firefox Account state (e.g. signed in, signed out, re-auth needed, etc.) is represented in application architecture
* There are unit tests to ensure we don't break the functionality in future

### Tasks

* Make sure signed in state is represented in our architecture
  * mcomella wrote some skeleton code to do this but he's not certain it's correct.
  * Specifically, the state transmitted from the AccountObserver (in FxaRepo) callbacks should be represented in the Observable `FxaRepo.accountStateDontUseMeYet`.
    * That way, NavigationOverlayFragment can observe the account state and change the behavior of the sign in/out button anyway
* Write unit tests to verify correctness of sign in state against FxA library

**Comment by liuche** [comment]
Clean up, testing, verification - talking to A-S if there are any questions.

**Comment by mcomella** [comment]
Some nits on the existing code from my review in PR #2513:
- "It might be a good idea to reach out to someone on the FxA team to validate some of these suspicions (e.g., if onAuthenticated is called with a null profile, state is "successful authentication without a profile." It's possible that it's some weird edge case in the service."
- "Is there any potential overlap between these states? NEEDS_REAUTHENTICATION seems like it might be a substate of NOT_AUTHENTICATED, for example."
  - We should be sure it's clear when these states are possible (e.g. kdoc)
