### ISSUE TITLE
The images/thumbnails from LAT installation screen are not updated

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2531]
## Steps to reproduce
1. Reach the section where LAT FF for Fire TV can be installed.
2. Observe the images.
### Expected behavior
The images from installation section should be updated to the current design.
### Actual behavior
The images from installation section are not updated.

### Device information
* Fire TV device: **`Fire Stick 2nd Gen.`**
* Latest affected Firefox version: **`FF for Fire TV 4.0-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 3.11`**
* Turbo Mode: **`N/A`**
![20190712_114852](https://user-images.githubusercontent.com/42831109/61118232-f134c200-a4a0-11e9-80fa-4e4ef40b335c.jpg)
![20190712_114839](https://user-images.githubusercontent.com/42831109/61118234-f3971c00-a4a0-11e9-9fcd-79db3cf95123.jpg)

**Comment by athomasmoz** [comment]
New screenshots are already submitted for 4.0 release. Please check post-release

**Comment by athomasmoz** [comment]
@abodea can you check if this is still an issue?

**Comment by abodea** [comment]
@athomasmoz please note that for the `Test` LAT I can still see this issue. For the RC everything is updated.

**Comment by athomasmoz** [comment]
Oh, that's surprising. We probably need to change them in both places. Let's keep this open, but mark a little lower priority, since it's only testers using the LATs

**Comment by dnarcese** [comment]
I updated the images on the LAT to match the release images.
