### ISSUE TITLE
Add Twitch.tv on the Pinned Tiles section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2534]
### Why/User Benefit/User Problem
As a FF user, I want twitch.tv to be on the top Tiles from the section. This being one of the most popular streaming platform, owned by Amazon.
### Acceptance Criteria (how do I know when I’m done?)
Twitch.tv is displayed on the Pinned Tiles.

**Comment by athomasmoz** [comment]
@abodea part of our selection criteria for sites on the homecsreen is whether or not they already have a Fire TV app. Twitch has its own Fire TV app, so I'm not aware of a need from users to access it through the web

**Comment by athomasmoz** [comment]
@abodea part of our selection criteria for sites on the homecsreen is whether or not they already have a Fire TV app. Twitch has its own Fire TV app, so I'm not aware of a need from users to access it through the web
