### ISSUE TITLE
Send notes on challenges setting up FxA to FxA team

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2538]
Follow-up to #2445.

### Vision statement / What / Requirements
- There are breaking changes in the a-c landing on Tuesday so they need to be addressed eventually - might as well do it now while I'm familiar with the code
- There are no tests for that PR (a good practice)
- I have feedback for Grisha from my experience integrating FxA

### Acceptance criteria
- [x] ~~Rebase on latest a-c, which has breaking changes for this code~~ The original PR hasn't landed yet so I'll manage the rebase there
- [ ] ~~Write tests for core functionality~~
- [ ] Send feedback on FxA docs to Grisha
- [ ] Verify sync scopes are defined correctly. One of:
  - *if you can get at the token by hand, you can post it to our verify endpoint and it will tell your various interesting things about the token: https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/docs/api.md#post-v1verify*
  - *i'd make a build that requests sync scope manually; install that build, login to fxa. then make a build which removes manual scope, and introduces history or bookmarks sync. `adb install -r` that build, and make sure everything keeps working and you're not prompted to re-login*
  - *could he just call `getAccessToken("oldsync")` and see if that works, or is that hidden behind too many API layers?; that's exposed on the account object account-manager exposes*

### Timebox

2 days

**Comment by liuche** [comment]
@mcomella will send his notes to the FxA team, and we will move this out of the sprint.

**Comment by mcomella** [comment]
I documented my challenges [in this doc](https://docs.google.com/document/d/1pClm1YruqbPnjcYT7tm8CWebPAJNWUiSxVW7cXyvbOg/edit#) and will share it with the FxA team.
