### ISSUE TITLE
TV Guide Onboarding Displayed for All EN Locales

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2543]
## Steps to reproduce

1. Freshly install Firefox for Fire TV
2. Open it from an EN locale outside of the US (ie. Canada) with the TV Guide experiment turned on

### Expected behavior

No TV guide onboarding displayed

### Actual behavior

TV guide onboarding is displayed

### Notes

The locale configuration for TV guide onboarding should match the configuration for the new channels. To ensure these don't fall out of sync in the future, the code for the onboarding should delegate to existing show/hide logic in ChannelConfig

### Device information
* Fire TV device: Stick basic
* Latest affected Firefox version: 4.0-LAT2
* Earliest affected Firefox version: 3.11
* Turbo Mode: n/a

**Comment by mcomella** [comment]
@Baron-Severin Thanks for picking this up - I completely overlooked the fact that it needed to go into this release.
