### ISSUE TITLE
[meta][a11y] Support VoiceView for visually impaired users (basics)

### ISSUE THREAD

**Issue by yzen** [mozilla-mobile/firefox-tv#255]
Issues raised by :eeejay:
- [x] #292
- [x] #293 
- [x] #295

Docs: https://developer.amazon.com/docs/fire-tv/differences-from-android-tv-development.html#accessibility

---

At least based on this review: https://www.amazon.com/gp/customer-reviews/R1NQLY9SIOT4ZE/ref=cm_cr_getr_d_rvw_ttl?ie=UTF8&ASIN=B078B5YMPD Firefox does not seem to be accessible for users who are blind.

**Comment by bbinto** [comment]
Meeting with the accessibility team to discuss next steps

**Comment by mcomella** [comment]
#300 and #301 would be nice to do here (automatically enabling/disabling review mode based on state) but we should prioritize them.

**Comment by mcomella** [comment]
All depending bugs completed.

**Comment by jonisavage** [comment]
I've added VoiceView support as a "new feature" bulletpoint in https://support.mozilla.org/en-US/kb/firefox-fire-tv. From what I understand, we don't need an article because the feature happens automatically through the Fire TV settings?

**Comment by Sdaswani** [comment]
Yes, a11y is enabled by the user through the Fire TV settings, so I leave it to @bbinto if we need an article on it.
