### ISSUE TITLE
YouTube Welcome Screen is not displayed when accessing a Pocket Video for the first time

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2560]
## Steps to reproduce
1. Install FF for Fire TV.
2. Launch FF.
3. Select and open any YT video from Pocket.
### Expected behavior
The YT welcome screen should be displayed when launching any video for the first time.
### Actual behavior
The Welcome Screen is not displayed, and the video starts playing.
### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?
* Turbo Mode: On/OFF
### Notes
Please note that if opening a video from Pocket, and then tapping back, when the video will be closed the Welcome Screen is displayed.
[Video](https://drive.google.com/file/d/1Z9ao5hRRkxApVDqVKbt4-HMNZdRrinX4/view?usp=sharing)

**Comment by athomasmoz** [comment]
Thanks for logging. This is actually by design, so that users don't have an additional step between clicking to watch their video & the video starting
