### ISSUE TITLE
Users are Unaware they can pin tiles

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2565]
### Why/User Benefit/User Problem

I commonly see reports online like this one "Firefox offers eight pre-selected shortcuts. You cannot edit them, you cannot add new ones, and they’re not very useful." 

The ability to pin / bookmark tiles is a great feature for our users so that they can quickly return to their favourite sites, but they aren't aware of it.

### Acceptance Criteria (how do I know when I’m done?)

* Design proposed to improve discoverability of pinning
* Test plan set up to measure results (could be user research or A/B tests)

**Comment by athomasmoz** [comment]
Ideas:
* Show one-line toolbar when scroll to top of webpage
* Experiment with changing name/icon to bookmark
* Add a "your pinned tiles" section, or move our tiles into the new categories (Entertainment)

**Comment by dnarcese** [comment]
@brampitoyo Do you have specific plans/mocks for this bug already? I was thinking that "Experiment with changing name/icon to bookmark" would be an easy experiment to try. We have some room in this sprint, so I was wondering if this would be a good idea to pickup? (cc @athomasmoz)

**Comment by brampitoyo** [comment]
@dnarcese In the short term, let’s go with your suggestion of “Experiment with changing name/icon to bookmark”.

The changes are as follows.

## 1. Change icon from 📌 to ⭐️

* [bookmark outline](https://cl.ly/47c832f32b0f/bookmark-outline.svg)
* [bookmark filled](https://cl.ly/991c147d4f56/bookmark-filled.svg)

## 2. Change terminology from “pin” to “bookmark”

* Section title: “Pinned Sites” → “Top Sites”
* Button label: “Pin to homescreen” → “Bookmark this page to Top Sites”
* Toast: “Pinned to Firefox TV homescreen” → “Bookmark saved to Top Sites”
* Button label: “Unpin from homescreen” → “Remove bookmark from Top Sites”
* Toast: “Removed from Firefox TV homescreen” → “Bookmark removed from Top Sites”
* Modal dialogue: “Remove [sitename] from Pinned sites?” → “Remove [sitename] from Top Sites?”

## 3. Change order of animation

Currently, when you pin or unpin a site, we do things in this order:

1. Return to webpage
2. Show confirmation toast
3. If you press _Menu_ or _Back_ button, tile will animate in or out

We’d like to clarify that a bookmark has been added, so let’s do things in this order:

1. Animate tile in or out (it will be slightly below the fold – that’s ok), then wait for ~0.25 seconds
2. Return to webpage
3. Show confirmation toast

## Some things stay the same

* Don’t change the star icon to blue when a site is bookmarked
* Don’t put a blue star next to the site name, when it’s bookmarked

**Comment by athomasmoz** [comment]
Closing this as it was the UX story, which is now completed. First implementation story is #2631
