### ISSUE TITLE
Use DeviceType.TV in FxA configuration

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2567]
### Vision statement / What / Requirements
Users will expect to see a TV icon for Fire TV in their accounts.firefox.com dashboard: we should use the DeviceType.TV that FxA is adding in: https://github.com/mozilla/application-services/issues/1407

### Acceptance criteria
- [ ] FFTV FxA config uses DeviceType.TV

**Comment by eoger** [comment]
Blocked on https://github.com/mozilla-mobile/android-components/pull/4114 riding the a-c train.

**Comment by eoger** [comment]
It's available by the way :)

**Comment by mcomella** [comment]
Thanks for the heads up: it looks like this was closed in https://github.com/mozilla-mobile/firefox-tv/commit/a58cbd51dcb952eb3c1541c7afa6113a8e399075
