### ISSUE TITLE
The FxA button doesn't have a text when it is selected

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2584]
## Steps to reproduce
1. Launch FF for Fire TV.
2. Select the FxA button.
### Expected behavior
There is a text under the button representing what that button means/is.
### Actual behavior
Nothing is displayed.
### Device information
* Fire TV device: **`Fire TV Stick 4k and 2nd Gen Stick`**
* Latest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Earliest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Turbo Mode: **`On And Off`**
![20190725_164458](https://user-images.githubusercontent.com/42831109/61879589-fe6b9b00-aefb-11e9-90a6-437e315f907e.jpg)

**Comment by athomasmoz** [comment]
This functionality is not yet implemented. Will be covered in #2489
