### ISSUE TITLE
[FxA] The main screen elements from FxA cannot be accessed anymore after returning from Terms of Service

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2587]
## Steps to reproduce
1. Launch FF for fire TV.
2. Access the FxA section.
3. Acces `Terms of Service` from FxA,
4. Scroll Up and Down a few times.
5. Tap back.
6. Tap on the up button from the remote.
### Expected behavior
The Main Menu of FxA is correctly displayed and every section from it can be accessed(Email, Continue button, Terms of Service, Privacy Notice)
### Actual behavior
There is a yellow margin displayed and nothing can be accessed in FxA main screen.
### Device information
* Fire TV device: **`Fire TV Stick 4k and 2nd Gen Stick`**
* Latest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Earliest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Turbo Mode: **`On And Off`**
![20190725_181917](https://user-images.githubusercontent.com/42831109/61887012-73919d00-af09-11e9-86b6-205dced43b8d.jpg)

**Comment by mcomella** [comment]
I have a larger concern for FxA: afaik, the web isn't designed to be navigated with 4-way dpad by default so websites need to implement additional functionality to support this use case. I'm concerned that the FxA sign in flow has not implemented these controls and so we'll run into many edge case issues like this where focus is no longer on the proper elements.

**Comment by athomasmoz** [comment]
Submitted to FxA https://github.com/mozilla/fxa/issues/2023

**Comment by npark-mozilla** [comment]
I cannot repro this issue - after pressing cursor, I can get focus on each clickable elements.  Closing for now.
