### ISSUE TITLE
https://www.tvnow.de/ tries to rotate the screen

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#259]
Via Amazon store review

https://www.amazon.de/review/R1MKGYGJ2GZRAF/ref=cm_cr_dp_title?ie=UTF8&ASIN=B078B5YMPD

Another review:
Requesting to change user agent as the website redirects to mobile website

... man müsste den Useragent umstellen können. Es wird zum Beispiel bei tvnow.de die mobile Seite aufgerufen, was sie nicht nutzbar macht. Habe jetzt den Silk Browser installiert. Schade.

**Comment by bbinto** [comment]
See #202

**Comment by athomasmoz** [comment]
Request desktop site has been added as workaround.
