### ISSUE TITLE
CBS sports video playback is broken for Fire TV

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2598]
## Steps to reproduce
1. Launch FF.
2. Access https://www.cbssports.com.
3. Select and play any video.
### Expected behavior
The videos are working correctly.
### Actual behavior
The videos are not playing and the following error is displayed: **`This video is not available on your platform`.**
### Device information
* Fire TV device: **`Fire TV Stick 4k and 2nd Gen Stick`**
* Latest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Earliest affected Firefox version: **`Firefox TV v4.0`**
* Turbo Mode: **`On And Off`**
## Important Notes:
CBS Sports website is not working at all, I tried on the following devices/browsers:
- **Android devices with Fenix, Fennec, Google Chrome, Samsung Internet, Brave, Focus**
- **iOS devices with Safari, Firefox browsers**
- **Desktop with Google Chrome, Firefox, Brave, Opera,** 
- **Fire TV with Firefox and Silck.**
The only thing that is working on this websites are ADS, playing over and over.
![20190726_102845](https://user-images.githubusercontent.com/42831109/61934987-302f4100-af92-11e9-9c79-25a2c2de88f4.jpg)

**Comment by abodea** [comment]
Related to #2526.

**Comment by npark-mozilla** [comment]
If this site is working on SF, it's probably only being serviced within US, with a terrible error msg for outside US.

**Comment by athomasmoz** [comment]
Tried this on my stick basic in CA and the videos worked. No error message

**Comment by athomasmoz** [comment]
Determined playback only available in US.
