### ISSUE TITLE
CBS Sports and SB Nation thumbnails images are not updated

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2600]
## Steps to reproduce
1. Launch FF.
2. Scroll down and select the sports section.
3. Notice CBS Sports and SB Nation.
### Expected behavior
Those two websites thumbnails should be updated.
### Actual behavior
The default thumbnails are displayed.
### Device information
* Fire TV device: **`Fire TV Stick 4k and 2nd Gen Stick`*** Latest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Earliest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Turbo Mode: **`On and Off`**
![20190726_110552](https://user-images.githubusercontent.com/42831109/61936645-d761a780-af95-11e9-93ce-48e7bb992cc8.jpg)

**Comment by athomasmoz** [comment]
Closing as we removed the tiles, so no longer relevant
