### ISSUE TITLE
radio.de doesn't work (pop up issues)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#262]
via review

https://www.amazon.de/review/R3V1WG0JC0H49Y/ref=cm_cr_dp_title?ie=UTF8&ASIN=B078B5YMPD

**Comment by bbinto** [comment]
#267

**Comment by mcomella** [comment]
I can't reproduce on the Android TV emulator – @bbinto can you reproduce?

I do notice a lot of inline ads though.

fwiw, I was trying to reproduce to see if we could dupe to #267.

**Comment by bbinto** [comment]
Same with me, I couldn't reproduce, closing for now (I'll reach out to the user again)
