### ISSUE TITLE
Add JUnit rule to simplify testing async Rx code

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2626]

**Comment by mcomella** [comment]
@Baron-Severin Please elaborate on a description here.

P3: this bug is to re-use test code. When we actually need to re-use it again, we can revisit this.

**Comment by Baron-Severin** [comment]
> @Baron-Severin Please elaborate on a description here.
> 
> P3: this bug is to re-use test code. When we actually need to re-use it again (which may be a little ways off), we can revisit this.

@mcomella This bug was opened to track work that 1) didn't fit exactly into another story where it was needed, and 2) was quick to write (a few hours).  Spending time filling out issues for work like that doesn't seem particularly valuable to me.  I feel that it also discourages opening them in the first place, resulting in larger, sprawling PRs.

**Comment by mcomella** [comment]
On Wed, Jul 31, 2019 at 12:53 PM Severin Rudie <notifications@github.com>
wrote:

> @Baron-Severin <https://github.com/Baron-Severin> Please elaborate on a
> description here.
>
> P3: this bug is to re-use test code. When we actually need to re-use it
> again (which may be a little ways off), we can revisit this.
>
> @mcomella <https://github.com/mcomella> This bug was opened to track work
> that 1) didn't fit exactly into another story where it was needed, and 2)
> was quick to write (a few hours). Spending time filling out issues for work
> like that doesn't seem particularly valuable to me. I feel that it also
> discourages opening them in the first place, resulting in larger, sprawling
> PRs.
>

My comment was written during triage when weren't sure how to prioritize
the issue. In the future, it'd be good to mention it's something that you
intend on closing now so we know how to handle it in triage. Also, was this
issue added to the project board? We should make sure it's there so we can
track it for velocity measurement.

**Comment by Baron-Severin** [comment]
Yeah, that was my bad. I'll make sure to be more clear about that in the future. I haven't moved it in yet, but I will today.
