### ISSUE TITLE
[FxA] The text blinking cursor is moved to the last password character

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2638]
## Steps to reproduce
1. Launch FF.
2. Access the `Send Tab` menu.
3. Enter any valid FF email.
4. On the password field, add any text/correct password.
5. On the password field move the blinking cursor to the beginning of the password.
6. Tap on the password field in order to reach the section where you can type the password.
### Expected behavior
The blinking cursor should be at the beginning of the password.
### Actual behavior
The text blinking cursor is moved to the last password character.
### Device information
* Fire TV device: Fire Stick 4k.
* Latest affected Firefox version: **`Firefox TV v4.2 LAT1`**
* Earliest affected Firefox version: **`Firefox TV v4.1 LAT2`**
* Turbo Mode: On/Off
[Video](https://drive.google.com/file/d/1y_m95sx62yWcs0iD8RY4u6GOsafURYv4/view?usp=sharing)

**Comment by athomasmoz** [comment]
Closing off as lower priority compared to effort. Would either mean a custom keyboard, or working with FxA team to prevent users from being able to move the cursor within the field
