### ISSUE TITLE
[FxA] Implement the functionality to edit a password

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2639]
### Why/User Benefit/User Problem
As a FF user if I add 1 wrong character to my password, I want to be able to modify it and not delete all the characters until I can reach the wrong entered character.
### Acceptance Criteria (how do I know when I’m done?)
When adding a wrong password with small mistakes, the password can be edited.

**Comment by athomasmoz** [comment]
This would likely require a custom keyboard. It's not worth the effort to implement, so I'm closing this off for now
