### ISSUE TITLE
Accounts & receive tab screenshots for l10n review

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2648]
### Why/User Benefit/User Problem

We want to send screenshots to l10n to verify different localizations of the accounts and receive tabs strings, so that our users in different locales can understand our marketing & instructions

### Acceptance Criteria (how do I know when I’m done?)

* Screenshots of accounts strings have been send to l10n team for verification
* Screenshots of receive tabs strings have been send to l10n team for verification

### Notes

* [List of strings](https://docs.google.com/spreadsheets/d/1z852T9AKhFpQFq8JcX633-zsC81vxAkKYKyilwdistU/edit?ts=5d423a76#gid=0)
* This is expected to be done by QA and there's no dev work needed here

**Comment by npark-mozilla** [comment]
This should be the last task for the Account and Receive Tabs feature, once the dev work is completed

**Comment by npark-mozilla** [comment]
Screenshot is sent to l10n team: https://drive.google.com/file/d/1khpru0pPY8BKY36Yz97wnbcSyubxSkSn/view?usp=sharing
