### ISSUE TITLE
Support tv.youtube.com

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#265]
“I'm enjoying Firefox for Amazon Fire TV Stick and YouTube app despite the looming and controversial removal of main YouTube app on New Years 2018. I like to ask a question about the app.

Does it work with YouTubeTV (which is a subscription service $35 a month for Cord Cutters which includes locals in about 84 markets as of 2017) and watch locals on there? If not, tell us why? Are you aware of YouTube's YouTubeTV? 

https://tv.youtube.com “

**Comment by boek** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/1250545/34689317-e65fb44a-f469-11e7-86ef-581dd1e652ef.png">

My guess is we'll not be able to get this to work :(

**Comment by Sdaswani** [comment]
Another user report on this: https://support.mozilla.org/en-US/questions/1239990

**Comment by Sdaswani** [comment]
Closing as duplicated by #1500.
