### ISSUE TITLE
Default search engine not using the replaced search code

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2664]
## Steps to reproduce
Type in a search term and trigger search

### Expected behavior
Search url includes client referer google-b-1-amzftv

### Actual behavior
Search url includes client referer firefox-b-1-m

### Acceptance Criteria
Write additional tests for this case
Communicate w/ Search team (mconnor) when this fix will go in

### Device information
* Fire TV device: all
* Latest affected Firefox version: master 134fc3f
* Earliest affected Firefox version: probably not fixed w/ #2462 
* Turbo Mode: NA

**Comment by liuche** [comment]
Previous PR [here](https://github.com/mozilla-mobile/firefox-tv/pull/2507).

**Comment by liuche** [comment]
@mcomella also, could we get this into the 4.2 release? I think it's pretty low risk, and it's already broken anyway, and I'd like to get this out so that we can get more visibility since Q4 planning is going on....

**Comment by liuche** [comment]
Adding the QA ready label.

The only thing that we should test here is that when we search through the input bar (like "cats") that the search url is a) a Google url, that b) contains the `google-b-1-amzftv` referer id in US, or the `google-b-amzftv` for non-US.

**Comment by liuche** [comment]
I've also followed up with mconnor, to ping us at the end of next week ~8/16 if he doesn't start seeing this on his end, after we do our release.

**Comment by abodea** [comment]
#### Hi, please note that I checked this issue on the latest master build here are my results:
| Device  | Region |Search Engine | google-b-1-amzftv|  google-b-amzftv|
| :-------------: | :-------------: |:-------------:| :-----:| :-----:|
| Fire TV Stick 2nd Gen   | EN-US    | Google | ✅  | ❌  |
| Fire TV Stick 2nd Gen   | non-US (**UK**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**Canada**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**Australia**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**India**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**Mexico**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**Espana**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**France**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**Osterreich**)   | Google | ❌  | ✅   |
| Fire TV Stick 2nd Gen   | non-US (**Deutschland**)   | Google | ❌  |  ✅  |
| Fire TV Stick 2nd Gen   | non-US (**Italia**)   | Google | ❌  |  ✅  |
| Fire TV Stick 2nd Gen   | non-US (**Brasil**)   | Google | ❌  |  ✅  |
| Fire TV Stick 2nd Gen   | non-US (**Japan**)   | Google | ❌  |  ✅  |
| Fire TV Stick 4k  | EN-US   | Google | ✅  |  ❌   |
| Fire TV Stick 4k  | non-US(**UK**)   | Google | ❌  |  ✅     |

#### I searched for different random words while testing. 
#### Also, note that after I changed the locale a restart was needed for each locale. When I changed back to `EN-US` the `google-b-1-amzftv` was always displayed.
Verified as fixed on the latest master debug build.
