### ISSUE TITLE
[FxA]Navigation issue on login page

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-tv#2666]
## Steps to reproduce
1. Navigate to the FxA page
2. Tap down on the dpad to reach "Terms of Service"
3. Tap right on the dpad to reach "Privacy Notice"

### Expected behavior
By tapping to the right the user should be able to navigate from the "Terms of Service" to the "Privacy Notice"

### Actual behavior
Can't navigate to the right.
The only way to access the "Privacy Notice" link is to navigate down.

### Device information
* Fire TV device: **Fire TV Stick 2nd Gen**
* Latest affected Firefox version:  Firefox for Fire TV v4.2 LAT2 
* Earliest affected Firefox version: Firefox for Fire TV v4.1 LAT2
* Turbo Mode: ON

**Comment by athomasmoz** [comment]
Closing as lower priority. This will no longer be relevant after FxA changes.
