### ISSUE TITLE
[FxA]Drop blue highlight in input boxes

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-tv#2672]
## Steps to reproduce
1. Navigate to FxA
2. Enter an email address and submit
3. Navigate back up to the Email input box
4. Observe the blue highlight of the previously entered email

### Expected behavior
No practical use of the input being selected (highlighted in this case)

### Actual behavior
Input is highlighted (selected) but offers no tools or options to actually take any advantage of this.

### Device information
* Fire TV device: **Fire TV Stick 2nd Gen**
* Latest affected Firefox version: **Firefox for Fire TV v4.2 LAT2**
* Earliest affected Firefox version: **Firefox for Fire TV v4.2 LAT2**
* Turbo Mode: ON

**Comment by athomasmoz** [comment]
Hey @AndiAJ , do you mind adding a screenshot to help with prioritization of this issue?

**Comment by AndiAJ** [comment]
Hi @athomasmoz , please find attached the video

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51314259/63412195-e35b5080-c3ff-11e9-9f5e-a617805c5263.gif)

**Comment by athomasmoz** [comment]
Thanks for the extra details! I believe this is expected behaviour, so closing this one off.
