### ISSUE TITLE
Remove `tools/search` directory, which appears to be unused

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2678]
### Vision statement / What / Requirements
We used to generate our search engines from this directory but now they're generated from a-c and this directory appears to be unused.

### Impact
If undone, devs may be confused and waste time changing unused files.

### Acceptance criteria
- Verify directory is unused
- Directory is removed

**Comment by mcomella** [comment]
QA: we removed a directory that (we think) used to be used to generate our search engines. Please verify our search engines are still working correctly after this change.

**Comment by abodea** [comment]
Verified as fixed on the 4.3-LAT1 using 4k stick.
Note that everything worked as expected.
