### ISSUE TITLE
Language Support on Amazon developer dashboard lists locales we don't translate, doesn't list locales we do

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2682]
### Vision statement / What / Requirements
Language support lists:
> Chinese, English, French, German, Hindi, Japanese, Korean, Russian, Spanish

In our APK:
- supported langues: "de", "en-US", "es-ES", "fr", "it", "ja", "pt-BR", "zh-CN"
- We don't bundle Hindi, Russian, or Korean
- We additionally support Brazilian Portuguese (could this be the source of people stuck on an older build?)

### Impact
We may be shipping builds to users we don't intend to – probably with English strings – and not shipping builds to users we intend to.

### Acceptance criteria
- Verify we're shipping only to the locales that we support (in the Amazon dashboard)
- If not, fix

**Comment by dnarcese** [comment]
I will update our language support in the 4.5 release.

**Comment by dnarcese** [comment]
From Amazon docs https://developer.amazon.com/docs/app-submission/distribute-your-app-internationally.html#supported_languages:
> This "Language Support" section adds these supported languages to the device's app details page in the Appstore, letting users know which languages your app supports. The section does not impact any Appstore logic in regards to localization.

So, changing these languages in the release dashboard does not affect which countries get the app, it goes to every country by default. It just lets users know which languages we support. So we should update it to be accurate.

**Comment by dnarcese** [comment]
Dashboard is now updated with language support: Chinese, English, French, German, Italian, Japanese, Portuguese, Spanish.
