### ISSUE TITLE
UX: Turbo Mode Rebrand

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2687]
### Why/User Benefit/User Problem

User interviews showed that the "turbo mode" name did not reflect the added privacy from this feature
Better align with other Firefox branding, 

### Acceptance Criteria (how do I know when I’m done?)

* Updated design for onboarding screen that rebrands as Enhanced Tracking Protection
* Updated icon & description for toolbar
* Updated icon & description for settings

### Notes

This will be A/B tested initially

**Comment by brampitoyo** [comment]
> Updated design for onboarding screen that rebrands as Enhanced Tracking Protection

https://drive.google.com/file/d/1HoQQtap4p4tB3CK8L6wfPhIQqcWEEtpE/view?usp=sharing

Copy:

**Enhanced Tracking Protection**

Protect your privacy while you browse. Block invisible content that tracks the site you visit and profiles you. Blocking some of this content may make pages load faster.

-----

> Updated icon & description for toolbar
> Updated icon & description for settings

* Icon: https://drive.google.com/file/d/1HqzFEkje0PSmpkS_4yYHrTYQvotX866s/view?usp=sharing
* Description: Enhanced Tracking Protection

The same icon and description applies to both, although I have a concern that **the Settings description may not fit**. What do you think, @athomasmoz @dnarcese?

Maybe this is another problem that can be solved with scrolling text.

**Comment by dnarcese** [comment]
@brampitoyo Yes, I think scrolling text would be a great candidate here.

**Comment by athomasmoz** [comment]
This looks awesome @brampitoyo ! I love how you kept it consistent with Desktop. A few notes:
* For the onboarding screenshot, do you mind removing the settings cog, since it's no longer there
* We don't have turbo mode in the settings section yet. I think we should exclude it from the A/B test, but have another ticket to add it in. If someone was to click on the turbo mode settings, what's the expected behaviour? Should we just show them the onboarding screen?

**Comment by brampitoyo** [comment]
@athomasmoz Thanks for your eagle-eyed observations!

> For the onboarding screenshot, do you mind removing the settings cog, since it's no longer there

I’ve removed the Settings cog from onboarding, and updated the asset link above:

https://drive.google.com/file/d/1L3XCXUEgnbdx7J8CrKHqjjlngo__qJuF

> If someone was to click on the turbo mode settings, what's the expected behaviour?

The Enhanced Tracking Protection tile should be an ON/OFF toggle when clicked, with slightly different title and icon on both states.

![Homescreen - focus Settings tile 1@2x](https://user-images.githubusercontent.com/51007/63236471-dae50780-c291-11e9-8839-7b6fcfbc149c.png)

![Homescreen - focus Settings tile 1@2x](https://user-images.githubusercontent.com/51007/63236523-15e73b00-c292-11e9-99d7-2a9e64c238a0.png)

Since ETP is already a prominent toggle on the toolbar, there’s no urgency to make it a Settings menu item right this moment.

**Comment by athomasmoz** [comment]
We recently found that the turbo mode onboarding image uses up a lot of disk space #2703 , please keep that in mind when adding the new image. cc @brampitoyo

**Comment by brampitoyo** [comment]
@athomasmoz Originally, I thought that disk space wasn’t an issue for us (stable wifi at home, video streaming uses up a lot of space already), but I didn’t know that our APK size was ~5.5 MB.

This meant that the onboarding graphic alone (at 1 MB) took up nearly 20% of our APK size! I converted it to the JPG format on “Medium” quality setting, and this dropped the size to ~200 KB. The link above has been updated. Hope that solves our problem.

**Comment by liuche** [comment]
Proposal: 
Combine FFTV list w/ Desktop list

Open questions:
- Would we be missing any sites with this approach
- How up to date do we need to stay up to date with the ETP? (Maybe AC will update)
- Can we use what AC is using? (How complicated is it to combine lists? maybe need to talk to AC)

**Comment by athomasmoz** [comment]
Closing in favour of first eng ticket: #2689
