### ISSUE TITLE
YouTube: Issues with playlists and subscribed channels after logging in

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#269]
https://www.amazon.co.uk/review/R9TLH4MYNTXAJ/ref=cm_cr_dp_title?ie=UTF8&ASIN=B078B5YMPD

"Logging in with YouTube doesn't even allow loading of playlists or subscribed channels. A waste of time. Clunky UI with no bookmarking."

**Comment by npark-mozilla** [comment]
I cannot reproduce this bug with basic fire stick (and accessing Youtube Canada).  My playlists and subscriptions, including history are all accessible.

**Comment by bbinto** [comment]
Ok, let's close this then.
