### ISSUE TITLE
Confirm Telemetry on Account Login & Receive Tab

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2693]
### Vision statement / What / Requirements

As a Product Manager, I want to capture action counts for new features, so that I can measure success, but still maintain users' privacy

### Acceptance criteria

* The new telemetry probes added for Accounts & Receive tab have been reviewed
  * All required probes are added
  * No personal information is collected
  * No information that could determine the site or page of a received tab is tracked
* Telemetry documentation is updated to reflect the changes

### Telemetry Probes

* Pre-boarding:
  * Pre-boarding screen shown
  * Sign in
  * Not now
* Toolbar:
  * Send tabs button clicks
  * Account button clicks
  * Re-authenticate clicks
* Onboarding
  * Onboarding screen shown
  * Okay button clicks
* Tab received
  * Tab received event
  * Including what type of device (high level only, desktop/ios/android) if possible
  * This **should not** include any information on the tab that was sent (ie. URL)
* Accounts
  * Account page view
  * Received tab tutorial clicks
  * Disconnect clicks
* Login state (logged in, not logged in, needs to re-authenticate)

**Comment by athomasmoz** [comment]
We are comfortable calling this story done if it has been checked locally.

**Comment by mcomella** [comment]
afaik, this was reviewed by No-Jun and he provided a label so I think it can be closed.
