### ISSUE TITLE
Follow-up: Fix more sites for "mp4 videos distorted in fullscreen after scrolling"

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2700]
Bugs #2540 and #2541 fixed this issue for some sites: this follow-up is to fix these bugs on other sites (e.g. youtube desktop). Those bugs are similar enough to merge them into a single follow-up bug.

## Steps to reproduce
_See those other bugs above for a more detailed STR._
- Go to an affected site w/ videos
  - https://youtube.com?app=desktop
  - https://www.travelandleisure.com/video – this can be a slow page, as documented below, but works correctly when the page has a chance to fully load.
  - ?
- Scroll page
- Fullscreen video

### Expected behavior
Video is fullscreened & undistorted

### Actual behavior
Video is fullscreened but distorted, usually with a black offset

### Device information
* Fire TV device:
  * 4k pendant: video is crunched & black offset
  * 4k Stick, Stick gen 2: video has black offset
* Latest affected Firefox version: v4.3-LAT1
* Earliest affected Firefox version: ?
* Turbo Mode: ?

---

### Known issues that we can also address:
- This fix is expected to work most of the time but may fail on slow web pages (it uses time outs to work around platform behavior)

**Comment by athomasmoz** [comment]
@npark-mozilla is running some tests after the initial fix. We can update this ticket & prioritize based on the results from that

**Comment by mcomella** [comment]
#2798 seems like a better issue to track this all in.
