### ISSUE TITLE
turbo_mode_onboarding and 2 other images use 1.64 MB of disk space

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2703]
### Vision statement / What / Requirements
For a size reference, before shipping FxA, our app size was around 5.43 MB.

Three images now take up 1.6 MB combined in the latest APK (though we may not have had those images in that older APKs):
- `turbo_mode_onboarding.png` - 1005 KB
- `pocket_channel.png` - 399 KB
- `tv_homescreen_onboarding.png` - 287.9 KB

### Impact
Large APK sizes, on mobile, are shown to decrease install rates. Also, larger APK sizes slow down the app.

By comparison, Glean will add ~0.5 MB to the APK and FxA will add 3 MB (once we fix it: #2647). GV is 45 MB.

### Acceptance criteria
- Large images are reduced in size, if possible

---

Besides copying the files into the repository, there is nothing for engineering to do here.

@brampitoyo, do you have any quick wins to reduce the size of these files? Running all the image files in the app through my optimizer (ImageOptim) reduces the entire collection of images by only 20 KB.

**Comment by brampitoyo** [comment]
@mcomella I’ve converted the image to a medium-quality JPG, and now it sits at ~200 KB:

https://drive.google.com/file/d/1I4dqxyFhfsR-lGAlqoVkZ3x1xtcGC82P

Will it help?

**Comment by mcomella** [comment]
@brampitoyo Yes! I haven't verified how the lossy compression looks on device yet but it does greatly reduce the impact of this image in a non-trivial way. Can you make a similar change for the other two images I mentioned?

**Comment by brampitoyo** [comment]
@mcomella Good to know. Thanks! Let me file a separate GitHub issue to replace and minify the image.

**Comment by brampitoyo** [comment]
* `tv_homescreen_onboarding.png` – 287.9 KB → 141.8 KB
https://drive.google.com/file/d/1Itt1YXyRMSIgntDP3rXkPE-C4YurCEJO
* `pocket_channel.png` – 399 KB → 123.6 KB
https://drive.google.com/file/d/1IP-JC-3KrEetptIBhA2CsAvijlXIJ1oQ
* `turbo_mode_onboarding.jpg` exported and minified differently – 200 KB → 132.4 KB.
Same link: https://drive.google.com/file/d/1I4dqxyFhfsR-lGAlqoVkZ3x1xtcGC82P

**Comment by mcomella** [comment]
Note: trivial work so I'm not sizing but pulling into sprint because I'm working on it.

**Comment by mcomella** [comment]
@brampitoyo We're not using enhanced tracking protection yet – we're still on turbo mode – but the image provided is for tracking protection.

**Comment by brampitoyo** [comment]
@mcomella 🤦‍♂️ Sorry, this was totally my mistake. Thank you for catching it.

Turbo Mode onboarding was located in a different folder. Link: https://drive.google.com/file/d/1Jf2_tUNxgOukY948HWZ-mRcjY5RADApK

**Comment by mcomella** [comment]
QA: please make sure the turbo mode and TV guide onboarding images still look good. :)

**Comment by mcomella** [comment]
Closed by https://github.com/mozilla-mobile/firefox-tv/commit/6bae3a9f45a79c84bd2a162ff9928a352ff0e06c.

**Comment by npark-mozilla** [comment]
LGTM on Cube
