### ISSUE TITLE
YouTube overrides browser history control?

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-tv#271]
This is an odd one, I think YouTube is messing with the browsers history management:

* Cold start Firefox
* Open the YouTube shortcut
* Hamburger Menu -> Home
* Open the Google Video Search shortcut
* Hamburger Menu -> Home
* Open the Rotten Tomatoes shortcut
* Press the back button

Expected, going back to home either home screen or Google Video Search (unclear what the correct behaviour is)

Actual: YouTube opens, even though it should not be the previous item in the backforward list.

**Comment by mcomella** [comment]
First step: see if we can still repro.

**Comment by liuche** [comment]
We don't seem to have history on newly opened tiles from the home screen anymore, so I can't repro this. (However, it could be that there's some difference between redirects in non-US countries, that are creating a history back stack?)

I do notice some funny Youtube behavior with the back button though - (in the emulator) when you hit back after loading YT from the tile, it acts as if you're "navigating" left, and opens UI (popping open the sidebar menu, and then moving to select the "Home" icon). It doesn't seem like there's much we can do about this.

In any case, closing this issue, please reopen if it's still a problem.
