### ISSUE TITLE
app_banner, which is unused on Fire TV, is 237 KB

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2714]
### Vision statement / What / Requirements
`app_banner.png` is used as the app tile on Android TV: it's unused on Android TV. We could replace it with something tiny to save size in our shipped APK but still support being a tile on Android TV and the emulator.

This is a tiny change that has a size improvement on the scale (100's of KB) of the improvements made by #2703, which replaced some large images with smaller ones to save space in the APK.

### Impact
We save 200+ KB in the app, improving install times for us and users.

There is very little engineering effort here.

### Acceptance criteria
- `app_banner` is replaced with something smaller. It can possibly even be removed because `ic_launcher` may be used instead.

**Comment by mcomella** [comment]
QA: please verify the app icon has not changed on the Fire TV homescreen. This is really only relevant when this hits LAT & production because the app icon in debug builds already uses a placeholder.

**Comment by brampitoyo** [comment]
If we can’t substitute the image, try using this converted + minified JPG, where the size goes down from 237 KB → 152.8 KB.

https://drive.google.com/file/d/1JL44W5Tex4WHuA-1_yIlyQ7SKDtpincQ

**Comment by mcomella** [comment]
Thanks Bram. I should have updated: it looks like the substitution worked but I'll let you know if something went wrong.

**Comment by abodea** [comment]
Verified as fixed in 4.3-LAT2, note that the image didn't changed on the Fire TV homescreen.
