### ISSUE TITLE
Create TestRail test case for Send Tab

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2720]
### Vision statement / What / Requirements
Send tab is an important use case for us but one that's hard to automate: we should create a TestRail case for it.

### Acceptance criteria
- TestRail test case exists & is run for send tab

**Comment by mcomella** [comment]
@athomasmoz You asked me to add this to the backlog but I don't know where to sort it so I left it in the "To be triaged" column.

**Comment by abodea** [comment]
#### Hi, I just finished the test cases for `Send Tab` here are some details:
Under the `send tab` folder you can find:
 - First Launch
 - Onboarding screens
 - Create accounts & Sign in & Logout
 - Send Tab Settings
 - Send tabs(from desktop/mobile)

Included in both FFTV Lite and Basic Functional Tests.
I tried to make sure that it contains a sign up or a login too, being part of the flow.
Based on my comment I will close this issue, let me know if something needs to be modified.
