### ISSUE TITLE
Browser freezes / buffers when streaming live content

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#273]
via feedback email:

"After several minutes of streaming live content it buffers and/or freezes. "

Might be related to #269

**Comment by bbinto** [comment]
More info from the user

The only 2 YouTube live streams I watch with regularity are CNN and Kitten Academy.  The buffering occurs with both.   It normally starts after watching for a while - approx. 30+ minute would be my guess.

I watch shorter videos as well - normally each lasts less than 20 minutes -  but haven't experienced the same problem, that I can recall.  Not sure if that means it's somehow related to the length of time the app is open without being refreshed - if that makes sense.

**Comment by mcomella** [comment]
Related to #230?

**Comment by mcomella** [comment]
Dupe to #268.
