### ISSUE TITLE
Replace full-megazord-forUnitTests with `support-test-appservices`

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2738]
via https://github.com/mozilla-mobile/firefox-tv/pull/2710#discussion_r316145661

### Vision statement / What / Requirements
> With the next release we ship a support-test-appservices component that will include the right [full-megazord-forUnitTests] version as a transitive dependency so that you do not have to sync them manually anymore.

The line to replace is here: https://searchfox.org/mozilla-mobile/rev/8c8b0dac29761cab203489aec508f6bdfd3a1009/firefox-tv/app/build.gradle#215

### Impact
I'm not sure what happens if the dependencies get out of sync: we may get clear or inexplicable build or runtime errors. If we fix it now (a one line, trivial change), we avoid this issue.

### Acceptance criteria
- Replace `full-megazord-forUnitTests` declaration with `support-test-appservices`

**Comment by dnarcese** [comment]
Fixed in #2750
