### ISSUE TITLE
Inconsistent display of facebook watch homescreen image 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-tv#2763]
## Steps to reproduce
1. Navigate to https://www.facebook.com/watch/
2. Check the featured shows image

### Expected behavior
The image is properly displayed

### Actual behavior
Inconsistent display, pixelated image

### Device information
* Fire TV device: **FireTV 4k pendant**
* Latest affected Firefox version: **Firefox for FireTV 4.4-LAT1**
* Earliest affected Firefox version: **Firefox for FireTV v4.0**
* Turbo Mode: ON

### Notes
► Images
![20190829_162154](https://user-images.githubusercontent.com/51314259/63944657-a4ba3b80-ca7a-11e9-95ae-b4908bf7f56e.jpg)

![20190829_162526](https://user-images.githubusercontent.com/51314259/63944626-91a76b80-ca7a-11e9-922d-9aab9101e53c.jpg)

**Comment by athomasmoz** [comment]
This is likely because we are asking for the mobile version of Facebook site. Desktop mode could be a workaround for users.

**Comment by athomasmoz** [comment]
Closing as we are unlikely to address the issue, and the focus should be on pointing users to desktop version
