### ISSUE TITLE
Handle receiving multiple tabs around the same time

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2777]
### Vision statement / What / Requirements
Users can send multiple tabs to a single device. If their device is inactive, these tabs will queue and, when they open Firefox on that device, they'll receive them around the same time.

After consulting with Bram, I went with the simplest technical solution (@brampitoyo please double-check this matches your understanding):
- if you receive multiple in the same push, choose one to open
- If you receive multiple pushes, try to open them all

Essentially, we don't support the user sending multiple tabs to Fire TV at the same time: we should consider whether or not we want to support this. We can use the telemetry we add for send tab to determine if users are received multiple tabs at the same time or not and thus if we should support this.

### Impact
After this change, users can send multiple tabs to their device without worrying.

### Acceptance criteria
- User receives multiple tabs in an actionable way

**Comment by jonalmeida** [comment]
This is a pretty common action; you can select multiple tabs and send them to a device today on desktop, Fenix (and iOS?).

> if you receive multiple in the same push, choose one to open

This isn't a case that is possible today even though the API for receiving tabs in a-c is built for it. Desktop has an implementation that performs individual "pushes" one after each other, it doesn't combine them into one push event. The current a-s send tab APIs also does the same thing as well.

**Comment by mcomella** [comment]
Thanks for explaining the behavior: I didn't realize how users could send multiple tabs in a single push.

> This is a pretty common action; you can select multiple tabs and send them to a device today on desktop, Fenix (and iOS?).

@jonalmeida Are there telemetry numbers to verify that? If so, can you point us to them?

**Comment by jonalmeida** [comment]
> @jonalmeida Are there telemetry numbers to verify that? If so, can you point us to them?

Sorry, by common I meant it's quite a visible option since [enhanced tab management](https://www.theverge.com/2018/12/11/18136370/mozilla-firefox-64-version-tab-management-feature-recommendation) was a major feature of 64, intuition makes me think we should probably support it. :)

**Comment by brampitoyo** [comment]
@jonalmeida I didn’t know that it’s been possible to send multiple tabs from desktop for 9 months. With such a large userbase, we want FFTV to be a good receiver.

@mcomella Can I propose a slight tweak to our behaviour?

-----

Currently, our behaviour for single tabs is pretty simple: if we receive one tab in a push, open it

![send-one-tab](https://user-images.githubusercontent.com/51007/64227208-b7c78280-cf36-11e9-9e50-6af633412ef1.png)

-----

The behaviour that we have outlined for multiple tabs is also pretty simple:

* If we receive multiple tabs in the same push, choose one to open
* If we receive multiple pushes, try to open them all

But if it’s possible to send many tabs from desktop, which has such a large userbase, maybe we want to be a better receiver.

-----

Ok. Maybe we’d like to have a dedicated place for received tabs on the homescreen, where the user is able to pick which tab to open. Like so:

![send-multiple-tabs-1](https://user-images.githubusercontent.com/51007/64227466-bba7d480-cf37-11e9-9d2f-f8a4ea086e15.png)

The problem: this requires some visible things to be designed, which will fill up the homescreen.

Can we do something simpler?

-----

I propose that it may be simpler to do something like:

* On 1st push, if we receive multiple tabs:
    * Open the first tab received
    * Store all the other tabs in history, in order, making them accessible via the “Forward” button
    * Show toast: “x other tabs received. Press → to go forward and see them.”

* On 2nd, 3rd, 4th, etc. pushes:
    * Invisible to user: jump forward to the point in history where the last tab from 1st push is located
    * Visible to user: Replace that tab with the first tab we receive from second push
    * If other tabs from 2nd push are present, store them in history
    * If other tabs are present, show toast

![send-multiple-tabs-2](https://user-images.githubusercontent.com/51007/64228215-37a31c00-cf3a-11e9-9ed4-e777590e93ec.png)

By storing tabs in the history stack, we don’t have to design a special place in the homescreen to receive them.

While this will allow us to receive many tabs without discarding any of them, I understand that we’ll need a strong, clear toast message to let users know that tabs are **stored forward in history**. As a consequence, clicking any link on the current page will erase that forward stack! So I think that this is a behaviour that we want in the short term, but may not want in the future.

(Of course, this issue can elegantly be solved if we have tabbed browsing – a conversation for another bug).

**Comment by jonalmeida** [comment]
> On 1st push, if we receive multiple tabs

@brampitoyo to clarify, when we receive multiple tabs today, they are always seen as individual tabs sent one after each other. There is no grouping involved on any of the clients.

So when you say..
> Store all the other tabs in history, in order, making them accessible via the “Forward” button

That would probably be the same case as the "On 2nd, 3rd, 4th, etc. pushes" section of your comment.

i.e. to say, each push maps to one tabs.

**Comment by mcomella** [comment]
@brampitoyo To confirm, this is post-MVP, right? For those cases, your simple approach seems reasonable, as does the more involved homescreen version.

**Comment by brampitoyo** [comment]
@mcomella Yes. I confirm that the more complex behaviour should be a post-MVP follow up. For MVP, we want the simplest solution.

**Comment by athomasmoz** [comment]
Closing issue in favour of the breakout issues:
#2904 
#2907 
#2908
