### ISSUE TITLE
Turn on Receive Tab for release builds (not for users: disabled by default)

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2781]
**Do this after S5 code freeze (sep 4)**
### Vision statement / What / Requirements
Receiving tabs is only on for debug builds. We want to give QA enough time to test the feature on release builds, so **we should turn it on before our next mid-sprint LAT**.
### Impact
Will allow QA to test the version of receive tab that will be released to users.
### Acceptance criteria
- ADM permissions are moved from debug manifest to release manifest

### Not included
- Enabling receive tab for users: that's #2813

**Comment by mcomella** [comment]
QA: please verify you can send a tab to either a LAT or a local release build (i.e. using the SystemRelease build variant). Note: if building a local release build, you'll have had to set up the APK keys correctly: see [this thread](https://groups.google.com/a/mozilla.com/forum/#!topic/amazon-dev/SRnlRSbQf-o) for details.
