### ISSUE TITLE
Shifted videos in full screen view

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-tv#2798]
## Steps to reproduce
1. From the "Sports" TV Guide tap on NBC Sports
2. Play any video in full screen mode

### Expected behavior
Video content is properly palyed

### Actual behavior
After antering full screen view the video content s shifted. 

### Device information
* Fire TV device: ?
* Latest affected Firefox version: v4.4 LAT2
* Earliest affected Firefox version: v4.1 LAT2
* Turbo Mode: ON

### Notes
This issue is opened to have an overview of all videos that have issues while in full screen mode as per [this discussion](https://github.com/mozilla-mobile/firefox-tv/issues/2526#issuecomment-523562039)

►Video
![20190905_163548](https://user-images.githubusercontent.com/51314259/64347440-99c45580-cffc-11e9-9ee6-03e89b3d6065.gif)

**Comment by AndiAJ** [comment]
Hi, during today's testing v4.4LAT I've noticed 2 more full screen shifting, namely Washington Post & Rotten Tomatoes.
To have a better overview I'll create the bellow table to add other affected websites.

| Name   | Status |
| ------------- | ------------- |
|  NBC Sports (TV Guide) | ❌  |
|  Washington Post (Pinned tiles) | ❌  |
|  Rotten Tomatoes (Pinned tiles) | ❌  |

**Comment by mcomella** [comment]
I added the content from https://github.com/mozilla-mobile/firefox-tv/issues/2700 here and I'll close that issue.

**Comment by athomasmoz** [comment]
Closing in favour of a new bug with updated description listing all effected sites #2851
