### ISSUE TITLE
Locks up on exit

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#280]
Via Amazon review:

does not exit well from Fire Stick. Using the controls on the remote, I could not get the program to terminate to the main Fire menu. So, I had to re-boot the device. Playback of streaming movies worked well.

**Comment by bbinto** [comment]
@bbinto to reach out to user to provide more details, might be related to #393

**Comment by athomasmoz** [comment]
Closing ticket. Back button or Home button can now be used to exit app
