### ISSUE TITLE
[FxA] Return user to page they started on after sign in

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2805]
### Why/User Benefit/User Problem
We have one WebView and we use the WebView to sign into FxA so whatever page the user was looking at gets replaced by the sign in process, even after successful sign in. It's in their back stack so in theory they can still press back to see the page but it's unintuitive to go back through the sign in flow to get there.

Ideally, the sign in flow wouldn't disrupt the user's browsing experience.

### Acceptance Criteria (how do I know when I’m done?)
- After successful sign in (which may require successful email confirmation), the website the user was on before sign in is restored

### Not included
- If the user does not complete sign in, the the user was on before sign in is restored (mcomella: because I'm not sure how feasible this is)

**Comment by mcomella** [comment]
QA: after the user successfully signs in, the browser should update to the page the user was on before sign in: please verify this behavior. Note that the user will have to first close onboarding and then close the overlay to see the web content with the restored page.

**Comment by abodea** [comment]
Verified as fixed in **`FFTV 4.5`** note that after a successfully login, I was redirected to the menu overview and the `Your tabs. Now ready for prime time` overlay prompt was displayed, and after closing it the menu overview was displayed.
