### ISSUE TITLE
[FxA] If user needs to reauthenticate, cannot receive tabs and unclear why because status is not updated until app is cold started

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2806]
## Steps to reproduce
- Sign in to FxA
- via https://accounts.firefox.com, revoke access to this device

### Expected behavior
Soon after, or after app is backgrounded and foregrounded, sign in status is updated to the "needs reauthentication" state

### Actual behavior
FxA sign in state is not updated, even after backgrounding and foregrounding the app. In order to refresh the state, the app must be cold started, e.g. the app must be force killed and restarted.

### Device information
* Fire TV device: Android TV emulator
* Latest affected Firefox version: v4.4-LAT2 master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

---

@grigoryk Is this expected behavior? I tested on the emulator: perhaps it'd be different if I was on a device that supports push?

We may need to manually call the "refresh device status" methods on the FxA account manager at various times.

**Comment by athomasmoz** [comment]
Need to verify this on device

**Comment by dnarcese** [comment]
Adding a push event when access is revoked is tracked in FxA here mozilla/application-services#1418

**Comment by mcomella** [comment]
> Adding a push event when access is revoked is tracked in FxA here [mozilla/application-services#1418](https://github.com/mozilla/application-services/issues/1418)

Alternatively, we can do this with polling.

**Comment by Baron-Severin** [comment]
@athomasmoz how frequently do we want to poll here?  It's a trade off between how rapidly users see that they've been logged out vs how many extra requests we hit our backend with.

**Comment by athomasmoz** [comment]
Hmm what's the impact on sending the request? Could we start with 24hours?

**Comment by Baron-Severin** [comment]
> Hmm what's the impact on sending the request?

Impact on us: e.g., I log out on desktop.  FFTV will still think I'm logged in (display the wrong icon, not nav to reauthenticate page on FxA button click) until we next poll.

Impact on FxA: the more frequently we poll, the more requests they need to handle.  This increases server costs.

> Could we start with 24hours?

I don't know where to balance this.  Anything longer than instant update is a bad user experience, but doing constant checks would be extremely expensive.

**Comment by mcomella** [comment]
QA: please
- Sign in to FxA
- via https://accounts.firefox.com, revoke access to this device
- Press the home button to background the app
- Open the app

Expected: the user's account needs reauthentication (i.e. a little exxclamation point appears nad clicking their account will request sign in).

**Comment by abodea** [comment]
Verified as fixed on the latest build from master.
After returning to the app, the user need to re-authenticate in order to can send tabs again.
