### ISSUE TITLE
Blue highlight when pressing back and forward buttons to navigate through pictures on Flickr

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-tv#2808]
## Steps to reproduce
1. Navigate to "flickr" from the Pinned Tiles section
2. Search for any term (e.g. f1)
3. Tap on any of the pictures
4. Tap on the '<' or '>' signs

### Expected behavior
Can navigate whithout any UI issues

### Actual behavior
When pressing '<' or '>' a blue rectangle highlight shows up

### Device information
* Fire TV device: Fire TV Pendant 4k
* Latest affected Firefox version: v4.4LAT2
* Earliest affected Firefox version:  v4.4LAT2
* Turbo Mode: ON

### Notes
► Video
![flick](https://user-images.githubusercontent.com/51314259/64411164-50741480-d095-11e9-9b46-d24de2492039.gif)

**Comment by athomasmoz** [comment]
Closing off as lower priority. This may be expected behaviour
