### ISSUE TITLE
[Meta] Refactor App 

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#281]
- [ ] #284: Breakdown
- [ ] How long will this take? includes l10n, CI; new 2.0 features?

---

Our current code base needs to be rebuilt from first principles for Fire TV, as opposed to being re-purposed from another from Focus Android.

**Comment by Sdaswani** [comment]
The refactored App must support all features in 1.0 and 1.1, plus the following:

- Accessibility https://developer.amazon.com/docs/fire-tv/differences-from-android-tv-development.html#accessibility
- Parental control improvements
- Custom Top Tiles
- Request Desktop site

**Comment by mcomella** [comment]
Dupe #351.
