### ISSUE TITLE
Turn on Receive Tab for users

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2813]
We expect Receive Tab to be turned on for QA in release builds first: #2781.

### Vision statement / What / Requirements
Let's ship Receive tab to users!

### Impact
Without this patch, users don't get receive tab.

### Acceptance criteria
- Receive tab is enabled for users
- Receive tab is not enabled for users not on the latest version
  - Issue: if we enable Receive tab using our A/B testing flags, users not on the latest version will see a partial implementation, which isn't very good. We'll have to figure out how to hack around the A/B testing system or hard-code it as enabled.

**Comment by mcomella** [comment]
@athomasmoz I have an open question: do we want to have the option to disable FxA login and send tabs remotely, without an app update? The trade-offs are listed below.

> Issue: if we enable Receive tab using our A/B testing flags, users not on the latest version will see a partial implementation, which isn't very good. 

Here's my recommended solutions and their trade-offs:

**If we do not want the option to disable them remotely,** we can hard-code FxA login/send tab as enabled. Trade-offs (pros are +, cons are -, neutral notes are \*):
- \+ Very simple
- \* This was never intended to be A/B tested anyway
- \- Can't disable FxA/send tab without an app release (though this is like most features we release)

**If we do want the option to disable them remotely,** we can put them behind a _new_ A/B testing flag so enabling the feature won't enable an incomplete implementation for users on older versions. Trade-offs:
- \+ Allows us to disable FxA login/send tab remotely without having to enable the incomplete implementation on older devices
- \- Will take a little over an hour to test and implement
- \- If someone is testing the incomplete feature on older versions (will this happen in practice?), they're unlikely to realize they need to use different feature flags on different versions, wasting their time
- \- Will add clutter on our A/B testing dashboard (but this will happen eventually anyway)

---

Here are some **alternative ideas I discarded as worse**:
- Add a branch C == enabled to the existing A/B testing flag: this will cause each user on older versions to submit a Sentry error each time this method is called and we'll never be able to stop it
- On the existing flag, reverse the A and B branches: doesn't actually work as we want. If we need to disable the implementation on the latest version, we'll enable the incomplete implementation on the older versions

**Comment by mcomella** [comment]
Blocked on Ashley's response.

**Comment by mcomella** [comment]
QA: after this lands, send tab will be enabled for all users (estimated build v4.5-LAT2). Please verify that FxA sign in and send tab is working correctly.

CC @npark-mozilla

**Comment by mcomella** [comment]
> Blocked on Ashley's response.

Ashley replied in meeting that this is not an experiment so we should just hard-code it.

**Comment by npark-mozilla** [comment]
Immediately after this lands, all UI tests will fail.  I have  #2847 for it, which is currently WIP.

**Comment by abodea** [comment]
Verified as fixed on v4.5-LAT3 as the FxA sign in and Send Tab are working correctly.
