### ISSUE TITLE
Enable JavaScript debugging

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#282]
According to Amazon, this should enable the JavaScript console.

`WebView.setWebContentsDebuggingEnabled(true);`

**Comment by mcomella** [comment]
The suggested method doesn't exist on AmazonWebView – I assume it'll be added in a future iteration.

**Comment by Sdaswani** [comment]
OK checking with Amazon. Odd!

**Comment by Sdaswani** [comment]
Amazon's recommendation is to not compile against the Amazon Webview jar file - are we doing that @mcomella ?

"[C]ompiling against the Amazon Web View jar file ... is no longer necessary. Just use the standard Android Web View. All web view calls will be mapped to Amazon Web View on Fire TV."

**Comment by mcomella** [comment]
We do this now.
