### ISSUE TITLE
[FxA] The Send Tab Feature button is not displayed if tapping on "Not now" button on the onboarding screen while being in the app

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2827]
## Steps to reproduce
1. Install and launch FF for Fire TV.
2. Use the following command in order to enable the send tab feature: **`adb shell am start -n org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments SendTab-2511:B`**
3. On the send tab onboarding screen select and tap on the `Not now` button.

### Expected behavior
The send tab button is displayed at the top in the menu overview, with the option to sign-in later.
### Actual behavior
The send tab button is not displayed on the menu overview.
### Device information
* Fire TV device: **`Fire TV Stick 4k`**
* Latest affected Firefox version: **`FF for Fire TV 4.5-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 4.5-LAT2`**
* Turbo Mode: **`On and Off`**
#### Notes 
This issue can be reproduced only if adding the command for send tab while the FF for Fire TV is launched, otherwise if adding the command while being in the Fire TV homescreen, the send tab button appears even if selecting not now.
[Video](https://drive.google.com/file/d/1JmGB5oBblbOpflVmtpAgbcUV2BfLppoG/view?usp=sharing)

**Comment by mcomella** [comment]
@abodea This doesn't seem to be reproducible in the v4.5-LAT3 (4?) build – if so, can you please close?

**Comment by abodea** [comment]
@mcomella Thank you for the reminder!
Verified as fixed on v4.5-LAT4, note that the icon was correctly displayed.
