### ISSUE TITLE
[FxA] FF for Fire TV remains stuck if receiving a tab while being in the "Sent Tabs" section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2828]
## Steps to reproduce
1. Install and launch FF for Fire TV.
2. Login with valid credentials.
3. Access the `Sent Tabs` menu after a successfully login.
4. From the other device send any tab.
### Expected behavior
The tab is received and the `Sent Tabs` menu can be dismissed in order to access the recently sent tab.
### Actual behavior
The FF for Fire TV remains stuck on the `Sent Tabs` screen after receiving a tab from other device.
### Device information
* Fire TV device: **`Fire TV Stick 4k`**
* Latest affected Firefox version: **`FF for Fire TV 4.5-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 4.5-LAT2`**
* Turbo Mode: **`On and Off`**
#### Notes
[logcat.txt](https://github.com/mozilla-mobile/firefox-tv/files/3604435/logcat.txt)
This issue can be bypassed only with a FF restart.

**Comment by dnarcese** [comment]
Dupe #2854
