### ISSUE TITLE
[FxA] The Send Tab icon is not displayed if the account is using the the default picture

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2835]
### Prerequisite
The account should have the default image.
## Steps to reproduce
1. Launch FFTV.
2. Activate `Send Tab` using `adb shell am start -n org.mozilla.tv.firefox/org.mozilla.tv.firefox.MainActivity -a android.intent.action.MAIN --esa qaActiveExperiments SendTab-2511:B` command.
3. From another device send any tabs.
4. Wait until the webpage is opened.
5. Access the menu overview.
6. Search for the Send Tab button.
### Expected behavior
The Send tab button is displayed.
### Actual behavior
The Send tab button can be selected but it's not displayed.
### Device information
* Fire TV device: **`Fire TV Stick 4k`**
* Latest affected Firefox version: **`FF for Fire TV 4.5-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 4.5-LAT2`**
* Turbo Mode: **`On and Off`**
![20190913_144908](https://user-images.githubusercontent.com/42831109/64861753-71121080-d639-11e9-95e9-081471e7c8de.jpg)

**Comment by abodea** [comment]
I was able to reproduce this issue only after receiving tabs on FFTV, strange behavior.

**Comment by dnarcese** [comment]
This seems to be a problem with the default avatar not showing. I also notice it is not showing in the sent tabs settings page.

**Comment by Baron-Severin** [comment]
This was broken by https://github.com/mozilla-mobile/firefox-tv/pull/2723

**Comment by Baron-Severin** [comment]
Root cause is that Picasso doesn't support SVGs.  Working on a fix

**Comment by abodea** [comment]
Verified as fixed on v4.5-LAT4.
The default icon is now displayed.
