### ISSUE TITLE
Missing Telemetry from #2693

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2843]
## Steps to reproduce
In #2693, telemetry events for fxa are defined, but following telemetry events aren't in the code yet.
Pre-boarding:
	◦	~Pre-boarding screen shown~ the button clicks will infer this
	◦	Sign in
	◦	Not now

Login State
	◦	Logged in
        ◦	Not Logged in

**Comment by Baron-Severin** [comment]
Note that there was a bug in the implementation of this telemetry that was fixed in #2937.
