### ISSUE TITLE
Cannot play videos on hdfilme.tv

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#285]
> [V]ideos on http://hdfilme.tv don't run, which really is a pity. In other Smart TV browsers they work (Samsung) or work at least partially (in Amazon's Silk, but for each video the mode needs to be changed to "desktop view which is really cumbersome in the long run).

From a user report on our mailing list.

**Comment by liuche** [comment]
If it requires desktop site, #202 could be a workaround.

**Comment by bromelio** [comment]
Is there any news on this issue, please?

**Comment by Sdaswani** [comment]
@bromelio it's scheduled for our 2.0 release, which won't ship for a few months. We are hoping enabling a way to request the desktop site is a easy workaround.

**Comment by bromelio** [comment]
Hello. You asked me about my Fire TV Software version (under which 4k works now in Firefox and in general). It is Fire OS 6.2.5.3.

**Comment by Sdaswani** [comment]
Related to #277

**Comment by athomasmoz** [comment]
Looks like this was fixed with #277
