### ISSUE TITLE
Receving tab freezes the app completely 

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2854]
## Steps to reproduce
Build debug off master, and launch it with FxA experiment enabled
Log into Fxa in FFTV, then go to send tabs dialog (fxa profile settings page), stay there
From Firefox Desktop, send a tab

### Expected behavior
Tab is shown
### Actual behavior
The popup notification of tab being received briefly shows up, and the app is completely frozen.

### Device information
* Fire TV device: 4K
* Latest affected Firefox version: master
* Earliest affected Firefox version: master
* Turbo Mode: Yes

**Comment by dnarcese** [comment]
Same as #2828?

**Comment by npark-mozilla** [comment]
@dnarcese yes it looks like it's the same issue
