### ISSUE TITLE
Videos Not Playing in 4K

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#286]
> [W]hy are 4k videos only shown in HD on my 4k Smart TV in combination with the 4k fire tv and > 20 Mbit/s internet speed, the same videos that Chrome shows in 4k? Can I do anything about that?

**Comment by bbinto** [comment]
As per Amazon contact, we are currently waiting on details how to enable it in our app.

**Comment by mcomella** [comment]
Dupe to #277.
