### ISSUE TITLE
Dismissing Onboarding screen should take user to home screen overlay

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2860]
## Steps to reproduce

1. Log in to your account on FFTV
2. Receive tab onboarding screen should be shown. Hit Dismiss

### Expected behavior

You are returned to the homescreen

### Actual behavior

You are returned to the sign in confirmation page

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by abodea** [comment]
Verified as fixed in v4.5-LAT4.
Note that after the successfully login the user is redirected to the home screen overlay where the Onboarding is displayed, dismissing it, the screen remains to the user home screen overlay.
