### ISSUE TITLE
Show receive tab onboarding screen every time a user logs in

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2861]
## Steps to reproduce

1. Open FFTV
2. Sign in to your account

### Expected behavior

Onboarding screen is shown

### Actual behavior

Onboarding screen is only shown if it's the first time you have signed in on that device

### UX note

It’s important to show the onboarding every time, because there are only a few scenarios where users need to sign out and back in:

1. To fix problem. Something doesn’t work, so better try again.
2. Because another person needs to send tabs.

We hope not to have too many problems in scenario 1. This leaves us with scenario 2, where a new user may not know how to send tabs and need to see the onboarding.

### Device information
* Fire TV device: ?
* Latest affected Firefox version: 4.5-LAT
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by abodea** [comment]
Verified as fixed in v4.5-LAT4.
Note that I did 10+ logins on the same device and the onboarding screen was displayed every time.
