### ISSUE TITLE
Desktop requested / Non-desktop requested toast message is no longer visible

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2864]
## Steps to reproduce
- Go to website
- Go back to overlay, and select 'request desktop...' button

### Expected behavior
- Desktop version opens, with the toast message indicating that desktop version is requested

### Actual behavior
- No toast message

### Device information
* Fire TV device: Cube, Gen 2
* Latest affected Firefox version: master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by dnarcese** [comment]
[This commit](https://github.com/mozilla-mobile/firefox-tv/commit/d027a30d7e0af5922515598a81ecd3479cc1aa64) is where this broke

**Comment by dnarcese** [comment]
Pinned tile toasts are also broken but should be fixed when this is fixed.

**Comment by mcomella** [comment]
QA: please ensure request desktop site toasts are visible.

**Comment by abodea** [comment]
Verified as fixed on the latest build from master. Note that the desktop site toasts are visible when enabling and disabling desktop mode.
Thanks @Baron-Severin for the build.
