### ISSUE TITLE
RECEIVE_TAB telemetry is not seen on redash

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#2865]
## Steps to reproduce
- Enable FxA, and send tab from Firefox desktop (release build)
- Go to telemetry website and check for receive_tab entry

### Expected behavior
- receive_tab entry is shown

### Actual behavior
- Other telemetry type count are incremented, but after a number of send tab activity, RECEIVE_TAB is not shown.

### Device information
* Fire TV device: All
* Latest affected Firefox version: master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by Baron-Severin** [comment]
@npark-mozilla @athomasmoz it looks like the actual event is labeled "received_tab", not "receive_tab".  This hasn't gone out to users, so we can change it without much trouble.  In this case, should we update the code or the query?

**Comment by athomasmoz** [comment]
Good catch. The current event name is fine with me
