### ISSUE TITLE
[FxA] After sign in, clearing data, and sign in, tabs are not received

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2867]
Break-out from https://github.com/mozilla-mobile/firefox-tv/issues/2833#issuecomment-532795469: each of these bugs are one of two separate code paths that result in tabs not being received.

## Steps to reproduce
- Sign into FxA
- Verify you can receive tabs
- Clear app data on the device (i.e. not in the app; I used `adb shell pm clear org.mozilla.tv.firefox.debug` while the app was foregrounded)
- Sign into FxA
- Send a tab

### Expected behavior
Tabs are received.

### Actual behavior
Tabs are not received.

- Signing out and signing back in does not fix the issue
- Restarting the device does not fix the issue
- Uninstalling the app, reinstalling, and signing in again fixes the issue

### Device information
* Fire TV device: Fire TV Cube, Fire TV 4K pendant
* Latest affected Firefox version: v4.5-LAT2 master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

---

As per https://github.com/mozilla-mobile/firefox-tv/issues/2833#issuecomment-532795469, [`AbstractAmazonPushService.onMessage`](https://searchfox.org/mozilla-mobile/rev/84667ea7969a4c48afba2f9a17e0b2940a33db01/android-components/components/lib/push-amazon/src/main/java/mozilla/components/lib/push/amazon/AbstractAmazonPushService.kt#54) is called and gets to [`AutoPushFeature.onMessageReceived`](https://searchfox.org/mozilla-mobile/rev/84667ea7969a4c48afba2f9a17e0b2940a33db01/android-components/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#147). However, `DeliveryManager.with(connection)` silently fails to execute the block because [`connection.isInitialized` returns false](https://searchfox.org/mozilla-mobile/rev/84667ea7969a4c48afba2f9a17e0b2940a33db01/android-components/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#326) because [`api` is null](https://searchfox.org/mozilla-mobile/rev/84667ea7969a4c48afba2f9a17e0b2940a33db01/android-components/components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt#116). **This persists even after the app is force-stopped and restarted.** Polling for tabs on startup works successfully but push does not.

Perhaps the ADM server on the device gets confused if you don't explicitly unregister your app before registering your app again.

**Comment by mcomella** [comment]
> Restarting the device does not fix the issue
> Uninstalling the app, reinstalling, and signing in again fixes the issue

Given some users will never be able to send tabs, prioritizing as high impact P1.

**Comment by mcomella** [comment]
Jonathan found a fix that will land in a-c and that is expect to get uplifted into tomorrow's release.

**Comment by mcomella** [comment]
This is expected to be fixed with the a-c upgrade in https://github.com/mozilla-mobile/firefox-tv/pull/2879.

**Comment by mcomella** [comment]
Merged in https://github.com/mozilla-mobile/firefox-tv/commit/e630830f9b228de6fc54ae8ca3fa287c25b7fbad

**Comment by abodea** [comment]
Verified as fixed in v4.5-LAT4 following the steps from the description.
Tabs are received correctly.
