### ISSUE TITLE
[FxA] Implement a prompt informing the user when logging off on Fire TV

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2872]
### Why/User Benefit/User Problem
As a FFTV user, I want to be informed when I log off from my FF account about what is going to happen.
### Acceptance Criteria (how do I know when I’m done?)
The logging off prompt is implemented in FFTV.
### Notes
On the Fenix is something similar on what I'm referring to.
I consider this important because there is no information regarding what is going to happen when you log off.
![Screenshot_20190919-155546](https://user-images.githubusercontent.com/42831109/65246984-3fe18680-daf8-11e9-9c02-fd092d67cd3d.png)

**Comment by athomasmoz** [comment]
Closing as lower priority for now. Agreed that a prompt will become important in future to describe the impact on account, will re-open when more sync features are considered
