### ISSUE TITLE
[FxA] The avatar is not updated on FFTV after changing it on the account

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2873]
## Steps to reproduce
1. Login with valid credentials(same acc) on FFTV and desktop.
2. Send a tab, perform a sync.
3. Observe the avatar.
4. From the desktop change the avatar.
5. Restart FFTV few times.
### Expected behavior
The avatar is changed.
### Actual behavior
The avatar is not changed.
### Device information
* Fire TV device: **`Fire TV Stick 4k`**
* Latest affected Firefox version: **`FF for Fire TV 4.5-LAT3`**
* Earliest affected Firefox version: **`FF for Fire TV 4.5-LAT2`**
* Turbo Mode: **`On and Off`**

**Comment by mcomella** [comment]
I don't think we receive push messages, or do automated polling, to update profile information: in the current implementation, I'd only expect the profile information to change when cold starting, when it has to be refreshed. This is similar to #2806 where user can revoke access to their account but it doesn't update the status on device.

**Comment by dnarcese** [comment]
This is tracked in FxA here https://github.com/mozilla/application-services/issues/1418

**Comment by athomasmoz** [comment]
Closing this in favour of tracking in FxA
