### ISSUE TITLE
[FxA] Send tab onboarding is shown each time app is cold started

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2875]
## Steps to reproduce
- Start app
- Sign in
- Clear Send tab onboarding
- Force stop app (I used `adb shell force-stop <app-id>`)
- Start app

### Expected behavior
Onboarding is not shown

### Actual behavior
Onboarding is shown

### Device information
* Fire TV device: ?
* Latest affected Firefox version: v4.5-LAT3 master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by abodea** [comment]
Verified as fixed in v.4.5-LAT4.
Note that I used the `adb shell am force-stop org.mozilla.tv.firefox` command to force stop.
When launching the onboarding wasn't displayed.
