### ISSUE TITLE
[FxA] Unable to receive tabs sent from Firefox Nightly 71

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2877]
This is likely a problem with FxA/send tab upstream. Tracking upstream in ~~https://github.com/mozilla/fxa/issues/2546~~ https://bugzilla.mozilla.org/show_bug.cgi?id=1582542

## Steps to reproduce
- Sign in on FFTV
- Send tab from Firefox Nightly to FFTV

### Expected behavior
Tab receiveid

### Actual behavior
Tab not received

### Device information
* Fire TV device: ?
* Latest affected Firefox version: v4.5-LAT3 master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by mcomella** [comment]
The upstream issue has been closed and Andrei reported on Slack that he believes it's fixed: closing.

**Comment by abodea** [comment]
I just verified the issue on the bugzilla, on the 70.0b14 and 71.0a1(latest nightly). Note that I've sent more than 15 tabs from beta 14 and the latest nightly, everything worked as expected, tabs being received on the Fire TV.
