### ISSUE TITLE
Verify CI is working correctly after releng TC changes

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2885]
### Vision statement / What / Requirements
Releng is making major refactors to our CI integration in order to make it closer to what our other mobile apps are using and to reduce the amount of work relman has to do during a release.

### Impact
Without verifying that our CI is working in advance, it may not work when we need it to and it might be hard to merge code or create a release.

### Acceptance criteria
- CI on PR merges, even from across repos, works correctly
- CI on master merges works correctly
- CI for release builds works correctly
  - Should automatically upload release builds to Amazon app store and not destroy existing state if we need it (e.g. staged rollout in progress)
  - Copy-pasted, localized release notes ("bug fixes & improvements") should be automatically uploaded to the App Store for release builds
  - Should be able to download builds to upload for LATs (which don't support automatic uploads)
  - (was this completed?) Should automatically upload builds to GitHub Releases

**Comment by mitchhentges** [comment]
Automatically uploading builds to Github wasn't completed, but when `firefox-tv@mozilla.com` is emailed that automation is ready, it links to both the APK and the release to make uploading it a breeze

**Comment by mcomella** [comment]
Mitch thinks we should try this out on a real release:

> On the next release, there might be a CI issue (related to how docker images are built), maybe? It's not possible to test without a real release, so I'm leaning the team pinging releng if/when an issue arises

So I believe no further verification work is necessary here, if we keep this in mind before doing our next release.
