### ISSUE TITLE
Installation Failure: Package has no certificates at entry AndroidManifest.xml

### ISSUE THREAD

**Issue by hackel** [mozilla-mobile/firefox-tv#2893]
## Steps to reproduce
Install Firefox TV: `adb install firefox-tv-4.5.apk`

### Expected behavior
App installs normally

### Actual behavior
`failed to install firefox-tv-4.5.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl913086765.tmp/base.apk has no certificates at entry AndroidManifest.xml]`

### Device information
* Android TV device: Android 8
* Latest affected Firefox version: 4.5
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by mcomella** [comment]
Thanks for reporting, I think the uploaded APK was not signed so I:
- Uploaded a new APK that is a signed version of the old one: `firefox-tv-4.5-signed.apk`
- Renamed the existing APK (to avoid being destructive): `firefox-tv-4.5-unsigned.apk`

Please try installing `firefox-tv-4.5-signed.apk` and see if it works! If it doesn't, please reopen this issue.
