### ISSUE TITLE
Bundled Pocket tiles point to now invalid youtube TV URL

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2912]
## Steps to reproduce
- Clear app data
- Open FFTV
- Click a pocket tile

### Expected behavior
Taken to video on mobile youtube

### Actual behavior
Unable to watch video: taken to youTube TV redirect screen (because it's now unavailable), which redirects to YouTube desktop homescreen.

Note: these bundled tiles should only be visible for < 24 hours and only visible to new users.

### Device information
* Fire TV device: 4k Stick
* Latest affected Firefox version: v4.5 master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

### Note to QA
Please verify that:
- Bundled Pocket tiles now redirect to mobile YouTube
- Normal (pulled periodically) tiles still redirect to mobile YouTube

**Comment by athomasmoz** [comment]
NOTE: This is only the ones that show up on the first day, not the ones from Pocket server (daily)

**Comment by mcomella** [comment]
@Baron-Severin Can you add a note for QA about how to test this and what to look out for when doing so? It's a good practice when adding `qa-ready` labels.

**Comment by abodea** [comment]
Verified as fixed on `v4.6-LAT1` using Fire TV Stick 4k.
Note that I freshly installed FFTV 5 times and at first launch, I opened all the Tiles from Pocket Recommends. Every single tile was opened in **`https://w.youtube.com`**.

I also used, Clear all cookies and site data(but I'm not really sure how relevant this one is).

@Baron-Severin can you please confirm that this is a valid verification?

**Comment by Baron-Severin** [comment]
> Verified as fixed on `v4.6-LAT1` using Fire TV Stick 4k.
> Note that I freshly installed FFTV 5 times and at first launch, I opened all the Tiles from Pocket Recommends. Every single tile was opened in **`https://w.youtube.com`**.
> 
> I also used, Clear all cookies and site data(but I'm not really sure how relevant this one is).
> 
> @Baron-Severin can you please confirm that this is a valid verification?

Yep, that sounds valid to me.
