### ISSUE TITLE
[a11y] Announce toggle buttons in settings

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#293]
e.g. for telemetry, mention it's enabled and state: "enabled"/"disabled".

**Comment by mcomella** [comment]
The layout looks like:
```xml
<LinearLayout focusable="true">
    <TextView text="Send usage data"/>
    <CheckBox/>
```

The problem is that when we focus the parent layout, the CheckBox is not announced (but intuitively should be, like how the TextView is announced). I think this makes sense: in theory, should only be able to change the CheckBox if you focus it, so it shouldn't announce the checkbox (and thus give you the ability to change it) unless you focus it directly – I confirmed the same behavior in talkback. Unfortunately, we contradict theory by setting the click listener on the parent container rather than letting the user focus the checkbox directly. We do this for good keyboard navigation (the parent container changes background color when focused).

Some solutions:
- Modify the accessibility behavior of the parent in code to read the child
- Focus parent without a11y, focus checkbox with a11y
- Change the parent background color based on child focus and focus the child instead
- (might not work) When child is focused, redirect focus to parent immediately. It might announce in the wrong order though (i.e. "Checkbox checked. Send usage data").

I think the first is most correct but easiest to screw up later (because XML is separated from code).

**Comment by mcomella** [comment]
I just came up with a better solution using ^ – thanks Eitan! (I tried this attr initially but this is a strange situation so I missed this one). Solution:
- Set CheckBox importantForAccessibility=yes, add contentDescription with same text as TextView
- Add code listener: when accessibility is disabled, set containing linear layout as focusable; when enabled, set containing linear layout as non focusable

This simplifies the code dramatically – I'll pop in a quick fix.

**Comment by Sdaswani** [comment]
Will this make 1.1?

**Comment by mcomella** [comment]
It has the same result for users as the existing implementation so it's not necessary for 1.1 – I just like to simplify it before the refactor so we don't forget about it (and to make the refactor easier).

**Comment by mcomella** [comment]
Filed #383.
