### ISSUE TITLE
[FxA] "Not now" button telemetry is incorrect: sent every time preboarding is shown

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2937]
https://searchfox.org/mozilla-mobile/rev/5a11d65b0db47eab3a32946148ff68bd0d452ff5/firefox-tv/app/src/main/java/org/mozilla/tv/firefox/onboarding/ReceiveTabPreboardingActivity.kt#55 - we're currently triggering the "Not now" telemetry every time the receive tabs preboarding is shown, rather than when "Not now" is pressed.

### Device information
* Fire TV device: ?
* Latest affected Firefox version: v4.5+ master
* Earliest affected Firefox version: ?
* Turbo Mode: ?

**Comment by athomasmoz** [comment]
If this is a quick fix, let's do it. If larger, may be worth reprioritizing against other issues

**Comment by abodea** [comment]
@Baron-Severin can you please help me check this?
I never verified telemetry on FFTV, I understand that the changes are regarding pressing `Not Now` but I'm not really exactly sure where to check and see the fix.

**Comment by Baron-Severin** [comment]
> @Baron-Severin can you please help me check this?
> I never verified telemetry on FFTV, I understand that the changes are regarding pressing `Not Now` but I'm not really exactly sure where to check and see the fix.

We spoke about this synchronously, and dev will verify this issue.

**Comment by mcomella** [comment]
I verified this is working correctly by, in a local debug build, setting a conditional breakpoint in `TelemetryEvent.queue` for the condition `value != null && value.startsWith("fxa_preboarding")`. I:
- Cleared data, selected Sign in: verified it was not "not now" telemetry
- Restarted the app, verified "not now" was not fired
- Cleared data, select Not Now: verified "not now" telemetry is fired once
