### ISSUE TITLE
Remove unused focus_preference and licenses.html

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2948]
### Vision statement / What / Requirements
afaict, these are unused and removing them are quick wins.

### Impact
If we don't remove licenses.html, we may mistakenly update it, wasting time and not getting our licenses listed.

### Acceptance criteria
- If unused, focus_preference and licenses.html are removed

**Comment by Baron-Severin** [comment]
Closed by https://github.com/mozilla-mobile/firefox-tv/pull/2960
