### ISSUE TITLE
Master is crashing on bitbar

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2956]
See https://mozilla.testdroid.com/#testing/device-session/296208/1369793/35285766

**Comment by mcomella** [comment]
@Baron-Severin Can this be closed? https://github.com/mozilla-mobile/firefox-tv/pull/2957 was merged.

**Comment by Baron-Severin** [comment]
> @Baron-Severin Can this be closed? #2957 was merged.

I don't see any Bitbar crashes since 11-11, so I think so.
