### ISSUE TITLE
Unable to pin tiles on homescreen: pin button unavailable

### ISSUE THREAD

**Issue by Mostef69** [mozilla-mobile/firefox-tv#2973]
### Device information
* Fire TV device: ? Yes
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?
* Turbo Mode: ? Yes/no
Hello excuse me I use Google translation,
 I do not know if it's a bug, but I'm having trouble pinning a favorite page on
 Fire TV icon pin is not active, I am unable to choose this function, I deleted the original pin websites like Instagram, Flickr ect ... Yet originally they have well  been pinned, I entered a web address on the search bar and I tried to go to the pin button but this button is inactive so I can not position myself on the pin icon!  I followed the tutorial as mentioned on this page https://support.mozilla.org/en/kb/eping ... er-a-site

 And I followed the instructions on the Firefox Information Medium as mentioned below.

 Pin a site:
 To add web links to your home screen, follow these instructions:

 1 Enter the name of the site you want to pin in the Firefox search bar.

 2 Click the pin icon at the top of the page (the icon is surrounded by a blue ring when selected).  The icon turns white when the page is pinned.

 That said the pin function does not work have I forgotten something?  Thanks for enlightening me because there I block.  And when I'm on the website leboncoin.fr I do not have the address bar at the top of the page thank you to enlighten me thank you to all.

**Comment by mcomella** [comment]
@Mostef69 Thanks for reporting this issue.

When you enter the name of the site in the Firefox search bar, did you click "Next" to load the page? The pin button will not be available until the page is loaded.

I recorded a video of myself pinning a page. Did you follow steps similar to mine? https://drive.google.com/file/d/1LKmsS9knpR9pcXSbgtt4dAx2aKHbCf29/view?usp=sharing

**Comment by Mostef69** [comment]
I followed the procedure identical to the video I had already tried, here is a video the pinning function does not work

https://drive.google.com/file/d/1EpANllIphYbC4Kb47I6euj7Ha1VE2R8Y/view?usp=drivesdk

**Comment by mcomella** [comment]
@Mostef69 Thanks for the video – that was really helpful! Try the following steps to resolve the issue:
1. Enter the site you want to pin in the Firefox search bar.
1. Press the menu button ![2018-01-18-09-55-00-58a1d6](https://user-images.githubusercontent.com/759372/70764310-12c5fe00-1d0c-11ea-89c2-874f434ed357.png) to open the homescreen
    1. Note: in the provided video, the back button was pressed instead
1. Click the pin icon firefox for fire tv pin 3.0 at the top of the page. 

If this doesn't make sense, let me know and I can record a video. I hope it helps!

**Comment by Mostef69** [comment]
Excuse me really, the original method to pin a website with the button of the remote control with 3 horizontal lines had not occurred to me, I used the button of the remote control with the arrow back, here  why the Firefox pin button was not active or highlighted with the blue ring, I could not position myself on it, but now the problem is solved sorry again for the inconvenience, because I thought it more logical to  use the remote control button with the "back arrow" to go back to the Firefox homepage and then pin the website, and that's my big mistake, I think a lot of people made the same mistake as I did.  I think it would be wise to add the button of the "back arrow" to return to the Firefox home page and also pin a website in this way, in this case there would be 2 possibilities to pin a website c  is to say button on the remote control "back arrow" and button with the 3 horizontal lines thank you for your responsiveness

**Comment by athomasmoz** [comment]
Thank you for your feedback and logging the initial request. That's helpful to know and I agree, it's likely the others are trying the same approach. I have logged a a feature request for it #2974

**Comment by Mostef69** [comment]
Glad it could help the Firefox community, and I'm sure Firefox will be more ergonomic on Fire TV, good luck.

**Comment by melmoxyz** [comment]
Using First version on His ende AndroidTV. I cannot pit tile either.  Observed behavior.  Enter desired website address- successful to browse.
Enter address in search the pin icon stays grey
Enter address in search and press menu 3-line.... on remote .   Tv menu pops up.  Not Firefox menu.   

The expected behavior does happen on my FireTV but not on AndroidTV same app version 4.6

**Comment by muslok** [comment]
My Android TV remote does not have a menu button only back button and close button. The pin button should get activated when you type a web address in the search bar.

**Comment by melmoxyz** [comment]
It does not get activated.  Only opens TV setting menu. 

 

I am using FireTV app in Android TV

**Comment by mcomella** [comment]
@muslok We have an issue for being unable to pin tiles on Android TV devices: https://github.com/mozilla-mobile/firefox-tv/issues/2977 Quoting from that issue https://github.com/mozilla-mobile/firefox-tv/issues/2977#issuecomment-573230031:

>  Unfortunately, this is because we rely on the menu (3 line) icon on Fire TV remotes to get to the menu. Android TV is not officially supported, but something we may explore in future #2660.

**Comment by xeyownt** [comment]
Info for Nvidia Shield TV owner: the menu button on the remote can be configured to send the `menu` command to the application, instead of open the Shield settings instead.
