### ISSUE TITLE
Remove Pocket from Homepage

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2988]
### Vision

Based on success criteria of Pocket on FFTV, we have decided to remove this from the homepage. 

### Acceptance criteria

* Pocket has been removed from the homescreen
* Documentation that includes Pocket has a caveat added that it is no longer supported as of version X

**Comment by abodea** [comment]
Verified as fixed on the latest build **v4.7-LAT1** with **FFTV 4k** and **FFTV pendant.**
