### ISSUE TITLE
Remove pocket from onboarding screen

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2999]
With pocket removed, the onboarding screen should reflect it:
<img width="1285" alt="Screen Shot 2020-06-26 at 4 14 56 PM" src="https://user-images.githubusercontent.com/3597594/85897446-5a076e00-b7c8-11ea-906e-b1e4747a622f.png">

@brampitoyo

**Comment by brampitoyo** [comment]
@psymoon Posting updated onboarding screen, sans Pocket.

@mcomella I’m also posting an updated onboarding screen with the shield icon replacing the rocket, below.

They’re both sized ~160 KB – not that different from our previous asset.

![turbo_mode_onboarding_rocket](https://user-images.githubusercontent.com/51007/85963289-02a41080-ba09-11ea-99de-1145215d89f7.jpg)

![turbo_mode_onboarding_shield](https://user-images.githubusercontent.com/51007/85963297-0afc4b80-ba09-11ea-8d3c-b3a63d2555c7.jpg)
