### ISSUE TITLE
Confirm support of CSS Grid

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#304]
(via verdi)

I was briefly playing with Firefox on FireTV the other day and saw that it didn't support CSS grid.

e.g. https://mozilladevelopers.github.io/playground/css-grid/02-first-grid/

**Comment by digitarald** [comment]
FYI: Chrome shipped Grid in 57, Fire TV run Chrome 55.

**Comment by mcomella** [comment]
Fire TV uses Chromium 70 now.
