### ISSUE TITLE
Release build task failures

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-tv#3044]
I tried to kick off a release build for 4.7.2 but two of the tasks have failed:

 * Sign for Github - https://firefox-ci-tc.services.mozilla.com/tasks/DJ_WRGK_RrifI507T2UUXg
 * Push to Amazon - https://firefox-ci-tc.services.mozilla.com/tasks/Iu-vfF5CRoKJR4S_4gQ5wQ

It looks like they both failed with the same error.

I compared this to 4.7.1, which is the last build we did a few months ago, and there too these tasks failed. So I wonder how we shipped that release. Maybe @mcomella knows?

**Comment by mcomella** [comment]
@st3fan These tasks are not essential for releases. Amazon does not required signed builds to be uploaded to their store (and in fact, if you add your own signing, they strip it) so you can download the unsigned release APK and upload it to the Amazon store for a release. These two tasks are primarily for convenience:
- we put signed APKs on GitHub (for early & historical QA) so we used the "Sign for Github" task to do that quickly and consistently
- uploading APKs to Amazon is error-prone so we used the "Push to Amazon" task to do that automatically

Note: to test a release build locally, you'll still have to sign it. We have the `./firefox-tv/tools/sign_apk.sh` script to help with that.

**Comment by st3fan** [comment]
With #3045 I disabled the tasks that are always failing.
