### ISSUE TITLE
Create sleeping cursor into Firefox logo

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#309]
Automatically move a sleeping (~5 sec) mouse cursor to the lower right corner and turn it into a Firefox logo

![image](https://user-images.githubusercontent.com/122897/34830564-4301169a-f6b2-11e7-8f82-b7ef76ea2dcb.png)

**Comment by mcomella** [comment]
@athomasmoz Do we still want to do this? It's seems too late to introduce something like this.

**Comment by athomasmoz** [comment]
Agreed. Closing
