### ISSUE TITLE
Create/update separate privacy notice for Firefox for Fire TV

### ISSUE THREAD

**Issue by learnedhoof** [mozilla-mobile/firefox-tv#310]
Currently https://www.mozilla.org/privacy/firefox-fire-tv redirects to the [Focus Privacy notice](https://www.mozilla.org/privacy/firefox-focus/). Information was accurate for initial release, but we will want to get a properly branded notice up in preparation for any new features that may impact privacy.

@first44y can also assist with this.

**Comment by bbinto** [comment]
@porfitron will take this on.

**Comment by liuche** [comment]
Duping to #692
