### ISSUE TITLE
[a11y] Check with :eeejay that our a11y is acceptable for v1.1

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#316]
Once #255 is done.

@Sdaswani FYI that this is the issue.

**Comment by mcomella** [comment]
@Sdaswani All a11y bugs just landed on master – please let :eeejay know that we're ready for him to look this over.

**Comment by Sdaswani** [comment]
Done - https://github.com/eeejay has said overall it's working well!
