### ISSUE TITLE
Add telemetry for clear cookies

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#328]
Meta #319.

**Comment by mcomella** [comment]
@bbinto Should the clear cookies event happen when the user clicks the initial "clear cookies button" (which launches a dialog) or when they confirm the interaction in the "Are you sure?" dialog?

**Comment by bbinto** [comment]
"Are you sure" dialog please, well actually both would be good but fine to go out with "are you sure" first.
