### ISSUE TITLE
With Voiceview enabled, back won't always work on when displaying web

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#330]
When voiceview is enabled, the back and menu keys have voiceview functionalities.

STR:
- Enable voiceview
- open a google search page by typing a text in the search bar
- In the google search page, navigate the green selection throught the text, and press menu button.

Actual:
- it interprets as 'all' and starts reading all texts
Expected:
- Show menu
Workaround: the 'webview' must be selected in order for the menu button to work.  'webview' can be selected by pressing back button from the query text selection (Haven't figured out how to select the webview otherwise)

- Press go back button

Actual:
- Doesn't do anything
Expected:
- go back to the Home view

**Comment by Sdaswani** [comment]
I _think_ this is expected right @mcomella ?

**Comment by npark-mozilla** [comment]
If this is expected, then I suppose there should be some instructions provided for the voiceview users, as now it'd be pretty difficult to navigate the app without knowing how to go back to the main menu.

**Comment by eeejay** [comment]
I think double pressing those buttons will give the original, non-VoiceView, functionality. Or at least it's supposed to.

**Comment by npark-mozilla** [comment]
Ah yes, just the 3-line menu button responds with double click (i.e. it opens the side menus) so no worries there.  Only seeing the back button not responding to double clicks.

**Comment by mcomella** [comment]
Double-clicking menu to use the actual functionality is expected behavior – one click will announce the page layout ("orientation text") to help users spatially navigate.

The back button I think should just function as a back button.

**Comment by Sdaswani** [comment]
> The back button I think should just function as a back button.

So there is an issue here @mcomella ?

**Comment by mcomella** [comment]
Yes, I can reproduce.

**Comment by mcomella** [comment]
It appears that `onBackPressed` (for both MainActivity and BrowserFragment) is not getting called when VoiceView is activated but it does when VoiceView is deactivated. I don't see this problem outside of the WebView.

**Comment by mcomella** [comment]
The problem is we intercept the touch event before `onBackPressed` and it gets captured with:
```java
if (event.getKeyCode() == KeyEvent.KEYCODE_BACK && browserFragment != null && browserFragment.isVisible() && !isCursorEnabled && !isDrawerOpen) {
```

Which will change Back -> Escape. We do this for Youtube and use `isCursorVisible` as a proxy for, "Are we on Youtube?" because we don't have access to the current url from MainActivity (though the Cursor should be handled in BrowserFragment anyway...).
