### ISSUE TITLE
Localizations for 1.1

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#334]
We need localizations in ten languages () for the following strings: Simplified Chinese, English, French, German, Hindi, Japanese, Korean, Russian, Spanish, Italian

### Title
Turbo Mode

### [Hed + Body Copy]
Turbo Mode helps you browse faster
Turbo Mode automatically blocks trackers and ads to help get you where you're going faster. If there's a speed bump – like a site that isn't behaving the way you expect – just turn Turbo Mode off.

### [Buttons]
Keep Turbo Mode Enabled
Turn Turbo Mode Off

**Comment by lime124** [comment]
We also just use the string "Turbo Mode" in the browse lane. 

What are thoughts are on translating turbo mode vs keeping it in English?

**Comment by Delphine** [comment]
We usually translate new features. Especially given that here we are dealing with a number of different scripts for these languages, so users would be lost.
I didn't realize there would be a new feature name introduced in these strings. Machine translation may not do well on that, but we can go for it. 
Anyways, once we have the l10n repos set up localizers will be able to go in and correct these strings.

**Comment by Sdaswani** [comment]
@Delphine it is _sort_ of a new feature - it's really just Focus' tracking protection, renamed to 'Turbo Mode'. And @lime124 is suggesting perhaps we keep it 'Turbo Mode' in all languages, so maybe that helps a little?

> Machine translation may not do well on that, but we can go for it.
👍 🙏

**Comment by Delphine** [comment]
After giving this more thought, I'd like to insist on translating "Turbo mode". Another example to add to what I've already mentioned above is that "Mode" in German means "Fashion" so they'd be getting "Turbo Fashion" the way it is.
"Turbo" is usually understood universally, it's especially the "mode" that I'm worried about :)

**Comment by Delphine** [comment]
Here are the translations: 
https://public.etherpad-mozilla.org/p/l10n.fireTV

**Comment by Sdaswani** [comment]
Thanks @Delphine - one of the engineers will get these integrated soon.

**Comment by npark-mozilla** [comment]
@Delphine : just noticed the machine translation of Korean is really awkward (really difficult to understand too, thanks to the embedded sentence), is it possible for me to make a suggestion for it?  (I swear I won't put any nasty texts :) )

**Comment by Delphine** [comment]
@npark-mozilla : Of course! Be my guest :) 
The only ones that were not machine translated are French, Italian and Simplified Chinese.
I would have rather used DeepL for all the other languages but unfortunately it only supports a few. So the rest went through Google Translate and we all know how good that can be for some languages ^^

**Comment by npark-mozilla** [comment]
@Delphine cool! in the etherpad I struck out the old one and added the revision below.

**Comment by mcomella** [comment]
AFAICT: the action item here is to copy the lines from the etherpad into our strings.xml files to be used in the app.

**Comment by Sdaswani** [comment]
Yes exactly @mcomella .
