### ISSUE TITLE
Document new UI telemetry probes

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#341]

**Comment by mcomella** [comment]
Be sure to document that back on the controller on youtube is not recorded (because it's esc).

**Comment by Sdaswani** [comment]
Moving out of blocking list for 1.1.

**Comment by mcomella** [comment]
Bryan said he's working on this.

**Comment by mcomella** [comment]
Completed: @liuche would you like to review? Please close if r+ or you don't want to review.

https://github.com/mozilla-mobile/firefox-tv/wiki/Telemetry

**Comment by mcomella** [comment]
Note that this doesn't take into account the telemetry changes that will need to occur with liuche's new overlay.

**Comment by mcomella** [comment]
@liuche I kept in the SSL error probes from focus because they didn't seem focus and seemed potentially useful – do I need to fill out a data review form for that?
