### ISSUE TITLE
[refactor] Onboarding: make sure it still works

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#350]

**Comment by mcomella** [comment]
@npark-mozilla Can you verify this on master and close it if it works?

**Comment by npark-mozilla** [comment]
The latest screenshot shows that onboarding screen is there, so it should be working.

**Comment by mcomella** [comment]
@npark-mozilla Does selecting each of "Turbo mode on" or "Turbo mode off" set the setting properly?

**Comment by npark-mozilla** [comment]
@mcomella yup it does. btw, I used the latest LAT download to be sure.
