### ISSUE TITLE
[refactor] Fix IWebView

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#352]
Questions to answer:
- Does it have the appropriate number of abstractions? (e.g. IWebView, inherited webviews like SystemWebView, WebViewProvider) Should we reduce it?
- Do we want to keep the WebView inheritance? Composability over inheritance!

Keep in mind: this doesn't *need* to change now and we can fix it later. Decide how important it is / the amount of effort to change it now or later.

**Comment by liuche** [comment]
@mcomella will start fixing the IWebView abstraction and file follow-up bugs for smaller pieces, which we can pass onto @boek when he gets back from PTO.

**Comment by mcomella** [comment]
Turns out we didn't actually break IWebView: we added a method and removed one, but we don't do any gross casting or anything – moving on to the next issue!
