### ISSUE TITLE
[a11y] Add more orientation text to onboarding (i.e. up-down to select yes-no)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#364]
To be considered for monday morning fix.

**Comment by mcomella** [comment]
Current behavior:
- Text on left (the turbo mode description) is announced when screen is first shown. Can be repeated by clicking menu button. Immediately after the text is spoken, the focused button is announced: "Keep Turbo Mode Enabled, button"
- Can only focus buttons on right side

via Slack, eeejay mentions this is pretty intuitive. Other app behaviors with onboarding are similar:
- netflix announces content on screen and mentions the focused button: "Start your free month. Navigate down to sign in." Pressing menu does nothing. Highlighting "Start your free month" always announces, "Navigate down to sign in."
- hulu announces content on screen and mentions the focused button: "Press select button to log in or move right." Pressing menu does nothing. Highlighting "Log in" always announces, "Press select ... or move right."
- A fewer other apps I tried don't support a11y well – they provide no onboarding or orientation text: vimeo, twitch

It seems like we could improve by providing additional orientation text as to the relation of the buttons (up and down, not left and right) but considering we're hard-pressed to add strings, I think we're best off shipping v1.1 as is and adding this fix later – I'll confirm with eeejay.

**Comment by Sdaswani** [comment]
Fine fixing this in a later release.

**Comment by mcomella** [comment]
We don't need individual issues to track orientation text: see #299.
