### ISSUE TITLE
Enable Telemetry for Debug Builds

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#367]
Use the 'debug' channel - Data has said this channel should just work. This is important for a few reasons:

1) It would allow engineers / QA to test telemetry _end-to-end_ during development / QA.
2) It would allow Product / @bbinto to understand data flows while using debug builds.

**Comment by liuche** [comment]
I have a commit that enables dev builds, but before I open a PR i want to make sure that these telemetry events aren't being bucketed incorrectly. I'll monitor this query and open the PR if the correct probes go into a 'debug' channel.

https://sql.telemetry.mozilla.org/queries/50358/source#135207

**Comment by liuche** [comment]
Bumping this from the 2.0 milestone.
I made a custom dummy probe and sent it from a telemetry-enabled debug build, but I haven't seen it show up. Need to follow up with @frank.

**Comment by mcomella** [comment]
We do this in other products: no need for investigation.

To fix this bug:
- Remove the check for dev build in `DataUploadPreference.isEnabled`. This gets called by `TelemetryWrapper.init`.
- Verify upload is working correctly. Set a breakpoint in `TelemetryWrapper.stopMainActivity`, step into `scheduleUpload`, and ensure it steps over the `configuration.isUploadEnabled` escape.

https://github.com/mozilla-mobile/firefox-tv/blob/e7ec58eb14fd2487a3c7568da45e202683a6c342/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L185-L189

And here's `scheduleUpload`: https://github.com/mozilla-mobile/android-components/blob/08b534d6bfa5ccb856e476e36e7eb6e7915a4301/components/service/telemetry/src/main/java/org/mozilla/telemetry/Telemetry.java#L120
