### ISSUE TITLE
[a11y] Turbo mode button is repeated twice in VoiceView

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/firefox-tv#375]
I hear "Turbo Mode On, switch, Turbo Mode On"

**Comment by Sdaswani** [comment]
@mcomella not sure if you can get this in 1.1.

**Comment by mcomella** [comment]
This might go away with the overlay refactor.

**Comment by mcomella** [comment]
@liuche I think there's no way this will still occur in the overlay – can we close it?

**Comment by mcomella** [comment]
We changed the UI so this shouldn't happen - we'll reopen if it's still a problem.
