### ISSUE TITLE
Auth with provider happens in new tab/window - ParamountNetwork.com

### ISSUE THREAD

**Issue by porfitron** [mozilla-mobile/firefox-tv#376]
This will probably happen with other services as well, but when you try to authenticate at paramountnetwork.com to watch Live TV, the site tries to pop a new tab, where you would authenticate with your TV provider (DirecTV, Comcast, etc.); in the case of Firefox on Fire TV, it takes over the window as only a blank screen, so authentication is not possible.

**Comment by athomasmoz** [comment]
Closing, but working on testing major sites to see how common an issue this is.
