### ISSUE TITLE
YouTube TV Freezes

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#378]
STR:
1. Open YT TV from Top Sites
2. Play a video
3. While Video is playing, use menu button to bring up 'browse lane'
4. Video freezes, close browse lane
5. Back on video, no buttons are responding

**Comment by Sdaswani** [comment]
I have to press the home button to get out of this stuck state.

**Comment by Sdaswani** [comment]
Sometimes I'm able to use the menu button to get unstuck and back to top sites, but definitely on the video I'm always stuck.

**Comment by liuche** [comment]
@Sdaswani it's enough to just put it into the current milestone, that's more helpful than assigning multiple people because that's not the sprint convention and it's confusing who's working on what.

**Comment by liuche** [comment]
I think this is a return of #175 - we removed the auto-refresh as part of a11y but maybe that didn't fix it after all.

**Comment by Sdaswani** [comment]
Yes @npark-mozilla mentioned it was an issue he had seen.

**Comment by ukpw** [comment]
I have tried this and found that on closing the browse lane, the YouTube logo shows and it returns me to the start of the video where I have to play it from the start.

**Comment by Sdaswani** [comment]
@ukpw are you using version 1.1 or 1.0.2? the issue is in 1.1, I see the same behavior in 1.0.2.

**Comment by ukpw** [comment]
I currently have version 1.0.2 installed and am not presented with the option to update to 1.1.

**Comment by liuche** [comment]
This issue is only present on the dev branch - it has not been released so the behavior will not change from 1.0.2 to 1.1 (assuming we land this change).
