### ISSUE TITLE
Use system WebView

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#379]
With this bug:
- onFocusChangeListener should move to WebView

Follow-ups:
- Verify https://github.com/mozilla-mobile/firefox-tv/issues/854 is fixed: should just work
- Enable JS debugging: https://github.com/mozilla-mobile/firefox-tv/issues/282

**Comment by mcomella** [comment]
@bbinto Was there a new release of AmazonWebView?

**Comment by bbinto** [comment]
No sure, Carter suggested to talk to their eng team for further details, probably should set something up with them next week.

**Comment by mcomella** [comment]
It seems the Amazon WebView is no longer necessary so let's just update with the platform.

**Comment by liuche** [comment]
![2018-05-15 15 38 38](https://user-images.githubusercontent.com/1082253/40087564-fe5e408c-5857-11e8-98ec-f35103ba8744.jpg)

Dropping this image here so I can link it elsewhere on the wiki. It also gives some context into where everything goes.

**Comment by liuche** [comment]
Oops, just to clarify, this is going to be the Amazon WebView underneath, but can be used just like the system webview.

**Comment by mcomella** [comment]
I have a (bitrotted) WIP to do this: https://github.com/mcomella/firefox-tv/tree/rm-awv It should give you a good idea of what needs to change to do this.

**Comment by pocmo** [comment]
FYI: We are working on getting `browser-engine(-system)` into a state that it can be used here. This will give us the system WebView too. However I think we will still need 1-3 weeks. I just wanted to let you know in case this helps you prioritizing.

**Comment by pocmo** [comment]
> FYI: We are working on getting browser-engine(-system) into a state that it can be used here. This will give us the system WebView too. However I think we will still need 1-3 weeks. I just wanted to let you know in case this helps you prioritizing.

Filed #1039 for that.

**Comment by pocmo** [comment]
This happened as part of #1039.
