### ISSUE TITLE
Drop malformed url requests for non-main frame (was: AmazonWebView does not have WebResourceRequest)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/firefox-tv#38]
shouldInterceptRequest method takes a string instead of WebResourceRequest with AmazonWebView. Look into if we need to create a WebResourceRequest here.

**Comment by mcomella** [comment]
The only method we use is `request.isForMainFrame`, which I think we can check with the `TrackingProtectionWebViewClient.currentPageUrl`:

```java
        if (!request.isForMainFrame() &&
                !scheme.equals("http") && !scheme.equals("https")) {
            // Block any malformed non-http(s) URIs. WebView will already ignore things like market: URLs,
            // but not in all cases (malformed market: URIs, such as market:://... will still end up here).
            // (Note: data: URIs are automatically handled by WebView, and won't end up here either.)
            // file:// URIs are disabled separately by setting WebSettings.setAllowFileAccess()
            return new AmazonWebResourceResponse(null, null, null);
        }
```

I didn't have time to investigate whether or not this would be sufficient, however.

Note that the UrlMatcher for tracking protection whitelists first-party requests (against the `currentPageUrl` so checking for main frame requests is actually unnecessary, afaict).

**Comment by mcomella** [comment]
liuche found where this was initially implemented and it contains useful comments: https://github.com/mozilla-mobile/focus-android/issues/106#issuecomment-281780919

**Comment by mcomella** [comment]
[triage] We're going to wait on the WebView upgrade to see if this API is added back in #379.

**Comment by mcomella** [comment]
This is handled by components now: they're probably doing the right thing. :)
