### ISSUE TITLE
[Meta] UI improvements

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#381]
@lime124 -- I'd like to ask you to come up with a few simple MUST-have UI improvements, and a list of nice-to-haves in your opinion and once we have that (next week in SF), I'd like to prioritize / calibrate them with other feature work + refactoring for 2.0

Could this one also fall under this meta bug?

- #270

**Comment by liuche** [comment]
#270 is basically a technical limitation due to the way Youtube's TV site expects a keyboard, so engineering needs to come up with some workarounds and try out hacks.

**Comment by liuche** [comment]
Moving out of 2.0 milestone - mocks for 2.0 are done but some more work to do.

**Comment by liuche** [comment]
Closing because UX delivered specs, see 2.0 milestone.
