### ISSUE TITLE
[a11y] Add orientation text for navigation overlay

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#388]
Right now we announce "edit: Search or enter address" but don't describe what's in the menu – eeejay mentioned this in unintuitive.

**Comment by bbinto** [comment]
let's wait until we know about @lime124's UI improvements plans.

**Comment by mcomella** [comment]
[triage] Nice to have but not required.

**Comment by mcomella** [comment]
We don't need individual issues to track orientation text: see #299.
