### ISSUE TITLE
Turbo Mode toggle drawable is very blurry / low resolution

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#397]
Whatever drawable is being used for the switch is very blurry / low resolution

<img width="118" alt="screen shot 2018-01-24 at 11 23 27 am" src="https://user-images.githubusercontent.com/102331/35343613-0b0c1716-00f9-11e8-8d0e-58a7f1ef13fe.png">

**Comment by mcomella** [comment]
One thing that's weird about this: that's the system's drawable!

Blind fixes:
- Try using switch compat / original switch
- Use our own drawable

**Comment by liuche** [comment]
This will be closed by the new UI Overlay, where this will be a button rather than a switch (#433 )
