### ISSUE TITLE
Back button doesn't go back to "Firefox Home" from web content

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#419]
(from Amazon for 1.1)

Steps to reproduce:

1. Install and launch the app
2. Go to any website
3. Press the Back button on the remote.

Expected result: Eventually returned to Firefox home screen

Actual result: Back button doesn't do anything when you've reached the point where you should return to the home screen

**Comment by mcomella** [comment]
I think this only happens for youtube, which is a known issue.

**Comment by liuche** [comment]
Closing because this works for non-YT sites.
