### ISSUE TITLE
Enable ProGuard for release/beta builds

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/firefox-tv#42]
Look into adding new configurations to ProGuard for AmazonWebView libraries.

**Comment by bkmunar** [comment]
Waiting on Amazon to give us a proguard file

**Comment by Sdaswani** [comment]
I emailed Amazon - keep bugging me if you don't hear back from me.

**Comment by Sdaswani** [comment]
Reply from Amazon: ‘I don’t think we have a recommended configuration for Amazon Web View. Are you seeing any issues?’ let me know what to ask next.

**Comment by liuche** [comment]
Huh, that's pretty weird that Amazon doesn't have a proguard configuration. I guess it doesn't matter much, and we just won't optimize the Amazon WebView. Since we're not seeing an storage problems with apps being too big, we can punt optimizing the library until they do. Still weird though.
