### ISSUE TITLE
Blue menu bar remains on the left side of screen after opening menu

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#422]
(from Amazon about 1.1)

If the Firefox Settings menu is opened while on a web page, after returning to the website, the blue menu bar remains on the left side of the screen.

Steps to Reproduce:

1. Install and Launch the app.
2. In the search bar, type Google.com.
3. Click the menu key on the remote to pull up the Firefox Menu bar.
4. Click Settings.
5. Click the back button to return to Google.
6. Observe.

Actual Result: The blue settings bar remains and does not disappear.

Expected Result: The settings bar should be hidden until the user pulls it up using the remote.

**Comment by mcomella** [comment]
Maybe fixed with refactor.

**Comment by mcomella** [comment]
Will be gone with refactor.
