### ISSUE TITLE
[April 30] Improve crash reporting by integrating Sentry

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#429]
- [x] Add and init Sentry
- [x] Ensure crashes are caught (bg thread checks periodically, [according to docs](https://docs.sentry.io/clients/java/config/#buffering-events-to-disk))
- [x] Look at crash logs to make sure no sensitive data (urls, identifiers) are being collected
- [x] Decide how to include Sentry "secret" - manually on build? Integrate builds with TC (later)?
- [x] Handle ProGuard UUIDs
- [x] Include `release`? Or will this be handled automatically? *Happens automatically: uses versionName*
- [x] Distinguish between LAT and release? *This should be handled automatically with version number where LAT is `M.m.b.*`*
- [x] We need to decide if we need/want to include a toggle in settings to opt-in/out
- [x] Should we remove user UUID field?
- [x] Document crash reporting (a la [Firefox iOS Sentry wiki page](https://github.com/mozilla-mobile/firefox-ios/wiki/Crash-Reporting-with-Sentry)) and what types of data is being collected
- [x] Update external docs (SUMO)? *afaict, there are no specific docs for Firefox TV so there's nothing to update*
- [ ] Email a few notes on things we can do with Sentry (e.g. breadcrumbs)
- [ ] Releng checklist

---

Apparently we've used Sentry on iOS. Which ones respect user privacy?

**Comment by Sdaswani** [comment]
@mcomella Sentry is approved by our Legal / Policy team so should be OK on the privacy front.

**Comment by mcomella** [comment]
FYI – asking for @pocmo 's opinion via IRC.

**Comment by mcomella** [comment]
A summary of Sebastian's opinion via email (I would say it verbatim but I'm not sure he wants me to):
- Sentry would be fastest to add without legal/privacy overhead: we already run our own instance, which doesn't send data to third parties
- It's used on iOS so Stefan may have an opinion
- Ideally, we should look at a data dump to ensure nothing critical like URLs are being collected
- After playing with a hosted version of Sentry, Sebastian felt it was okay – it only sends crashes and doesn't know session data so it can't give us the crash rates and in particular compare across channels (has Beta regressed from Release?)
- Sebastian was wondering if we could extract Fennec's crash reporter into a library and use our crash stats interface but hasn't looked into it yet

**Comment by boek** [comment]
> After playing with a hosted version of Sentry, Sebastian felt it was okay – it only sends crashes and doesn't know session data so it can't give us the crash rates and in particular compare across channels (has Beta regressed from Release?)

What we were going to do with Focus was have beta report to a different bucket than release to be able to compare the two.

**Comment by pocmo** [comment]
What I noticed yesterday is that Sentry has a "releases" tab (Not sure if this is new?) and there it shows which issues are new in a specific release. It's not a crash rate - but at least helps to see if an update will cause a bunch of new issues.

**Comment by mcomella** [comment]
It seems that crash reporting from the Amazon dashboard is deprecated: "Starting April 30th, 2018, crash reports will no longer be available on the developer portal. Many third parties offer free and paid crash reporting services." Throwing back to triage...

**Comment by pocmo** [comment]
FYI: With GeckoView integration we can't rely on Google Play crash reporting anymore and are going to move ahead with Sentry in Focus/Klar:
https://github.com/mozilla-mobile/focus-android/issues/2326

**Comment by Sdaswani** [comment]
Sentry makes a lot of sense as it’s all set up and supported internally.

**Comment by Sdaswani** [comment]
Why is this assigned to me @mcomella - meaning what do I need to provide? :)

**Comment by mcomella** [comment]
> @Sdaswani to follow up with amazon to see what's going on.

From the last bug.

**Comment by Sdaswani** [comment]
Ah yes I am discussing with them on Friday but honestly I think we still need to move to Sentry.

**Comment by Sdaswani** [comment]
https://sentry.prod.mozaws.net/operations/firefox-tv-debug/#welcome
https://sentry.prod.mozaws.net/operations/firefox-tv/#welcome

**Comment by mcomella** [comment]
@Sdaswani How do we create accounts to log into this sentry endpoint?

**Comment by mcomella** [comment]
From https://github.com/mozilla-mobile/focus-android/issues/2326#issuecomment-375788591:

> @bbinto Sentry is approved in our mobile products - can you confirm we don't need a separate toggle for this?

Sebastian also has a good checklist in his focus bug.

**Comment by mcomella** [comment]
> @Sdaswani How do we create accounts to log into this sentry endpoint?

Susheel gave me access.

**Comment by liuche** [comment]
Added a few more items to the checklist .

From the Focus Android issue for adding Sentry, we should also consider how we're going to build in the Sentry secret (we'll also have to do this for including the Pocket API key in #659 ).

From the [bugzilla discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=1402946) over adding Sentry to Firefox iOS, things look to be fine from the Legal and Security side:
- (Focus) Privacy Policy have been made by Legal already to include crash reporting
- Julien Vehent from Security has already said that there are no security concerns with the operational security of our internal Sentry instance, provided ops is fine with it

I will send an email to the firefox-tv list with Travis (from ops) and Mika (Legal) cc-ed to announce our intent to add Sentry (although I don't forsee any problems).

**Comment by Sdaswani** [comment]
If it means anything, I agree! 🤣

**Comment by mcomella** [comment]
Implementation notes:

From firefox-ios Slack:
> Hey. I’m looking at the sentry integration (since I’m doing it on Fire TV). I noticed that `sendUsageData` is only checked on Sentry init – does Sentry only send data on application start-up? e.g. what happens if the user toggles `sendUsageData` while the app is running and then they crash (or we log some other sentry event/breadcrumb)?
>
> @mcomella probably nothing... users toggling "send usage data" on/off seems likely to be a one-time change, so its an edge case we don't cover

Also, Stefan mentions:

> do you sentry integration and test it on sentry.prod.mozaws.net - but before you ship i may have a better sentry server for you

**Comment by mcomella** [comment]
Here's iOS' init method: https://github.com/mozilla-mobile/firefox-ios/blob/988384977656692eff4579b4f2fac29ea3b5fb8c/Shared/SentryIntegration.swift#L34

**Comment by liuche** [comment]
I don't think there's much we can do about 2 (especially since fingerprinting is already done by other websites, apps), but the risk is pretty low.

For 1), can we send a different id each time? What does Firefox iOS/Focus do?

For 3), I think it's okay to include stack traces (is there an Android doc that states non-PII in stack traces, the way Apple does?, but we should audit our own logging to make sure we don't store any PII because we shouldn't log that anyway.

**Comment by mcomella** [comment]
> Firefox for iOS only has a single, "Send Usage Data" toggle. I imagine most people don't want the granularity to only share telemetry and not crash reports (or vice versa) so I propose we include crash reporting under our existing telemetry toggle.

Spoke to Tif on Slack: 

Tif wonders why desktop includes separate toggles and thinks we should investigate. However, given the timing and priorities, for v1, we're going to design it as a single toggle. Tif notes that we should be careful that users won't get surprised or mad by the changes.

**Comment by lime124** [comment]
By making sure appropriate documentation or sumo pages get updated to
reflect the additional thing being sent. :)

**Comment by liuche** [comment]
The Focus privacy policy does cover crash reporting collection (#692 is open to make a Firefox TV-specific one, but Legal is busy at the moment so I assume we're just going to keep using the one for Focus).

**Comment by mcomella** [comment]
> For 1), can we send a different id each time? What does Firefox iOS/Focus do?

It looks like Firefox iOS is missing unique user IDs with their crash reports (from the Sentry UI). I don't see them explicitly removing the code so I wonder if there's a discrepancy between the SDKs such that Android creates a UUID if it's not available and iOS doesn't.

> For 3), I think it's okay to include stack traces

I'm less concerned about the actual stack traces and the messages we put in them, e.g. "utf-8 should always be available" in this line: https://github.com/mozilla-mobile/firefox-tv/blob/8ccd0c27218da7971a1a1301aa6fafce65803c12/app/src/main/java/org/mozilla/focus/utils/SupportUtils.java#L24

This is probably why GPS and Amazon's crash reporting don't provide these messages (though they are really helpful for debugging).

> (is there an Android doc that states non-PII in stack traces, the way Apple does?, 

So this doesn't seem relevant.

> but we should audit our own logging to make sure we don't store any PII because we shouldn't log that anyway.

Is this something you want before the initial landing? If so, you can review the code now and I'll do that as you review.

**Comment by mcomella** [comment]
Filed some follow-ups:
- #747 ✈️ : fail release builds without a key
- #746: add which buildVariant we're using to crash events

**Comment by Sdaswani** [comment]
Those docs are great!
