### ISSUE TITLE
Prevent from redirecting to an external app

### ISSUE THREAD

**Issue by dmusican** [mozilla-mobile/firefox-tv#431]
I'm trying to use Firefox on Fire TV to watch live sports at nbcsports.com. When I click on a live stream, it seems to try to redirect me to an app; a message says "redirecting to mobile app," and then I get a further message about not having the right software installed. I don't want to redirect to a mobile app; I want to remain in the browser. It would be wonderful to have a setting to control this.

**Comment by bbinto** [comment]
Once #202 is implemented, this could solve the issue.

**Comment by mcomella** [comment]
To add more details, it sounds like the website is redirecting users to their mobile apps. Without request desktop site (#202), we could:
- Evangelize websites to stop redirecting TV to mobile apps (this requires websites to rewrite their code to identify TV user agents)
- Create heuristics to identify pop-ups like these and remove them

Neither of these are really feasible so we're going to add "Request desktop site" and see if this is still an issue users experience.
