### ISSUE TITLE
When entering URL vis android fire tv app from phone, the autocomplete feature interferes with typing

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#432]
STR:
Open Fire TV app from android phone, connect to your fire tv stick
Open Firefox on Fire tv, and tap 'Search or enter address' field.
Try typing a full url on phone or via remote

Expected:
URL is entered without issue.
Actual:
The autocomplete feature constantly overwrites what I'm typing, especially when I use the fire tv app keyboard from the phone.  (The fire tv remote app is from Amazon as well)
After using the phone app, text entering via remote gets interfered too,

**Comment by npark-mozilla** [comment]
Seems like the workaround is to type URL really slowly on phone, and I have to type each character twice.

**Comment by Sdaswani** [comment]
I think this is a duplicate: https://github.com/mozilla-mobile/firefox-tv/issues/276

**Comment by npark-mozilla** [comment]
Ah, yes it is.  strange it worked for me last week...
