### ISSUE TITLE
Save/load high-quality favicons for custom home tiles

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#442]
This needs more spec (letter? screenshot?) and fallback (what if none of these options look good)?

**Comment by liuche** [comment]
@liuche to reach out to shorlander to figure out how the other Firefox/ActivityStream projects do this.

**Comment by Sdaswani** [comment]
Maybe this can be an option - take a screenshot programmatically, but hopefully no need for external storage: https://stackoverflow.com/questions/2661536/how-to-programmatically-take-a-screenshot-in-android

**Comment by mcomella** [comment]
fwiw, if you have questions, I was the one who implemented the naming algorithm and icon algorithms for Activity Stream Android (but we diverged from desktop's behavior partly because our top sites algorithm was different).

**Comment by lime124** [comment]
@liuche i'm not sure if this is the right issue but here goes anyway. Bryan Bell is going to be the best person to talk to.

He told me this: Open graph tags. It’s a micro format standard. Websites used to mark what images are usable And icons
And if that’s not doing the job we have a service that finds good icons for sites. we have a server that’s looking and saves icons for popular stuff.

**Comment by Sdaswani** [comment]
So @lime124 @liuche - there are 4 items in a tile:

1. "identifier": This seems to be an internal identifer @liuche ?
2. "url": Obviously, the url to 'bookmark'
3. "title": @lime124 suggested we use web page title, sounds good to me
4. "img": This is the toughest piece. There are a couple of options I'm seeing above
     * Open Graph Tags https://davidwalsh.name/facebook-meta-tags
     * Service that finds good icons for sites. We need to locate the API for this @liuche ?
     * Screenshot of the page https://github.com/mozilla-mobile/firefox-tv/issues/442#issuecomment-366340982

Any others?

@liuche let us know your thoughts on this, e.g., is it possible we won't get a title or img given the above?

cc @bbinto

**Comment by mcomella** [comment]
I'm asking the AS team (bbell, engineers) what the algorithms are. Some additional resources:
- At least in the past, AS uses the [page-metadata-parser](https://github.com/mozilla/page-metadata-parser) to get favicons, titles.
- There's [a REST service](https://github.com/mozilla/page-metadata-service) that runs ^ on pages and returns the data to you. Unclear if this is still active.

We still need info about fallback (e.g. if a site doesn't have a favicon, what do we show?), which is why I'm asking the AS team.

**Comment by Sdaswani** [comment]
@mcomella i'm wondering if the fall back can be the screenshot of the page?

**Comment by mcomella** [comment]
@Sdaswani afaik, the primary tile visual is actually a screenshot with a favicon in the corner – it's not a fallback, e.g. this tile from my AS on desktop:

![screen shot 2018-02-20 at 16 56 45](https://user-images.githubusercontent.com/759372/36457495-29b75362-165f-11e8-92be-a3d6a28806ea.png)

In any case, if we want to follow what desktop does, we just need the actual designs (or source) to figure out what to do here.

**Comment by Sdaswani** [comment]
@mcomella if we can generate the screenshot ourself via https://github.com/mozilla-mobile/firefox-tv/issues/442#issuecomment-366340982 and not require the favicon, we don't need a fallback as it's all generated on the device?

**Comment by mcomella** [comment]
No responses yet but code spelunking turned up image algo. Here's [the simple version](https://github.com/mozilla/activity-stream/blob/d8f8946bb2623b3b6919e6b36eedc952d18706d7/system-addon/content-src/components/TopSites/TopSites.jsx#L19) (via telemetry):
```js
    if (link.tippyTopIcon || link.faviconRef === "tippytop") {
      acc.tippytop++;
    } else if (link.faviconSize >= MIN_RICH_FAVICON_SIZE) {
      acc.rich_icon++;
    } else if (link.screenshot && link.faviconSize >= MIN_CORNER_FAVICON_SIZE) {
      acc.screenshot_with_icon++;
    } else if (link.screenshot) {
      acc.screenshot++;
    } else {
      acc.no_image++;
}
```

And [the more complete version](https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/components/TopSites/TopSite.jsx#L70).

**Comment by mcomella** [comment]
I moved the title part to #511.

TODO for images:
- Where does AS desktop get favicons from? e.g. open graph tags?
- Code to download images
- Can we take screenshots?

**Comment by mcomella** [comment]
Favicons get fetched from [TopSitesFeed._fetchIcon](https://github.com/mozilla/activity-stream/blob/2456e6e386b54f6627422da85a895eeafc1fc379/system-addon/lib/TopSitesFeed.jsm#L167) which, following the code as best as I can, calls out to FaviconFeed.jsm. This updates the tippy top list from a remote endpoint (if necessary), and then calls out to Gecko to get a favicon for the page ([call to Gecko](https://github.com/mozilla/activity-stream/blob/2456e6e386b54f6627422da85a895eeafc1fc379/system-addon/lib/FaviconFeed.jsm#L128); [Gecko receiving call](https://searchfox.org/mozilla-central/rev/47cb352984bac15c476dcd75f8360f902673cb98/toolkit/components/places/nsFaviconService.cpp#314)).

So it looks like we need to see if Gecko does anything clever for favicons now...

**Comment by mcomella** [comment]
fwiw, [the page-metadata-parser has some clever rules about extracting images](https://github.com/mozilla/page-metadata-parser/blob/6332b71ab281ad3b82aa43799ded70d27c50f631/parser.js#L72): maybe Gecko uses that?

**Comment by mcomella** [comment]
Apparently tippy top refers to two things:
- We ship with a small number of tippy top icons
- We download [a tippy top manifest](https://activity-stream-icons.services.mozilla.com/v1/icons.json.br) at runtime with the urls of over 900 high res icons

Gecko is actually just acting dumb and downloading the favicon from the URL we specify.

Curiously, afaict, we're only downloading icons from this tippy top list and don't download icons otherwise.

**Comment by mcomella** [comment]
Spoke with :nanj on IRC ([log](https://mozilla.logbot.info/activity-stream/20180221#c14339749)):
1) We first pull high-res favicons from Gecko's places DB. We use 4 types: <link rel=`icon`, `apple-touch-icon*`, and `fluid-icon`. ([code](https://searchfox.org/mozilla-central/rev/47cb352984bac15c476dcd75f8360f902673cb98/browser/modules/ContentLinkHandler.jsm#324))
2) We fall back to the tippy-top manifest/bundled icons (since these can go out of date but the icons we fetch from the page are not always high-res).

Note: open-graph tags are used for highlights images ([code](https://searchfox.org/mozilla-central/rev/47cb352984bac15c476dcd75f8360f902673cb98/browser/modules/ContentMetaHandler.jsm)), but not the top sites favicons.

**Comment by mcomella** [comment]
Still TODO:
- Write code to download images (following scheme above)
- Can we take screenshots?

**Comment by lime124** [comment]
heh - that looks good and makes sense to me! :) thanks @mcomella

**Comment by Sdaswani** [comment]
@mcomella thanks for the leg work on this! I really think the first bullet option you presented (i.e., capturing the visible area of the view) will work fine. So don't worry about where it is scrolled, and only take a picture when the user decides to pin. But I defer to @lime124 , just my two cents.

**Comment by lime124** [comment]
I would prefer to do the same as desktop but understand that we might have to take an incremental approach.

**Comment by mcomella** [comment]
Broke out screenshots to #521.

**Comment by mcomella** [comment]
@lime124 If an incremental approach were needed for the home tile icons, what would you consider a desirable v1? The elements to consider are:
- Screenshots
- Icons
- Some fallback (e.g. one letter of domain)
- (What the title, and its fallback, may look like: #511)

From an eng perspective, it'd be simplest to choose one of screenshots or favicons.

**Comment by lime124** [comment]
@mcomella - nice chatting as always. As we discussed, let's pick screenshots to focus on if we can't get to our desired outcome. Thanks for pointing out Gemma's study to me on Top Sites - super interesting stuff and was helpful in coming to a decision!

**Comment by mcomella** [comment]
wrt ^, focusing on screenshots first (#521). 

I have a WIP here – https://github.com/mcomella/firefox-tv/tree/i442-icons – that extracts `<link>` tags from a page and creates Java objects around them. Next steps are something like:
- Filter: whitelist rel, exclude masks, filter on image type
- Sort by most likely images
- Cache this table somewhere
- Prefetch
- When home tiles are shown, generate icon: download them in sequence (if not cached from prefetch), caching/using the first betch match, mix with screenshot if necessary, and place on tile.

**Comment by mcomella** [comment]
We might be able to adapt the fennec favicon code: https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/icons

**Comment by mcomella** [comment]
[planning] We're going with just screenshots for 2.0.

**Comment by liuche** [comment]
For 2.0 we're going to do screenshots for #521, so I'm moving this out of milestone.

**Comment by mcomella** [comment]
> I have a WIP here – https://github.com/mcomella/firefox-tv/tree/i442-icons

Moved to https://github.com/mcomella/firefox-tv/tree/inc-i442-icons for my branch naming sanity. :)

**Comment by athomasmoz** [comment]
Closing as lower priority for now.
