### ISSUE TITLE
Allow removing of tiles

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#443]
Allow deleting existing home tiles, and new ones. All tiles will be considered "pinned" (even the defaults).

SVG for menu icon: https://gist.github.com/liuche/5ca87ac2c9925cdb0e81094fa803fdfa
(this is the same as the one used in #513 so don't add this svg twice)

String for option: "Remove"

**Comment by liuche** [comment]
This is blacklisting tiles - keep in mind that there will be two cases: removing existing tiles, and then removing "pinned" tiles the user chooses.

**Comment by liuche** [comment]
Assigning to @lime124 for some mocks on what this "deletion" interaction should be. Easiest thing would be long-press to open up a context menu, but maybe this is not too discoverable. Adding new UI to the tiles could be okay, if it's simple, and easy to select with the remote (e.g., doesn't get confusing with moving left/right between tiles).

**Comment by lime124** [comment]
@liuche this is my line of thinking. when a tile is selected, the little circle with a menu icon appears. pressing menu opens up a content menu for that tile with the delete option. for now it's only delete but in the future it can hold other things.

unfortunately my sketch expired today and i'm still waiting on a license from IT so i'm totally locked out of my files. this was the best i could capture. and the send one is new tab in firefox show the context menu idea.

<img width="374" alt="screen shot 2018-02-16 at 8 52 01 pm" src="https://user-images.githubusercontent.com/287322/36338098-461168d8-135b-11e8-85f3-5ac517e591c5.png">

<img width="394" alt="screen shot 2018-02-16 at 8 51 48 pm" src="https://user-images.githubusercontent.com/287322/36338097-45fa86d6-135b-11e8-83c5-18b6d2f3a8fa.png">

**Comment by lime124** [comment]
based off of @mcomella 's suggestion, eitan agreed we should use " Fire TV has orientation text we can use: it tells the user the layout of the page and what to press to interact" to let the person know they can press the menu button to get that mini context menu.

**Comment by liuche** [comment]
@mcomella I'm not sure what "orientation text" is - does @bkmunar need to do anything else to make that work, or do we get it for free?

**Comment by mcomella** [comment]
@liuche It's kinda free: https://developer.amazon.com/docs/fire-tv/implement-voiceview-accessibility-features-fire-os.html#implementing-orientation-text-for-voiceview

**Comment by liuche** [comment]
@lime124 While hunting for new strings, I saw in the IA for #433 that we should have a confirmation toast for deleting a tile from the home screen.

Do we still want that confirmation, and if so, we'll need to get a string from @BrianNJones for it.
