### ISSUE TITLE
German translation of "Keep Turbo Mode Enabled" doesn't mean anything in German

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-tv#455]
This was reported by a German user here: https://bugzilla.mozilla.org/show_bug.cgi?id=1435201
Apparently, what is currently stated means "exit the turbo mode activated" in German, which doesn't mean anything.

The correct translation would be "Turbo Modus aktiviert lassen" (English meaning: "leave/keep the turbo mode activated")".

String can be found here: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/res/values-de/strings.xml#L191

**Comment by bbinto** [comment]
I confirm "Turbo Modus aktiviert lassen" should be used as the new string for keeping turbo mode active.

**Comment by liuche** [comment]
Just to confirm, do we want to ship this in a new 1.1.2 build? I'll file a bug.

**Comment by Sdaswani** [comment]
Yes please @liuche
