### ISSUE TITLE
Release eng for 1.1.2 build

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#458]
We want to make a 1.1.2 build next week, that will include the changes for #455, cut from the 1.1.1 branch NOT master.

- [x] Cut a new release branch from 1.1.1 branch, push it to the repo, and protect it (through Settings > Branches)
- [x] Update the version on the new 1.1.2 branch
- [x] Cherry pick #455, and any other changes we decide to ship in 1.1.2
- [x] Draft a release in Releases, matching the style of previous releases

**Comment by bkmunar** [comment]
@liuche can u review this

**Comment by bkmunar** [comment]
@Sdaswani 1.1.2 branch is available for u
