### ISSUE TITLE
v1.1.2 Release Check

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#466]
How I generated the build:
![screen shot 2018-02-05 at 2 53 33 pm](https://user-images.githubusercontent.com/4879954/35833145-caa02c40-0a84-11e8-8686-537b267a951b.png)

How I uploaded the build:
![screen shot 2018-02-05 at 2 54 22 pm](https://user-images.githubusercontent.com/4879954/35833151-d2f56090-0a84-11e8-9a87-e874d4b58e33.png)

@liuche please review before I submit. Thanks! cc @bkmunar

**Comment by Sdaswani** [comment]
Also Amazon shows the build is 1.1.2:
![screen shot 2018-02-05 at 2 58 05 pm](https://user-images.githubusercontent.com/4879954/35833192-067111ee-0a85-11e8-8d16-ddf7a29a3123.png)

**Comment by liuche** [comment]
Looks good to me, successful release build.

For future reference, in master we replaced the "focus" variant with "amazon", so for 2.+ builds we'll no longer be using focus.

**Comment by Sdaswani** [comment]
@liuche on bottom left of this picture you should see the commit logs:
https://user-images.githubusercontent.com/4879954/35833145-caa02c40-0a84-11e8-8686-537b267a951b.png
