### ISSUE TITLE
Remove allocations from CursorViewModel update loop

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#474]
Right now we're allocating ~60 times per second inside the update loop – it appears `delay`, from kotlin's coroutines, allocates:

![screen shot 2018-02-07 at 13 34 31](https://user-images.githubusercontent.com/759372/35948455-5e2e5d22-0c21-11e8-9e46-3f20a44a38c9.png)

We should move to an approach that does not allocate. It's possible there's a way to do this with coroutines that won't allocate but we could also move to a message-based Handler, which the CursorView currently uses to hide itself. Once you're done, use the profiler to ensure nothing is allocating inside the update loop!

Recommended P5 because, afaict, this isn't causing users to see any negative effects (though I think I see occasional GC while the Cursor is moving so maybe it is!).

Note: this specific issue was introduced as a result of the refactor but we still allocate in the existing code base so we're no worse off.

**Comment by Sdaswani** [comment]
Interesting. Thanks for filing @mcomella - agree it's a P5, but as the Fire is not a beast of a machine, we definitely want our code to be CPU and memory efficient.

**Comment by mcomella** [comment]
Fixed with #1912
