### ISSUE TITLE
UX work

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-tv#481]
Browse Screen
- [x] create UI for new cursor
- [ ] work with ? for cursor implementation
- [x] check progress on page loading animation
- [x] check progress on overall status bar

Nav Overlay
- [x] review progress and provide feedback
- [x] provide color for states (e.g. selection)
- [x] provide new assets to dev
- [ ] finalize UI

Home
- [x] settings placement #446 
- [ ]  provide color for button state (if different from nav overlay)
- [x] edit tile mode
- [ ] review progress and provide feedback

**Comment by mcomella** [comment]
2.0 work.

**Comment by lime124** [comment]
close!
