### ISSUE TITLE
Reactivate travis-ci + sputnik

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#483]
To make it easier to catch nits in reviews.

**Comment by mcomella** [comment]
Note: thanks to Bryan, TC will fail when there are lint errors but this will decrease the turn-around time.

**Comment by mcomella** [comment]
Sputnik isn't commenting on failed PRs like https://github.com/mozilla-mobile/firefox-tv/pull/704 – maybe we need to land the travis changes on master?

**Comment by mcomella** [comment]
Discovered [some logs](https://travis-ci.org/mozilla-mobile/firefox-tv/builds/356442105?utm_source=github_status&utm_medium=notification) from travis:
```
[DEBUG] 2018-03-21 16:42:42,688 Problem while reading env variable: sputnik_api_key
...
16:42:50.410 [main] INFO  p.t.s.connector.saas.SaasConnector - Sending violations: [{"file":".travis.yml","violations":[]},{"file":"README.md","violations":[]},{"file":"app/src/main/java/org/mozilla/focus/utils/DrawableUtils.java","violations":[{"line":21,"message":"[Checkstyle] ERROR: \u0027+\u0027 is not preceded with whitespace."},{"line":21,"message":"[Checkstyle] ERROR: \u0027+\u0027 is not followed by whitespace."}]}]
16:42:50.411 [main] INFO  p.t.s.connector.http.HttpConnector - Request  2: POST to https://sputnik.ci:443/api/github/mozilla-mobile/firefox-tv/pulls/704/violations?build_id=356442105
16:42:52.498 [main] INFO  p.t.s.connector.http.HttpConnector - Response 2: HTTP/1.1 500 Server Error
Exception in thread "main" pl.touk.sputnik.connector.saas.SaasException: Error when listing files, check your api key
	at pl.touk.sputnik.connector.saas.SaasFacade.publish(SaasFacade.java:65)
	at pl.touk.sputnik.engine.Engine.run(Engine.java:47)
	at pl.touk.sputnik.Main.main(Main.java:36)
Caused by: pl.touk.sputnik.connector.http.HttpException: Response status [500]
	at pl.touk.sputnik.connector.http.HttpConnector.consumeAndLogEntity(HttpConnector.java:56)
	at pl.touk.sputnik.connector.saas.SaasConnector.sendReview(SaasConnector.java:55)
	at pl.touk.sputnik.connector.saas.SaasFacade.publish(SaasFacade.java:63)
	... 2 more
```

Maybe I need to create an API key from my github account and pass it into travis as an env var?

**Comment by mcomella** [comment]
@pocmo Have you seen this?

**Comment by pocmo** [comment]
> @pocmo Have you seen this (no sputnik_api_key)? There's nothing in the docs about providing this.

> And actually, it looks like focus-android is breaking on this too (scroll down to log, unfold sputnik block). Maybe sputnik isn't maintained anymore...

Yeah, it just stopped working suddenly for us too. :(

I haven't looked to much into it and was hoping that it just fixes itself. However I noticed that they added support for ktlint and detekt and enabled that for Focus... in the hope that it will work again soon. :)

**Comment by mcomella** [comment]
Closed with https://github.com/mozilla-mobile/firefox-tv/commit/f67ad0af9a4f643222bb124fa3adcde7ab9622b3.

Hopefully sputnik will just start working again.

**Comment by mcomella** [comment]
> Hopefully sputnik will just start working again.

They fixed sputnik on the server-side: https://github.com/TouK/sputnik-ci/issues/15 Yay!
