### ISSUE TITLE
Firefox for Fire TV 1.1.2 doesn't work with Olympics videos on cbc.ca

### ISSUE THREAD

**Issue by rtanglao** [mozilla-mobile/firefox-tv#487]
# Steps to reproduce on Fire TV Basic or Fire TV 4K in Canada (not sure this works in the USA at all due to DRM)

1. olympics.cbc.ca
1. navigate to any video and click on play

# Expected Result

1. video plays (it plays in Silk)

# Actual Result

1. Error message repeatedly displayed:   "We are currently experiencing technical difficulties"
* video of error message: https://www.flickr.com/photos/roland/39542260824/

If this is webcompat please let me know where I should re-file this !

**Comment by Sdaswani** [comment]
cc @bbinto

**Comment by bbinto** [comment]
Slightly bias b/c of my Canadian love and past with the CBC , I'd consider it a timely P1 to at least figure out what the reason is. If you need contacts at CBC to discuss format/encoding, happy to make an intro.

And/or Susheel and I can punt over to Amazon for further investigation.

**Comment by mcomella** [comment]
I'm unable to reproduce in US: instead, I get an infinite loading spinner. Note that waiting long enough on this infinite spinner actually causes the WebView to stop loading pages: filed #488.

@rtanglao Can you reproduce with turbo mode off?

**Comment by Sdaswani** [comment]
@mcomella did turbo mode make a difference for you?

**Comment by rtanglao** [comment]
For what's it's worth, when I tried it in Silk, Silk displayed a dialogue box asking me to approve something along the lines of "unique identifier" or some such ? sorry for the vaguness but i can't get it to show up again in Silk! maybe this "identification" process doesn't work in Firefox for Fire TV for some reason?!?!

**Comment by rtanglao** [comment]
got it!
The dialogue that Silk displays is:
"olympics.cbc.ca wants to uniquely identify your device to play protected content" and the options are "BLOCK" and "ALLOW". This dialogue doesn't display in Firefox for Fire TV!

Screenshot:
https://www.flickr.com/photos/roland/26399841778/

**Comment by rtanglao** [comment]
@mcomella  here ya go :-)

ok weird, i have two fire tv sticks and they have different behaviour:

1. fire tv 4k : infinite spinner with or without turbo mode (but maybe we don't care about fire tv 4k because it's not supported in Canada?!?)
1. fire tv basic: Error message repeatedly displayed: "We are currently experiencing technical difficulties" with or without turbo mode

**Comment by Sdaswani** [comment]
Thanks @rtanglao i think we don't support DRM'ed content yet, so that may be the issue. I will ask Amazon about this.

**Comment by bbinto** [comment]
Here is the logcat
[v1.1.video.log](https://github.com/mozilla-mobile/firefox-tv/files/1729303/v1.1.video.log)

**Comment by Sdaswani** [comment]
@rtanglao Amazon did some digging and they said the video worked in silk - can you give a specific example of a video (if you have the URL) that worked in silk please? And you are in Vanada right?

**Comment by mcomella** [comment]
[triage] Unactionable without additional info: Roland please reopen if you respond.

**Comment by Sdaswani** [comment]
No worries @rtanglao!

**Comment by rtanglao** [comment]
* I am in Vancouver Canada. The following link (and all CBC event replay videos from the Olympics) works in Silk on my 4K Fire TV stick  in Vancouver, BC, Canada where I live: https://olympics.cbc.ca/video/todays-events/cross-country-skiing-feb-team-sprint-free-finals/
* https://olympics.cbc.ca/video/todays-events/cross-country-skiing-feb-team-sprint-free-finals/ doesn't work in Firefox for Fire TV in Vancouver, BC, Canada
* I don't think https://olympics.cbc.ca/video/todays-events/cross-country-skiing-feb-team-sprint-free-finals/ will work on any browser (Silk or Firefox for Fire TV) outside of Canada
* If the Amazon folks are USA based, they can either use a VPN with a Canadian IP address or ask their Amazon Canada colleagues :-) This is due to DRM I guess
* Having said the above, I realize that this is probably not the highest priority but perhaps other video sites will have similar DRM issues. If not feel free to close as WONTFIX of course

**Comment by Sdaswani** [comment]
Thanks for the legwork @rtanglao ! As the olympics are over, we can WONTFIX, but I really appreciate your help identifying issues and I thank you in advance for reporting more that you find in the future.

**Comment by rtanglao** [comment]
thanks @Sdaswani  i assume that we will have the same issue with the CBC paralympics videos, i'll add a comment here if we do indeed have issues. The paralympics start on March 9 and go for a week. Again probably not big enough to reopen. But maybe the same or similar for NFL, NBA, March Madness Basketball etc?

**Comment by Sdaswani** [comment]
@rtanglao I was going to ask you to check March Madness actually - is that big in Canada?
