### ISSUE TITLE
Browser stops loading any page after trying to watch CBC videos (e.g. March Madness? formerly: Olympics)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#488]
STR
1) Visit olympics.cbc.ca
2) Watch recap video (i.e. not live)

Expected: Video loads
Actual: Infinite loading spinner. When pressing back, the page doesn't change. Clicking back to home and selecting a new home tile will not load the page and only show a white screen.

Note: I reproduced this in the US. Randall sees different behavior in CA: #487.

CC @Sdaswani @bbinto

**Comment by Sdaswani** [comment]
Olympics fin.

**Comment by mcomella** [comment]
[triage] This may affect seasonal events like March Madness – let's see if we can reproduce at all.

**Comment by Sdaswani** [comment]
@Sdaswani to test March Madness.

**Comment by Sdaswani** [comment]
It's not a great experience, but you can play videos at ncaa.com/marchmadness, and according to [this](https://www.ncaa.com/news/basketball-men/article/2016-03-07/ncaar-march-madnessr-livetm-provide-access-2016-ncaa-division) you'll be able to live stream games from there when the tourney begins.

You can load videos, but the play button oddly takes a while to appear - I wonder if there is some js gating the loading of the play button.

@bbinto a few thoughts:
1) our 2.0 release coincides with the start of the tournament - do we want to drop a tile for this site, and an associated sumo article on how to play?
2) do we want to spend some time making the experience better, i.e., investigating while the play button is slow to load?

**Comment by bbinto** [comment]
+1 for the idea, Susheel, might be a nice delightful experience for the user.

As for SUMO, you'd want to cover the play button delay in there?

**Comment by Sdaswani** [comment]
@bbinto yes, we cover the play button delay article in the SUMO article, since we will have it pinned. But there is an argument that we shouldn't pin it without making the experience super slick (so we would want to investigate making it better).

**Comment by bbinto** [comment]
Do we need to discuss the play button delay in SUMO though? What makes a topic worth putting on SUMO?

So maybe let's not include it and let the user decide if they want to pin it?

**Comment by Sdaswani** [comment]
I thought if we pin it then we should have some instruction around it. If we let the user pin it themselves, I agree no need for a SUMO.

**Comment by bbinto** [comment]
Ok, let's not pin it
