### ISSUE TITLE
update cursor/pointer

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-tv#489]
update from the blue circle to an svg.

**Comment by boek** [comment]
https://gist.github.com/boek/3383a5e43b563874649aae694c95f6c6

Here is the svg!

**Comment by mcomella** [comment]
fwiw, the cursor draws in the top left corner and uses translation to move across the screen – we could make that more intuitive if we are using an SVG (rather than a radial gradient). That being said, I don't know what the most efficient way to do this is and I assume translation is pretty efficient.

**Comment by liuche** [comment]
Waiting on some new assets from UX which has some dependencies, so we're moving this out into 2.1.

**Comment by mcomella** [comment]
@lime124 The new asset has padding built into it, which means the cursor (constrained by the 45dp we specify) appears smaller:

![device-2018-03-21-134601](https://user-images.githubusercontent.com/759372/37736502-5382dcdc-2d0e-11e8-91ef-ade296f24572.png)

![device-2018-03-21-134503](https://user-images.githubusercontent.com/759372/37736505-55300b7c-2d0e-11e8-97c4-0c9bfc0c6425.png)

Is that okay? If we want to make it bigger, we're going to need larger assets.

fwiw, I notice I tend to overshoot things more often with this cursor (though the hit area is smaller than the cursor so maybe that's fine).

**Comment by lime124** [comment]
One usability problem I'm seeing with the old, bigger cursor vs the new, smaller one is that on my TV (which has lots of overscan) I 'lose" the cursor when scroll up/down or side to side. The smaller one completely goes off screen, whereas some part of the cursor remains visible with the larger one.

Are other people experiencing that too?

To fix the overshot problem, can we make the target area bigger without changing the cursor size?

**Comment by mcomella** [comment]
This was accidentally closed so I'm moving UX review to #721.
