### ISSUE TITLE
Telemetry for custom tiles

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#490]
- [x] differentiate between clicking a custom tile vs default tiles
- [x] delete custom/default tile
- [x] pin/unpin custom tile
- [x] count # of custom tiles, and total tiles (to create a histogram)

We also need to restore the telemetry removed with the Overlay addition:
- [x] Back/forward/reload
- [x] home
- [x] settings
- [x] Turbo
- [x] URL bar
- [x] Overlay opened/closed

**Comment by mcomella** [comment]
Waiting on deletion of tiles: #443.
