### ISSUE TITLE
Overlay Doesn't Disappear after URL / Search Input

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#502]
STR:
1. Open FTV 1.4 / master
2. Open Overlay
3. Enter a search term (or a site, haven't tried, but assume affected too)
4. Press enter

Expected: Overlay is dismissed, and search result page is shown
Actual: Overlay remains, and search result page is shown under overlay

**Comment by liuche** [comment]
Overlay should disappear after entering url/search term.
