### ISSUE TITLE
Send usage data checkbox is always set to not selected

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#503]
AmazonWebvieeDebug variant, commit 068a0d69d5e21662b212d042f94dcb69eda01e72

Even when I go into settings and set Send usage data to true, when I exit and revisit the Settings page, it's set as not selected.

**Comment by Sdaswani** [comment]
I think this has to do with debug builds only, it shouldn't happen with 1.4.

**Comment by npark-mozilla** [comment]
Found that this is as expected for debug build, closing.

**Comment by npark-mozilla** [comment]
@liuche just to confirm, this is expected behavior, correct?
