### ISSUE TITLE
[debug only] Selecting About in Settings crashes app

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#504]
On AmazonWebviewDebug build, commit 068a0d69d5e21662b212d042f94dcb69eda01e72

STR:
Go to Settings
select/unselect 'Send usage data' 
click 'About'

Expected:
Shows blank about page

Actual:
App exits with this stack trace:

/art     ( 2515): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/ResourceType( 2515): Attempt to retrieve bag 0x0103003e which is invalid or in a cycle.
D/AndroidRuntime( 2515): Shutting down VM
E/AndroidRuntime( 2515): FATAL EXCEPTION: main
E/AndroidRuntime( 2515): Process: org.mozilla.tv.firefox.debug, PID: 2515
E/AndroidRuntime( 2515): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.tv.firefox.debug/org.mozilla.focus.activity.InfoActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class org.mozilla.focus.web.IWebView
E/AndroidRuntime( 2515): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2367)
E/AndroidRuntime( 2515): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435)
E/AndroidRuntime( 2515): 	at android.app.ActivityThread.access$800(ActivityThread.java:160)
E/AndroidRuntime( 2515): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 2515): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2515): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2515): 	at android.app.ActivityThread.main(ActivityThread.java:5483)
E/AndroidRuntime( 2515): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2515): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2515): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
E/AndroidRuntime( 2515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/AndroidRuntime( 2515): Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class org.mozilla.focus.web.IWebView
E/AndroidRuntime( 2515): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:767)
E/AndroidRuntime( 2515): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
E/AndroidRuntime( 2515): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
E/AndroidRuntime( 2515): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
E/AndroidRuntime( 2515): 	at org.mozilla.focus.fragment.InfoFragment.onCreateView(InfoFragment.java:40)
E/AndroidRuntime( 2515): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
E/AndroidRuntime( 2515): 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
E/AndroidRuntime( 2515): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
E/AndroidRuntime( 2515): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1252)
E/AndroidRuntime( 2515): 	at android.app.Activity.performStart(Activity.java:6042)
E/AndroidRuntime( 2515): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
E/AndroidRuntime( 2515): 	... 10 more
E/AndroidRuntime( 2515): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter factory
E/AndroidRuntime( 2515): 	at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.kt)
E/AndroidRuntime( 2515): 	at org.mozilla.focus.activity.InfoActivity.onCreateView(InfoActivity.java:107)
E/AndroidRuntime( 2515): 	at android.app.Activity.onCreateView(Activity.java:5341)
E/AndroidRuntime( 2515): 	at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:41)
E/AndroidRuntime( 2515): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
E/AndroidRuntime( 2515): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737)
E/AndroidRuntime( 2515): 	... 31 more
I/AndroidRuntime( 2515): To Report FATAL to activityManagerService
I/ActivityManager(  974): handleApplicationCrash
W/ActivityManager(  974):   Force finishing activity 1 org.mozilla.tv.firefox.debug/org.mozilla.focus.activity.InfoActivity
I/ActivityManager(  974): addErrorToDropBox inserted hashcode=46ed9db36343a6d639288feee8cfaab80a3bb30c for eventType crash.
I/Vlog    (  974): 3p:fg_crash:fgtracking=false;DV;1,key=org.mozilla.tv.firefox.debug;DV;1,Counter=1.0;CT;1,unit=count;DV;1,metadata=46ed9db36343a6d639288feee8cfaab80a3bb30c!{"d"#{"app_version"#"11"}};DV;1:HI

**Comment by Sdaswani** [comment]
I think I saw this too but couldn't repro.

**Comment by Sdaswani** [comment]
I saw it on a stick.

**Comment by npark-mozilla** [comment]
@liuche  that was on a stick

**Comment by liuche** [comment]
I don't see this on Beta, and I'm pretty sure this is the #503 + debug telemetry always off interaction. Will look more into this later, but I don't think this affects release.

**Comment by Sdaswani** [comment]
@liuche i saw the crash on the settings page in the LAT version. but i couldn't repro after the one timei saw it crash.

**Comment by AaronMT** [comment]
I get this only if I deselect send usage data first

**Comment by Sdaswani** [comment]
@AaronMT can you reliably reproduce?

**Comment by boek** [comment]
Did we fix this? I'm not able to reproduce from master on the stick

**Comment by Sdaswani** [comment]
I don’t think so @boek - @AaronMT was able to reliably reproduce as of yesterday.

**Comment by Sdaswani** [comment]
@AaronMT can you reliably reproduce on the LAT version, or only on debug?

**Comment by liuche** [comment]
If this only debug-only, we should move this out of the 2.0 milestone and into the triage list.

**Comment by liuche** [comment]
Moving out of 2.0 since it's debug-only.

**Comment by npark-mozilla** [comment]
I tested with the Live app and verified that it doesn't happen on it.

**Comment by AaronMT** [comment]
I haven't seen this in a while, I can select About when I build debug locally
