### ISSUE TITLE
Screenshots for l10n review

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-tv#505]
Heads-up that v2 has been completed from an l10n point of view: https://pontoon.mozilla.org/projects/firefox-for-fire-tv/

However, heads-up that we can't test these languages until we get screenshots and l10n builds for testing. Note that builds would only be accessible to me (since localizers don't have Fire TV) - so while I can do *some* testing on locales, it wouldn't be 100% reliable since I don't understand most of these languages, and thus I wouldn't be able to always tell if we're missing important words or if they are truncated / overlapping / etc.

A couple questions:
* do we expect any new strings at this point for v2 (@Sdaswani, @lime124)? 
* any idea when we can expect to get screenshots in place for testing? Can we get this up on a roadmap somewhere if it's not expected for v2? (FWIW since there aren't that many new strings in v2, I don't think it's critical at this point to get the screenshots for that version. It's going forwards that it's really going to become crucial)

thanks!

**Comment by liuche** [comment]
Will decide if this needs to be in 2.0, based on what new strings we have - definitely needs to be in 2.1 at the latest.

**Comment by Sdaswani** [comment]
@Delphine thanks for the update.

1. To confirm, the strings for v2 that you've localized already are the two listed in this GH issue description: https://github.com/mozilla-mobile/firefox-tv/issues/441#issue-293323029
2. Unfortunately, it looks like we will need to localize a few other strings: it looks like we will need a few more strings localized for v2.0: https://github.com/mozilla-mobile/firefox-tv/issues/441#issuecomment-367126724
3. l10n screenshots probably won't be available for 2.0, so we will have to get by with your 'best effort' described above. @npark-mozilla @AaronMT not sure if you guys can swoop in for a rescue and think of a way to easily get screenshots automated?

**Comment by Delphine** [comment]
1. I see neither "Pinned to Firefox TV homescreen" or "Removed from Firefox TV homescreen"
in our current strings. So unless they've been modified, we don't have these two in yet.
The strings that were localized for v2 are the ones for the tiles on the homescreen + the Turbo Mode ones that localizers had to update since it was done by MT initially

2. Ok. Please let me know what the l10n timeline looks like for these as soon as you know (when we'll get them + deadline by when we need to hand them back in) so that we can distribute all our current Mozilla l10n product work evenly amongst localizers

3. Thanks for the heads-up. Waiting on No-Jun and Aaron in case! :)

**Comment by npark-mozilla** [comment]
@Sdaswani In theory what we do in focus android should work for firefox tv - we'll take a look, but no promises for v2 :) but I think we can get this working eventually. so a quick question for @Delphine : is there a l10n webpage for firefox tv that lists all supported locales?

**Comment by Delphine** [comment]
@npark-mozilla: We have a list of the locales we ship on Mozilla side, I think that's what interests you most: 
* easy to read because there are both language and equivalent locale code: https://pontoon.mozilla.org/projects/firefox-for-fire-tv/
* l10n repo for project: https://github.com/mozilla-l10n/firefoxtv-l10n/tree/master/locales
Thanks for looking into this!

**Comment by liuche** [comment]
Since this is a recurring question, I've created a (very skeletal) l10n wiki page here: https://github.com/mozilla-mobile/firefox-tv/wiki/Localization

**Comment by Sdaswani** [comment]
@Delphine do you have all the strings for 2.0 yet? My guess is no so if not @lime124 can you please put them here when you get a chance?

**Comment by Delphine** [comment]
I don't know if I have all the strings for 2.0 - if there are still more please let me know (+ we need a deadline for them too). Thanks

**Comment by liuche** [comment]
@Delphine where should I put new strings that need to be translated? I'll put the ones we have here:
"Pinned to Firefox TV homescreen"
"Removed from Firefox TV homescreen"

Should we file another bug, or do we need to export anything yet?

**Comment by liuche** [comment]
Closing this because @Delphine signed off on screenshots on Tuesday PST morning.
