### ISSUE TITLE
Get titles for custom home tiles

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#511]
In desktop AS, [titles appear to come from `link.label || link.hostname`](https://github.com/mozilla/activity-stream/blob/2456e6e386b54f6627422da85a895eeafc1fc379/system-addon/content-src/components/TopSites/TopSite.jsx#L163) where:
- `link.label` appears to be [a user defined value](https://github.com/mozilla/activity-stream/blob/2456e6e386b54f6627422da85a895eeafc1fc379/system-addon/content-src/components/TopSites/TopSiteForm.jsx#L54)
- `link.hostname`, from my memory with fennec AS and without digging into the code, is `subdomain.domain` e.g. `bugzilla.mozilla` for bugzilla.mozilla.org

One problem I see here: if a user pins two sites from the same "subdomain.domain", the titles will be identical as will the icons if a screenshot isn't used. Desktop gets around this by 1) not choosing two sites from the same "subdomain.domain" and, 2) if a user adds another one, allowing the user to customize the title.

@lime124 How do we want to solve this (since we don't allow custom titles, afaik)? fwiw, in fennec, we had a more complicated title scheme that we can borrow (something like if there's a collision, we use the page titles instead, or display some of the page path).

TODO:
- Steal ["subdomain.domain" code from fennec](https://searchfox.org/mozilla-central/rev/47cb352984bac15c476dcd75f8360f902673cb98/mobile/android/base/java/org/mozilla/gecko/util/URIUtils.java#88) (since removing TLD is non-trivial otherwise).
- Hook up subdomain.domain extraction to the overlay (blocked on #441)

**Comment by lime124** [comment]
@mcomella and I chatted in slack and settled on implementing what fennec does until we are able to implement the ability that let's people edit the name.

**Comment by mcomella** [comment]
Spoke with Tif on Slack: we should look at what fennec does when there are name collisions and try that. I'd recommend passing that algo by Tif again because it's dealing with a more complicated use case (where sites can be added arbitrarily by an algorithm).

**Comment by mcomella** [comment]
fwiw, once you dig out the algorithm, I suggest passing it by Tif again because fennec is dealing with a different use case (naming an auto-generated list of sites).

**Comment by mcomella** [comment]
@lime124 Assuming we couldn't get around to doing what fennec does in the case of name collision, is "subdomain.domain" an acceptable v1?

**Comment by lime124** [comment]
as @mcomella and i discussed, yep that works for me!

**Comment by liuche** [comment]
FYI my current implementation of pinning just uses the (possible heavily wrapped) url.

![screenshot_1519691249](https://user-images.githubusercontent.com/1082253/36710037-452b5776-1b30-11e8-9843-5399598a8434.png)

**Comment by mcomella** [comment]
I filed #583 for name collisions polish.
