### ISSUE TITLE
Very difficult to input urls on emulator

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#512]
![screenshot_1519241541](https://user-images.githubusercontent.com/1082253/36501120-226f1706-16fb-11e8-8177-25a45ec1eeae.png)

Keyboard covers the text input.

Possible solutions:
- Set "resize keyboard" but we need to make sure this doesn't affect the onscreen Amazon keyboard
- Partial fix: select all text on click, so even though you can't see the text bar, you can type something into the text box

**Comment by mcomella** [comment]
fwiw, if we ported this app to Android TV, I assume we'd have the same problem.

**Comment by mcomella** [comment]
[triage] Try the obvious fix – add resizeKeyboard. If it doesn't work, unassign – it's probably not worth it.

**Comment by mcomella** [comment]
Aaron mentions this makes QA difficult so I'm throwing this back to triage.

**Comment by mcomella** [comment]
This isn't an issue anymore: the url bar is above the fold.
