### ISSUE TITLE
Add "Close" hint and logo to overlay

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#513]
See #433 for mocks.

Neither part should be focusable.

Menu SVG: https://gist.github.com/liuche/5ca87ac2c9925cdb0e81094fa803fdfa
(this is the same as the one used in #443 so don't add this svg twice)

~~@mcomella do you know how a11y works for things that aren't selectable?~~
No a11y text needed

**Comment by mcomella** [comment]
Things that are not focusable will not be spoken unless you add in-code overrides.

However, Amazon provides "Orientation text" that will explain to the user the layout of the page and perhaps how to close it. I think hitting menu to close the menu after you hit menu to open it is intuitive though – the visual cue is just a reminder.
