### ISSUE TITLE
FirefoxProgressBar constantly redraws itself, even when hidden

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#519]
It works on `87a3260c` but stops working on `a3ce1676` (from #287), where the loading progress indicator was added. It hangs on `assertBodyText` when we stop to make sure the page was loaded. I'm not sure why this would happen... :\

**Comment by mcomella** [comment]
Note: this isn't a terribly important test because we'll probably notice pretty quick if JS evaluation breaks.

**Comment by mcomella** [comment]
@pocmo @npark-mozilla Do you know why adding a view over the WebView (the progress bar, which also animates) might cause:
```kotlin
onWebView()
                .withElement(findElement(Locator.TAG_NAME, "body"))
                .check(webMatches(getText(), equalTo(expected)))
```

to hang? I think it gets stuck on withElement or findElement.

**Comment by npark-mozilla** [comment]
@mcomella I remember a while back when I was trying to use Locator.TAG_NAME, it often hung, so I try to stick with .ID for the most case.

**Comment by mcomella** [comment]
Changing to ID doesn't seem to be working. Here's my diff
```
diff --git a/app/src/androidTest/java/org/mozilla/focus/integration/IWebViewEvalJavascriptTest.kt b/app/src/androidTest/java/org/mozilla/focus/integration/IWebViewEvalJavascriptTest.kt
index 6ab98adf..b1b27642 100644
--- a/app/src/androidTest/java/org/mozilla/focus/integration/IWebViewEvalJavascriptTest.kt
+++ b/app/src/androidTest/java/org/mozilla/focus/integration/IWebViewEvalJavascriptTest.kt
@@ -65,7 +65,7 @@ class IWebViewEvalJavascriptTest {
     @Test
     fun evalJSTest() {
         val expectedLoadedText = "Loaded"
-        mockServer.enqueue(MockResponse().setBody("<html><body>$expectedLoadedText</body></html>"))
+        mockServer.enqueue(MockResponse().setBody("<html><body id='body'>$expectedLoadedText</body></html>"))
         mockServer.start()
         val url = mockServer.url("").toString()
 
@@ -114,7 +114,7 @@ class IWebViewEvalJavascriptTest {
 
     private fun assertBodyText(expected: String) {
         onWebView()
-                .withElement(findElement(Locator.TAG_NAME, "body"))
+                .withElement(findElement(Locator.ID, "body"))
                 .check(webMatches(getText(), equalTo(expected)))
     }
```

**Comment by mcomella** [comment]
Ah, if I leave it idle long enough, I get:
```
android.support.test.espresso.AppNotIdleException: Looped for 3535 iterations over 60 SECONDS. The following Idle Conditions failed .
```

Maybe something is still running on the UI thread.

**Comment by mcomella** [comment]
I figured it out – good thing we have tests! :)

`GifImageView` calls `invalidate` at the end of `onDraw`, which causes `onDraw` to be called again. This might be able to be fixed by setting `Visibility = GONE` on animation end (which we probably should do when the progress bar is hidden anyway) or explicitly stop calling invalidate at some point.

@bkmunar Can you look into fixing this?
