### ISSUE TITLE
String translations/l10n import + export for v2.0

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#523]
Here are the outstanding strings that we need for translation:
- [x] Pinned to Firefox TV homescreen
- [x] Removed from Firefox TV homescreen
- [x] Pin (accessibility text for button)
- [x] Close (Close Hint in the overlay)
- [x] Remove (delete tile from home screen, but this can be reused if necessary)
- [ ] ? "is checked" for #528 (but we might get that for free)
- [x] String export
- [x] String import

Strings should be exported and passed off to @Delphine by 3/6, and deadline for re-import is 3/12.

**Comment by Delphine** [comment]
Thanks!
We've got our l10n repos up and Pontoon hooked up for translation. Jeff did an export last week, so we can follow the same process from now on for strings :) thanks!

**Comment by liuche** [comment]
@lime124 and @BrianNJones are there any other new strings that we need for 2.0? I think "delete" we can reuse.

**Comment by lime124** [comment]
We don't have that many visible strings in general. For accessibility, I'm not sure where those strings are saved. Do you @liuche ? Ideally, I would like to just be able to look at the strings.xml file to give a better answer but right now there's too much extra stuff in there.

In the nav overlay there's:
- Search or enter address [in the text box]
- Close [isn't in the UI yet - @liuche you filed a ticket for that]
- the two strings above for the toast [pinned/removed from homescreen]

In the browser there aren't any strings that come to mind outside of the error strings we reused from Focus.

On the homsecreen:
- Search or enter address [which is the one as from the nav overlay]
- the tiles use URLs/page titles - things that don't need translation
- the context menu, we'll only have "Remove"

Settings, everything is the same. We _do_ need to update some of them but haven't done it. And we aren't doing parental controls.

And finally Turbo Mode onboarding, we didn't touch that screen at all either.

Surely I've forgotten something, that seems like very few strings...?

**Comment by liuche** [comment]
Thanks for the follow-up, @lime124 ! Self-assigning to go through the strings Tif highlighted and get the strings in for exporting (and also go through any more of the mocks). @Delphine we'll plan to have an export to you on Thursday.

**Comment by liuche** [comment]
@bbinto @Sdaswani what's the date for the last string import FROM l10n? 3/12 will give us 2 weekends for localization (but that's only one day before the release which is 3/13).

(3/9 was our original code freeze so I told Delphine that would be the earliest deadline for "last import".)

**Comment by Sdaswani** [comment]
I'm fine 3/12 being the last date for import, assuming all we do on 3/12 is import new strings into the 2.0 branch that we froze on 3/7.

**Comment by Delphine** [comment]
Thanks everyone! I think that should work. I've notified localizers about the next export date for strings as well as the deadline for completion.

**Comment by boek** [comment]
I added Close as well to the checklist

**Comment by BrianNJones** [comment]
Thanks Tif. I've been locked out of email since Friday (had to get new
phone and multi-factor auth via DUO wasn't playing nice).

We've prioritized re-using strings, so new ones should be minimal. Nav
overlay "Search or enter address" is in both Firefox and Focus. The 2 toast
strings are net-new, however.

-Brian

**Comment by Delphine** [comment]
@liuche: hey, any updates concerning the string export for this? will you be doing any in the end? thanks!

**Comment by liuche** [comment]
Hi @Delphine, I'm just wrapping up the last new string I think we'll have, #551. I could do an export earlier than March 6 (discussed earlier in the thread), like later today or tomorrow - will ping you about that.

**Comment by Delphine** [comment]
@liuche: Aha, ok I got confused - I understood we were supposed to get these strings last Tues (but the thread indicates I'm wrong, haha!). Thanks!

**Comment by liuche** [comment]
Closing this because everything is done - we'll do one more string import on 3/12.

**Comment by Delphine** [comment]
@liuche: Unless I'm missing something - since we just exposed strings a couple hours ago, I think we're going to need a couple (few? Depending on if we need to go in and fix strings - to check they are in fact fixed) more imports before 3/12 in order to generate up to date screenshots for l10n QA. I can let you know when locales are looking more caught up.

**Comment by Sdaswani** [comment]
I think that makes sense @Delphine - @npark-mozilla and @AaronMT have kindly volunteered to run screenshots as necessary, do let us know when they are caught up.

**Comment by Delphine** [comment]
@Sdaswani : Thanks! I see they are mostly caught up (all except 2 that are at 97%)
If it's possible to run screenshots with latest strings today or tomorrow, that would be great. And then one last time at the very end of the week (since deadline I believe would be Mon). Thanks everyone!

**Comment by Sdaswani** [comment]
We will run them Thursday morning and next Tuesday morning - does that work @liuche ?
