### ISSUE TITLE
[perf] Use hardware rendering for progress bar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#525]
In order to use an animated gif in #287, we use a software layer for `FirefoxProgressBar`. However, the CPU (and maybe the GPU, tbh) is being used for page load so using software layers will slow down page load time. We should move back to the GPU (and perhaps investigate the effect of the loading animation on page load performance there).

fwiw, before bug #519 is fixed, the progress is constantly redrawing itself and on my emulator (not a great metric compared to the TV), the CPU hovers between 20-30% CPU usage compared to 0% with a WIP fix.

CC @bkmunar @liuche

**Comment by mcomella** [comment]
Another thought: currently, we call `invalidate` at the end of `onDraw` – does the system limit this to 60 FPS (a reasonable number of times to draw) or are we actually drawing as fast as the CPU dispatch `onDraw` calls, utilizing more CPU than we need to?

**Comment by mcomella** [comment]
[triage] Ideal for 2.0 but we can check with Barbara if she notices page load perf and if not, drop it to 2.1.

Might be fixed with AnimatedVectorDrawable but apparently runs on UI thread in APIs before 25, so might run in software anyway.

**Comment by Sdaswani** [comment]
@sdaswani and @bbinto to test and give their opinion, also @AaronMT and @npark-mozilla to give their thoughts on if page loading is slow because of this.

**Comment by mcomella** [comment]
I notice a big perf difference on the Fire Stick (SF office) when trying to move the cursor while the page is loading and the progress bar is shown.

**Comment by Sdaswani** [comment]
Yes, though I'd say it's not unusable, thought it's responsive _enough_ (e.g., you can still scroll the page down, etc.). Something to fix up in 2.1, for sure.

**Comment by liuche** [comment]
Clearing assignees bc this is enough of a noticeable change that we should fix it.

**Comment by mcomella** [comment]
@liuche I was thinking one solution to this bug would be to convert Gifs to AnimationDrawables, which I think is better supported than the `Movie` class. I found a script, though we'd have to vet it: https://medium.com/@tushar.acharya/converting-animated-gifs-to-animationdrawables-c6594084d7ad
