### ISSUE TITLE
Run detekt on taskcluster (and fix issues)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#537]
`detekt` doesn't seem to run for pull requests or master merges. So far there are 35 smells reported.

**Comment by mcomella** [comment]
@bkmunar says there were a lot of issues to correct, so we did intentionally punt this.

**Comment by mcomella** [comment]
We should only do this after removing unused code.

**Comment by bkmunar** [comment]
@mcomella I'm picking this up, is it ok to do what sebastian said? Just use detekt where the condition is at right now depending on how many "smells" there are?
