### ISSUE TITLE
Run spotbugs on taskcluster (and fix issues)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#538]
Like detekt (#537) findbugs doesn't seem to run on taskcluster for pull requests and master pushes. There are 6 warnings so far.

**Comment by Sdaswani** [comment]
@bkmunar says there were a lot of issues to correct, so we did intentionally punt this.

**Comment by mcomella** [comment]
I think findbugs is no longer maintained and spotbugs replaced it.

**Comment by mcomella** [comment]
We only try to write new kotlin code so I don't think it's worth the time to get this working as it only runs on Java, afaict: https://github.com/spotbugs/spotbugs/issues/573
