### ISSUE TITLE
Improve structure of the overlay views: don't use nested LinearLayouts

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-tv#540]
When adding items to the top/bottom right corners of the overlay I added a nested layout_weight. We should improve the structure to support pinning views to all four corners

context: https://github.com/mozilla-mobile/firefox-tv/pull/529#discussion_r170763479

**Comment by mcomella** [comment]
I think we should address this when it becomes a problem (e.g. when we're stuck changing the code or there are perf problems). Closing for now so we don't have to push around the issue.
