### ISSUE TITLE
URL bar will overwrite user input when loading

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#548]
STR:
1) Click IMDB

The next steps should be performed quickly, while the page loads

2) Open menu
3) Start typing

Expected: input stays
Actual: input is overwritten by redirects

**Comment by mcomella** [comment]
This is pretty bad, I'm putting it in 2.0 and would even call it a release blocker.

**Comment by boek** [comment]
What I kinda got to work was using

```
val imm = activity.getSystemService(Context.INPUT_METHOD_SERVICE) as? InputMethodManager
imm?.isAcceptingText
```

This returns true when the TextEdit has focus. But it can have focus without the soft keyboard up. Which could prevent the URLBar from updating while the overlay is open and the URLBar has focus. Any further insight or suggestions would be greatly appreciated!
