### ISSUE TITLE
Add accessibility string to "pin" behavior

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#551]
Quoting from #441
liuche:
> Okay, so the string can be "Pin"? Just wanted to explicitly ask what string I should add as the label for the thumbtack icon. (or "Pin to top sites" or "Pin to home screen" or whatever was suggested earlier in this thread.)

BrianNJones:
> @liuche @lime124 I think we need a slightly more expansive accessibility string than "Pin." Recommend "Pin to homescreen"...is there concern that there may be confusion re: whether reference is to Firefox TV vs. device homescreen?

**Comment by liuche** [comment]
Opening this as a separate bug so we could land the code.

Since we have the toast for the pin/unpin action, and it's reversible, do you think that would be enough? It might be confusing, so I would also be fine with it saying "Pin site to Firefox homescreen".

**Comment by lime124** [comment]
To be clear - this is the label for the pin button? This isn't for the toast that appears after the pin button is toggled.

I think we  do need to be concise as this word(s) is going to be read by the screen reader each time the focus lands on the button as well as the current state. e.g turbo mode, checkbox, checked. 

I do think Pin to Firefox homescreen,checkbox, checked to heading towards wordy. I'm not sure about just Pin to homescreen, checkbox, checked. 

Do you have any thoughts @eeejay?

**Comment by eeejay** [comment]
"Pin to homescreen" does seem better. I'm not sure I'm following why "Pin site to Firefox homescreen" was suggested. What will the toast string be?

**Comment by BrianNJones** [comment]
I'm good w/"Pin to homescreen."

**Comment by liuche** [comment]
After this string has been added we can export and close #523
