### ISSUE TITLE
Ellipsize text in urlbar (on overlay and loading url bar)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#563]
Moving this out of Milestone 2.0, because @lime124 says this isn't a blocker.

**Comment by liuche** [comment]
@boek looked at ellipsizing and it's hard because of the autocomplete, but a fallback could be fixing the size of the progress bar.

**Comment by liuche** [comment]
@lime124 to follow up with legal about if there are any problems with not showing the entire url.

**Comment by lime124** [comment]
removing legal - there's no problem here. I've opened another GH issue to cover those concerns/thoughts: #693 

We're good to ellipsize the URL 'button' in the overlay. I can provide a width for the progress bar (but not right this second :) )

**Comment by athomasmoz** [comment]
closing as no longer relevant
