### ISSUE TITLE
Come up with a better active state for nav overlay buttons

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-tv#564]
Currently the active and focus state are a little too similar.

---

![screen](https://user-images.githubusercontent.com/1250545/36918822-fb7d2eaa-1e0f-11e8-8d4a-e0571c26a6f6.png)

**Comment by Sdaswani** [comment]
XS once @lime124 decides on a color.

**Comment by boek** [comment]
![image](https://user-images.githubusercontent.com/1250545/37065038-2c4fc5be-2154-11e8-86bf-2e7ea73a9d05.png)
