### ISSUE TITLE
Use a single HomeTilesManager to handle pinning/unpinning sites

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#569]
Currently, we use both BundledTileManager and HomeTileManager to handle pinning and unpinning, but we should extract that out into a single interface of pin/unpin so it's not confusing. Follow-up to #533

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
