### ISSUE TITLE
Deleting a Custom Tile Crashes the App

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#571]
STR:
1. Create a Custom Tile
2. Try to delete it

**Comment by liuche** [comment]
@Sdaswani is this deleting from the home screen, or unpinning it?

**Comment by Sdaswani** [comment]
Deleting from the home screen, I didn't try unpinning it from overlay.

**Comment by Sdaswani** [comment]
This doesn't happen with the latest LAT.

**Comment by mcomella** [comment]
Removing from milestone to make our issue count more accurate: this was fixed with #443.
