### ISSUE TITLE
Deleting a Pinned Tile Doesn't Actually Delete It

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#572]
STR:
1. Go to Home Screen, and delete a Pinned Tile
2. Load a site
3. Go back to Home Screen, Pinned Tile remains

**Comment by Sdaswani** [comment]
This has been fixed with the latest LAT.

**Comment by mcomella** [comment]
Removing from milestone to make our issue count more accurate: this was fixed with #443.
