### ISSUE TITLE
Pinned sites should be added to the end of the list

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#573]
I think it should be put at the bottom, or at least Youtube shouldn't be displaced. Not sure what @lime124 had in mind though.

**Comment by liuche** [comment]
In the spec, we said pinning the site puts it at the top. @lime124, what do you think?

**Comment by Sdaswani** [comment]
That is a fair decision but just wanted to call it out to @bbinto since Youtube wouldn't be as easily accessible.

**Comment by lime124** [comment]
@liuche @Sdaswani - i actually thought we had agreed to append it to the end of the list 😬. in the future, we need to add in the ability to reorganize so people can put it wherever they want.
