### ISSUE TITLE
Retain visit history

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#575]
We should retain visit history and display an autocompleted URL in both the home-screen's URL bar and in the browser overlay's URL bar.

=> Visit http://thestar.com
=> Navigate back to home-screen and or enter the same URL

Expected to see the URL autocomplete because it was visited previously

**Comment by mcomella** [comment]
[triage] With the keyboard rewrite.

**Comment by athomasmoz** [comment]
Closing for now. There are some privacy concerns with this, especially given the TV is used by the whole family. Will revisit when thinking about history & privacy as a larger issue
