### ISSUE TITLE
Add automation for bi-weekly l10n import

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#577]
Like MickeyMoz does for focus-android.

We shouldn't need to manually import strings all the time, a bot can do that for us and open PRs.

**Comment by mcomella** [comment]
[triage] liuche can look at this during the releng work week.

**Comment by liuche** [comment]
Fixed! The hook is [here](https://tools.taskcluster.net/hooks/project-mobile/firefox-tv-strings-import), on for daily trigger like with Focus.
