### ISSUE TITLE
Handle custom title name collision

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#583]
Right now we do "subdomain.domain" so if you register two youtube.com's, you'll get "youtube" and "youtube" but their screenshots will be different.

Tif said we should try to do something like fennec does: https://github.com/mozilla-mobile/firefox-tv/issues/511#issuecomment-367445729 fwiw, once you dig out the algorithm, I suggest passing it by Tif again because fennec is dealing with a different use case (naming an auto-generated list of sites).

Moving to v2.0 because it's a follow-up to an issue, but Tif said we have an acceptable v1 with #511 so it doesn't need to be finished.

**Comment by mcomella** [comment]
This is not a release blocker:

> Moving to v2.0 because it's a follow-up to an issue, but Tif said we have an acceptable v1 with #511 so it doesn't need to be finished.

**Comment by mcomella** [comment]
[triage] Not 2.0 but we should look out for feedback for this feature.

**Comment by bbinto** [comment]
We will wait for feedback & data to see how we can improve this.

**Comment by mcomella** [comment]
Dupe #1997.
