### ISSUE TITLE
Youtube Videos Don't Always Autoplay

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#586]
1. Visit Youtube
2. Choose a video

Actual: Video doesn't autoplay, have to press select and then the play button to start it up
Expected: Video begins playing

This also happens if you pin a youtube video and click on it's custom tile.

FYI sometimes it autoplays, but more often than not it doesn't.

**Comment by liuche** [comment]
I'm seeing this in the old version of the app that's currently in the app store too, so it's not a regression from new code - maybe something with the way youtube.com is handling requests.

**Comment by Sdaswani** [comment]
ok it's not a release blocker but something to look at if we can before 2.0 release if we have time during the QA / UX polish period.

**Comment by mcomella** [comment]
I received a user report that sounds like this issue: they clicked a tile on Youtube, saw a black screen and assumed it was taking a long time to load, so they hit back and clicked the tile again (at which point the video played). If the user thinks the videos aren't loading and this problem happens several times in a row, **they may never be able to watch the video.**

Our work-around has been to click the center button but I'm not sure that other users (e.g. ^) have that intuition.
