### ISSUE TITLE
App Crashing After Pinning Youtube Video

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#587]
EDIT: As @bkmunar and I are investigating, we're back-tracking all the way to ~~pre-pin~~ cursor refactor code, and we're still see this crash. ~~It looks like it might be switching from the overlay to Home/Settings that is causing a crash.~~ Through bisecting, we believe it's related to when the webview is destroyed (but since the repro isn't consistent, this is a best guess).

STR:

1. Visit Youtube
2. Play a Video (note you may have to start playing it because of https://github.com/mozilla-mobile/firefox-tv/issues/585)
3. ~~Let it play for a bit~~ Fast-forward ~1/3, then open overlay
4. Pin the site
5. From overlay, go Home (or to Settings)

Observe.

Actual: App Crashes (_sometimes_, so try a couple of times)
Expected: App doesn't crash

**Comment by bkmunar** [comment]
Couple of things while trying to investigate this:
1. The crash log @liuche pasted in, I think, is not the crash related to the one this issue is talking about. That specific crash log is repeated multiple times throughout the lifecycle of the app and doesn't result in this crash

2. The STR for this crash is *extremely* spotty. This morning I could get it to crash within 1-5 tries of STR, but after lunch I now have tried to crash it 20+ times now and it still has no given in. 

Possible reasons why it's crashing:
per @mcomella , maybe when we pin the YT site and take the screenshot is where the problem occurs? I remember him saying something about a thread issue that might be causing saving the screenshot and causing a crash?

Also have talked about a native crash having to do with Amazon code but since the STR involves pinning and then going to the homescreen that doesn't seem likely.

Please add anything else you might add @mcomella and @liuche !!

**Comment by Sdaswani** [comment]
Yeah my guess it's the screen shots.

**Comment by liuche** [comment]
Agreed, this log is showing up even if we're not crashing, so it's something else.

We also tried commenting out the screenshots, the exitFullscreen code. Will continue to comment out other code and see if we can isolate where this is happening.

**Comment by liuche** [comment]
Narrowed it down to a single commit (all the way back from Feb 2!), trying some fixes now.

**Comment by Sdaswani** [comment]
**git bisect** FTW!

**Comment by Sdaswani** [comment]
I just reproduced this. Trying to get the crash this time.

**Comment by Sdaswani** [comment]
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207): Method not supported in Android WebView
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207): java.lang.UnsupportedOperationException
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at com.amazon.android.webkit.android.AndroidWebViewDelegate.getWebViewReflection(AndroidWebViewDelegate.java:901)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at com.amazon.android.webkit.android.AndroidWebViewDelegate.onPause(AndroidWebViewDelegate.java:375)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at com.amazon.android.webkit.AmazonWebView.onPause(AmazonWebView.java:816)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at org.mozilla.focus.web.IWebViewLifecycleFragment.onPause(IWebViewLifecycleFragment.kt:69)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.Fragment.performPause(Fragment.java:2542)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1476)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:853)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2577)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:851)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:805)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at org.mozilla.focus.fragment.ScreenController.showHomeScreen(ScreenController.kt:93)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at org.mozilla.focus.fragment.BrowserFragment$onNavigationEvent$1.invoke(BrowserFragment.kt:131)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at org.mozilla.focus.fragment.BrowserFragment$onNavigationEvent$1.invoke(BrowserFragment.kt:44)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at org.mozilla.focus.widget.BrowserNavigationOverlay.onClick(BrowserNavigationOverlay.kt:129)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.View.performClick(View.java:5047)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.View.onKeyUp(View.java:9301)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.KeyEvent.dispatch(KeyEvent.java:2687)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.View.dispatchKeyEvent(View.java:8683)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1508)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2405)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1738)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.app.Activity.dispatchKeyEvent(Activity.java:2718)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at org.mozilla.focus.activity.MainActivity.dispatchKeyEvent(MainActivity.kt:165)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2320)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4088)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4038)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3653)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3619)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3736)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3627)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3793)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3600)
E/com.amazon.android.webkit.android.AndroidWebViewDelegate(21207):      at android.view.ViewRootImpl$Inp
W/cr_AwContents(21207): WebView.destroy() called while WebView is still attached to window.

**Comment by liuche** [comment]
Let's see if reverting the whole patch that we (believe) causes this problem (rather than putting null checks) fixes this problem.

I realize we didn't put down where we found this problem, so documenting it here:
Commit: https://github.com/mozilla-mobile/firefox-tv/commit/71aaeecd28372c5e92b4cbcd05c266c91bf3653d

**Comment by liuche** [comment]
I still haven't been able to repro with master, but will try the `release` flavor.
