### ISSUE TITLE
Hitting back from Settings shouldn't hide the overlay

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#589]
Filing from LAT feedback.

**Comment by boek** [comment]
@liuche Is this happening because we're replacing the browser fragment with the settings fragment? What approach would work better to prevent the webview from reloading?

**Comment by liuche** [comment]
I thought the fragments should retain their state when they're switching - it doesn't seem like we're recreating the fragment because the url is correct (unless we fetch that from Sessions). My guess (without having looked at the code) is that we're conservatively calling some sort of onResume or init that ends up reloading the website.

**Comment by mcomella** [comment]
Note: there's a difference between 1) FragmentTransaction.add and 2) FragmentTransaction.replace (which is essentially remove then add). iirc, we've been calling replace.

**Comment by liuche** [comment]
FragmentTransaction.add doesn't "add" something to the back stack - it just layers the fragment literally on top, in the same container.

@bbinto I'm going to skip the reload page part - from looking at our old builds, that happened anyway and will require more work to persist, but I can at least make the overlay state persist.

**Comment by liuche** [comment]
Should land this for the next release.
