### ISSUE TITLE
Context menu indicator doesn't change colors when home tile is pressed

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#596]
![screenshot_1520379035](https://user-images.githubusercontent.com/759372/37064855-73694b10-2153-11e8-97bd-1211fd19f085.png)

**Comment by mcomella** [comment]
Without looking at the code, we could:
- change the context menu color
- Only highlight under the context menu

@lime124 What is the ideal case here?

**Comment by boek** [comment]
I spoke with @lime124 while we were going over overlay colors and she said we should change the context menu icon color to be the same pressed state for now
