### ISSUE TITLE
need string for empty homescreen

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-tv#603]
STR
1. On homescreen, delete all the tiles
2. Observe

Expected:
Not a empty screen

Actual:
A barren screen

@BrianNJones for ideas on a possible string to prompt people to go add more tiles because they deleted them.

**Comment by lime124** [comment]
not release blocker and too late for 2.0 for strings

**Comment by bbinto** [comment]
Currently only 130 users have 0 tiles (https://sql.telemetry.mozilla.org/queries/51947#138709)

**Comment by aminalhazwani** [comment]
Gonna close this as we open a more pattern-oriented issue https://github.com/mozilla-mobile/firefox-tv/issues/1168
