### ISSUE TITLE
Pressing back on controller to navigate back in browser with overlay open feels unnatural

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#607]
...as an Android user. I'd expect back to close the overlay.

STR:
1) Go to a website
2) Click a link (or otherwise navigate to a new page)
3) Click menu to open overlay
4) Click back on controller

Expected: overlay closes
Actual: browser goes back. Note that hitting back again (since it's the end of the navigation history) will actually close the overlay. I don't love the inconsistency either.

Second opinions from Android users: @liuche @bbinto ?

CC @lime124

**Comment by mcomella** [comment]
fwiw, I think this could feel less unnatural if the overlay was easier to see through: Tif mentions the overlay should be more see-through and it's hard to see through in the bright office (and I have a similar experience).

**Comment by Sdaswani** [comment]
I think it makes sense to close the overlay when the user presses back, as it's on the top of the navigation stack.

**Comment by liuche** [comment]
This was in the spec for the overlay, where you can go back until there is no more history, and then close the overlay - @lime124 what do you think?

**Comment by lime124** [comment]
from slack last night - this is what we all agreed upon to solve the weirdness people are experiencing:

- from the overlay - remote back button closes the overlay 
- from browser view - remote back button goes to the previous page all the way back to homescreen and exits the app
- from the overlay - onscreenback button goes to the previous webpage and that's it until there are no more webpages and then it disables
