### ISSUE TITLE
Run UI/integration tests on CI

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#615]
Regressions suck.

**Comment by mcomella** [comment]
No commercial frameworks for cloud testing TV but we can manage our own docker emulator (which doesn't have the same behavior as the hardware). Thus, this is more long term.

**Comment by mcomella** [comment]
Aaron runs this daily so we don't need to do this immediately.

NJ is going to talk to Aaron about setting up a docker instance but again, it's long term.

**Comment by AaronMT** [comment]
We're going to order another Fire TV stick and get tests running on a Mac Mini in office for the interim

**Comment by mcomella** [comment]
Aaron is working on getting UI builds running locally, according to No-Jun.

**Comment by mcomella** [comment]
This was completed a few days (weeks?) ago: see https://groups.google.com/a/mozilla.com/forum/#!search/from$3Anpark@mozilla.com$20firebase/firefox-tv/81HdtzzNapU/2KFg1mhaGwAJ
