### ISSUE TITLE
Turbo Mode Button is Off When It Should Be On

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#624]
1. Fresh Install of 1.4.0.6
2. Keep Turbo Mode Enabled
3. Loading Any Tile
4. Bring Up Overlay
5. Turbo Mode is Off

**Comment by liuche** [comment]
@Sdaswani I don't think this is a bug - I tried this out and it looks like turbo mode is still on, but maybe the new "selected" state is throwing you off? It's more grey, not blue.

**Comment by Sdaswani** [comment]
My bad, was using PiP so probably didn't notice the difference.
