### ISSUE TITLE
Mitigate long compression times: fine-grain locking in HomeTileScreenshotStore

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#627]
In some edge cases (#610), screenshots can't load and block the titles from appearing – we should timeout the screenshot access so that titles can load even if screenshots can't. Then we can do the proper fix in #610.

**Comment by mcomella** [comment]
This is turning out to be non-trivial:
- We can't just time out because the threads are blocking, thus non-cancellable
- An existing bug: there are a maximum number of threads we can use from the CommonPool. When we exhaust that thread count, our new queue jobs, even if they're non-read jobs, will block until the job completes. This means that even if we schedule a timeout, our other blocking tasks won't be able to run until these complete (or we interrupt them, which I'm not sure we handle gracefully).

I'm trying to create my own thread pool but:
- I'm concerned about the resource use of having X idle threads sitting around. Maybe this should be an generic IO thread pool until we figure out what to do with it?
- If the timeout is too short (1500 ms with 2 threads in pool), we sometimes use the placeholder even when the write thread is not blocked
- We could use a CachedThreadPool (creates and destroys threads as necessary) but I'm concerned about the performance implications of having a thread for each home tile (we could guard access with a queue that allows 8 consumers max, but then we're starting to add complexity...)

I guess most threads are *actually blocked on the file system lock*... Maybe we should do more fine-grained locking and call that the quick solution.

**Comment by Sdaswani** [comment]
@mcomella sounds like this is a big task - maybe pause it and work on a smaller 2.0 issue?

**Comment by mcomella** [comment]
Sorry - I yak shaved pretty bad on this but I came up with the fine-grained locking solution last night and it turns out it was actually pretty simple. I just need to add comments, which I'm timeboxing right now.
