### ISSUE TITLE
Updates to color.xml, photon_colors.xml, tv_colors.xml

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-tv#629]
This is mostly about getting our color palette in alignment and using consistent naming.

Should we combine photon_colors and tv_colors into a single doc?

Use photon naming for existing/defined photon colors - e.g. photonBlue50 
- there are some colors in tv_colors that are already defined in photon_colors

Figure out naming scheme for new, tv only colors - e.g. tv_ink2 
- this is for UX to work with design systems on

Make sure all color values are in color.xml and to refer to a defined color value - e.g. background of progress bar is defined as E3E3E5 in progress_bar_background.xml

**Comment by mcomella** [comment]
[triage] Clean up the existing code (use Sebastian's photon library too?) and we'll add more to it as necessary.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
