### ISSUE TITLE
Add padding to home tile titles

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#635]
Looks bad (see rotten tomatoes):

![device-2018-03-08-200026](https://user-images.githubusercontent.com/759372/37189883-77d6adb4-230b-11e8-91f9-3c30ba3060d2.png)

**Comment by Sdaswani** [comment]
@lime124 can you let us know if this polish that must get in to 2.0?

**Comment by mcomella** [comment]
This was trivial so I did it.

![device-2018-03-09-105204](https://user-images.githubusercontent.com/759372/37224314-f2bfd952-2387-11e8-8e55-6dd7e47e2e68.png)

@lime124 What do you think of ^? I have 6dp padding on the horizontal axis and I added an ellipsis to the start of the title (since I figured the base domain is more important than the subdomain).

**Comment by lime124** [comment]
I think that works well. the ellipses at the start is a bit odd, but i think the usability of being able to see the more relevant part of the domain trumps that. thanks @mcomella !
