### ISSUE TITLE
Use TV white

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#640]
photon white should be tv white #eeeeee. [ux polish]

    I think this applies to the text and the icons in the overlay.
    the cursor in the search box on the homescreen
    the background of the home tiles?
    svg files also use FFFFFF

**Comment by mcomella** [comment]
![device-2018-03-09-111958](https://user-images.githubusercontent.com/759372/37225567-e3539f86-238b-11e8-97a4-528334e5c3a4.png)

@lime124 tv_white on the home tile backgrounds has the same problem with the background color on a few tiles - what should we do? Maybe #ffffff on home tile backgrounds and file a follow-up to get new assets?

**Comment by mcomella** [comment]
@lime124 Also, the close text on the overlay is #ededf0. I took the liberty of rounding that to #tv_white. Is that correct?

**Comment by mcomella** [comment]
@lime124 Here's what I came up with, assuming home tile backgrounds are still #ffffff:

![device-2018-03-09-114339](https://user-images.githubusercontent.com/759372/37226576-3d3e0fd8-238f-11e8-9298-11bfb9c5c211.png)

![device-2018-03-09-115007](https://user-images.githubusercontent.com/759372/37226838-1ae132d4-2390-11e8-8c5c-13a3a9bd8fe9.png)

@lime124 What do you think?

Note that I also took the liberty of adding right padding to URL bar of the overlay because otherwise the long text would overlap the blue highlight.

fwiw, we could also change the fill color of the webView, so that when it doesn't have page content yet, it draws tv_white, but pages seem to use #ffffff so I think this would flicker and look bad.

**Comment by lime124** [comment]
@mcomella see thumb's up above...

re padding in the URL bar: awesome
re home tiles being white: yes - we'll have to leave it at fff and file a follow up ticket to see if we can fix this (or perhaps it's made moot by our new homescreen work
re webview - don't worry about that instance
re icons on overlay - i'm going to take your word that those are tv white. on such a dark background the eye thinks that it's white. :)
