### ISSUE TITLE
Add settings pressed state

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#641]
no press state on settings button on the homescreen [ux polish]

    (This looks different on the Stick (android 22) and the Square (android 25))

    the press state is weird on a tile - this is specifically about the color of the "menu" hint [ux polish]

**Comment by mcomella** [comment]
Menu hint is #596 so this is just about the settings pressed state.

**Comment by mcomella** [comment]
@lime124 Do you have desired colors? Or I could just steal them from the settings screen.

**Comment by lime124** [comment]
@mcomella am i correct in ascertaining that the focus state is white at 20%?

**Comment by mcomella** [comment]
This view is set up strangely – I'll have to get back to you on the colors.

**Comment by boek** [comment]
This has the same ripple problem as #648. There is/was a press state on the Stick

**Comment by mcomella** [comment]
Out of time.

To clarify, Tif wants Settings opacity to be white at 20% opacity when focused and white at 10% opacity when pressed. Maybe we'll fix this up with the ripples #648.
