### ISSUE TITLE
Browser view polish

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#642]
the elevation doesn't seem to be getting applied to the progress bar [ux polish]
progress bar is distracting from the rest of the page b/c it's too bright and attention getting [ux polish]

    things to try for ux first: truncate URL so box just jump around in width, change opacity of box (85-90%), change opacity of gif (or perhaps change opacity of the whole progress bar)

**Comment by lime124** [comment]
- the elevation meaning there doesn't look like there is a drop shadow behind it.
- let's try background of the progress bar at 85%. -     android:background="@drawable/progress_bar_background"
- text color updated to this lighter grey - A0A0A3. let's call it tv_grey_2 for now
- opacity of animation to 85% - i was able to do it by adding gifImageView.alpha = .85f
 to firefoxprogressbar.kt 


the
