### ISSUE TITLE
After removing unused resources, ensure no instances of white exist

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#644]
Use tv_white instead.

**Comment by mcomella** [comment]
Consider writing a script that integrates with CI/builds so that this doesn't break.

**Comment by liuche** [comment]
@lime124 mentioned that we might want to get different colors from @shorlander. However, if it's just a matter of changing all the #ffffff to a single color, we can do that easily and don't need new icons.

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
