### ISSUE TITLE
MemoryLeak? Create WebViews in onCreateView but destroy in `onDestroy`

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#652]
We did this to fix a crash bug #587, but it seems like there may be a memory leak.

**Comment by Sdaswani** [comment]
@mcomella is the mem leak frequent enough to put that fix back? Getting it to crash was a lot of magic button pressing.

**Comment by mcomella** [comment]
I'm not sure - I'd propose we use this bug to investigate. Each time we switch from Browser to Home or Settings, we go through this cycle so we should see if it creates a memory leak.

**Comment by Sdaswani** [comment]
Oh ok it was a true question, not made in response to anything specific :) .

**Comment by mcomella** [comment]
Dupe #654.
