### ISSUE TITLE
Redundant WebViews may take up resources: reuse the webview when going back to BrowserFragment from Settings

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#654]
Splitting this off from #589 - if we can somehow reuse the webview, then we don't need to restore the url/reload.

Not sure how much work this is, but some things we could try are
a) Make the lifecycle of the WebView persist past the View lifecycle of BrowserFragment (which is only as long as its visible on the top of the fragment stack, I think), but allow it to be destroyed when returning to the home screen
b) Tie the WebView to the lifecycle of the app/MainActivity (which might have some perf problems if people keep the app open for a long time, on the home screen, or even leaving the app)

**Comment by mcomella** [comment]
Keep in mind the memory leak issue of #652.

**Comment by mcomella** [comment]
When we have multiple WebView instances, force GC in the profiler doesn't always seem to remove the WebView instances on the first try: this means redundant WebViews might be using more resources than they need to. This gives extra emphasis to the utility of this bug.

**Comment by mcomella** [comment]
We only have one WebView now.
