### ISSUE TITLE
Progress bar text is hard to read on non-white backgrounds

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#656]
![device-2018-03-09-180831](https://user-images.githubusercontent.com/759372/37237188-0f54dd82-23c5-11e8-84cd-2985b164a1e5.png)

**Comment by Sdaswani** [comment]
@bbinto is this a release blocker? i don't think so.

**Comment by bbinto** [comment]
no

**Comment by liuche** [comment]
This apparently looks fine on tvs, which is what this color was chosen for, so closing this.

If anyone sees any more problems ON TVs, please reopen this bug.
