### ISSUE TITLE
Add NYTimes Video to Bundled Sites

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#657]
While testing 2.0, I came across a nice NYTimes Video Site which works well on FFTV. May want to pin it to let user's know FFTV is a good source of news.

**Comment by lime124** [comment]
i just remembered there are other video sites like lynda and skillshare (both require buying something) but there may be other educational sites out there too.

liuche mentioned tedtalks.

**Comment by athomasmoz** [comment]
Closing in favour of larger story to update our list of pinned sites.
