### ISSUE TITLE
Remove unused settings.xml and code it calls

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#667]
Follow-up to #662: this was a little tricky to get right because it specifies default values for settings like "block analytic trackers" and don't "block web fonts".

**Comment by liuche** [comment]
Do we still need `pref_key_performance_block_webfonts`?

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
