### ISSUE TITLE
Bundled home tile has no padding between icon and title background

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#671]
Looks like a regression from #598: the bundled home tiles got larger (I'm not sure if this was intentional).

![device-2018-03-13-163038](https://user-images.githubusercontent.com/759372/37375249-f7f6cbd6-26db-11e8-80be-238fe16159b8.png)

@lime124 Can you confirm this is an issue?

**Comment by lime124** [comment]
so if i follow, the shipped set of tiles (e.g. imdb) the icons are bigger than we're expecting? eyeballing instagram and flickr, they definitely look bigger to me. 

@mcomella do you happen to know what they were or do you need that number from me?

**Comment by mcomella** [comment]
We can undo this.

**Comment by mcomella** [comment]
@bkmunar Can you look into this when you get a chance? It's a regression from the enlarge screenshots bug.

**Comment by liuche** [comment]
Oops, @lime124 is actually already flagged on the PR! #680

**Comment by lime124** [comment]
oops commented on the PR! thanks!
