### ISSUE TITLE
Clearing data resets telemetry setting state

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#678]
Not sure if this is expected (? @mcomella)

Enable telemetry (send usage data), clear data -> state flipped

R.id.telemetryButton; isChecked (true) -> R.id.telemetryButton; isChecked (false)

This is on my Debug build.

**Comment by mcomella** [comment]
@AaronMT Can you reproduce this on Beta? I think our telemetry switch is just completely busted on debug builds.

**Comment by Sdaswani** [comment]
@AaronMT closing unless you say it's happening on non-debug builds too.
