### ISSUE TITLE
Typing and loading youtube.com/tv from overlay urlbar just reloads the current (non-YT) page

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#682]
Might be related to our youtube-specific code, which causes a reload if the url is "youtube.com/tv".

**Comment by mcomella** [comment]
My first step here was to try just removing this hack algother: I made progress, which I mention in #393. I know what the solution needs to be, but it's not working as expected and I've already exceeded my timebox so I'll see how I want to proceed next week.
