### ISSUE TITLE
Create Short Form Privacy Notice Page

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#692]
"Also - we can make a separate short notice for this that makes sense. And it doesn’t have to be a webpage unless you prefer that"
![image uploaded from ios](https://user-images.githubusercontent.com/4879954/37544874-d0df622a-2923-11e8-9850-08dce05fe93f.jpg)

**Comment by Sdaswani** [comment]
Legal is providing a new privacy notice - @bbinto can we get this into 2.1, 2.2, or worst case 3.0?

**Comment by bbinto** [comment]
That's bundled with #691, right?

I'll let eng decide if they can get it into 2.1, 2.2 is absolutely sufficient from my point of view (happy to move #691 to 2.2 as well)

**Comment by Sdaswani** [comment]
This is related to 691 though this change is easier than that as 691 requires more work and some UX. So no this isn’t bundled as it’s just a URL change.

**Comment by bkmunar** [comment]
Any updates on the link? @Sdaswani

**Comment by Sdaswani** [comment]
not yet @bkmunar

**Comment by Sdaswani** [comment]
Legal is busy this week with some fire alarms, so the new privacy notice probably won't be ready until next week.

**Comment by liuche** [comment]
Moving this to 2.2.

**Comment by liuche** [comment]
Er, moving back bc we're extending the 2.1 sprint to catch this extra week.

**Comment by liuche** [comment]
Looks like Legal is still busy so bumping this to 2.2 along with #691 .

**Comment by mcomella** [comment]
Note: Privacy notice needs to include sentry crash reporting.

**Comment by athomasmoz** [comment]
Closing as we have a FFTV / FFES privacy notice page that we point to
