### ISSUE TITLE
Show link url (so user knows where they are going if they clicked on the link)

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/firefox-tv#693]
Chatting with mika about this. In firefox desktop, there is a bar in the lower left corner that appears when you hover over links (showing the destination url) as well as all it shows the state of things as the page loads after clicking on the link (e.g. waiting, transferring, etc).

Our task here is to determine what security properties we can implement (e.g. is it possible to hover over a link on TV?), what requirements we need to meet, and determine how in the UI to do so.

We'll need to work with legal on this (Marshall, Winnie, and mika) and I'm guessing go through security review.

**Comment by mcomella** [comment]
> is it possible to hover over a link on TV?

Silk does it (their links show hover effects, unlike ours) but it might require a lot of rejiggering of our code because they might have to mimic a pointing input device to do this.

**Comment by bbinto** [comment]
@bbinto to reach out to Mika how to prioritize these requests

**Comment by athomasmoz** [comment]
Closing for now as lower priority
