### ISSUE TITLE
[April 30] Amazon removing crash reporting

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#695]
<img width="1137" alt="screen shot 2018-03-19 at 1 30 00 pm" src="https://user-images.githubusercontent.com/1082253/37620517-b7ec3aba-2b79-11e8-84e6-29052dffcad7.png">

@Sdaswani to follow up with amazon to see what's going on.

**Comment by mcomella** [comment]
See #429 for initiative to replace crash reporting.

**Comment by bbinto** [comment]
We need to decide if we need/want to include a toggle in settings to opt-in/out

**Comment by mcomella** [comment]
Dupe #429.
