### ISSUE TITLE
Correct version numbers, don't screw it up again

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#697]
Problems:
- [x] Master needs v2.1
- [ ] v2.0 branch/tag doesn't have the correct version (do we care)?
- [x] Let's not do this again (releng checklist template?)

**Comment by liuche** [comment]
Going to close this - I'm okay with the v2.0 branch not having the correct version.

Added a wiki page for releng.

**Comment by mcomella** [comment]
Added a releng bug for this sprint: https://github.com/mozilla-mobile/firefox-tv/issues/709
