### ISSUE TITLE
Pressed state for cursor

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#706]
*edit:* Updated assets with larger cursor: [Cursor2-assets.zip](https://github.com/mozilla-mobile/firefox-tv/files/1842947/Cursor2-assets.zip)

---

Follow-up to #489, which just changes the UI.

@lime124 I assume we want this in v2.1 if possible?

**Comment by boek** [comment]
![screen recording 2018-03-19 at 03 34 pm](https://user-images.githubusercontent.com/1250545/37724647-7bb86886-2cee-11e8-84e4-4b2d9fae8203.gif)
![cursor-bg-active](https://user-images.githubusercontent.com/1250545/37724681-8ea4a202-2cee-11e8-8200-467ae888fde7.png)
![cursor-bg](https://user-images.githubusercontent.com/1250545/37724683-8ec1f0c8-2cee-11e8-8c4b-343549b860f5.png)
![cursor-fg-active](https://user-images.githubusercontent.com/1250545/37724684-8edfb982-2cee-11e8-8409-75af3736d51a.png)
![cursor-fg](https://user-images.githubusercontent.com/1250545/37724686-8f0b3af8-2cee-11e8-9b4f-f100c198d402.png)

**Comment by lime124** [comment]
yes please!
