### ISSUE TITLE
v2.1 releng

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#709]
Adding a checklist so we don't forget to do stuff:

## Overview
For major releases, code freeze is the second Wednesday of the sprint (**Wednesday #2**), followed by two days of UX polish.

For non-major releases, code freeze is the second Friday (**Friday #2**).

## Sprint start [Monday #1]
- [x] Bump app version on `master` branch (versioning follows: Major-Release.Sprint.Bugfix.LAT)

## String Import
- [x] Import before release

## String freeze [Wednesday #2]
- [x] Export strings

- [x] Sentry, see wiki

**Comment by Sdaswani** [comment]
We would ship the bugfix as a branch off of 2.0.1 though, so that's fine to bump master up.

**Comment by liuche** [comment]
Yeah, I guess that's not too bad to downgrade on a branch only. I think the most correct thing would be to version bump on shipping, but then it's more likely we'll forget - I bumped master from 1.4.something, and I think in the past we've skipped version bumps before too.

**Comment by Sdaswani** [comment]
We wouldn't 'downgrade' on the 2.0.1 branch? We'd create a new branch (e.g., 2.0.2) from 2.0.1, make some fixes, and then upgrade it to 2.0.2.

**Comment by liuche** [comment]
Before we ship we should do one more import, because the "Your Rights" strings actually need to be re-translated.

**Comment by liuche** [comment]
@mcomella what is the Sentry checkbox, is it just to build with the Sentry keys?

**Comment by mcomella** [comment]
Yes.

**Comment by mcomella** [comment]
I:
- Uploaded the APK to Amazon
- Updated the GH releases page

We're waiting on Delphine & folks for French (and maybe German) release notes: see also #833.

**Comment by mcomella** [comment]
The app has been submitted.
