### ISSUE TITLE
Pressing back on controller from overlay soft keyboard dismisses overlay

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#713]
STR:
- go to page
- open overlay
- click url bar to enter text and raise soft keyboard
- hit back

Expected: soft keyboard dismissed
Actual: keyboard and overlay dismissed

I think the problem is that the soft keyboard is not intercepting the back pressed event, even though it handles it, so the back event also gets sent to the overlay, from which we dismiss the keyboard.

Unfortunately, it seems non-trivial to detect if a soft keyboard is raised, so this might be non-trivial to fix: Jeff tried https://github.com/mozilla-mobile/firefox-tv/issues/548#issuecomment-371977621 with little success and the internet seems to detect layout size changes, which doesn't work for us because the soft keyboard is an overlay.

One way to fix this might be to make the overlay part of the system back stack (e.g. launch it as fragment).

Workarounds:
- Close overlay with back and reopen with menu
- Click "previous" on the soft keyboard

**Comment by liuche** [comment]
@mcomella I was looking at this and I think the emulator is doing something different from the tv. Can you double check this and let me know if this is reproducible on a tv (rather than just the emulator)?

**Comment by mcomella** [comment]
My original STR is with the TV and I can reproduce on the emulator with the following steps:
- Load page (I used google video)
- Open overlay
- *Click* url bar to open soft keyboard
- Hit back in external menu (i.e. the one with the power button)

Expected: Overlay is shown, keyboard dismissed
Actual: Browser is shown, keyboard and overlay dismissed

**Bryan noticed a behavior:** if you long-press back, the down event dismisses the keyboard and the up event dismisses the overlay.

**Comment by bkmunar** [comment]
I know I'm a genius

**Comment by liuche** [comment]
@bkmunar also if you could test this on a firetv, that would be helpful - I forgot to bring mine, and I know there are differences between emulator and TV.

(Or @mcomella but I think he's doing some Fennec stuff atm)
