### ISSUE TITLE
Add Codecov coverage

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#716]

**Comment by mcomella** [comment]
I re-enabled travis CI check, which restored the code coverage checks from Focus. I don't know if there's more required to get code coverage set up.

**Comment by AaronMT** [comment]
@npark-mozilla - anything else required?

**Comment by npark-mozilla** [comment]
Other than adding codecov badge on README.md (see focus android example), I think this is it. cool!
