### ISSUE TITLE
UX review updated cursor: adjust the size

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#721]
Assets from https://github.com/mozilla-mobile/firefox-tv/issues/721#issuecomment-375487382: 

[Cursor2-assets.zip](https://github.com/mozilla-mobile/firefox-tv/files/1839591/Cursor2-assets.zip)

---

It accidentally landed early in https://github.com/mozilla-mobile/firefox-tv/pull/711#pullrequestreview-105908701 and it's probably not worth backing out.

Here's the old conversation from the old issue, #489:

---

@lime124 The new asset has padding built into it, which means the cursor (constrained by the 45dp we specify) appears smaller:

![device-2018-03-21-134601](https://user-images.githubusercontent.com/759372/37736502-5382dcdc-2d0e-11e8-91ef-ade296f24572.png)

![device-2018-03-21-134503](https://user-images.githubusercontent.com/759372/37736505-55300b7c-2d0e-11e8-97c4-0c9bfc0c6425.png)

Is that okay? If we want to make it bigger, we're going to need larger assets.

fwiw, I notice I tend to overshoot things more often with this cursor (though the hit area is smaller than the cursor so maybe that's fine).

---

From Tif:

One usability problem I'm seeing with the old, bigger cursor vs the new, smaller one is that on my TV (which has lots of overscan) I 'lose" the cursor when scroll up/down or side to side. The smaller one completely goes off screen, whereas some part of the cursor remains visible with the larger one.

Are other people experiencing that too?

To fix the overshot problem, can we make the target area bigger without changing the cursor size?

**Comment by mcomella** [comment]
> To fix the overshot problem, can we make the target area bigger without changing the cursor size?

What is the target area and how does it differ from the cursor size?

**Comment by lime124** [comment]
@mcomella and I discussed over slack. We misunderstood each other. Bryan gave updated assets to fix the usability issue. Does this cover press state too? Sorry I’m getting a bit confused across the issues :grimacing:

**Comment by mcomella** [comment]
This is with the new asset:

![device-2018-03-22-161929](https://user-images.githubusercontent.com/759372/37803584-dc92bb8a-2dec-11e8-8552-7fe8708186c4.png)

If you overlay this image with the old cursor image, the blue circles are roughly the same size but the shadow is larger than the old asset (which looks good to me).

@lime124 What do you think? By the way, thanks for updating from our conversation!

**Comment by mcomella** [comment]
Reviewed in the PR: https://github.com/mozilla-mobile/firefox-tv/pull/722#issuecomment-375712155
