### ISSUE TITLE
When going page -> home -> page2, back stack feels wrong

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#731]
I know this was an intentional decision but this particular behavior feels weird to me (which I don't know if it was the intended use case). STR:
- Go to a web page
- Open the overlay, go home
- Go to another web page
- Hit back

Expected: go to home screen
Actual: goes back to first web page

Maybe we should clear the back stack if the user ever goes home (rambling thoughts: but I guess it accidentally sucks to lose that back-stack so suddenly... But I guess hitting home from the overlay will lose back stack even if the user doesn't go to a different site anyway. Maybe that's why Android is designed the way it is? To avoid destruction of the back stack?).

@lime124 Did you consider this use case when you made this decision? What do you think?

**Comment by lime124** [comment]
The actual result  in the str was not the intent. Home is at the very top
of our information hierarchy or stack. Pressing back from the home screen
exits the app.

I have IA that I can share later but now I’m about to eat dinner.

**Comment by lime124** [comment]
![app ia](https://user-images.githubusercontent.com/287322/38062851-00bf288c-32ab-11e8-85a0-f764f76c9f84.png)
As promised - lmk if there are any follow up questions!

**Comment by mcomella** [comment]
@lime124 My STR leads me to "Previous Item in Stack" (on the bottom left): is "Previous item in stack". I assume that means "Previous browser page" and it cannot be the home screen? In which case, the STR I've provided is the intended behavior?

**Comment by lime124** [comment]
Ok so if you look at "previous item in stack"  that's basically any webpage i.e. your history. then follow the line to "first item in stack - i.e. homescreen". if the you're at the first item in the stack, i.e the homescreen, that's where you'll go. otherwise you'll just be shown the previous webpage.

Ahhh!! I see where you're coming from now! In my brain first item in the stack = homescreen. Being back on the homescreen is the top of the stack always, there's nothing before it other than Amazon home. 

Hopefully that makes more sense now. Sorry for that confusion :-/

**Comment by mcomella** [comment]
Tif and I spoke on Slack: one discrepancy is that, currently, there are multiple conceptual back stacks. If you go to several websites and then go home, from home's perspective, you've just cleared the back stack (i.e. hit back and you'll leave the app: this is the first conceptual back stack. However, if you load a new page in the browser and then press back, you'll go back to the last page you viewed in the browser, which is the second conceptual back stack.

I think a few ways we can fix this by:
- Clearing the (browser) back stack when home is visited (this is what Tif's mental model appears to be: home is *always* at the top of the stack)
- Put everything on a single back stack (e.g. so home is like a browser page). This seems more conventional to me, from an Android user's perspective

**Comment by mcomella** [comment]
In v3.0, we're merging the home screen and the overlay so this bug is no longer relevant.
