### ISSUE TITLE
Animate cursor pressed state

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#738]
The current implementation is pretty jarring. I think we should cross-fade between the two views.

@lime124 Would you agree? (pressed cursor state is on master)

**Comment by mcomella** [comment]
Here's a quick mock-up with animations:
https://drive.google.com/open?id=1AiArxhzvD2bl2QhzxDdva2sOzQ86Y7Q8

And here's master without animations:
https://drive.google.com/open?id=1YrPy5N-uHWVjytBd0JEq63dKLff9g-3b

The code is available here:
https://github.com/mcomella/firefox-tv/tree/i738-proto-pressed-anim

One downside to animations is that it's pretty janky to run them when the page is loading.

---

After playing around with this, I wonder if it's jarring because the pressed cursor is so dark, rather than that it's missing animations. Also, there's the usual caveat that I'm using this on a monitor in a brightly lit room so I don't know what it'd be like.

**Comment by lime124** [comment]
working with Bryan Bell...stay tuned :)

**Comment by athomasmoz** [comment]
Closing as low priority
