### ISSUE TITLE
Pause & Resume Timers

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#756]
To pause JavaScript timers while app is in background, call  WebView.pauseTimers in Activity onPause(). Also call  WebView.resumeTimers in Activity onResume() to resume JavaScript.

**Comment by mcomella** [comment]
See also #751.

**Comment by mcomella** [comment]
@Sdaswani Do you have more context on why this is necessary? We want to move `pauseTimers` to `onStop` for #936 because if we don't, it hinders the user experience of voice command integration with video sites, especially Youtube.

**Comment by mcomella** [comment]
It seems this was added to prevent videos from playing when Firefox is in the background: moving to onStop should be fine for this case.
