### ISSUE TITLE
[Home] Combine browser/homescreen architecture

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#762]
With the new homescreen being part of overlay, we'll need to change the browser/homescreen architecture.

Options we discussed were:
* Use Fragment backstack to handle overlay/browser/overlay stack
* Use two fragments, browser fragment (with a blank "firefox:blank"), and overlay fragment

**Comment by mcomella** [comment]
As part of #507, I've been looking at the way we manage fragments: BrowserFragment is tied to SessionManager so it makes the behavior unnecessarily complicated. We may want to consider simplifying the behavior with this bug.

**Comment by liuche** [comment]
I also investigated the `FragmentSupportManager.add` idea for combining fragments on top of each other (instead of having BrowserFragment manage the overlay as part of its layout), but in order for that to work, we need to have a separate ViewGroup container for BF and Overlay so we can have transparency - you can't just literally add the layout of one Fragment on top of another.

In addition to that, if Pocket is in a separate (third) container, then we'd have a hierarchy and have to manage all the back stack of each container rather than just using the FragmentSupportManager. If Pocket and BrowserFragment share a container (with `FSM.replace`) we'd have to handle the behavior of "don't show Pocket Fragment when popping the Fragment backstack to BrowserFragment, but do show it when going back in the Browser navigation history".

Simplest thing is just to do:
* BrowserFragment + Overlay in a single fragment (so transparency doesn't require two separate containers for fragments)
* Use fragment `.replace` to switch between Pocket and Browser Fragments - this means we can't open the overlay on top of the Pocket Fragment
