### ISSUE TITLE
[Pocket] Error handling on Pocket video feed

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#769]
Requires UX feedback. Consider keeping it simple for v1 and adding telemetry to figure out how often these are seen.

**Comment by aminalhazwani** [comment]
@mcomella is this what you need?

![Pocket Video Feed Error](https://user-images.githubusercontent.com/1721875/38565127-cab63e98-3ce0-11e8-9229-c4d87599ab72.jpg)

**Comment by mcomella** [comment]
Yep – thanks! fwiw, I'm still working out how much we cache the feed data and thus how often this can possibly be seen (e.g. if we always have cached data, it'll only be seen the first time).

@BrianNJones Do you have some strings in mind?

**Comment by BrianNJones** [comment]
String for error displayed above. I think (?) users will understand that feed = video, but it can't hurt to be as plain as possible:
[Error msg]
Whoops. Something went wrong while the video was loading.
[Button]
Try Again

@mcomella, do we envision a scenario where the feed totally fails to load, even after user tries reloading? If so, we'll need an emsg for that.

**Comment by aminalhazwani** [comment]
hey @BrianNJones, question: on Android we usually do not Title Case, for buttons the the design system [recommends](https://design.firefox.com/photon/copy/capitalization.html#platform-styles) ALL CAPS to be platform complaint (I never been a big fan of ALL CAPS as it potentially brings issues for localization, but that is another story). I also noticed that Android P will start to introduce [new button styles](https://www.androidpolice.com/wp-content/uploads/2018/03/nexus2cee_Screenshot_20180307-174145-668x1188.png) so, should we align with this new direction and Sentence case the label to `Try again`? Thanks!

**Comment by BrianNJones** [comment]
hi @aminalhazwani - you bring up a great point and I should have been more clear. Fire TV runs on Android; but is it an Android device in the way a Samsung phone is? Seems we need to define whether our metaphor is "Android" or "streaming devices." (If there were a Firefox for Roku, for example.) 

(Confession: I meant to make the button sentence case...typo! Thanks for the catch!)

**Comment by mcomella** [comment]
> Fire TV runs on Android; but is it an Android device in the way a Samsung phone is? Seems we need to define whether our metaphor is "Android" or "streaming devices."

This is a really good point. There is also the question of how closely Fire TV follows the Android conventions and how it intends to follow them in the future too. I think there are product questions here (do we ever plan to ship on Roku? Android TV?) and design questions (is Fire TV "Android"? Do we want to have our own design language?).

Do you think we should file a bug to discuss this as a team? Or perhaps someone wants to take ownership over this?

**Comment by BrianNJones** [comment]
I vote for discussing as a team, both to work toward consensus and to get a
sense of the bigger product possibilities picture.

**Comment by aminalhazwani** [comment]
Yeah, I second what @BrianNJones says. The design system group initially identified copy rules for Windows, Apple and Android but the Firefox product line is growing and crossing platform borders. It makes sense to think about this more holistically.

If we start also to think about when we make those products communicate, think for example about sending tabs, or casting from a mobile device to the tv it becomes even more important.

**Comment by mcomella** [comment]
@BrianNJones @aminalhazwani I filed #836: please review it to make sure you agree with the why/what/acceptance I described (feel free to edit the post directly).

Also, we'll hit the bug to discuss in triage but if you think of a better way to start the discussion (e.g. ad-hoc meeting), please set it up! :)

**Comment by liuche** [comment]
Here are the actual strings from #829:

[Error msg]
Hmm. We're having trouble displaying video recommendations by Pocket.
[Button]
Try again

**Comment by liuche** [comment]
And to close the loop, these were also landed already in #829 so closing this issue now.

**Comment by Sdaswani** [comment]
@dnarcese and I are confused whether this screen can ever happen if the megatile got filled out on our home screen. She will investigate and re-open is necessary.

**Comment by aminalhazwani** [comment]
Ok! Thanks @Sdaswani!

**Comment by liuche** [comment]
Oops, thought this bug was just for landing strings, so re-opening this to make the UI that incorporates the strings.

**Comment by dnarcese** [comment]
Currently, we do not refresh the Pocket feed after it is opened the first time, so this screen is very unlikely to be seen at this point. The error will get shown on the Pocket megatile, which will prevent a click-through to the Pocket feed. It will be important to implement this error screen once refreshing is added.
