### ISSUE TITLE
[Pocket] External dependencies for Pocket (Questions for other teams)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#771]
Sample questions:

Pocket
- Can we get the top 3 from the API (we could just cache this though...)?
- How often is the API updated?
- Can the API manage our traffic? How often can we download per user?
- Will Pocket want to host this content themselves later, as a web experience?
- How does the vision of Pocket sign-in interact with their plans?
- Assets, colors, logos (in SVG?)
- Where do the videos come from? If more than youtube, why are they all Youtube? Hypotheses: 1) Pocket is not categorizing video pages well so it is missing some that might be videos (e.g. a NY times article that is primarily a video) or 2) users are only Pocket'ing videos that are Youtube videos.
- For youtube, the best experience is youtube.com/tv, however, the URLs it lists are youtube.com URLs ([sample JSON](https://github.com/mozilla-mobile/firefox-tv/issues/659#issuecomment-375758100)). How can we rewrite these URLs to make them /tv? Perhaps we can use the `dedupe_url` field?
- `image_src` provides an image with param, `resize=w450`: can we change this to whatever size we need?

**Comment by mcomella** [comment]
Another question:
- For youtube, the best experience is youtube.com/tv, however, the URLs it lists are youtube.com URLs ([sample JSON](https://github.com/mozilla-mobile/firefox-tv/issues/659#issuecomment-375758100)). How can we rewrite these URLs to make them /tv? Perhaps we can use the `dedupe_url` field?

**Comment by liuche** [comment]
@bbinto I can start the conversation with Pocket in an email thread, but can you remind me who the point person is here (w/ email)?

**Comment by kennylong** [comment]
@mcomella Taking a stab at answering some of your questions:

> Can the API manage our traffic? How often can we download per user?

* As long as you're hitting the CDN version of the feed (`getpocket.cdn.mozilla.net`) you will be fine.

> Can we get the top 3 from the API (we could just cache this though...)?

* You can add a `count` param to the request if you'd like.

> How often is the API updated?

* One new video is added to the top of the feed each hour.

> Will Pocket want to host this content themselves later, as a web experience?

* No current plans for this but maybe worth exploring.

> How does the vision of Pocket sign-in interact with their plans?

* Not sure I follow what the question is here, but happy to chat further.

> Assets, colors, logos (in SVG?)

* You should reach out to Peter Cho for all Pocket asset/design questions.

> Where do the videos come from? If more than youtube, why are they all Youtube? Hypotheses: 1) Pocket is not categorizing video pages well so it is missing some that might be videos (e.g. a NY times article that is primarily a video) or 2) users are only Pocket'ing videos that are Youtube videos.

* As you noticed, the videos come primarily from YouTube, but sometimes you'll see one from Vimeo.
* While users do Pocket articles/pages with videos embedded on sites other than YouTube/Vimeo, these are not included at this time.
* We are very open to feedback on the quality & types of videos included in the video feed!

> For youtube, the best experience is youtube.com/tv, however, the URLs it lists are youtube.com URLs. How can we rewrite these URLs to make them /tv? Perhaps we can use the `dedupe_url` field?
> `image_src` provides an image with param, `resize=w450`: can we change this to whatever size we need?

* For both of these questions ^ I think it would be best for you to define what you need in the response and we can update it. That way you don't have to do any manipulation on your end.

On that last one, if you'd like to start an email thread or set up a call, feel free.

**Comment by liuche** [comment]
Hi @kennylong, thanks for the answers! A few follow-up questions:

> Can we get the top 3 from the API?
As far as I can tell, this only gives the 3 most recent - do you have a "best 3" or "most popular", so we can provide the most appealing content in our homescreen thumbnail? If Pocket Videos is something experimental at the moment, that's something we can discuss later if Pocket Videos gets traction in Firefox TV.

> For youtube, the best experience is youtube.com/tv, however, the URLs it lists are youtube.com URLs.
The TV-optimized Youtube TV urls are of the format: https://www.youtube.com/tv#/watch/video/idle?v=I-SpRl-AxI0 so it would be ideal to be able to get those in our response from the API, rather than just the "desktop" url (which we'd have to parse and then reconstruct)

> image with param, resize=w450: can we change this to whatever size we need
The value we need depends on screen density (4k, 1080p) so since the CDN seems to handle resizing, for now we can just calculate what we need and request it, at least until we figure out if there's a set of values we need.

> How does the vision of Pocket sign-in interact with their plans?
This isn't super relevant right now (since we won't implement sign-in in our MVP) but our long-term vision for FireTV/Pocket integration is to allow users to both discover video content (duh) but also provide a way for people to "sync" their videos to watch later on their home screen (ideal for video watching) - which requires sign-in. Ideally Pocket might eventually start serving its own "tv-optimized" video feed (much like Pocket "Must Read" or "Trending" pages.) We were interested in seeing if there was interest from Pocket to provide that (sign-in experience, tv-optimized webpage to set standards for tv web), maybe if Firefox TV demonstrates value in Pocket Videos (which right now doesn't seem to have any consumer-facing interface) through X volume or clicks.

**Comment by liuche** [comment]
Note: started a thread with Peter Cho 4/13 to ask about assets/UX, will document comments/responses here if necessary.

**Comment by BrianNJones** [comment]
<One new video is added to the top of the feed each hour.>
Do we have visibility into what metrics (?) determine what video is added?

**Comment by liuche** [comment]
Re: top 3 - Kenny said he'd see if they can provide an API for "best 3" (appealing content/thumbnail), that would update ~1/day.

**Comment by liuche** [comment]
@BrianNJones to answer your question:

>  Do we have visibility into what metrics (?) determine what video is added? 

(1) Pocket internal data: videos that are a combination of popular (saves) and high engagement (e.g. returning to video after save, watching, sharing, favoriting)
(2) External sites that are monitored for items that should be considered.

**Comment by kennylong** [comment]
@liuche Just want to update you on what we're planning to do with the API response to address some of the issues we've talked about:

*(1) Update URLs*

* Remove `dedupe_url`
* Make `url` the straight URL
* Add in a `tv_url` – https://www.youtube.com/tv#/watch/video/idle?v=[VIDEO_ID]

Open question:
* What should we do with the `tv_url` for Vimeo URLs that are added to the feed? They are less common but they could happen.

*(2) Add an additional sort value based on popularity*

While the API will continue to return the X most recently added videos (whatever specified in the `count` param), we will include a new value that lets you sort by popularity, which should allow you to get the three best from the last day or so to the top (for the tile).

We'll version this so it doesn't break anything you or other teams have already done.

Let me know if you have questions/suggestions. Targeting this happening next week.

**Comment by liuche** [comment]
Thank you! This is fantastic :)

> What should we do with the tv_url for Vimeo URLs that are added to the feed? They are less common but they could happen.

For now, if you can just duplicate the url into the tv_url - it would be nice to just check tv_url for everything because we're only building for tv, but it's up to you (we can also fall back to url if it's null/empty).

**Comment by mcomella** [comment]
The open item for this bug, afaict, is to get the Pocket feed updated to our needs. These are:
- https://github.com/mozilla-mobile/firefox-tv/issues/771#issuecomment-383172373
- @liuche Why do need sort by popularity from ^? Maybe I haven't seen the latest specs on the data we want
- (Performance optimization) Being able to get an appropriate image size based on screen density. The current size (450w) is larger than we need so we can scale down with minimal artifacts

**Comment by liuche** [comment]
@mcomella popularity sort would be so we could get "the best videos" to show in the thumbnails. This probably makes it slightly more complicated (e.g., for the feed to reflect the thumbnails properly, we should put the top 4 at the front, and make sure they're not duplicated below, etc).

**Comment by kennylong** [comment]
@mcomella @liuche The global video has been updated with the [previously mentioned changes](https://github.com/mozilla-mobile/firefox-tv/issues/771#issuecomment-383172373), and can now be accessed with `version=2`. A sample response looks like this:
```
{
	"status": 1,
	"recommendations": [{
			"id": 16119,
			"url": "https://www.youtube.com/watch?v=MGBjIXMD_0s",
			"tv_url": "https://www.youtube.com/tv#/watch/video/idle?v=MGBjIXMD_0s",
			"title": "Pelicans crash Pepperdine University graduation",
			"excerpt": "When your university is located next to the Pacific Ocean, at some point pelicans are bound to crash your graduation.",
			"domain": "youtube.com",
			"image_src": "https://img-getpocket.cdn.mozilla.net/direct?url=http%3A%2F%2Fimg.youtube.com%2Fvi%2FMGBjIXMD_0s%2Fmaxresdefault.jpg&resize=w450",
			"published_timestamp": "0",
			"sort_id": 0,
			"popularity_sort_id": 2
		},
		{
			"id": 16104,
			"url": "https://www.youtube.com/watch?v=CwQ_DVtOESI",
			"tv_url": "https://www.youtube.com/tv#/watch/video/idle?v=CwQ_DVtOESI",
			"title": "LHR to SFO in 4 mins",
			"excerpt": "BA287 LHR-SFO 17th Feb 2018. SFO Mark Dembrey. SFO Holly Tucker. Capt Dave Wallsworth. Airbus A380-841 G-XLEJ.",
			"domain": "youtube.com",
			"image_src": "https://img-getpocket.cdn.mozilla.net/direct?url=http%3A%2F%2Fimg.youtube.com%2Fvi%2FCwQ_DVtOESI%2Fmaxresdefault.jpg&resize=w450",
			"published_timestamp": "0",
			"sort_id": 1,
			"popularity_sort_id": 1
		}
	]
}
```
Documentation has been updated as well. Let me know if you have any questions.

**Comment by mcomella** [comment]
Remaining:
- @liuche Should we file a bug to additionally use popularity sort? Might have to discuss with UX about expected behavior (e.g. the most popular videos might always sit in the front so it won't look like the feed is updating regularly)
- (Performance optimization) Being able to get an appropriate image size based on screen density. The current size (450w) is larger than we need so we can scale down with minimal artifacts #866: backlogged

Sounds like we can close this and liuche will file a new bug if we need it.

**Comment by mcomella** [comment]
Thanks Kenny!
