### ISSUE TITLE
[Home] Verify existing telemetry isn't broken

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#772]
This involves discussion with Product, to determine what probes to collect.
- [ ] Unique tiles clicked per user per session
...anything else?

**Comment by mcomella** [comment]
Since we rejiggered the overlay, let's use this bug to verify too. 

> Unique tiles clicked per user per session

We did this in v2.1: #798. And we're adding some home screen probes in #777 so I don't actually think there are any probes to add here.

**Comment by mcomella** [comment]
Unfortunately, I don't remember what has been verified and what hasn't (check #777?) so we should go through the existing telemetry again and make sure it's all working.

**Comment by dnarcese** [comment]
Closing because I've verified that existing telemetry is working.
Except: `sslErrorEvent` needs to be implemented - issue #1140 filed.
