### ISSUE TITLE
[Pocket] Add Megatile error handling (can slip?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#775]
Requires UX feedback. Consider keeping it simple for v1 and adding telemetry to figure out how often these are seen.

**Comment by aminalhazwani** [comment]
We could use the same chip as we do for the remove tile message https://github.com/mozilla-mobile/firefox-tv/issues/782#issuecomment-380109379

![Remove Pocket Tile](https://user-images.githubusercontent.com/1721875/38560569-37cc2cb4-3cd6-11e8-8349-694c80c5f4d4.jpg)

**Comment by mcomella** [comment]
@aminalhazwani Sorry I wasn't clear – this bug is also for solving what we should show if we're unable to obtain image thumbnails.

**Comment by mcomella** [comment]
Dupe #889.
