### ISSUE TITLE
[Pocket] Add mechanism to undo Pocket tile removal

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#776]
Currently users can remove tiles and re-add them by revisiting the website and repinning as a custom tile. However, there is no way to undo the removal of native content.

**Comment by bbinto** [comment]
Dependent on #780

**Comment by bbinto** [comment]
Needs UX for eng to estimate

**Comment by aminalhazwani** [comment]
Probably we can close this as a dupe of #1174 @athomasmoz
