### ISSUE TITLE
[Pocket] Discovery: Need a way to add/remove the Pocket MegaTile

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#780]
Follow-up to #774 

_Added by @bbinto_

**Why/User Benefit**
- If users don't want to have recommended Pocket videos shown, they should have an option to remove them
- Firefox's promise to give users choice

**What**
- Option to remove Pocket video mega tile
- Option to add it back
- Define patterns to remove/add things

**Acceptance Criteria (how do I know when I’m done?)**
- Probe when people remove/re-add mega tile
- Inform users about their actions on removing/adding mega tile (toast notification)

**KPIs/Data**
- Consistent event tracking of events such as add/remove
- How useful is the feature? E.g. x% of users remove mega tile
- How do we know people use the tile? (see #777)
- Do people know how to use the feature?

**Comment by bbinto** [comment]
More discovery is needed, maybe something via settings turn on/off etc.

**Comment by aminalhazwani** [comment]
These last days I noticed an interesting pattern on the XBOX, and the Fire TV too. They display a little popup/snackbar at the bottom right corner of the TV showing contextual features that are accessible with the remote/controller. We could build a component that would allow us to highlight how to access features with the remote (and maybe even with voice in the the future).

![img_dcaa85499b7a-1](https://user-images.githubusercontent.com/1721875/42888488-ad63627e-8aa8-11e8-8799-d32209b3a29b.jpeg)

For re-adding the Pocket tile we could add a new settings item with a toggle/switch as @bbinto suggests.

**Comment by aminalhazwani** [comment]
We are thinking about moving to pocket section - where the videos would be directly available in the homescreen - instead of mega tile.

**Comment by aminalhazwani** [comment]
We are thinking about having a "global" mechanism, for removing/restoring whole homescreen section, eg pinned sites section, pocket recommended videos section, settings section

**Comment by aminalhazwani** [comment]
Closing this after filing #1174
