### ISSUE TITLE
eglCodecCommon glUtilsParamSize errors in logcat

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#781]
I see these a lot in logcat with debug mode on my emulator:
```
**** ERROR unknown type 0x0 (glSizeof,73)
04-05 22:01:50.669 6161-6194/org.mozilla.tv.firefox.debug E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000b44
```

I assume these are coming from the WebView. Maybe Amazon would know?

**Comment by mcomella** [comment]
[triage] Leave in and see if this is fixed by AmazonWebView -> WebView change.

**Comment by bbinto** [comment]
@mcomella to check if this also happens in the non-debug mode

**Comment by mcomella** [comment]
@Baron-Severin Quick search indicates this happens on the emulator using the host GPU: can you see if you get the same errors on device?

**Comment by Baron-Severin** [comment]
@mcomella I'm not seeing that log on device or in my emulator.  Is there any particular action that I need to be taking before it will show up?

**Comment by mcomella** [comment]
@Baron-Severin Just browsing web pages (YouTube or its videos, maybe?). If you can't reproduce, feel free to close and we can reopen again if it's an issue.

**Comment by Baron-Severin** [comment]
@mcomella 👍 

I've been unable to reproduce on device or emulator.  We will reopen this if it crops back up.

**Comment by ncalexan** [comment]
I imagine this is a Gecko (possibly Web Render?) interaction, 'cuz I see exactly this running a much newer GeckoView in an x86 emulator (under macOS).
