### ISSUE TITLE
Change OnUrlEnteredListener inputs to a sealed class

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#800]
This is going to cause some incorrect telemetry for url loading at some point. Currently, `OnUrlEnteredListener` is really confusing to use because it has two functions, but they both call the same thing, just with some arguments as null.

* It should be clear that this interface shouldn't be implemented, and all callers should call through to these
* Have a single function, where the arguments will either indicate that it's a "tile click" or a "user entered url"

**Comment by mcomella** [comment]
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.
