### ISSUE TITLE
Provide Firefox TV apks for download (Play Store, Android TV)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#802]
There doesn't appear to be a good TV browser on Google Play for Android TV, except Puffin (which doesn't work in all countries).

* We could provide download links (for people to sideload) [cheap]
* Could release on Play Store (but requires signing, release drivers) [requires other teams]

@ekager (being our unofficial tech PR) mentioned that there are people with Android TVs who ask about getting Firefox on Android TVs.

Seems like this should probably just work, but a few thoughts:
* It shouldn't be hard to provide (unofficial) signed apks on archive.mozilla.org, or directly on the github, especially if we only do major releases - we probably don't want to ship this on Google Play
* For sideloading, this would be a tiny group of people, so this doesn't provide much organizational value, but we could see if people like it enough to consider shipping on Google Play eventually (when/if we have more resources, and can respond to feature/bugs if there are inconsistencies between Fire TV and Android TV)
* On the other hand if there's no competition then we'll just automatically be the best browser out there?

https://forum.xda-developers.com/shield-tv/themes-apps/app-firefox-android-tv-t3725470
https://www.reddit.com/r/AndroidTV/comments/7q3myj/firefox_for_android_tv_is_a_nice_remotefriendly/

"It's an extracted Fire TV app that happens to work on mainline Android TV, **so they likely have an exclusivity deal with Amazon or something**"
^ don't love this sentiment :(

**Comment by mcomella** [comment]
> For sideloading, this would be a tiny group of people,

I [crunched the numbers of non-Amazon devices](https://sql.telemetry.mozilla.org/queries/52549#139939) and also got [a users-per-device list](https://sql.telemetry.mozilla.org/queries/52548): I agree, it's small atm.

**Comment by liuche** [comment]
Puffin also has a "send link to tv" using QR codes.

![screenshot_2018-08-10 puffin tv - fast web browser - apps on google play](https://user-images.githubusercontent.com/1082253/43980327-a0952b02-9ca2-11e8-8a7e-b974f7315128.png)

**Comment by liuche** [comment]
Duping to #240

**Comment by kawshik201** [comment]
It's 7 months since last comment, is there any plan to release the app on Android TV's Play Store?
