### ISSUE TITLE
Going to Youtube pinned site plays audio playback only, with black screen

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#820]
On 4K device
STR:
- Go to youtube, select video, start playback.
- Pin site
- Exit Firefox
- Restart firefox, then select the pinned youtube site

Expected:
- Goes to the link, plays video properly.
Actual:
- Audio playback starts, but the screen is black.

**Comment by npark-mozilla** [comment]
ADB log while only audio playback is heard.
[blackscreen.log](https://github.com/mozilla-mobile/firefox-tv/files/1918076/blackscreen.log)

**Comment by npark-mozilla** [comment]
Only error I see from logcat is:
cmp=com.amazon.venezia/.pdi.AppLaunchActivity (has extras)} from uid 10091 on display 0
04-16 19:04:14.100  3438  3438 D AmazonHdmiService: onDisplayChanged: mode switch
04-16 19:04:14.219  3438 22020 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=org.mozilla.tv.firefox cmp=org.mozilla.tv.firefox/org.mozilla.focus.MainActivity (has extras)} from uid 10098 on display 0
04-16 19:04:14.220  3438 22020 E PerfBoost: PerfBoost APPLICATION_START status: PERFBOOST_NOT_AVAILABLE_ERROR

**Comment by liuche** [comment]
from npark:
- also happens if going back to Amazon home screen (rather than killing FF)
- only on custom pinned YT (not default YT site)
- video will come back after opening overlay

**Comment by liuche** [comment]
Questions:
- Does this happen on Silk? (is it a webview problem?)

**Comment by npark-mozilla** [comment]
This seems to happen on silk browser as well.  
When I add a youtube video bookmark and visit the bookmark from the main view, it shows black screen as well.

**Comment by liuche** [comment]
@bbinto flagging you because this is something to follow up with Amazon about.

**Comment by AaronMT** [comment]
Not sure how to 'exit Firefox'. I hit the Home button, and tap Firefox and the app resumes. However, I did restart my device and loading the pinned YouTube URL loads the video fine.

Works for me?
