### ISSUE TITLE
[Pocket] Introduce pocket mega tile on first launch

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/firefox-tv#828]
Why:

- Explain why FFTV users are seeing this new tile in their homescreen

What:

- An overlay that displays at first launch with the pocket mega tile and, a title and short explanation that give more context about the feature
- A link to a web page that gives further information about the feature

Who:

- All FFTV users

Acceptance Criteria:

- Users can dismiss the overlay and access the homescreen
- Users can find out more via the "Learn more" link

Metrics/KPIs:

- Click on "Learn more"
- Click on pocket mega tile right after the overlay is dismissed

**Comment by aminalhazwani** [comment]
Some explorations

<img width="1770" alt="screen shot 2018-04-18 at 2 33 13 pm" src="https://user-images.githubusercontent.com/1721875/38933121-6c0bf502-4318-11e8-91c7-178597625a0a.png">

**Comment by aminalhazwani** [comment]
And with a "Help" button in the right corner of the pocket feed header we could give a way to users to see the overlay again

![fftv pocket video feed - first card](https://user-images.githubusercontent.com/1721875/38990666-7e0f99e8-43db-11e8-9b50-47acef7bb288.jpg)

**Comment by BrianNJones** [comment]
@aminalhazwani , great! I'll adapt some of the already-approved copy from Firefox for Desktop to (hopefully) minimize translation needs.

**Comment by BrianNJones** [comment]
@aminalhazwani, strings below. 

[Hedline}
Introducing videos recommended by Pocket
[Body Copy]
The most interesting videos on the web. Recommended by Pocket, now part of Mozilla.
[Button]
Okay, got it

**Comment by mcomella** [comment]
> I'll adapt some of the already-approved copy ... to (hopefully) minimize translation needs.

fwiw, there's nothing that we can do on our end to minimize the translation needs (because context matters) so unless the localizers correlate related strings themselves, re-using strings doesn't minimize translation needs.

**Comment by mcomella** [comment]
FYI: string export is next wednesday and we should triage this on Tuesday to see if it'll make v3.0.

**Comment by aminalhazwani** [comment]
> if you can also give us the asset to include

@liuche [here](https://github.com/FirefoxUX/people/blob/gh-pages/aalhazwani/firefox-for-fire-tv/homescreen-pocket-tile/assets/pocket-mega-tile.png) you can download the asset but I would like to check first with @bbinto regarding what video thumbnails to display here, do we have any restriction Barbara? Or can I just pick 4 attractive thumbs from the pocket recommendations?

> Is the "learn more" a link to a SUMO page? or some other page?

The link has been removed after review with @brianNjones, [here](https://firefoxux.github.io/people/aalhazwani/firefox-for-fire-tv/homescreen-pocket-tile/#artboard0) the latest version.

All the links to mocks and assets are avaiable here https://github.com/mozilla-mobile/firefox-tv/issues/759#issue-311393555.

**Comment by bbinto** [comment]
@aminalhazwani, good point, thanks for reaching out. As long as these were/are coming from the recommendations feed, I let you pick them first, please share them with me though for final review. I want to reach out to some folks internally about it once I have them.

(I'd be fine with the picks you show in the mock to proceed for final approval)

**Comment by bkmunar** [comment]
@aminalhazwani what will the background of the overlay look when a user pressed the help button in the pocket feed? Is the intent to make the background transparent with a specific opacity and blur??

**Comment by aminalhazwani** [comment]
@bkmunar yes, that is correct! The background is set to Grey 70 alpha 80% so `#cc38383d`, and the background blur amount is set to `20px`. Is there an Android-equivalent of the CSS filter blur property?

**Comment by bkmunar** [comment]
I think we would need to create our custom blur for that

**Comment by aminalhazwani** [comment]
Ok, let me know if it's feasible! I opted for a blur effect because due to typography- and image-heavy background content a simple translucent layer wasn't contrasting enough. If it's not doable I can think of alternatives.

**Comment by liuche** [comment]
Update from bkmunar, from our earlier conversation:
* PR should be ready by EOD, needed to fix the layouts because they didn't look right
* @bkmunar and I worked through using string substitution
* @aminalhazwani : @bkmunar said blur was hard to do with basic Android and should be filed as a follow-up, so can we get a contingency plan (maybe we can try just an opacity like the overlay?)
* @bkmunar will file a follow-up and describe what he's tried for blur/why it's hard

**Comment by aminalhazwani** [comment]
@liuche ok! Let's use the opacity like the overlay, it should be dark enough to contrast with the background. For the blur - as you suggest - we can file a follow-up, thank you and thanks @bkmunar!

**Comment by bkmunar** [comment]
We need to use an Activity instead of a Fragment because I ran into a problem where the background color will not show transparency due to the nature of Fragments not being able to be stacked.

**Comment by bkmunar** [comment]
This is what it looks like at the moment
![img_3966](https://user-images.githubusercontent.com/8356717/39899603-bf3d873a-5471-11e8-845b-7cb4c3e109ad.JPG)

**Comment by bkmunar** [comment]
@aminalhazwani would love if you gave me the fonts and font sizes!

**Comment by bkmunar** [comment]
you're going to have to clear the app data every time since it shows once like the spec says. Do you have the help button asset?

**Comment by aminalhazwani** [comment]
@bkmunar here the icon [help-24.svg.zip](https://github.com/mozilla-mobile/firefox-tv/files/2001121/help-24.svg.zip), sorry!

Problably you would also need a focus state for the help button. I added it to the [mocks](https://firefoxux.github.io/people/aalhazwani/firefox-for-fire-tv/pocket-video-feed/index.html#artboard9)! While we wait for standardizing how we focus things - see #837 - you can use the same outline as we use for the pocket tile and the search/url bar.

Regarding the overlay, thanks, I managed to make it display. Some considerations:
- We can make use `<color name="pocket_onboarding_background">#e60c0c0d</color>` for the background color
- We should make the "Ok, got it" button focus by default when the overlay is open
- I would make the the overlay display on app launch, not when the Pocket mega tile is selected. If possible we should introduce the new tile before people actually see it.

**Comment by aminalhazwani** [comment]
Hey @bkmunar is there anything else that I can help you with? Let me know 🙂
