### ISSUE TITLE
Round corners of pocket card images when not highlighted

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#844]
Follow-up to #761 for UX polish days via https://github.com/mozilla-mobile/firefox-tv/issues/761#issuecomment-383564270.

**Comment by mcomella** [comment]
@aminalhazwani If I'm not mistaken, when the card is highlighted the image's corners are no longer rounded, correct? I think it'd look weird without animations so should they be animating between rounded and non-rounded (I'm not sure how feasible that is)? And if we didn't have animations to switch between them, do you think that'd be okay?

**Comment by aminalhazwani** [comment]
> If I'm not mistaken, when the card is highlighted the image's corners are no longer rounded, correct?

@mcomella yes, when the card is highlighted only Top Left and Top Right are rounded. BR and BL are squared.

> And if we didn't have animations to switch between them, do you think that'd be okay?

Yes, if the animation is not easily feasible lets switch between them border radius without animation. We can play with animation and transition in a later polish.

**Comment by mcomella** [comment]
@aminalhazwani For awareness, rounding corners on Android is a little bit of a pain compared to other platforms like iOS and web: rather than setting one property, it requires a custom background "Drawable" with rounded corners and colors and there are often problems related to clipping of content drawn over the view. ImageViews may be especially tricky (since the image layer is separate from the background layer): but we can probably add our new custom view to our Android components lib and be done with it. :) fwiw, CardViews make this much easier.

That being said, I think we should be able to do this during UX polish. :)

**Comment by aminalhazwani** [comment]
If we are using - or will use - `CardView` I am more than happy to read more extensively the documentation so that I could align the designs with the current technology constrains, thanks @mcomella!

**Comment by mcomella** [comment]
@aminalhazwani The CardView lib basically just makes rounding corners and adding elevation easy but I'm skeptical about how heavy weight the API is (but I guess it doesn't matter until we see real problems! :)

**Comment by mcomella** [comment]
We have a new homescreen design where this is no longer relevant.
