### ISSUE TITLE
Build unsigned release builds from Taskcluster

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#852]
Like Focus, we should build release builds from TC rather than by hand.

Afterwards, we need to:
- [ ] Remove fake release builds made to test this
- [ ] Update the docs for how to make release builds

**Comment by liuche** [comment]
For reference, to get this to work I needed to:
* Request a firefox-tv taskcluster project
* Taskcluster Secrets: Add the secrets to Taskcluster
* Taskcluster Roles: Create a Firefox-TV release role and add the secrets scope ( https://tools.taskcluster.net/auth/roles/repo%3Agithub.com%2Fmozilla-mobile%2Ffirefox-tv%3Arelease )
* Add the task description for the release task
* Make a release tag on the branch

**Comment by bbinto** [comment]
@liuche would you mind providing us with a concrete "Why" to better prioritize
