### ISSUE TITLE
Change scaling, position of highlighted Pocket video feed card

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#855]
### Why/User Benefit/User Problem
Scaling width and height with the same ratio makes the highlighted card considerably high with unused and unnecessary real estate under the video title.

### What / Requirements
If I read the code correctly the non-highlighted card is 240dp large and 290dp high. We can scale the width by .1% so that it becomes 264dp while the height can remain the same. We only need to move the highlighted card up - y axis - by 3.5dp if possible, so that the thumb of an highlighted card is vertically aligned with the thumb of a non-highlighted card.

<img width="497" alt="screen shot 2018-04-24 at 12 51 38 pm" src="https://user-images.githubusercontent.com/1721875/39182837-72c095d8-47be-11e8-96fe-fee5a76f1fa4.png">

**Comment by athomasmoz** [comment]
Closing as low priority
