### ISSUE TITLE
Don't change textAppearance when focusing/unfocusing Pocket card on feed

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#857]
Apparently I forgot to take this out. @aminalhazwani Should the font be Roboto Medium or Regular?

**Comment by mcomella** [comment]
@aminalhazwani I went with medium – let me know if it should change.

**Comment by aminalhazwani** [comment]
Sorry @mcomella, missed this one. Medium is the one, thanks for following on this one!
