### ISSUE TITLE
The application does not properly fit in 16:9 (overscan)

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#859]
On a 1080P 16:9 television, the default setting, the application does not fit to display.

![img_0252](https://user-images.githubusercontent.com/102331/39313671-8e1b6672-4940-11e8-910c-38421fa463a0.JPG)

If I change the TV to "Just Scan" the edges are not cropped

**Comment by mcomella** [comment]
@aminalhazwani Did you take overscan into account for your new overlay designs?

**Comment by aminalhazwani** [comment]
> Did you take overscan into account for your new overlay designs?

@mcomella yes - I added a [screen](https://firefoxux.github.io/people/aalhazwani/firefox-for-fire-tv/homescreen-pocket-tile/index.html#artboard7) to the mocks for reference. I followed the Amazon Fire TV recommendations, so 5% from all edges.

**Comment by mcomella** [comment]
Okay, I'm going to close this then.

@AaronMT I landed style changes on master that should fix this issue: please refile if you're still seeing this.
