### ISSUE TITLE
Pocket megatile loading screen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#864]
User benefit: without a loading state, it looks weird and it's unclear to the user that we're loading. What we have in the mocks is a transition between gradient images in the thumbnails: seems straightforward.

fwiw, we cache our data and never replace the cache with bad data so users will only see this each time the app is started after OOM.

**Comment by mcomella** [comment]
Actually, there are issues more important than a loading screen right now.

**Comment by aminalhazwani** [comment]
![homescreen pocket tile loading](https://user-images.githubusercontent.com/1721875/41938068-e22267e4-7946-11e8-86f0-2cee97607e3b.jpg)
