### ISSUE TITLE
Pocket video feed loading state

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#865]
User benefit: without a loading state, it looks weird and it's unclear to the user that we're loading. What we have in the mocks is a transition between gradient images for each card view: seems relatively straightforward.

fwiw, we cache our data and never replace the cache with bad data so users will only see this each time the app is started after OOM.

**Comment by liuche** [comment]
This is S if we don't do placeholder animations.

**Comment by Baron-Severin** [comment]
@mcomella @liuche To clarify, is this a state in which our Pocket recommendation list is loading, or the images themselves are loading?

**Comment by Baron-Severin** [comment]
@aminalhazwani How does this behavior look to you?

![pocket-load](https://user-images.githubusercontent.com/13170306/45459613-ee651700-b6ad-11e8-9b50-9238a3a836b8.gif)

**Comment by aminalhazwani** [comment]
Looking good @Baron-Severin, thanks for working on this!

**Comment by mcomella** [comment]
On Tue, Sep 11, 2018 at 4:30 PM Severin Rudie <notifications@github.com>
wrote:

> @mcomella <https://github.com/mcomella> @liuche
> <https://github.com/liuche> To clarify, is this a state in which our
> Pocket recommendation list is loading, or the images themselves are loading?
>

The former, the whole list is loading from the server; Picasso handles the
loading images state.
