### ISSUE TITLE
l10n screenshots with newly imported strings

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#868]
Follow-up to #829 once the strings get translated. @AaronMT was mentioned to do the checklist item in the bug.

From Delphine:
> @liuche: Thanks for filing this. Do you think you could add a check-box for generating screenshots (which implies importing most recent strings right before making the screenshots) in this list? I'm unsure of the rest of the timeline but basically a good moment to get them would be like a few days before the final string import on your side.

**Comment by liuche** [comment]
We should probably automate this script as well with Taskcluster if we can. @AaronMT where are the screenshots scripts located, and how are they run? Can you add a section on screenshots to the bottom of the [Localization wiki page](https://github.com/mozilla-mobile/firefox-tv/wiki/Localization)?

**Comment by AaronMT** [comment]
@liuche firefox-tv/app/src/androidTest/java/org/mozilla/focus/screenshots/TVScreenshots.java

As previously mentioned, for this release the script will need to be rewritten to support all the UI changes.

> Can you add a section on screenshots to the bottom of the Localization wiki page?

Sure.

**Comment by liuche** [comment]
We'll assign @AaronMT once all the UI changes are in and the script can be updated.

**Comment by liuche** [comment]
I think our UI for the new changes (new homscreen, pocket feed) are mostly in place. @dnarcese is working on #895 (unsure if you need that). The only things that are missing are the Pocket error messages (no tiles, empty feed, etc), but we'll be adding those soon.

@AaronMT could you do a run of screenshots for L10N on the current master?

**Comment by AaronMT** [comment]
Testing builds are blocked on issue #1010

**Comment by liuche** [comment]
Should be unblocked now.

**Comment by liuche** [comment]
@AaronMT is this also blocked on #1099 ?

**Comment by AaronMT** [comment]
and #1108

**Comment by bbinto** [comment]
@AaronMT - any updates on this?

**Comment by AaronMT** [comment]
Running against master with current fixes

**Comment by AaronMT** [comment]
Master run: https://www.dropbox.com/sh/kzcf7d66sw0oke6/AAC3Z4Zjk1toFiVeTdT7ahUea?dl=0

Gonna close this one and open another for any other issues if need be

**Comment by Delphine** [comment]
Hey @AaronMT! Thanks for the screenshots, but seems like I can not access them? I will try from another connection in case it's due to my current location (I'm traveling right now)

**Comment by Delphine** [comment]
Heads-up: I can access the screenshots from where I am now. Thanks
