### ISSUE TITLE
Directional pad navigation becomes locked on address-bar focus

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#874]
I keep running into issues where I can not navigate the browser overlay with the directional pad. Hitting the down arrow focuses the address-bar, hitting down again should focus the tiles (YouTube) but nothing happens. I have to navigate across the top toolbar (forward, over to Turbo Browsing, and then over to Settings) - from settings, I can hit down to go to a tile.

**Comment by AaronMT** [comment]
Here's one way to reproduce

Visit 

* https://www.microsoft.com/en-ca/windows/features
* Tap the video, begin playback
* Back out and open the menu

Hit up on the directional pad and over in an attempt to go to settings. 

* Notice the movement is locked

In order to get to settings you must go down from the address bar, over to the right a few tiles and then up to settings.

We shouldn't provide a puzzle for users.

**Comment by AaronMT** [comment]
Another way to reproduce, remove all default tiles and you can no further use the directional pad to move away from the address-bar or focus anything on the empty home-screen

**Comment by AaronMT** [comment]
Another way, just go down from the address-bar on first launch to YouTube, and then go up again to the address-bar. From there you are locked to going up to get to settings and have to go around the tiles.

**Comment by mcomella** [comment]
The overlay is in a partially complete state in v3.0 and we unfortunately dropped the ball in filing bugs to indicate our remaining follow-up work. I made improvements to this in #774 – let's see how it controls after that.

**Comment by liuche** [comment]
I'm not seeing this specific "locked" issue any more on master.

**Comment by mcomella** [comment]
I'm going to close this because it's taking up brain space and I think it's fixed - @AaronMT please reopen if you can still repro.
