### ISSUE TITLE
[a11y] Make sure it's not broken on overlay

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#878]
We did a lot of refactoring so let's make sure it all still works, especially the tile we added.

*edit: behavior differences I see:*
- [x] 1) On the initial overlay, "firefox:home" is announced instead of "Search or enter address"
- [x] 2) There is a bug when opening the overlay over web content where the web content will continue to be announced after the url bar is read
- [x] 3) Pocket videos in not announced
- [x] 4) Recycler view now has "row x, column y" announcements, unlike before
- [x] 5) Pocket error state, blocked on #889 
- [x] 6) Press and hold to SELECT toast is sometimes announced when menu is opened *I'm having trouble reproducing this*

**Comment by mcomella** [comment]
@aminalhazwani For 1, "firefox:home" isn't recognizable as a URL even for visual users so it could be confusing what users can do here. Should we replace that text on the initial screen with "Search or enter address" and display a url when on a real web page like before?

---

I fixed 3 already and 4 actually sounds like an improvement.

**Comment by mcomella** [comment]
I'm having difficulty with 2: I can't seem to get the announcements to stop. I tried `interrupt`, changing focusability of the webView when the overlay is shown, and overriding accessibility delegates. One set of code I had seemed to work but I lost that revision (d'oh!). I'm concerned that the events are getting added to a queue which we don't have access to which makes it hard to stop the events, or that the page is getting updated asynchronously in the background, which draws focus and announcements.

One fragile option we can try is changing visibility state of the WebView when accessibility is enabled/disabled. It's fragile because if we have a bug in our code, the browser could stop working altogether and it's pretty easy to break with code refactors (because we don't test these code paths often).

I'll revisit this after I play around with the other issues.

**Comment by aminalhazwani** [comment]
> Should we replace that text on the initial screen with "Search or enter address" and display a url when on a real web page like before?

@mcomella yes, let's use the same placeholder "Search or enter address". 

I noticed that now on Desktop we use "Search with {name of search engine} or enter address". Is this something we also want to follow? Maybe in the future where you could choose among multiple search engines.

**Comment by liuche** [comment]
1) firefox:home is announced - we don't have a "Search or enter address" so this is expected
2) Overlay is working - Verified that the following are announced: nav buttons, url, pocket recommendations tile, individual tiles (title, row, column)
3) Pocket videos megatile is announced
4) Recycler view now has "row x, column y" announcements
5) Pocket error state can be covered in #827
- [ ] 6) I don't ever see the "Press and hold SELECT" toast ever announced

Problems: 
* Some web content isn't read on webview, notably when a string has a link in it - the link in the line is read and selected, but the rest of the line isn't read. If a line has multiple links, navigation between links seems to not really work. Seems like VoiceView is not handling the webview quite correctly.
* If a link is selected and then the overlay is toggled, VoiceView will start reading other things on the screen outside of the selected box

**Comment by liuche** [comment]
It looks like VoiceView on Amazon Fire TV doesn't read Toasts/notifications aloud, but the TalkBack on the Android emulator does. @Sdaswani can you ask Amazon whether they will support toast notifications?

**Comment by Sdaswani** [comment]
@liuche is the question 'Will VoiceView on Amazon Fire TV support toast notifications, i.e., read Toasts/notifications aloud?' I want to make sure I ask the right question.

**Comment by Sdaswani** [comment]
@liuche from @haldeman99:

Our engineering team let me know that toasts/notifications are generated from multiple components on Fire TV, so they need to know which ones are not working. Can you provide the STR? I couldn’t deduce them from github.
 
Are you using setTicket (https://developer.android.com/reference/android/app/Notification.Builder#setTicker(java.lang.CharSequence)​?
