### ISSUE TITLE
HIDE MENU telemetry intended to be shown when user hides menu without action; is used when loading URLs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#879]
### Why/User Benefit/User Problem
We want to know when the user closes the overlay without an action so we have a heuristic for when the user hasn't found the overlay to be useful for them.

This probe is broken: it's used when the user loads a URL or loads a tile in addition to when they take no action (via hitting back or menu).

@bbinto How important is this to fix? Should we fix it for v3.0?

I'll update the docs to indicate this problem.

**Comment by bbinto** [comment]
@mcomella - what's the effort to fix it?

**Comment by Sdaswani** [comment]
I suggest if we make changes then we change the probe name.

**Comment by mcomella** [comment]
[triage] v3.0, we don't want to have bad telemetry.

If this broke in the v3.0 refactor, just fix it. If it broke before and we already have bad data, consider a new probe.

**Comment by Baron-Severin** [comment]
@bbinto @Sdaswani Could you help me clarify what it is that we intend to capture?

We want to know when the user opens the menu then closes it without performing an action.  Does changing focus (i.e., moving the selection around) count as an action?  One option that occurred to me is that we could send an event if the user opens and closes the menu without performing a click.

**Comment by Sdaswani** [comment]
@Baron-Severin I think 'not useful' could mean I opened it 1) by mistake, so it's not useful or 2) intentionally, and then didn't find anything to help get where I need to go. So I _think_ your option ('send an event if the user opens and closes the menu without performing a click') covers both those cases? If so, that's a great option IMHO. cc @bbinto

**Comment by Baron-Severin** [comment]
I'm going to move forward with that condition.  @bbinto please let me know if you would like me to take a different approach.

**Comment by Baron-Severin** [comment]
Looks like the telemetry events were broken in v2.0.1 on April 18th, so we'll have to rename them.  I've fixed the menu open / close events, and added a new one as discussed above.  The new event addresses an edge case in the earlier approach (user opens menu, user pins tile, user closes menu, our data shows that as a confused user).

I'm going to discuss event names with @liuche, then the code will be ready to land.
https://github.com/mozilla-mobile/firefox-tv/pull/1056

**Comment by bbinto** [comment]
@Baron-Severin and @Sdaswani sorry for the delay - agreed and OK with that change
