### ISSUE TITLE
Follow-up: Toast for "Unpin" hint is not shown according to spec

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#885]
Follow-up from #782 
### Steps to reproduce
* Open Firefox TV
* Go to home screen

### Expected behavior
* Toast hint shows up when tile is selected, max 3 times

### Actual behavior
* Toast hint shows up over Turbo mode screen
* Toast doesn't show up when navigating through tiles

### Device information

* Fire TV device: 25
* Firefox version: master

**Comment by bkmunar** [comment]
"Toast hint shows up when tile is selected, max 3 times" is this new? I don't see it in the original bug (the part about showing up when a tile is selected). But I can do it if it's approved! I just didn't know UX wanted that

**Comment by liuche** [comment]
Here was the option mentioned in Amin's initial suggestions: https://github.com/mozilla-mobile/firefox-tv/issues/782#issuecomment-380109379

The way the toast is currently implemented doesn't make sense (the context of showing the toast doesn't make sense, it never stops showing up), so it should be fixed - this is clearly a bug. This approach seems reasonable to me based on UX comments, but if it doesn't seem right, can clarify with UX.
