### ISSUE TITLE
Follow-up: Incorrect Nav button highlighting

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#886]
Follow-up from #770 and #768 
### Steps to reproduce
* Move from nav buttons down to recycler view tiles

### Expected behavior
* One Recycler View tile is highlighted

### Actual behavior
* A button on the navigation row gets highlighted, as well as a tile - this makes it look like there are two places that are "selected"

### Device information

* Fire TV device: all/25
* Firefox version: master

**Comment by bkmunar** [comment]
So this isn't reproducible on my device (I have the Fire TV with the dangling square, not the stick). So I can't get to this unless I have the other device. I've tested this extensively on this version of Fire TV enough to say with confidence that I don't think it's reproducible on it.

**Comment by mcomella** [comment]
Actually, I think I fixed this already in https://github.com/mozilla-mobile/firefox-tv/commit/45940fa7ae2658a066edf57732853a781090aa15
