### ISSUE TITLE
Pocket megatile error handling

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#889]
We have strings for if the megatile content isn't loading. #864 is a related bug.

**Comment by liuche** [comment]
Medium because it might be tricky to replace the existing layout for the error state.

**Comment by aminalhazwani** [comment]
![homescreen pocket tile error](https://user-images.githubusercontent.com/1721875/41938003-b3e7a7c2-7946-11e8-9e25-ae1443f6335e.jpg)

**Comment by aminalhazwani** [comment]
I updated the screen with the latest changes! You find the web inspector here https://github.com/mozilla-mobile/firefox-tv/wiki/Design#mocks-with-a-web-interface

![webpage](https://user-images.githubusercontent.com/1721875/45034191-11ad1800-b057-11e8-892d-9b7297c7e43b.jpg)

**Comment by dnarcese** [comment]
@aminalhazwani I'm not able to find the web inspector for this screen

**Comment by aminalhazwani** [comment]
I pushed version 11 with this screen but the build failed, I'll ping Blake to see if he can dig into it.

**Comment by aminalhazwani** [comment]
Ok, it's now online here https://firefoxux.github.io/people/aalhazwani/firefox-for-fire-tv/homescreen-pocket-tile/v11/index.html#artboard2 🙂
