### ISSUE TITLE
[Live App Test] Feedback on 2.1.0.1 build

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#896]
This will be for the Live App Test version that includes 1) new homescreen/overlay 2) basic Pocket feed.

Please leave all feedback, bugs, issues in a comment and we can collect and gather and open separate issues. Thanks!

(As a reminder, we decided in our retro to have each issue raised here filed as a separate issue so there is less confusion over what has been done/not).

**Comment by Sdaswani** [comment]
Submitted from https://tools.taskcluster.net/groups/GTf9DgyZQHKihuK3lFHudg/tasks/GTf9DgyZQHKihuK3lFHudg/runs/0/artifacts, that was super easy!

**Comment by porfitron** [comment]
When pressing down from home screen, current behavior is:
1) Search, 2) Pocket, 3) Center Tile
I personally believe it should be:
1) Search, 2) Pocket, 3) First tile on left (e.g. YouTube).

BTW, new cursor looks great (circle with dot in center).

**Comment by aminalhazwani** [comment]
Thanks for the feedback @porfitron together with @mcomella we are working on dpad navigation, see #906

**Comment by liuche** [comment]
Closing this bc everything is filed.
