### ISSUE TITLE
The White Screen of Emptiness

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/firefox-tv#900]
### Steps to reproduce

Press the three line button on the remote when any element on the screen (the address bar, Pocket, default tiles, cogwheel, turbo mode) are highlighted. 

### Expected behavior

Nothing to happen.

### Actual behavior

A white screen with only the cursor showing is displayed. (Pressing the back button takes the user back to the FireTV home page.)

### Device information

* Fire TV device: Fire TV with 4K Ultra HD and Alexa Voice Remote (Pendant Design), FireOS version 6.2.1.2
* Firefox version: 2.1.0.1

**Comment by mcomella** [comment]
[triage] Leaving in triage to wait for results. ^

**Comment by mcomella** [comment]
This needs #379 so I'm going to swap their positions in the sprints.

**Comment by liuche** [comment]
Closed by #1088.
