### ISSUE TITLE
Re-evaluate "homescreen" in copy for new homescreen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#913]
### Why/User Benefit/User Problem
Pinning a tile shows a toast with the copy, "Pinned to Firefox TV homescreen". With the new design, it might not be considered a "homescreen" anymore, especially in other locales.

### What / Requirements
- Re-evaluate copy and potentially change it.

@BrianNJones Have you had a chance to try out the new app experience? Do you think this string is still appropriate? Note that we have similar copy for the new toast, "Press and hold SELECT to unpin from homescreen." (or something like that)

**Comment by BrianNJones** [comment]
@mcomella, i still think that (while it may not be perfect-perfect), "homescreen" still works as the best and most familiar metaphor. that, and the possibility of confusion seems minute.

**Comment by mcomella** [comment]
Great, thanks Brian!
