### ISSUE TITLE
Empty video preview tile in the Pocket Feed

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#916]
Check with Pocket if there's anything they can fix here

![screen shot 2018-05-17 at 7 43 21 pm](https://user-images.githubusercontent.com/102331/40208977-b0e13cec-5a0a-11e8-9cf3-a3d73a92e1c3.png)

![screen shot 2018-05-17 at 7 44 40 pm](https://user-images.githubusercontent.com/102331/40208996-d31f1c98-5a0a-11e8-8f12-5fc9b5443819.png)

**Comment by kennylong** [comment]
@liuche @AaronMT Thanks for raising.

This should happen rarely. When we curate the videos, we do not add videos that are missing images. With that said, sometimes between the time we curate and it is added to the feed, an image can get removed for whatever reason.

We are looking into ways to detect this “default” image - unfortunately, it is not immediately clear from the name. For example:

- Working image: https://img.youtube.com/vi/620omdSZzBs/maxresdefault.jpg
- Blank image: https://img.youtube.com/vi/SYSMdf_hbpE/maxresdefault.jpg

We believe image size/dimensions might allow us to detect, but we don’t currently load the images ahead of time so need to sort out how to flag it appropriately.

**Comment by athomasmoz** [comment]
Closing as low-priority to fix on our side. Looks like investigation is ongoing on Pocket side
