### ISSUE TITLE
Failed to resolve: org.mozilla.telemetry:telemetry:1.2.0

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/firefox-tv#918]
### Steps to reproduce
Downloaded .zip from https://github.com/mozilla-mobile/firefox-tv and extracted.
Opened Android Studio 3.1.2 and imported the extracted file as a new project.
Let Android Studio build the app

### Expected behavior
The application should build without error

### Actual behavior
App does not build
Message of "Failed to resolve: org.mozilla.telemetry:telemetry:1.2.0" is displayed.  This references line 168 in app, that states "implementation 'org.mozilla.telemetry:telemetry:1.2.0'"

### Device information
Android Studio 3.1.2 on Ubuntu 18.04

**Comment by mcomella** [comment]
We're blocked by components: https://github.com/mozilla-mobile/android-components/issues/208

**Comment by pocmo** [comment]
The telemetry library is back on jcenter. Unfortunately only with the new group id. I'll try to prepare a patch.

**Comment by mcomella** [comment]
This was fixed on master, https://github.com/mozilla-mobile/firefox-tv/commit/226585b84fb97b508e08806a2dca670d1a15f3e0, but older builds will continue to be broken until this is fixed: https://github.com/mozilla-mobile/android-components/issues/208
