### ISSUE TITLE
Audit how we handle PDFs and if we can do anything about it

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#919]
Currently, we block downloads on the Fire TV - #146 - and so we might have a poor experience if a user tries to read a PDF, which I think the system downloads by default.

**Comment by bbinto** [comment]
Confirm that user experience of viewing/downloading PDF is clear, i.e. even if it doesn't work, communicate message to user

**Comment by athomasmoz** [comment]
Closing as low priority
