### ISSUE TITLE
Use browser-session component for browser state

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#929]
The component has not all features we need yet. However it's close already. I'll experiment a bit to see if there's something missing. This issue is mostly for tracking this work for now.

**Comment by bbinto** [comment]
@pocmo will you be able to write and connect/integrate with the FFTV code? 

If so, could you please let us know what t-shirt size this issue will land at?

**Comment by pocmo** [comment]
> @pocmo will you be able to write and connect/integrate with the FFTV code?

Yes, I'm doing the integration to see what parts are missing in our component. I'll open a PR at the end of it.

> If so, could you please let us know what t-shirt size this issue will land at?

That's definitely a Large.

**Comment by mcomella** [comment]
Note: it might be good for library consumers to integrate the components to get feedback from a different perspective than the library author but it could also be helpful for Sebastian to implement the components himself to understand the requirements first hand.

@pocmo btw, we're not using the "multi-session" parts of our code, but they're still in the codebase, dangling (e.g. iirc, opening external intents will create more sessions but the back stack makes it act like one session), so if it's easier for you to remove those parts of the code, please do!
