### ISSUE TITLE
Fullscreening problems: back/forward, mini-fullscreen

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#938]
We also don't handle the `BrowserIWebViewCallback` properly, and recreate it on `get()`.

### Steps to reproduce
1. Go to m.youtube.com, load a video
2. Fullscreen the video
3. Open overlay and click on navigation button to go back

### Expected behavior
Youtube website opens

### Actual behavior
Black screen

**Comment by liuche** [comment]
This also causes fullscreen-ed videos (BBC, m.youtube, etc) to not fullscreen properly - it looks like it's fullscreening but the video size and placement is the same, and it's not filling the fullscreen view (everything else is empty/black).

**Comment by jonalmeida** [comment]
The screenshot of the issue from #1172 just to have everything in one place while a-c also looks into it as well.

![](https://user-images.githubusercontent.com/11432165/45847254-7378ad80-bcf8-11e8-8427-15fb3fe2c421.png)

**Comment by liuche** [comment]
Didn't get a chance to investigate this fully, but one thing is the chromeClient doesn't call through to the fullscreenView show/hide when forward/back are called:
https://github.com/mozilla-mobile-skunkworks/firefox-connect/commit/9c3859a40beaa699488b2e9cd4f6c04339e4cc02

**Comment by mcomella** [comment]
It may add code complexity and potential coupling to fix this by letting users open the overlay while the video is fullscreened: perhaps we could consider alternative solutions, like closing fullscreen when the menu is opened, to fix this issue.

**Comment by jonalmeida** [comment]
The fullscreen issue is fixed as part of mozilla-mobile/android-components#828, expect it to be resolved in the next release.

**Comment by athomasmoz** [comment]
Need a special build from components. Susheel following up with them to request

**Comment by Sdaswani** [comment]
Yes, this will be made available tomorrow morning by 10am PST per @st3fan .

**Comment by Baron-Severin** [comment]
The A-C v.25 release has partially fixed this.

Fullscreened videos do not fullscreen properly -> fixed
Back press from m.youtube.com not working -> not fixed

@pocmo noted in slack that A-C is unable to intercept back presses from the WebView, and thinks we will have to call `exitFullscreen` if one occurs while fullscreen is active.

**Comment by jonalmeida** [comment]
Can this be split into two different issues? It's combined two things together and one was an `a-c` fix (mini-fullscreen) and the other is a fire tv fix (back press buttons).

The former is already fixed and released - this issue is still open with an `a-c` label and marked as Blocked.

**Comment by Sdaswani** [comment]
From what I understand @jonalmeida there is a still an a-c issue but I'll let @Baron-Severin confirm.

**Comment by Baron-Severin** [comment]
@pocmo believes the remaining problem has to be fixed on our end, although I haven't yet had a chance to try.  I think we're good to close this in A-C and attempt his suggested fix ourselves.  If it doesn't work out, we can always raise another issue.

Closing, splitting off the remaining problem into https://github.com/mozilla-mobile/firefox-tv/issues/1224.
