### ISSUE TITLE
Add telemetry to voice commands/MediaSession API

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#943]
### Why/User Benefit/User Problem
It'd be good to know how often these voice commands ("Alexa play") are used in Firefox so we know how often to support them.

Note: we may be unable to distinguish between a voice command and a media button press.

### What / Requirements
- Get telemetry spec
- Implement

**Comment by mcomella** [comment]
@bbinto Can you elaborate on what telemetry you'd like to see here? The table at [this link](https://developer.amazon.com/docs/fire-tv/mediasession-api-integration.html#set-the-media-session-callback-actions) shows what user utterances there are and what we commands we receive on the backend.

Note that remote hardware buttons (e.g. the play/pause button) also send these commands: we receive both an `onMediaButtonEvent` and the `onPlay/Pause` so while we can't say, "Who triggered this onPlay/Pause?" with 100% accuracy (it might be pretty accurate though - I'd need to look into it), we can see how many media button events there were compared to how many onPlay/Pause to determine how many were utterances vs. hardware

**Comment by bbinto** [comment]
> we can see how many media button events there were compared to how many onPlay/Pause to determine how many were utterances vs. hardware

@mcomella, for now if we could just get a probe in that detects when voice was used (your comment seems to suggest that), that's all I care about for now.

**Comment by mcomella** [comment]
> for now if we could just get a probe in that detects when voice was used

We can calculate this (assuming there is no way to trigger the mediaSession events I'm not aware of): we can add probes for each of the events we receive that are triggered by voice commands (play, pause, seekTo, next, previous). However, play/pause can also be triggered by the media buttons on the remote so we can add a probe for `onMediaButtonEvent` and, from our mediaSession play/pause events, we can subtract the number of play/pause media button events. To summarize:
```
play_pause_media_button = media_button WHERE button = play_pause
play_pause = play_media_session + pause_media_session - play_pause_media_button
voice_command_count = play_pause + seek + next + previous
```

I'll get on that.

**Comment by mcomella** [comment]
FYI: the API aggregates rewind/fast-forward into an absolute seek. I implemented seek telemetry for simplicity. We can calculate whether it's a rewind or fast-forward, however, so I filed #988 to do that. @bbinto Do we want to implement rewind/fast-forward telemetry before release?
