### ISSUE TITLE
Create 3.0 KPI dashboard

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#951]
See KPIs [here](https://github.com/mozilla-mobile/firefox-tv/issues/777#issue-311755508)

**Comment by bbinto** [comment]
@mmccorks - this should be done in the sprint starting September 10

**Comment by bbinto** [comment]
@mmccorks - any updates on this? Let Ashley or I know what else you need.

**Comment by Sdaswani** [comment]
@mmccorks says this should be done by code freeze.

**Comment by Sdaswani** [comment]
this dash is still be worked on but we can close this: https://sql.telemetry.mozilla.org/dashboard/firefox-for-firetv-3-0-release-dashboard
