### ISSUE TITLE
With Cube, 'Alexa, next/previous' causes the screen to go black, load continuously

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#963]
### Steps to reproduce
- Open Firefox TV, launch youtube, play a video
- Play several videos, then say 'Alexa, next' or 'Alexa, previous' 

### Expected behavior
- Jumps to next or previous video

### Actual behavior
- Shows black screen, and periodically shows the loading indicator, but does not load any video
- This does not happen when remote is used to skip to next / previous video via graphics UI

### Device information
- Fire TV cube
* Firefox version: 2.2 release branch local build

**Comment by npark-mozilla** [comment]
When I exit the app and reopen, then the video starts playing.

**Comment by mcomella** [comment]
Maybe we're sending keyboard commands too quickly and it causes the page to get into an inconsistent state sometimes (given I've seen something like this but not always).

**Comment by mcomella** [comment]
You can also press any button on the D-pad to begin playback again. play/pause does not work.

Theory: Youtube may go to the next video but it starts paused (though the fact that play/pause doesn't work is suspicious)

**Comment by mcomella** [comment]
Changing the button press to ACTION_UP only fixes the issue on Youtube but this might break other sites. Looking for a fix...

**Comment by mcomella** [comment]
I think I know what's happening.

When MediaSession calls `onSkipToNext` for "Alexa next", I fake a media next key event, down and up. However, the down key event tells MediaSession to call `onSkipToNext` and we get into a key dispatch infinite loop. We need to prevent MediaSession from seeing this event.
