### ISSUE TITLE
Pause Command Is Resuming Playback

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#965]
We tested the 2.2 APK on FireTV Cube.
Steps:

    "Alexa, open Youtube" - This will launch the YouTube.com app.
    Select Firefox. (version 2.2)
    Then, select a video to play and click on it to start playback.
    "Alexa, pause" - video paused
    Again say "Alexa pause"
    Expect Behavior: Nothing happens
    Observed Behavior: Video resumes
    Summary: It doesn't take utterances accurately and toggles between pause and play.
    Sometimes FF was crashing while doing pause and play.

https://github.com/mozilla-mobile/firefox-tv/issues/930#issuecomment-403700455

**Comment by mcomella** [comment]
I originally implemented this this way to avoid having to sync JS playback state since, iirc, the hardware play/pause uses the current playback state to determine which command (play or pause) to issue.

I haven't revisited this since we now sync playback state, however: it might be possible now.

**Comment by bbinto** [comment]
@HiralSModi - is this a release blocker?
