### ISSUE TITLE
Fix crash when using MediaSession events (native crash dump)

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#966]
crash log: https://github.com/mozilla-mobile/firefox-tv/issues/930#issuecomment-403700517

https://github.com/mozilla-mobile/firefox-tv/files/2178912/crash_log_cube.txt

**Comment by mcomella** [comment]
These are native crash dumps: this seems like a Chromium bug. Let's see if we can reproduce.

**Comment by mcomella** [comment]
@HiralSModi Do you have steps to reproduce?

**Comment by HiralSModi** [comment]
We just played with the application for some time and did multiple play/pause. Are you not able to reproduce the crash?

**Comment by mcomella** [comment]
@npark-mozilla Have you seen this? I haven't seen this but I haven't tested MediaSession in normal use case (actually sitting around and watching videos).

**Comment by npark-mozilla** [comment]
@mcomella hmm, I was playing videos of 1~2 min length though (with multiple play/pause), I didn't run into the crash yet but that could be because I haven't tried enough.

**Comment by HiralSModi** [comment]
Thank you! We are parallelly doing more tests at our end too.

**Comment by npark-mozilla** [comment]
I tested this on Fire TV Cube with OS 6.2.2.1 (NS6221/1326) using videos of various length, but was not able to repro a native crash.

**Comment by HiralSModi** [comment]
Thank you! Our QA is validating at our end.

**Comment by Sdaswani** [comment]
Thanks @HiralSModi I'm labeling this as blocked until we hear back from your QA as we can't reproduce.

**Comment by HiralSModi** [comment]
Our QA is also not able to reproduce now. Sorry for the confusion. I believe that was some bad device.

**Comment by Sdaswani** [comment]
No worries!
