### ISSUE TITLE
Build and target SDK 28 (9.0)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#991]
### Why/User Benefit/User Problem

* It will be a requirement for using new OS features
* The longer we stay behind the harder it gets to update
* We want to update to 28 in the components soon. To avoid conflicts we want to update the apps too.

### What / Requirements

* [x] Update build.gradle files
* [x] Build and run tests to see if there are issues that need to be fixed
* [x] Is there a 28 support library release or does switching to SDK 28 mean we need to switch to the androidx.* support libraries (many of them seem to still have alpha version numbers).

**Comment by mcomella** [comment]
If possible, I'd like to wait until 28 is officially released (afaik, it's still Beta). My reasons for this are:
- Jump to definition on the source code will decompile the code rather than taking you to the source (b/c sources aren't released until the platform is officially released?)
- Instant run stops working (similar reasons?)

@pocmo Do you know how to fix these issues while upgrading to 28?

**Comment by pocmo** [comment]
Yes. we can still wait. SDK 28 seems to be final already. However there's no final image for any phone yet. Also the support libraries for 28 seem to be still in alpha. We may want to wait until they are final. Focus wants to build a feature based on the new biometric APIs, so I expect them to switch as soon as the support libraries are ready.

**Comment by pocmo** [comment]
FYI: Focus made the switch to SDK 28. In the components repository we are waiting for a final release of the support libraries (currently: 28.0.0-rc02) and maybe Robolectric 4.0 (which comes with support for API 28).

**Comment by mcomella** [comment]
FYI: SDK 28 is released: https://github.com/mozilla-mobile/android-components/issues/404#issuecomment-423910343

We should add KTX while we're at it.

**Comment by pocmo** [comment]
FYI: Android Components 0.26 is expected to require SDK 28 (tentative release date: October 5th)

**Comment by mcomella** [comment]
Emily mentioned for Focus:

> it required a lot of [Settings changes](https://github.com/mozilla-mobile/focus-android/pull/3053/files) to support libraries. We also had to [accept the new licenses](https://github.com/mozilla-mobile/focus-android/pull/3088/files) which ended up being a bit complicated

**Comment by mcomella** [comment]
Also, API 28 blocks HTTP traffic by default so we need to add an option in our Android Manifest.
