### ISSUE TITLE
URL moves when moving back up to URL bar from Pocket tile

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/firefox-tv#995]
### Steps to reproduce

1. Visit a page with a long URL
2. Press Menu
3. URL bar is focused
4. Press Down / Go to pocket tile
5. Press Up / Go back to URL bar

### Expected behavior

URL stays in the same position showing the "root" domain

### Actual behavior

URL show usually unhelpful last characters

### Device information

* Fire TV device: Cube
* Firefox version: Master branch, latest commit 6c9e41a

**Comment by psymoon** [comment]
Does this only happen in Cube devices? I can't seem to reproduce it with Fire TV stick

**Comment by aminalhazwani** [comment]
I can reproduce this on a Fire TV 4K (diamond), device code `AFTN`. I don't have a stick. I am pushing latest `master` commit e2fdcce from Android Studio to the TV.

### Steps to reproduce
1. Open a page with a long URL
2. Open Menu
3. Focus pocket tile - URL shows first characters
![screencap-0](https://user-images.githubusercontent.com/1721875/44207528-df964d80-a15d-11e8-8cca-2a4b8cd2b178.png)
4. Go up to URL bar - URL shows last characters
![screencap](https://user-images.githubusercontent.com/1721875/44207470-b4136300-a15d-11e8-930b-fbbc9daa12f8.png)
5. Go up to Settings icon - URL moves back to first characters
![screencap-1](https://user-images.githubusercontent.com/1721875/44207597-300dab00-a15e-11e8-8ce6-758365995126.png)
