### ISSUE TITLE
Compile UI/integration tests during CI, local pre-push hooks

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#998]
We don't run UI tests because they take forever but we should at least compile them to ensure they haven't broken.

**Comment by pocmo** [comment]
Yep! @AaronMT just noticed that the `browser-session` integration broke `SessionLoadedIdlingResource` :)

**Comment by mcomella** [comment]
For this bug:
- Ensure we compile the android unit tests in [our pre-push hook](https://github.com/mozilla-mobile/firefox-tv/blob/master/quality/pre-push-recommended.sh). The gradle task to compile android unit tests is `compileAmazonWebviewDebugAndroidTestSources`
- Add this command to our [TaskCluster configs](https://github.com/mozilla-mobile/firefox-tv/blob/master/.taskcluster.yml) too so it runs in CI

**Comment by liuche** [comment]
blocked on #1010

**Comment by bbinto** [comment]
@liuche can this be unblocked now?

**Comment by liuche** [comment]
@npark-mozilla @AaronMT what needs to be done to fix this, or more importantly, who needs to do what step?
(I'm just not sure if you're blocked on us, or if you are, if there are any specific steps we should be doing first)

**Comment by npark-mozilla** [comment]
Oh, this bug is about UI Test build not being a part of the build, so we didn't know about the failure soon.  I guess if AndroidTest becomes part of the master build (optional, since tests are failing now) that's all it needs?  

I don't think we're blocked on this bug, we can work on tests now
